In [4]:
import pandas as pd

kr2021 = pd.read_stata(
    "Children MIS 2021.DTA",
    convert_categoricals=False
)

print(kr2021.shape)

(10988, 359)

In [5]:
# Extracting the 23 needed variables from the whole dataset 

selected_vars = [
    'v024','v025','v190',
    'ml0','ml101',
    'ml13a','ml13e','ml13h','ml13y',
    'ml501','ml501a','ml501b','ml501h',
    'ml503','ml503a','ml503b',
    'ml503e','ml503f','ml503g',
    'ml505','ml506','ml507','ml514'
]

kr2021_project = kr2021[selected_vars]

In [6]:
# Put those 23 variables to Excel and save it there automatically

kr2021_project.to_excel(
    "KR2021_Project_Data.xlsx",
    index=False
)

In [7]:
import pyreadstat

df, meta = pyreadstat.read_sav(
    "NGKR81FL.sav"
)

for var in selected_vars:
    print("\n")
    print("Variable:", var)
    print("Label:", meta.column_names_to_labels.get(var))
    print("Codes:", meta.variable_value_labels.get(var))

Variable: v024
Label: None
Codes: None


Variable: v025
Label: None
Codes: None


Variable: v190
Label: None
Codes: None


Variable: ml0
Label: None
Codes: None


Variable: ml101
Label: None
Codes: None


Variable: ml13a
Label: None
Codes: None


Variable: ml13e
Label: None
Codes: None


Variable: ml13h
Label: None
Codes: None


Variable: ml13y
Label: None
Codes: None


Variable: ml501
Label: None
Codes: None


Variable: ml501a
Label: None
Codes: None


Variable: ml501b
Label: None
Codes: None


Variable: ml501h
Label: None
Codes: None


Variable: ml503
Label: None
Codes: None


Variable: ml503a
Label: None
Codes: None


Variable: ml503b
Label: None
Codes: None


Variable: ml503e
Label: None
Codes: None


Variable: ml503f
Label: None
Codes: None


Variable: ml503g
Label: None
Codes: None


Variable: ml505
Label: None
Codes: None


Variable: ml506
Label: None
Codes: None


Variable: ml507
Label: None
Codes: None


Variable: ml514
Label: None
Codes: None

In [9]:
dir(meta)

['__annotations__',
 '__class__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__match_args__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'column_labels',
 'column_names',
 'column_names_to_labels',
 'creation_time',
 'file_encoding',
 'file_format',
 'file_label',
 'missing_ranges',
 'missing_user_values',
 'modification_time',
 'mr_sets',
 'notes',
 'number_columns',
 'number_rows',
 'original_variable_types',
 'readstat_variable_types',
 'table_name',
 'value_labels',
 'variable_alignment',
 'variable_display_width',
 'variable_measure',
 'variable_storage_width',
 'variable_to_label',
 'variable_value_labels']

In [12]:
print(meta.column_names_to_labels)

{'CASEID': 'Case Identification', 'HIDXA': 'Index to birth history', 'V000': 'Country code and phase', 'V001': 'Cluster number', 'V002': 'Household number', 'V003': "Respondent's line number", 'V004': 'Ultimate area unit', 'V005': "Women's individual sample weight (6 decimals)", 'V006': 'Month of interview', 'V007': 'Year of interview', 'V008': 'Date of interview (CMC)', 'V008A': 'Date of interview Century Day Code (CDC)', 'V009': "Respondent's month of birth", 'V010': "Respondent's year of birth", 'V011': 'Date of birth (CMC)', 'V012': "Respondent's current age", 'V013': 'Age in 5-year groups', 'V014': 'Completeness of age information', 'V015': 'Result of individual interview', 'V016': 'Day of interview', 'V021': 'Primary sampling unit', 'V022': 'Sample strata for sampling errors', 'V023': 'Stratification used in sample design', 'V024': 'Region', 'V025': 'Type of place of residence', 'V026': 'NA - De facto place of residence', 'V027': 'Number of visits', 'V028': 'Interviewer identification', 'V029': 'NA - Keyer identification', 'V030': 'Field supervisor', 'V031': 'NA - Field editor', 'V032': 'NA - Office editor', 'V034': 'NA - Line number of husband', 'V040': 'Cluster altitude in meters', 'V042': 'Household selected for hemoglobin', 'V045A': 'Language of questionnaire', 'V045B': 'Language of interview', 'V045C': 'Native language of respondent', 'V046': 'Translator used', 'V047': 'Team number', 'V101': 'Region', 'V102': 'Type of place of residence', 'V106': 'Highest educational level', 'V107': 'Highest year of education', 'V113': 'Source of drinking water', 'V115': 'Time to get to water source', 'V116': 'Type of toilet facility', 'V119': 'Household has: electricity', 'V120': 'Household has: radio', 'V121': 'Household has: television', 'V122': 'Household has: refrigerator', 'V123': 'Household has: bicycle', 'V124': 'Household has: motorcycle/scooter', 'V125': 'Household has: car/truck', 'V127': 'Main floor material', 'V128': 'Main wall material', 'V129': 'Main roof material', 'V130': 'Religion', 'V131': 'Ethnicity', 'V133': 'Education in single years', 'V134': 'NA - De facto place of residence', 'V135': 'Usual resident or visitor', 'V136': 'Number of household members (listed)', 'V137': 'Number of children 5 and under in household (de jure)', 'V138': 'Number of eligible women in household (de facto)', 'V139': 'De jure region of residence', 'V140': 'De jure type of place of residence', 'V141': 'NA - De jure place of residence', 'V149': 'Educational attainment', 'V150': 'Relationship to household head', 'V151': 'Sex of household head', 'V152': 'Age of household head', 'V153': 'Household has: telephone (land-line)', 'V155': 'Literacy', 'V156': 'NA - Ever participated in a literacy program outside of primary', 'V157': 'Frequency of reading newspaper or magazine', 'V158': 'Frequency of listening to radio', 'V159': 'Frequency of watching television', 'V160': 'Toilet facilities shared with other households', 'V161': 'Type of cooking fuel', 'V169A': 'Owns a mobile telephone', 'V169C': "Is respondent's mobile phone a smart phone", 'V171A': 'Use of internet', 'V171B': 'Frequency of using internet last month', 'V190': 'Wealth index combined', 'V191': 'Wealth index factor score combined (5 decimals)', 'V190A': 'Wealth index for urban/rural', 'V191A': 'Wealth index factor score for urban/rural (5 decimals)', 'ML101': 'Type of mosquito bed net(s) slept under last night', 'V417': 'Entries in pregnancy and postnatal care roster', 'V418A': 'Entries in child health roster', 'V419': 'Entries in height/weight roster', 'V459': 'Have mosquito bed net for sleeping (from household questionnaire)', 'V460': 'Children under 5 slept under mosquito bed net last night (household questionnaire)', 'V461': 'Respondent slept under mosquito bed net', 'V468': 'Record for Last Birth', 'BIDX': 'Birth column number', 'BORD': 'Birth order number', 'B0': 'Child is twin', 'B1': 'Month of birth', 'B2': 'Year of birth', 'B3': 'Date of birth (CMC)', 'B4': 'Sex of child', 'B5': 'Child is alive', 'B6': 'NA - Age at death', 'B7': 'NA - Age at death (months, imputed)', 'B8': 'Current age of child', 'B9': 'Child lives with whom', 'B10': 'Completeness of information', 'B11': 'Preceding birth interval (months)', 'B12': 'Succeeding birth interval (months)', 'B13': 'NA - Flag for age at death', 'B15': 'Live birth between births', 'B16': "Child's line number in household", 'B17': 'Day of birth', 'B18': 'Century Day Code of birth (CDC)', 'B19': 'Current age of child in months (months since birth for dead children)', 'V201': 'Total children ever born', 'V202': 'Sons at home', 'V203': 'Daughters at home', 'V204': 'Sons elsewhere', 'V205': 'Daughters elsewhere', 'V206': 'Sons who have died', 'V207': 'Daughters who have died', 'V208': 'Births in last five years', 'V209': 'Births in past year', 'V210': 'Births in month of interview', 'V213': 'Currently pregnant', 'V214': 'Duration of current pregnancy in months', 'V214A': 'Duration of current pregnancy original', 'V218': 'Number of living children', 'V219': 'Living children + current pregnancy', 'V220': 'Living children + current pregnancy (grouped)', 'V222': 'Last birth to interview (months)', 'V223': 'Completeness of current pregnancy information', 'V224': 'Entries in birth history', 'V237': 'Birth between last and interview', 'V238': 'Births in last three years', 'MIDX': 'Index to Birth History', 'M2A': 'Prenatal: doctor', 'M2B': 'Prenatal: nurse/midwife', 'M2C': 'Prenatal: auxiliary midwife', 'M2D': 'Prenatal: government health community extension health worker', 'M2E': 'NA - Prenatal: CS health professional', 'M2F': 'NA - Prenatal: CS health professional', 'M2G': 'Prenatal: traditional birth attendant', 'M2H': 'Prenatal: Community health worker/field worker', 'M2I': 'NA - Prenatal: CS other person', 'M2J': 'NA - Prenatal: CS other person', 'M2K': 'Prenatal: other', 'M2L': 'NA - Prenatal: CS other', 'M2M': 'NA - Prenatal: CS other', 'M2N': 'Prenatal: no one', 'M13': 'Timing of 1st antenatal check (months)', 'M13A': 'Timing of 1st antenatal check (original)', 'M14': 'Number of antenatal visits during pregnancy', 'M49A': 'During pregnancy took: SP/fansidar for malaria', 'M49B': 'NA - During pregnancy took: chloroquine for malaria', 'M49C': 'NA - During pregnancy took: CS drug for malaria', 'M49D': 'NA - During pregnancy took: CS drug for malaria', 'M49E': 'NA - During pregnancy took: CS drug for malaria', 'M49F': 'NA - During pregnancy took: CS drug for malaria', 'M49G': 'NA - During pregnancy took: CS drug for malaria', 'M49X': 'NA - During pregnancy took: other drug for malaria', 'M49Z': "NA - During pregnancy took: don't know", 'M49Y': 'NA - During pregnancy took: no drug for malaria', 'M57A': "Antenatal care: respondent's home", 'M57B': 'Antenatal care: other home', 'M57C': 'NA - Antenatal care: CS home', 'M57D': 'NA - Antenatal care: CS home', 'M57E': 'Antenatal care: government hospital', 'M57F': 'Antenatal care: government health center', 'M57G': 'Antenatal care: government health post', 'M57H': 'Antenatal care: other public sector', 'M57I': 'NA - Antenatal care: CS public health', 'M57J': 'NA - Antenatal care: CS public health', 'M57K': 'NA - Antenatal care: CS public health', 'M57L': 'NA - Antenatal care: CS public health', 'M57M': 'Antenatal care: private hospital', 'M57N': 'Antenatal care: private clinic', 'M57O': 'Antenatal care: other private medical sector', 'M57P': 'NA - Antenatal care: CS private medical', 'M57Q': 'NA - Antenatal care: CS private medical', 'M57R': 'NA - Antenatal care: CS private medical', 'M57NA': 'Antenatal care: NGO hospital', 'M57NB': 'Antenatal care: NGO clinic', 'M57NC': 'Antenatal care: other NGO medical sector', 'M57ND': 'NA - Antenatal care: NGO medical', 'M57NE': 'NA - Antenatal care: NGO medical', 'M57S': 'NA - Antenatal care: CS other', 'M57T': 'NA - Antenatal care: CS other', 'M57U': 'NA - Antenatal care: CS other', 'M57V': 'NA - Antenatal care: CS other', 'M57X': 'Antenatal care: other', 'ML1': 'Number of times took fansidar during pregnancy', 'ML2': 'Source of antimalarial during pregnancy', 'H22': 'Had fever in last two weeks', 'H31': 'NA - Had cough in last two weeks', 'H32A': 'Fever/cough: government hospital', 'H32B': 'Fever/cough: government health center', 'H32C': 'Fever/cough: government health post', 'H32D': 'Fever/cough: government mobile clinic', 'H32E': 'Fever/cough: government community health worker/fieldworker', 'H32F': 'Fever/cough: other public sector', 'H32G': 'NA - Fever/cough: CS public sector', 'H32H': 'NA - Fever/cough: CS public sector', 'H32I': 'NA - Fever/cough: CS public sector', 'H32J': 'Fever/cough: private hospital', 'H32K': 'Fever/cough: private pharmacy', 'H32L': 'Fever/cough: private doctor', 'H32M': 'Fever/cough: private clinic', 'H32N': 'Fever/cough: private mobile clinic', 'H32O': 'Fever/cough: private community health worker/fieldworker', 'H32P': 'Fever/cough: other private medical sector', 'H32Q': 'NA - Fever/cough: CS private medical', 'H32R': 'NA - Fever/cough: CS private medical', 'H32NA': 'Fever/cough: NGO hospital', 'H32NB': 'Fever/cough: NGO clinic', 'H32NC': 'Fever/cough: other NGO sector', 'H32ND': 'NA - Fever/cough: CS NGO', 'H32NE': 'NA - Fever/cough: CS NGO', 'H32S': 'Fever/cough: chemist shop/PPMV', 'H32T': 'Fever/cough: traditional practitioner', 'H32U': 'Fever/cough: market', 'H32V': 'Fever/cough: itinerant drug seller', 'H32W': 'Fever/cough: community-oriented resource person', 'H32X': 'Fever/cough: other', 'H32Y': 'Fever/cough: no treatment', 'H32Z': 'Fever/cough: medical treatment', 'H46A': 'Place first sought treatment for fever', 'H46B': 'Number of days after fever began sought advice or treatment', 'H47': "Blood taken from child's finger/heel for testing", 'H71': 'Was respondent told that child had malaria', 'HWIDX': 'Index to Birth History', 'HW1': "Child's age in months", 'HW16': 'Day of birth of child', 'HW17': 'Date measured (day)', 'HW18': 'Date measured (month)', 'HW19': 'Date measured (year)', 'HW51': 'Line number of parent/caretaker', 'HW52': 'Read consent statement - hemoglobin', 'HW53': 'Hemoglobin level (g/dl - 1 decimal)', 'HW55': 'Result of measurement - hemoglobin', 'HW56': 'Hemoglobin level adjusted for altitude (g/dl - 1 decimal)', 'HW57': 'Anemia level', 'HW58': 'NA - Agrees to referral - anemia', 'IDXML': 'Index to Birth History', 'ML0': 'Type of mosquito bed net(s) child slept under last night', 'ML11': 'NA - Child has fever/cough now', 'ML12': 'NA - Child has had convulsions in last 2 weeks', 'ML13A': 'Fansidar taken for fever', 'ML13B': 'Chloroquine taken for fever', 'ML13C': 'Amodiaquine taken for fever', 'ML13D': 'Quinine taken for fever', 'ML13DA': 'Quinine injection/IV taken for fever', 'ML13E': 'Combination with artemisinin taken for fever', 'ML13AA': 'Artesunate rectal taken for fever', 'ML13AB': 'Artesunate injection/IV taken for fever', 'ML13F': 'NA - CS antimalarial taken for fever', 'ML13G': 'NA - CS antimalarial taken for fever', 'ML13H': 'Other antimalarial taken for fever', 'ML13I': 'Antibiotic pill/syrup taken for fever', 'ML13J': 'Antibiotic injection taken for fever', 'ML13K': 'Aspirin taken for fever', 'ML13L': 'Acetaminophen/paracetamol/panadol taken for fever', 'ML13M': 'Ibuprofen taken for fever', 'ML13N': 'Amoxicillin taken for fever', 'ML13O': 'Cotrimoxazole taken for fever', 'ML13P': 'NA - CS other taken for fever', 'ML13X': 'Other taken for fever', 'ML13Y': "Nothing taken and didn't seek treatment for fever/cough", 'ML13Z': "Don't know if or what was taken for fever", 'ML14A': 'NA - Injection given for fever/convulsion', 'ML14B': 'NA - Suppository given for fever/convulsion', 'ML14Y': 'NA - No suppository or injection given for fever/convulsion', 'ML14Z': "NA - Don't know if suppository or injection given for fever/convulsion", 'ML15A': 'NA - Timing of start of fansidar', 'ML15B': 'NA - Number of days child took fansidar', 'ML15C': 'NA - First source for fansidar', 'ML16A': 'NA - Timing of start of chloroquine', 'ML16B': 'NA - Number of days child took chloroquine', 'ML16C': 'NA - First source for chloroquine', 'ML17A': 'NA - Timing of start of amodiaquine', 'ML17B': 'NA - Number of days child took amodiaquine', 'ML17C': 'NA - First source for amodiaquine', 'ML18A': 'NA - Timing of start of quinine', 'ML18B': 'NA - Number of days child took quinine', 'ML18C': 'NA - First source for quinine', 'ML19A': 'NA - For fever/convulsion: consulted traditional healer', 'ML19B': 'NA - For fever/convulsion: gave tepid sponging', 'ML19C': 'NA - For fever/convulsion: gave herbs', 'ML19D': 'NA - For fever/convulsion: CS', 'ML19E': 'NA - For fever/convulsion: CS', 'ML19F': 'NA - For fever/convulsion: CS', 'ML19X': 'NA - For fever/convulsion: other', 'ML19Y': 'NA - For fever/convulsion: gave/did nothing', 'ML19Z': "NA - For fever/convulsion: don't know if something else was done", 'ML20A': 'Timing of start of combination with artemisinin', 'ML20B': 'NA - Number of days child took combination with artemisinin', 'ML20C': 'NA - First source for combination with artemisinin', 'ML21A': 'NA - Timing of start of CS antimalarial use', 'ML21B': 'NA - Number of days child took CS antimalarial', 'ML21C': 'NA - First source for CS antimalarial', 'ML22A': 'NA - Timing of start of CS antimalarial use', 'ML22B': 'NA - Number of days child took CS antimalarial', 'ML22C': 'NA - First source for CS antimalarial', 'ML23A': 'NA - Timing of start of other anti-malarial use', 'ML23B': 'NA - Number of days child took other anti-malarial', 'ML23C': 'NA - First source for other anti-malarial', 'ML24C': 'NA - First source for antibiotic pill/syrup', 'ML25A': 'NA - Timing of start of artesunate', 'ML501': 'Last six months heard/seen malaria messages', 'ML501A': 'Malaria messages were heard/seen: radio', 'ML501B': 'Malaria messages were heard/seen: television', 'ML501C': 'Malaria messages were heard/seen: poster/billboard', 'ML501D': 'Malaria messages were heard/seen: newspaper/magazine', 'ML501E': 'Malaria messages were heard/seen: leaflet/brochure', 'ML501F': 'Malaria messages were heard/seen: healthcare provider', 'ML501G': 'Malaria messages were heard/seen: community health worker', 'ML501H': 'Malaria messages were heard/seen: social media', 'ML501I': 'Malaria messages were heard/seen: town announcer', 'ML501J': 'Malaria messages were heard/seen: inter-personal communication agent/community volunteer', 'ML501K': 'Malaria messages were heard/seen: family/friends', 'ML501X': 'Malaria messages were heard/seen: other', 'ML501Z': "Malaria messages were heard/seen: don't remember", 'ML503': 'Are there ways to avoid getting malaria', 'ML503A': 'Malaria can be prevented by: sleep inside a mosquito net', 'ML503B': 'Malaria can be prevented by: sleep inside an insecticide-treated mosquito net', 'ML503C': 'Malaria can be prevented by: use mosquito repellent or coil', 'ML503D': 'Malaria can be prevented by: take preventive medications', 'ML503E': 'Malaria can be prevented by: spray house with insecticide', 'ML503F': 'Malaria can be prevented by: fill in stagnant waters (puddles)', 'ML503G': 'Malaria can be prevented by: keep surroundings clean', 'ML503H': 'Malaria can be prevented by: put mosquito screen on windows', 'ML503I': 'NA - Malaria can be prevented by: CS', 'ML503J': 'NA - Malaria can be prevented by: CS', 'ML503K': 'NA - Malaria can be prevented by: CS', 'ML503X': 'Malaria can be prevented by: other', 'ML503Z': "Malaria can be prevented by: don't know", 'ML505': 'Agree/disagree with: people in community get malaria in rainy season', 'ML506': 'Agree/disagree with: when child has fever worry it is malaria', 'ML507': 'Agree/disagree with: getting malaria not a problem as can be treated', 'ML508': 'Agree/disagree with: only weak children can die from malaria', 'ML509': 'Agree/disagree with: sleep inside net when there are lots of mosquitoes', 'ML510': 'Agree/disagree with: sleep inside net when there are few mosquitoes', 'ML511': "Agree/disagree with: don't like sleep inside a net when is too warm", 'ML512': 'Agree/disagree with: if child has fever best to give medicine available at home', 'ML513': 'Agree/disagree with: people take children to health provider same day or next day develop fever', 'ML514': 'Agree/disagree with: people who have nets usually sleep under every night', 'S512A': 'Agree/disagree with: important children take full dose of medicine they are prescribed for malaria', 'SLGA': 'Local government area', 'SREGION': 'Region', 'SBONNY': 'Bonny State', 'S104A': 'Had informal education', 'S104B': 'Type of informal education', 'S211': 'Number of births 2016-2021', 'IDX95': 'Index to Birth History', 'S411A': 'Referred to higher level of care', 'S415A': 'Fever went away after took ACT'}

In [13]:
print(meta.variable_value_labels)

{'V013': {1.0: '15-19', 2.0: '20-24', 3.0: '25-29', 4.0: '30-34', 5.0: '35-39', 6.0: '40-44', 7.0: '45-49'}, 'V014': {1.0: 'Month and year - information complete', 2.0: 'Month and age - year imputed', 3.0: 'Year and age - month imputed', 4.0: 'Year and age - year ignored', 5.0: 'Year - age/month imputed', 6.0: 'Age - year/month imputed', 7.0: 'Month - age/year imputed', 8.0: 'None - all imputed'}, 'V015': {1.0: 'Completed', 2.0: 'Not at home', 3.0: 'Postponed', 4.0: 'Refused', 5.0: 'Partially completed', 6.0: 'Respondent incapacitated', 7.0: 'Other'}, 'V022': {1.0: 'Abia_Urban', 2.0: 'Abia_Rural', 3.0: 'Adamawa_Urban', 4.0: 'Adamawa_Rural', 5.0: 'Akwa Ibom_Urban', 6.0: 'Akwa Ibom_Rural', 7.0: 'Anambra_Urban', 8.0: 'Anambra_Rural', 9.0: 'Bauchi_Urban', 10.0: 'Bauchi_Rural', 11.0: 'Bayelsa_Urban', 12.0: 'Bayelsa_Rural', 13.0: 'Benue_Urban', 14.0: 'Benue_Rural', 15.0: 'Borno_Urban', 16.0: 'Borno_Rural', 17.0: 'Cross River_Urban', 18.0: 'Cross River_Rural', 19.0: 'Delta_Urban', 20.0: 'Delta_Rural', 21.0: 'Ebonyi_Urban', 22.0: 'Ebonyi_Rural', 23.0: 'Edo_Urban', 24.0: 'Edo_Rural', 25.0: 'Ekiti_Urban', 26.0: 'Ekiti_Rural', 27.0: 'Enugu_Urban', 28.0: 'Enugu_Rural', 29.0: 'Fct_Urban', 30.0: 'Fct_Rural', 31.0: 'Gombe_Urban', 32.0: 'Gombe_Rural', 33.0: 'Imo_Urban', 34.0: 'Imo_Rural', 35.0: 'Jigawa_Urban', 36.0: 'Jigawa_Rural', 37.0: 'Kaduna_Urban', 38.0: 'Kaduna_Rural', 39.0: 'Kano_Urban', 40.0: 'Kano_Rural', 41.0: 'Katsina_Urban', 42.0: 'Katsina_Rural', 43.0: 'Kebbi_Urban', 44.0: 'Kebbi_Rural', 45.0: 'Kogi_Urban', 46.0: 'Kogi_Rural', 47.0: 'Kwara_Urban', 48.0: 'Kwara_Rural', 49.0: 'Lagos_Urban', 50.0: 'Lagos_Rural', 51.0: 'Nasarawa_Urban', 52.0: 'Nasarawa_Rural', 53.0: 'Niger_Urban', 54.0: 'Niger_Rural', 55.0: 'Ogun_Urban', 56.0: 'Ogun_Rural', 57.0: 'Ondo_Urban', 58.0: 'Ondo_Rural', 59.0: 'Osun_Urban', 60.0: 'Osun_Rural', 61.0: 'Oyo_Urban', 62.0: 'Oyo_Rural', 63.0: 'Plateau_Urban', 64.0: 'Plateau_Rural', 65.0: 'Rivers_Urban', 66.0: 'Rivers_Urban', 67.0: 'Rivers_Rural', 68.0: 'Rivers_Rural', 69.0: 'Sokoto_Urban', 70.0: 'Sokoto_Rural', 71.0: 'Taraba_Urban', 72.0: 'Taraba_Rural', 73.0: 'Yobe_Urban', 74.0: 'Yobe_Rural', 75.0: 'Zamfara_Urban', 76.0: 'Zamfara_Rural'}, 'V023': {1.0: 'Abia_Urban', 2.0: 'Abia_Rural', 3.0: 'Adamawa_Urban', 4.0: 'Adamawa_Rural', 5.0: 'Akwa Ibom_Urban', 6.0: 'Akwa Ibom_Rural', 7.0: 'Anambra_Urban', 8.0: 'Anambra_Rural', 9.0: 'Bauchi_Urban', 10.0: 'Bauchi_Rural', 11.0: 'Bayelsa_Urban', 12.0: 'Bayelsa_Rural', 13.0: 'Benue_Urban', 14.0: 'Benue_Rural', 15.0: 'Borno_Urban', 16.0: 'Borno_Rural', 17.0: 'Cross River_Urban', 18.0: 'Cross River_Rural', 19.0: 'Delta_Urban', 20.0: 'Delta_Rural', 21.0: 'Ebonyi_Urban', 22.0: 'Ebonyi_Rural', 23.0: 'Edo_Urban', 24.0: 'Edo_Rural', 25.0: 'Ekiti_Urban', 26.0: 'Ekiti_Rural', 27.0: 'Enugu_Urban', 28.0: 'Enugu_Rural', 29.0: 'Fct_Urban', 30.0: 'Fct_Rural', 31.0: 'Gombe_Urban', 32.0: 'Gombe_Rural', 33.0: 'Imo_Urban', 34.0: 'Imo_Rural', 35.0: 'Jigawa_Urban', 36.0: 'Jigawa_Rural', 37.0: 'Kaduna_Urban', 38.0: 'Kaduna_Rural', 39.0: 'Kano_Urban', 40.0: 'Kano_Rural', 41.0: 'Katsina_Urban', 42.0: 'Katsina_Rural', 43.0: 'Kebbi_Urban', 44.0: 'Kebbi_Rural', 45.0: 'Kogi_Urban', 46.0: 'Kogi_Rural', 47.0: 'Kwara_Urban', 48.0: 'Kwara_Rural', 49.0: 'Lagos_Urban', 50.0: 'Lagos_Rural', 51.0: 'Nasarawa_Urban', 52.0: 'Nasarawa_Rural', 53.0: 'Niger_Urban', 54.0: 'Niger_Rural', 55.0: 'Ogun_Urban', 56.0: 'Ogun_Rural', 57.0: 'Ondo_Urban', 58.0: 'Ondo_Rural', 59.0: 'Osun_Urban', 60.0: 'Osun_Rural', 61.0: 'Oyo_Urban', 62.0: 'Oyo_Rural', 63.0: 'Plateau_Urban', 64.0: 'Plateau_Rural', 65.0: 'Rivers_Urban', 66.0: 'Rivers_Urban', 67.0: 'Rivers_Rural', 68.0: 'Rivers_Rural', 69.0: 'Sokoto_Urban', 70.0: 'Sokoto_Rural', 71.0: 'Taraba_Urban', 72.0: 'Taraba_Rural', 73.0: 'Yobe_Urban', 74.0: 'Yobe_Rural', 75.0: 'Zamfara_Urban', 76.0: 'Zamfara_Rural'}, 'V024': {1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}, 'V025': {1.0: 'Urban', 2.0: 'Rural'}, 'V026': {0.0: 'Capital, large city', 1.0: 'Small city', 2.0: 'Town', 3.0: 'Countryside'}, 'V034': {0.0: 'Husband not in household'}, 'V042': {0.0: 'Not selected', 1.0: 'Selected'}, 'V045A': {1.0: 'English', 2.0: 'Hausa', 3.0: 'Yoruba', 4.0: 'Igbo'}, 'V045B': {1.0: 'English', 2.0: 'Hausa', 3.0: 'Yoruba', 4.0: 'Igbo', 5.0: 'Fulfulde', 6.0: 'Other'}, 'V045C': {1.0: 'English', 2.0: 'Hausa', 3.0: 'Yoruba', 4.0: 'Igbo', 5.0: 'Fulfulde', 6.0: 'Other'}, 'V046': {0.0: 'No', 1.0: 'Yes'}, 'V101': {1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}, 'V102': {1.0: 'Urban', 2.0: 'Rural'}, 'V106': {0.0: 'No education', 1.0: 'Primary', 2.0: 'Secondary', 3.0: 'Higher'}, 'V107': {0.0: 'No years completed at level V106'}, 'V113': {10.0: 'PIPED WATER', 11.0: 'Piped into dwelling', 12.0: 'Piped to yard/plot', 13.0: 'Piped to neighbor', 14.0: 'Public tap/standpipe', 20.0: 'TUBE WELL WATER', 21.0: 'Tube well or borehole', 30.0: 'DUG WELL (OPEN/PROTECTED)', 31.0: 'Protected well', 32.0: 'Unprotected well', 40.0: 'SURFACE FROM SPRING', 41.0: 'Protected spring', 42.0: 'Unprotected spring', 43.0: 'River/dam/lake/ponds/stream/canal/irrigation channel', 51.0: 'Rainwater', 61.0: 'Tanker truck', 62.0: 'Cart with small tank', 71.0: 'Bottled water', 72.0: 'Sachet water', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'V115': {996.0: 'On premises', 997.0: 'Not a dejure resident', 998.0: "Don't know"}, 'V116': {10.0: 'FLUSH TOILET', 11.0: 'Flush to piped sewer system', 12.0: 'Flush to septic tank', 13.0: 'Flush to pit latrine', 14.0: 'Flush to somewhere else', 15.0: "Flush, don't know where", 20.0: 'PIT TOILET LATRINE', 21.0: 'Ventilated Improved Pit latrine (VIP)', 22.0: 'Pit latrine with slab', 23.0: 'Pit latrine without slab/open pit', 30.0: 'NO FACILITY', 31.0: 'No facility/bush/field', 41.0: 'Composting toilet', 42.0: 'Bucket toilet', 43.0: 'Hanging toilet/latrine', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'V119': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'V120': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'V121': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'V122': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'V123': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'V124': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'V125': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'V127': {10.0: 'NATURAL', 11.0: 'Earth/sand', 12.0: 'Dung', 20.0: 'RUDIMENTARY', 21.0: 'Wood planks', 22.0: 'Palm/bamboo', 30.0: 'FINISHED', 31.0: 'Parquet or polished wood', 32.0: 'Vinyl or asphalt strips', 33.0: 'Ceramic tiles', 34.0: 'Cement', 35.0: 'Carpet', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'V128': {10.0: 'NATURAL', 11.0: 'No walls', 12.0: 'Cane/palm/trunks', 13.0: 'Dirt', 20.0: 'RUDIMENTARY', 21.0: 'Bamboo with mud', 22.0: 'Stone with mud', 23.0: 'Uncovered adobe', 24.0: 'Plywood', 25.0: 'Cardboard', 26.0: 'Reused wood', 30.0: 'FINISHED', 31.0: 'Cement', 32.0: 'Stone with lime/cement', 33.0: 'Bricks', 34.0: 'Cement blocks', 35.0: 'Covered adobe', 36.0: 'Wood planks/shingles', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'V129': {10.0: 'NATURAL', 11.0: 'No roof', 12.0: 'Thatch/palm leaf', 13.0: 'Grass', 20.0: 'RUDIMENTARY', 21.0: 'Rustic mat', 22.0: 'Palm/bamboo', 23.0: 'Wood planks', 24.0: 'Cardboard', 30.0: 'FINISHED', 31.0: 'Metal/Zinc', 32.0: 'Wood', 33.0: 'Calamine/cement fiber', 34.0: 'Ceramic tiles', 35.0: 'Cement', 36.0: 'Roofing shingles', 37.0: 'Asbestos', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'V130': {1.0: 'Catholic', 2.0: 'Other Christian', 3.0: 'Islam', 4.0: 'Traditionalist', 96.0: 'Other'}, 'V131': {1.0: 'Abua', 2.0: 'Adra/Adarawa', 3.0: 'Adun', 4.0: 'Afcabeya', 5.0: 'Afemai', 6.0: 'Afizire', 7.0: 'Agatu', 8.0: 'Agbassa', 9.0: 'Agbor', 10.0: 'Afo', 11.0: 'Ajowa', 12.0: 'Akpa', 13.0: 'Akwai', 14.0: 'Akye', 15.0: 'Alago', 16.0: 'Amamong', 17.0: 'Amo', 18.0: 'Ana', 19.0: 'Anaguta', 20.0: 'Ankwai', 21.0: 'Annang', 22.0: 'Arab', 23.0: 'Arabo', 24.0: 'Arbar', 25.0: 'Arugu', 26.0: 'Aten/Atam', 27.0: 'Attakar', 28.0: 'Auchi', 29.0: 'Aulliminden', 30.0: 'Awo', 31.0: 'Ayetoro Gbede', 32.0: 'Badarare', 33.0: 'Bade/Badawe', 34.0: 'Bafeke', 35.0: 'Bagathiya', 36.0: 'Baggara', 37.0: 'Bagunge/Badagire', 38.0: 'Bahnake', 39.0: 'Baji/Biji', 40.0: 'Bajju', 41.0: 'Bambaro', 42.0: 'Bambuka', 43.0: 'Bandawa', 44.0: 'Banguji', 45.0: 'Bankalawa', 46.0: 'Bchama', 47.0: 'Barabaci', 48.0: 'Barawa', 49.0: 'Bargawa', 50.0: 'Bassa', 51.0: 'Bekworas', 53.0: 'Berom', 54.0: 'Bini/Edo', 55.0: 'Bogom', 56.0: 'Boiyawa/Bozaya', 57.0: 'Bolawa/Bolewa', 59.0: 'Buduma', 60.0: 'Buko', 61.0: 'Bura/Babur', 62.0: 'Buzu', 63.0: 'Byazhi', 64.0: 'Calabar', 65.0: 'Chala', 66.0: 'Chamba', 67.0: 'Chiba', 68.0: 'Chibok(g)', 69.0: 'Chip', 70.0: 'Dadiya', 71.0: 'Badakare/Dakarkari', 72.0: 'Dakka/Doka', 73.0: 'Dangula', 74.0: 'Daurawa/Dagarawa', 75.0: 'Defaka', 76.0: 'Degima', 77.0: 'Delta Ibo', 78.0: 'Dibo', 79.0: 'Diguza', 80.0: 'Djerma', 81.0: 'Dmoko', 82.0: 'Dolchi', 83.0: 'Ebira/Igbira', 84.0: 'Ebu', 85.0: 'Efik', 86.0: 'Egba', 87.0: 'Egbado', 88.0: 'Eggon', 89.0: 'Egun', 90.0: 'Eket', 91.0: 'Ekoi', 92.0: 'Ekpeye/Afisa/Epie', 94.0: 'Ekulu', 95.0: 'Eleme', 96.0: 'Emu', 97.0: 'Esan', 98.0: 'Etina', 99.0: 'Etsako', 100.0: 'Etulo', 101.0: 'Hadejawa', 102.0: 'Fanso', 103.0: 'Femawa', 104.0: 'Fer', 105.0: 'Filiya/Fali', 106.0: 'Fon', 107.0: 'Foron', 108.0: 'French', 109.0: 'Fulani', 110.0: 'Gamaku', 111.0: 'Gamaru', 112.0: 'Gamuni', 113.0: 'Gana Gana', 114.0: 'Ganawuri', 115.0: 'Gbaju/Gbagi', 116.0: 'Gede/Gude/Gai', 117.0: 'Gerawa', 118.0: 'Gizmawa', 119.0: 'Glauda', 120.0: 'Gmenchi', 121.0: 'Gomo/Gamoyaya', 122.0: 'Gobiri/Gobirawa/Bogobiri', 123.0: 'Gujjurawa', 124.0: 'Guemai', 125.0: 'Gumbarawa', 126.0: 'Gunganchi', 127.0: 'Gwandara', 128.0: 'Gwantu', 129.0: 'Hankwe', 130.0: 'Hausa', 131.0: 'Higgi', 132.0: 'Ibariba', 133.0: 'Ibibio', 134.0: 'Ichen', 135.0: 'Idanre', 136.0: 'Idoma', 137.0: 'Igala', 138.0: 'Igbo/Ibo', 139.0: 'Igede', 140.0: 'Ijaw/Izon', 141.0: 'Ijede', 142.0: 'Ijeme', 143.0: 'Ika', 144.0: 'Ikajo', 145.0: 'Ikara', 146.0: 'Ikpeshi', 147.0: 'Ikpide', 148.0: 'Ikulu', 149.0: 'Ikwere', 150.0: 'Ilaje', 151.0: 'Irigwe', 152.0: 'Ishan', 153.0: 'Isoko', 154.0: 'Itsekiri', 155.0: 'Jaba', 156.0: 'Jajiri', 157.0: 'Jakatoe', 158.0: 'Jaku', 159.0: 'Jara', 160.0: 'Jarawa', 162.0: 'Jibu', 163.0: 'Jonjo', 164.0: 'Jukun', 165.0: 'Kabawa', 166.0: 'Kadara', 167.0: 'Kagoma', 168.0: 'Kagoro', 169.0: 'Kaka', 170.0: 'Kakanda', 171.0: 'Kamantam', 172.0: 'Kambari', 173.0: 'Kambu/Kangu', 174.0: 'Kamuku', 175.0: 'Kanakuru', 176.0: 'Kanawa', 177.0: 'Kaninko', 178.0: 'Kantanawa', 179.0: 'Kanuri/Beriberi', 180.0: 'Manga', 181.0: 'Karekare', 182.0: 'Kataf/Atyap', 183.0: 'Kento', 184.0: 'Kibaku', 185.0: 'Kilba', 186.0: 'Kirdi', 187.0: 'Kodki', 188.0: 'Kofyar', 189.0: 'Kona', 190.0: 'Koro', 191.0: 'Koto', 192.0: 'Kuenuem', 193.0: 'Kumbo', 194.0: 'Kunkawa/Kawa', 195.0: 'Kurama', 196.0: 'Kuteb', 197.0: 'Kuturm', 198.0: 'Kwale/Ukwuani', 199.0: 'Kwanzo', 200.0: 'Lagelu', 201.0: 'Lantang', 202.0: 'Lemoro', 203.0: 'Loh', 204.0: 'Lunguda', 205.0: 'Maba/Mbadowa', 206.0: 'Mada', 207.0: 'Mafa/Maka/Maga', 208.0: 'Mambila', 209.0: 'Mandara', 210.0: 'Mangus/Manju', 211.0: 'Marghi/mangi', 212.0: 'Mbwa', 213.0: 'Mingo', 214.0: 'Mirnang', 215.0: 'Montor', 216.0: 'Mtchiga/Michika', 217.0: 'Mumuye', 218.0: 'Munga', 219.0: 'Mupung', 220.0: 'Mushere', 221.0: 'Mwagavol', 222.0: 'Naiawum', 223.0: 'Namoen', 224.0: 'Ndokwa', 225.0: 'Ndola', 226.0: 'Ngamo', 227.0: 'Ukale', 228.0: 'Ngoshe', 229.0: 'Nili', 230.0: 'Ninnma', 231.0: 'Ninzom', 232.0: 'Nkoroo', 233.0: 'Nnebe', 234.0: 'Numana', 235.0: 'Nungu', 236.0: 'nunku', 237.0: 'Nupe', 238.0: 'Obubua', 239.0: 'Odu', 240.0: 'Ogoja', 241.0: 'Ogoni', 242.0: 'Ogugu', 243.0: 'Okori/Ogori', 244.0: 'Omele', 245.0: 'Ora', 246.0: 'Oron', 247.0: 'Owan', 249.0: 'Owo', 250.0: "Pa'awa", 251.0: 'Paburi', 252.0: 'Paibun', 253.0: 'Panya', 254.0: 'Pasama', 255.0: 'Pero', 256.0: 'Piya', 257.0: 'Pyem', 258.0: 'Rukuba', 259.0: 'Rulere', 260.0: 'Rundawa', 261.0: 'Sayawa/Siyawa', 262.0: 'Sekere', 263.0: 'Sharawa', 264.0: 'Shomo', 265.0: 'Shuwa', 266.0: 'Somunka', 267.0: 'Sullubawa', 268.0: 'Sura', 269.0: 'Taira', 270.0: 'Tangale', 272.0: 'Tarok', 273.0: 'Tera', 274.0: 'Teskwa', 275.0: 'Tiguni ( ? )', 276.0: 'Tiv', 277.0: 'Tiyari', 278.0: 'Tula', 279.0: 'Ubaija', 280.0: 'Ugbia', 281.0: 'Uhionigbe', 282.0: 'Ukwuani', 283.0: 'Urhobo', 284.0: 'Uyo', 285.0: 'Uzaurue', 286.0: 'Uzeba', 287.0: 'Waja', 288.0: 'Waka', 289.0: 'Wanu', 290.0: 'Wari', 291.0: 'Warjawa', 292.0: 'Wodaabe', 293.0: 'Wurkum', 294.0: 'Yakurr', 295.0: 'Yandang', 296.0: 'Yendre', 297.0: 'Yonubi', 298.0: 'Yoruba', 299.0: 'Zabarmawa', 301.0: 'Kaje', 302.0: 'Igbanko', 303.0: 'Okori/Ogori', 304.0: 'Migili', 305.0: 'Gwari', 306.0: 'Uru', 307.0: 'Okirika', 308.0: 'Egi', 309.0: 'Ogba', 310.0: 'Moroa', 311.0: 'Marwa', 312.0: 'Toff', 313.0: 'Fulfulde', 314.0: 'Kabba/Okun', 315.0: 'Bakabe', 316.0: 'Burmanch', 317.0: 'Kalabari', 320.0: 'Miship', 321.0: 'Karimjo', 322.0: 'Kwa', 323.0: 'Angas', 324.0: 'Bobari', 325.0: 'Yarimawa', 326.0: 'Bakenga', 327.0: 'Agazawa', 328.0: 'Gwoza', 329.0: 'Zalidva', 330.0: 'Nyangdang', 331.0: 'Ngezim', 332.0: 'Hanbagda', 333.0: 'Njanyi', 334.0: 'Dumak', 335.0: 'Kwalla', 336.0: 'Yeskwa and Mubula', 337.0: 'Bile', 338.0: 'Offa', 339.0: 'Yungur', 340.0: 'Pura Pura', 341.0: 'Rindre', 342.0: 'Dukawa', 343.0: 'Ningi', 344.0: 'Cham', 345.0: 'Kamo', 346.0: 'Lala', 347.0: 'Laru', 348.0: 'Lisa', 349.0: 'Gaanda', 350.0: 'Ezza', 351.0: 'Kubasawa.', 352.0: 'Gusu', 353.0: 'Ikpoma', 354.0: 'Buh', 355.0: 'Mushere', 356.0: 'Chakeem', 357.0: 'Jipal', 358.0: 'Ugeb', 359.0: 'Koma', 360.0: 'Verre/Kila', 361.0: 'Zuru', 362.0: 'Honna', 363.0: 'Kapsiki', 364.0: 'Jere', 365.0: 'Gizi Yobe', 366.0: 'Karekare', 367.0: 'Kulere', 368.0: 'Beteer', 369.0: 'Bashama', 370.0: 'Antocha', 371.0: 'Baruba/Baruntin', 372.0: 'Nezou', 373.0: 'Dibba', 374.0: 'Kanum', 375.0: 'Gasawa', 376.0: 'Muryan', 377.0: 'Bageri', 378.0: 'Ahu', 379.0: 'Basange', 380.0: 'Nakere', 381.0: 'Batunu', 382.0: 'Sanga', 383.0: 'Ohari', 384.0: 'Numuro', 385.0: 'Tangale', 386.0: 'Guruma', 387.0: 'Otuwo', 388.0: 'Batala', 389.0: 'Ogbo', 390.0: 'Egbema', 391.0: 'Dara', 392.0: 'Andoni', 393.0: 'Obolo', 394.0: 'Pegan', 395.0: 'Iyala', 396.0: 'Jibawa', 397.0: 'Mungaduso', 398.0: 'Okobo', 996.0: 'Others', 998.0: "Don't Know"}, 'V133': {97.0: 'Inconsistent'}, 'V134': {0.0: 'Capital, large city', 1.0: 'Small city', 2.0: 'Town', 3.0: 'Countryside'}, 'V135': {1.0: 'Usual resident', 2.0: 'Visitor'}, 'V139': {0.0: 'Abroad', 1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun', 97.0: 'Not dejure resident'}, 'V140': {0.0: 'Abroad', 1.0: 'Urban', 2.0: 'Rural', 7.0: 'Not a dejure resident'}, 'V141': {0.0: 'Capital, large city', 1.0: 'City', 2.0: 'Town', 3.0: 'Countryside', 4.0: 'Abroad', 7.0: 'Not a dejure resident'}, 'V149': {0.0: 'No education', 1.0: 'Incomplete primary', 2.0: 'Complete primary', 3.0: 'Incomplete secondary', 4.0: 'Complete secondary', 5.0: 'Higher'}, 'V150': {1.0: 'Head', 2.0: 'Wife', 3.0: 'Daughter', 4.0: 'Daughter-in-law', 5.0: 'Granddaughter', 6.0: 'Mother', 7.0: 'Mother-in-law', 8.0: 'Sister', 9.0: 'Co-spouse', 10.0: 'Other relative', 11.0: 'Adopted/foster child', 12.0: 'Not related', 98.0: "Don't know"}, 'V151': {1.0: 'Male', 2.0: 'Female'}, 'V152': {97.0: '97+', 98.0: "Don't know"}, 'V153': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'V155': {0.0: 'Cannot read at all', 1.0: 'Able to read only parts of sentence', 2.0: 'Able to read whole sentence', 3.0: 'No card with required language', 4.0: 'Blind/visually impaired'}, 'V156': {0.0: 'No', 1.0: 'Yes'}, 'V157': {0.0: 'Not at all', 1.0: 'Less than once a week', 2.0: 'At least once a week', 3.0: 'Almost every day'}, 'V158': {0.0: 'Not at all', 1.0: 'Less than once a week', 2.0: 'At least once a week', 3.0: 'Almost every day'}, 'V159': {0.0: 'Not at all', 1.0: 'Less than once a week', 2.0: 'At least once a week', 3.0: 'Almost every day'}, 'V160': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'V161': {1.0: 'Electricity', 2.0: 'Solar cooker', 3.0: 'LPG', 4.0: 'Natural gas', 5.0: 'Biogas', 6.0: 'Alcohol/ethanol', 7.0: 'Gasoline/diesel', 8.0: 'Kerosene/paraffin', 9.0: 'Coal/lignite', 10.0: 'Charcoal', 11.0: 'Wood', 12.0: 'Straw/shrubs/grass', 13.0: 'Agricultural crop', 14.0: 'Animal dung/waste', 15.0: 'Processed biomass (pellets) or woodchips', 16.0: 'Garbage/plastic', 17.0: 'Sawdust', 95.0: 'No food cooked in house', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'V169A': {0.0: 'No', 1.0: 'Yes'}, 'V169C': {0.0: 'No', 1.0: 'Yes'}, 'V171A': {0.0: 'Never', 1.0: 'Yes, last 12 months', 2.0: 'Yes, before last 12 months', 3.0: "Yes, can't establish when"}, 'V171B': {0.0: 'Not at all', 1.0: 'Less than once a week', 2.0: 'At least once a week', 3.0: 'Almost every day'}, 'V190': {1.0: 'Poorest', 2.0: 'Poorer', 3.0: 'Middle', 4.0: 'Richer', 5.0: 'Richest'}, 'V190A': {1.0: 'Poorest', 2.0: 'Poorer', 3.0: 'Middle', 4.0: 'Richer', 5.0: 'Richest'}, 'ML101': {0.0: 'No net', 1.0: 'Only treated nets', 2.0: 'Both treated and untreated nets', 3.0: 'Only untreated nets'}, 'V459': {0.0: 'No', 1.0: 'Yes'}, 'V460': {0.0: 'No', 1.0: 'All children', 2.0: 'Some children', 3.0: 'No net in household'}, 'V461': {0.0: 'No', 1.0: 'Yes'}, 'V468': {0.0: 'See specific questions', 1.0: 'Last birth only', 2.0: 'All births in last 5 years'}, 'B0': {0.0: 'Single birth', 1.0: '1st of multiple', 2.0: '2nd of multiple', 3.0: '3rd of multiple', 4.0: '4th of multiple', 5.0: '5th of multiple'}, 'B4': {1.0: 'Male', 2.0: 'Female'}, 'B5': {0.0: 'No', 1.0: 'Yes'}, 'B6': {100.0: 'Died on day of birth', 101.0: 'Days: 1', 199.0: 'Days: number missing', 201.0: 'Months: 1', 299.0: 'Months: number missing', 301.0: 'Years: 1', 399.0: 'Years: number missing', 997.0: 'Inconsistent', 998.0: "Don't know"}, 'B9': {0.0: 'Respondent', 1.0: 'Father', 2.0: 'Other relative', 3.0: 'Someone else', 4.0: 'Lives elsewhere'}, 'B10': {0.0: 'Month, year and day', 1.0: 'Month and year - information complete', 2.0: 'Month and age - year imputed', 3.0: 'Year and age - month imputed', 4.0: 'Year and age - year ignored', 5.0: 'Year - age/month imputed', 6.0: 'Age - year/month imputed', 7.0: 'Month - age/year imputed', 8.0: 'None - all imputed'}, 'B13': {0.0: 'No flag', 1.0: '> interview', 2.0: '< breastfeeding', 3.0: '< age supplemented', 4.0: '< first breastfed', 5.0: '< last vaccination', 6.0: 'Outside range', 7.0: 'Imputed, units given', 8.0: 'Imputed, no units'}, 'B15': {0.0: 'No', 1.0: 'Yes'}, 'B16': {0.0: 'Not listed in household'}, 'V208': {0.0: 'No births'}, 'V209': {0

In [14]:
print(meta.value_labels)

{'labels0': {1.0: '15-19', 2.0: '20-24', 3.0: '25-29', 4.0: '30-34', 5.0: '35-39', 6.0: '40-44', 7.0: '45-49'}, 'labels1': {1.0: 'Month and year - information complete', 2.0: 'Month and age - year imputed', 3.0: 'Year and age - month imputed', 4.0: 'Year and age - year ignored', 5.0: 'Year - age/month imputed', 6.0: 'Age - year/month imputed', 7.0: 'Month - age/year imputed', 8.0: 'None - all imputed'}, 'labels2': {1.0: 'Completed', 2.0: 'Not at home', 3.0: 'Postponed', 4.0: 'Refused', 5.0: 'Partially completed', 6.0: 'Respondent incapacitated', 7.0: 'Other'}, 'labels3': {1.0: 'Abia_Urban', 2.0: 'Abia_Rural', 3.0: 'Adamawa_Urban', 4.0: 'Adamawa_Rural', 5.0: 'Akwa Ibom_Urban', 6.0: 'Akwa Ibom_Rural', 7.0: 'Anambra_Urban', 8.0: 'Anambra_Rural', 9.0: 'Bauchi_Urban', 10.0: 'Bauchi_Rural', 11.0: 'Bayelsa_Urban', 12.0: 'Bayelsa_Rural', 13.0: 'Benue_Urban', 14.0: 'Benue_Rural', 15.0: 'Borno_Urban', 16.0: 'Borno_Rural', 17.0: 'Cross River_Urban', 18.0: 'Cross River_Rural', 19.0: 'Delta_Urban', 20.0: 'Delta_Rural', 21.0: 'Ebonyi_Urban', 22.0: 'Ebonyi_Rural', 23.0: 'Edo_Urban', 24.0: 'Edo_Rural', 25.0: 'Ekiti_Urban', 26.0: 'Ekiti_Rural', 27.0: 'Enugu_Urban', 28.0: 'Enugu_Rural', 29.0: 'Fct_Urban', 30.0: 'Fct_Rural', 31.0: 'Gombe_Urban', 32.0: 'Gombe_Rural', 33.0: 'Imo_Urban', 34.0: 'Imo_Rural', 35.0: 'Jigawa_Urban', 36.0: 'Jigawa_Rural', 37.0: 'Kaduna_Urban', 38.0: 'Kaduna_Rural', 39.0: 'Kano_Urban', 40.0: 'Kano_Rural', 41.0: 'Katsina_Urban', 42.0: 'Katsina_Rural', 43.0: 'Kebbi_Urban', 44.0: 'Kebbi_Rural', 45.0: 'Kogi_Urban', 46.0: 'Kogi_Rural', 47.0: 'Kwara_Urban', 48.0: 'Kwara_Rural', 49.0: 'Lagos_Urban', 50.0: 'Lagos_Rural', 51.0: 'Nasarawa_Urban', 52.0: 'Nasarawa_Rural', 53.0: 'Niger_Urban', 54.0: 'Niger_Rural', 55.0: 'Ogun_Urban', 56.0: 'Ogun_Rural', 57.0: 'Ondo_Urban', 58.0: 'Ondo_Rural', 59.0: 'Osun_Urban', 60.0: 'Osun_Rural', 61.0: 'Oyo_Urban', 62.0: 'Oyo_Rural', 63.0: 'Plateau_Urban', 64.0: 'Plateau_Rural', 65.0: 'Rivers_Urban', 66.0: 'Rivers_Urban', 67.0: 'Rivers_Rural', 68.0: 'Rivers_Rural', 69.0: 'Sokoto_Urban', 70.0: 'Sokoto_Rural', 71.0: 'Taraba_Urban', 72.0: 'Taraba_Rural', 73.0: 'Yobe_Urban', 74.0: 'Yobe_Rural', 75.0: 'Zamfara_Urban', 76.0: 'Zamfara_Rural'}, 'labels4': {1.0: 'Abia_Urban', 2.0: 'Abia_Rural', 3.0: 'Adamawa_Urban', 4.0: 'Adamawa_Rural', 5.0: 'Akwa Ibom_Urban', 6.0: 'Akwa Ibom_Rural', 7.0: 'Anambra_Urban', 8.0: 'Anambra_Rural', 9.0: 'Bauchi_Urban', 10.0: 'Bauchi_Rural', 11.0: 'Bayelsa_Urban', 12.0: 'Bayelsa_Rural', 13.0: 'Benue_Urban', 14.0: 'Benue_Rural', 15.0: 'Borno_Urban', 16.0: 'Borno_Rural', 17.0: 'Cross River_Urban', 18.0: 'Cross River_Rural', 19.0: 'Delta_Urban', 20.0: 'Delta_Rural', 21.0: 'Ebonyi_Urban', 22.0: 'Ebonyi_Rural', 23.0: 'Edo_Urban', 24.0: 'Edo_Rural', 25.0: 'Ekiti_Urban', 26.0: 'Ekiti_Rural', 27.0: 'Enugu_Urban', 28.0: 'Enugu_Rural', 29.0: 'Fct_Urban', 30.0: 'Fct_Rural', 31.0: 'Gombe_Urban', 32.0: 'Gombe_Rural', 33.0: 'Imo_Urban', 34.0: 'Imo_Rural', 35.0: 'Jigawa_Urban', 36.0: 'Jigawa_Rural', 37.0: 'Kaduna_Urban', 38.0: 'Kaduna_Rural', 39.0: 'Kano_Urban', 40.0: 'Kano_Rural', 41.0: 'Katsina_Urban', 42.0: 'Katsina_Rural', 43.0: 'Kebbi_Urban', 44.0: 'Kebbi_Rural', 45.0: 'Kogi_Urban', 46.0: 'Kogi_Rural', 47.0: 'Kwara_Urban', 48.0: 'Kwara_Rural', 49.0: 'Lagos_Urban', 50.0: 'Lagos_Rural', 51.0: 'Nasarawa_Urban', 52.0: 'Nasarawa_Rural', 53.0: 'Niger_Urban', 54.0: 'Niger_Rural', 55.0: 'Ogun_Urban', 56.0: 'Ogun_Rural', 57.0: 'Ondo_Urban', 58.0: 'Ondo_Rural', 59.0: 'Osun_Urban', 60.0: 'Osun_Rural', 61.0: 'Oyo_Urban', 62.0: 'Oyo_Rural', 63.0: 'Plateau_Urban', 64.0: 'Plateau_Rural', 65.0: 'Rivers_Urban', 66.0: 'Rivers_Urban', 67.0: 'Rivers_Rural', 68.0: 'Rivers_Rural', 69.0: 'Sokoto_Urban', 70.0: 'Sokoto_Rural', 71.0: 'Taraba_Urban', 72.0: 'Taraba_Rural', 73.0: 'Yobe_Urban', 74.0: 'Yobe_Rural', 75.0: 'Zamfara_Urban', 76.0: 'Zamfara_Rural'}, 'labels5': {1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}, 'labels6': {1.0: 'Urban', 2.0: 'Rural'}, 'labels7': {0.0: 'Capital, large city', 1.0: 'Small city', 2.0: 'Town', 3.0: 'Countryside'}, 'labels8': {0.0: 'Husband not in household'}, 'labels9': {0.0: 'Not selected', 1.0: 'Selected'}, 'labels10': {1.0: 'English', 2.0: 'Hausa', 3.0: 'Yoruba', 4.0: 'Igbo'}, 'labels11': {1.0: 'English', 2.0: 'Hausa', 3.0: 'Yoruba', 4.0: 'Igbo', 5.0: 'Fulfulde', 6.0: 'Other'}, 'labels12': {1.0: 'English', 2.0: 'Hausa', 3.0: 'Yoruba', 4.0: 'Igbo', 5.0: 'Fulfulde', 6.0: 'Other'}, 'labels13': {0.0: 'No', 1.0: 'Yes'}, 'labels14': {1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}, 'labels15': {1.0: 'Urban', 2.0: 'Rural'}, 'labels16': {0.0: 'No education', 1.0: 'Primary', 2.0: 'Secondary', 3.0: 'Higher'}, 'labels17': {0.0: 'No years completed at level V106'}, 'labels18': {10.0: 'PIPED WATER', 11.0: 'Piped into dwelling', 12.0: 'Piped to yard/plot', 13.0: 'Piped to neighbor', 14.0: 'Public tap/standpipe', 20.0: 'TUBE WELL WATER', 21.0: 'Tube well or borehole', 30.0: 'DUG WELL (OPEN/PROTECTED)', 31.0: 'Protected well', 32.0: 'Unprotected well', 40.0: 'SURFACE FROM SPRING', 41.0: 'Protected spring', 42.0: 'Unprotected spring', 43.0: 'River/dam/lake/ponds/stream/canal/irrigation channel', 51.0: 'Rainwater', 61.0: 'Tanker truck', 62.0: 'Cart with small tank', 71.0: 'Bottled water', 72.0: 'Sachet water', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'labels19': {996.0: 'On premises', 997.0: 'Not a dejure resident', 998.0: "Don't know"}, 'labels20': {10.0: 'FLUSH TOILET', 11.0: 'Flush to piped sewer system', 12.0: 'Flush to septic tank', 13.0: 'Flush to pit latrine', 14.0: 'Flush to somewhere else', 15.0: "Flush, don't know where", 20.0: 'PIT TOILET LATRINE', 21.0: 'Ventilated Improved Pit latrine (VIP)', 22.0: 'Pit latrine with slab', 23.0: 'Pit latrine without slab/open pit', 30.0: 'NO FACILITY', 31.0: 'No facility/bush/field', 41.0: 'Composting toilet', 42.0: 'Bucket toilet', 43.0: 'Hanging toilet/latrine', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'labels21': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'labels22': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'labels23': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'labels24': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'labels25': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'labels26': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'labels27': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'labels28': {10.0: 'NATURAL', 11.0: 'Earth/sand', 12.0: 'Dung', 20.0: 'RUDIMENTARY', 21.0: 'Wood planks', 22.0: 'Palm/bamboo', 30.0: 'FINISHED', 31.0: 'Parquet or polished wood', 32.0: 'Vinyl or asphalt strips', 33.0: 'Ceramic tiles', 34.0: 'Cement', 35.0: 'Carpet', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'labels29': {10.0: 'NATURAL', 11.0: 'No walls', 12.0: 'Cane/palm/trunks', 13.0: 'Dirt', 20.0: 'RUDIMENTARY', 21.0: 'Bamboo with mud', 22.0: 'Stone with mud', 23.0: 'Uncovered adobe', 24.0: 'Plywood', 25.0: 'Cardboard', 26.0: 'Reused wood', 30.0: 'FINISHED', 31.0: 'Cement', 32.0: 'Stone with lime/cement', 33.0: 'Bricks', 34.0: 'Cement blocks', 35.0: 'Covered adobe', 36.0: 'Wood planks/shingles', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'labels30': {10.0: 'NATURAL', 11.0: 'No roof', 12.0: 'Thatch/palm leaf', 13.0: 'Grass', 20.0: 'RUDIMENTARY', 21.0: 'Rustic mat', 22.0: 'Palm/bamboo', 23.0: 'Wood planks', 24.0: 'Cardboard', 30.0: 'FINISHED', 31.0: 'Metal/Zinc', 32.0: 'Wood', 33.0: 'Calamine/cement fiber', 34.0: 'Ceramic tiles', 35.0: 'Cement', 36.0: 'Roofing shingles', 37.0: 'Asbestos', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'labels31': {1.0: 'Catholic', 2.0: 'Other Christian', 3.0: 'Islam', 4.0: 'Traditionalist', 96.0: 'Other'}, 'labels32': {1.0: 'Abua', 2.0: 'Adra/Adarawa', 3.0: 'Adun', 4.0: 'Afcabeya', 5.0: 'Afemai', 6.0: 'Afizire', 7.0: 'Agatu', 8.0: 'Agbassa', 9.0: 'Agbor', 10.0: 'Afo', 11.0: 'Ajowa', 12.0: 'Akpa', 13.0: 'Akwai', 14.0: 'Akye', 15.0: 'Alago', 16.0: 'Amamong', 17.0: 'Amo', 18.0: 'Ana', 19.0: 'Anaguta', 20.0: 'Ankwai', 21.0: 'Annang', 22.0: 'Arab', 23.0: 'Arabo', 24.0: 'Arbar', 25.0: 'Arugu', 26.0: 'Aten/Atam', 27.0: 'Attakar', 28.0: 'Auchi', 29.0: 'Aulliminden', 30.0: 'Awo', 31.0: 'Ayetoro Gbede', 32.0: 'Badarare', 33.0: 'Bade/Badawe', 34.0: 'Bafeke', 35.0: 'Bagathiya', 36.0: 'Baggara', 37.0: 'Bagunge/Badagire', 38.0: 'Bahnake', 39.0: 'Baji/Biji', 40.0: 'Bajju', 41.0: 'Bambaro', 42.0: 'Bambuka', 43.0: 'Bandawa', 44.0: 'Banguji', 45.0: 'Bankalawa', 46.0: 'Bchama', 47.0: 'Barabaci', 48.0: 'Barawa', 49.0: 'Bargawa', 50.0: 'Bassa', 51.0: 'Bekworas', 53.0: 'Berom', 54.0: 'Bini/Edo', 55.0: 'Bogom', 56.0: 'Boiyawa/Bozaya', 57.0: 'Bolawa/Bolewa', 59.0: 'Buduma', 60.0: 'Buko', 61.0: 'Bura/Babur', 62.0: 'Buzu', 63.0: 'Byazhi', 64.0: 'Calabar', 65.0: 'Chala', 66.0: 'Chamba', 67.0: 'Chiba', 68.0: 'Chibok(g)', 69.0: 'Chip', 70.0: 'Dadiya', 71.0: 'Badakare/Dakarkari', 72.0: 'Dakka/Doka', 73.0: 'Dangula', 74.0: 'Daurawa/Dagarawa', 75.0: 'Defaka', 76.0: 'Degima', 77.0: 'Delta Ibo', 78.0: 'Dibo', 79.0: 'Diguza', 80.0: 'Djerma', 81.0: 'Dmoko', 82.0: 'Dolchi', 83.0: 'Ebira/Igbira', 84.0: 'Ebu', 85.0: 'Efik', 86.0: 'Egba', 87.0: 'Egbado', 88.0: 'Eggon', 89.0: 'Egun', 90.0: 'Eket', 91.0: 'Ekoi', 92.0: 'Ekpeye/Afisa/Epie', 94.0: 'Ekulu', 95.0: 'Eleme', 96.0: 'Emu', 97.0: 'Esan', 98.0: 'Etina', 99.0: 'Etsako', 100.0: 'Etulo', 101.0: 'Hadejawa', 102.0: 'Fanso', 103.0: 'Femawa', 104.0: 'Fer', 105.0: 'Filiya/Fali', 106.0: 'Fon', 107.0: 'Foron', 108.0: 'French', 109.0: 'Fulani', 110.0: 'Gamaku', 111.0: 'Gamaru', 112.0: 'Gamuni', 113.0: 'Gana Gana', 114.0: 'Ganawuri', 115.0: 'Gbaju/Gbagi', 116.0: 'Gede/Gude/Gai', 117.0: 'Gerawa', 118.0: 'Gizmawa', 119.0: 'Glauda', 120.0: 'Gmenchi', 121.0: 'Gomo/Gamoyaya', 122.0: 'Gobiri/Gobirawa/Bogobiri', 123.0: 'Gujjurawa', 124.0: 'Guemai', 125.0: 'Gumbarawa', 126.0: 'Gunganchi', 127.0: 'Gwandara', 128.0: 'Gwantu', 129.0: 'Hankwe', 130.0: 'Hausa', 131.0: 'Higgi', 132.0: 'Ibariba', 133.0: 'Ibibio', 134.0: 'Ichen', 135.0: 'Idanre', 136.0: 'Idoma', 137.0: 'Igala', 138.0: 'Igbo/Ibo', 139.0: 'Igede', 140.0: 'Ijaw/Izon', 141.0: 'Ijede', 142.0: 'Ijeme', 143.0: 'Ika', 144.0: 'Ikajo', 145.0: 'Ikara', 146.0: 'Ikpeshi', 147.0: 'Ikpide', 148.0: 'Ikulu', 149.0: 'Ikwere', 150.0: 'Ilaje', 151.0: 'Irigwe', 152.0: 'Ishan', 153.0: 'Isoko', 154.0: 'Itsekiri', 155.0: 'Jaba', 156.0: 'Jajiri', 157.0: 'Jakatoe', 158.0: 'Jaku', 159.0: 'Jara', 160.0: 'Jarawa', 162.0: 'Jibu', 163.0: 'Jonjo', 164.0: 'Jukun', 165.0: 'Kabawa', 166.0: 'Kadara', 167.0: 'Kagoma', 168.0: 'Kagoro', 169.0: 'Kaka', 170.0: 'Kakanda', 171.0: 'Kamantam', 172.0: 'Kambari', 173.0: 'Kambu/Kangu', 174.0: 'Kamuku', 175.0: 'Kanakuru', 176.0: 'Kanawa', 177.0: 'Kaninko', 178.0: 'Kantanawa', 179.0: 'Kanuri/Beriberi', 180.0: 'Manga', 181.0: 'Karekare', 182.0: 'Kataf/Atyap', 183.0: 'Kento', 184.0: 'Kibaku', 185.0: 'Kilba', 186.0: 'Kirdi', 187.0: 'Kodki', 188.0: 'Kofyar', 189.0: 'Kona', 190.0: 'Koro', 191.0: 'Koto', 192.0: 'Kuenuem', 193.0: 'Kumbo', 194.0: 'Kunkawa/Kawa', 195.0: 'Kurama', 196.0: 'Kuteb', 197.0: 'Kuturm', 198.0: 'Kwale/Ukwuani', 199.0: 'Kwanzo', 200.0: 'Lagelu', 201.0: 'Lantang', 202.0: 'Lemoro', 203.0: 'Loh', 204.0: 'Lunguda', 205.0: 'Maba/Mbadowa', 206.0: 'Mada', 207.0: 'Mafa/Maka/Maga', 208.0: 'Mambila', 209.0: 'Mandara', 210.0: 'Mangus/Manju', 211.0: 'Marghi/mangi', 212.0: 'Mbwa', 213.0: 'Mingo', 214.0: 'Mirnang', 215.0: 'Montor', 216.0: 'Mtchiga/Michika', 217.0: 'Mumuye', 218.0: 'Munga', 219.0: 'Mupung', 220.0: 'Mushere', 221.0: 'Mwagavol', 222.0: 'Naiawum', 223.0: 'Namoen', 224.0: 'Ndokwa', 225.0: 'Ndola', 226.0: 'Ngamo', 227.0: 'Ukale', 228.0: 'Ngoshe', 229.0: 'Nili', 230.0: 'Ninnma', 231.0: 'Ninzom', 232.0: 'Nkoroo', 233.0: 'Nnebe', 234.0: 'Numana', 235.0: 'Nungu', 236.0: 'nunku', 237.0: 'Nupe', 238.0: 'Obubua', 239.0: 'Odu', 240.0: 'Ogoja', 241.0: 'Ogoni', 242.0: 'Ogugu', 243.0: 'Okori/Ogori', 244.0: 'Omele', 245.0: 'Ora', 246.0: 'Oron', 247.0: 'Owan', 249.0: 'Owo', 250.0: "Pa'awa", 251.0: 'Paburi', 252.0: 'Paibun', 253.0: 'Panya', 254.0: 'Pasama', 255.0: 'Pero', 256.0: 'Piya', 257.0: 'Pyem', 258.0: 'Rukuba', 259.0: 'Rulere', 260.0: 'Rundawa', 261.0: 'Sayawa/Siyawa', 262.0: 'Sekere', 263.0: 'Sharawa', 264.0: 'Shomo', 265.0: 'Shuwa', 266.0: 'Somunka', 267.0: 'Sullubawa', 268.0: 'Sura', 269.0: 'Taira', 270.0: 'Tangale', 272.0: 'Tarok', 273.0: 'Tera', 274.0: 'Teskwa', 275.0: 'Tiguni ( ? )', 276.0: 'Tiv', 277.0: 'Tiyari', 278.0: 'Tula', 279.0: 'Ubaija', 280.0: 'Ugbia', 281.0: 'Uhionigbe', 282.0: 'Ukwuani', 283.0: 'Urhobo', 284.0: 'Uyo', 285.0: 'Uzaurue', 286.0: 'Uzeba', 287.0: 'Waja', 288.0: 'Waka', 289.0: 'Wanu', 290.0: 'Wari', 291.0: 'Warjawa', 292.0: 'Wodaabe', 293.0: 'Wurkum', 294.0: 'Yakurr', 295.0: 'Yandang', 296.0: 'Yendre', 297.0: 'Yonubi', 298.0: 'Yoruba', 299.0: 'Zabarmawa', 301.0: 'Kaje', 302.0: 'Igbanko', 303.0: 'Okori/Ogori', 304.0: 'Migili', 305.0: 'Gwari', 306.0: 'Uru', 307.0: 'Okirika', 308.0: 'Egi', 309.0: 'Ogba', 310.0: 'Moroa', 311.0: 'Marwa', 312.0: 'Toff', 313.0: 'Fulfulde', 314.0: 'Kabba/Okun', 315.0: 'Bakabe', 316.0: 'Burmanch', 317.0: 'Kalabari', 320.0: 'Miship', 321.0: 'Karimjo', 322.0: 'Kwa', 323.0: 'Angas', 324.0: 'Bobari', 325.0: 'Yarimawa', 326.0: 'Bakenga', 327.0: 'Agazawa', 328.0: 'Gwoza', 329.0: 'Zalidva', 330.0: 'Nyangdang', 331.0: 'Ngezim', 332.0: 'Hanbagda', 333.0: 'Njanyi', 334.0: 'Dumak', 335.0: 'Kwalla', 336.0: 'Yeskwa and Mubula', 337.0: 'Bile', 338.0: 'Offa', 339.0: 'Yungur', 340.0: 'Pura Pura', 341.0: 'Rindre', 342.0: 'Dukawa', 343.0: 'Ningi', 344.0: 'Cham', 345.0: 'Kamo', 346.0: 'Lala', 347.0: 'Laru', 348.0: 'Lisa', 349.0: 'Gaanda', 350.0: 'Ezza', 351.0: 'Kubasawa.', 352.0: 'Gusu', 353.0: 'Ikpoma', 354.0: 'Buh', 355.0: 'Mushere', 356.0: 'Chakeem', 357.0: 'Jipal', 358.0: 'Ugeb', 359.0: 'Koma', 360.0: 'Verre/Kila', 361.0: 'Zuru', 362.0: 'Honna', 363.0: 'Kapsiki', 364.0: 'Jere', 365.0: 'Gizi Yobe', 366.0: 'Karekare', 367.0: 'Kulere', 368.0: 'Beteer', 369.0: 'Bashama', 370.0: 'Antocha', 371.0: 'Baruba/Baruntin', 372.0: 'Nezou', 373.0: 'Dibba', 374.0: 'Kanum', 375.0: 'Gasawa', 376.0: 'Muryan', 377.0: 'Bageri', 378.0: 'Ahu', 379.0: 'Basange', 380.0: 'Nakere', 381.0: 'Batunu', 382.0: 'Sanga', 383.0: 'Ohari', 384.0: 'Numuro', 385.0: 'Tangale', 386.0: 'Guruma', 387.0: 'Otuwo', 388.0: 'Batala', 389.0: 'Ogbo', 390.0: 'Egbema', 391.0: 'Dara', 392.0: 'Andoni', 393.0: 'Obolo', 394.0: 'Pegan', 395.0: 'Iyala', 396.0: 'Jibawa', 397.0: 'Mungaduso', 398.0: 'Okobo', 996.0: 'Others', 998.0: "Don't Know"}, 'labels33': {97.0: 'Inconsistent'}, 'labels34': {0.0: 'Capital, large city', 1.0: 'Small city', 2.0: 'Town', 3.0: 'Countryside'}, 'labels35': {1.0: 'Usual resident', 2.0: 'Visitor'}, 'labels36': {0.0: 'Abroad', 1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun', 97.0: 'Not dejure resident'}, 'labels37': {0.0: 'Abroad', 1.0: 'Urban', 2.0: 'Rural', 7.0: 'Not a dejure resident'}, 'labels38': {0.0: 'Capital, large city', 1.0: 'City', 2.0: 'Town', 3.0: 'Countryside', 4.0: 'Abroad', 7.0: 'Not a dejure resident'}, 'labels39': {0.0: 'No education', 1.0: 'Incomplete primary', 2.0: 'Complete primary', 3.0: 'Incomplete secondary', 4.0: 'Complete secondary', 5.0: 'Higher'}, 'labels40': {1.0: 'Head', 2.0: 'Wife', 3.0: 'Daughter', 4.0: 'Daughter-in-law', 5.0: 'Granddaughter', 6.0: 'Mother', 7.0: 'Mother-in-law', 8.0: 'Sister', 9.0: 'Co-spouse', 10.0: 'Other relative', 11.0: 'Adopted/foster child', 12.0: 'Not related', 98.0: "Don't know"}, 'labels41': {1.0: 'Male', 2.0: 'Female'}, 'labels42': {97.0: '97+', 98.0: "Don't know"}, 'labels43': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'labels44': {0.0: 'Cannot read at all', 1.0: 'Able to read only parts of sentence', 2.0: 'Able to read whole sentence', 3.0: 'No card with required language', 4.0: 'Blind/visually impaired'}, 'labels45': {0.0: 'No', 1.0: 'Yes'}, 'labels46': {0.0: 'Not at all', 1.0: 'Less than once a week', 2.0: 'At least once a week', 3.0: 'Almost every day'}, 'labels47': {0.0: 'Not at all', 1.0: 'Less than once a week', 2.0: 'At least once a week', 3.0: 'Almost every day'}, 'labels48': {0.0: 'Not at all', 1.0: 'Less than once a week', 2.0: 'At least once a week', 3.0: 'Almost every day'}, 'labels49': {0.0: 'No', 1.0: 'Yes', 7.0: 'Not a dejure resident'}, 'labels50': {1.0: 'Electricity', 2.0: 'Solar cooker', 3.0: 'LPG', 4.0: 'Natural gas', 5.0: 'Biogas', 6.0: 'Alcohol/ethanol', 7.0: 'Gasoline/diesel', 8.0: 'Kerosene/paraffin', 9.0: 'Coal/lignite', 10.0: 'Charcoal', 11.0: 'Wood', 12.0: 'Straw/shrubs/grass', 13.0: 'Agricultural crop', 14.0: 'Animal dung/waste', 15.0: 'Processed biomass (pellets) or woodchips', 16.0: 'Garbage/plastic', 17.0: 'Sawdust', 95.0: 'No food cooked in house', 96.0: 'Other', 97.0: 'Not a dejure resident'}, 'labels51': {0.0: 'No', 1.0: 'Yes'}, 'labels52': {0.0: 'No', 1.0: 'Yes'}, 'labels53': {0.0: 'Never', 1.0: 'Yes, last 12 months', 2.0: 'Yes, before last 12 months', 3.0: "Yes, can't establish when"}, 'labels54': {0.0: 'Not at all', 1.0: 'Less than once a week', 2.0: 'At least once a week', 3.0: 'Almost every day'}, 'labels55': {1.0: 'Poorest', 2.0: 'Poorer', 3.0: 'Middle', 4.0: 'Richer', 5.0: 'Richest'}, 'labels56': {1.0: 'Poorest', 2.0: 'Poorer', 3.0: 'Middle', 4.0: 'Richer', 5.0: 'Richest'}, 'labels57': {0.0: 'No net', 1.0: 'Only treated nets', 2.0: 'Both treated and untreated nets', 3.0: 'Only untreated nets'}, 'labels58': {0.0: 'No', 1.0: 'Yes'}, 'labels59': {0.0: 'No', 1.0: 'All children', 2.0: 'Some children', 3.0: 'No net in household'}, 'labels60': {0.0: 'No', 1.0: 'Yes'}, 'labels61': {0.0: 'See specific questions', 1.0: 'Last birth only', 2.0: 'All births in last 5 years'}, 'labels62': {0.0: 'Single birth', 1.0: '1st of multiple', 2.0: '2nd of multiple', 3.0: '3rd of multiple', 4.0: '4th of multiple', 5.0: '5th of multiple'}, 'labels63': {1.0: 'Male', 2.0: 'Female'}, 'labels64': {0.0: 'No', 1.0: 'Yes'}, 'labels65': {100.0: 'Died on day of birth', 101.0: 'Days: 1', 199.0: 'Days: number missing', 201.0: 'Months: 1', 299.0: 'Months: number missing', 301.0: 'Years: 1', 399.0: 'Years: number missing', 997.0: 'Inconsistent', 998.0: "Don't know"}, 'labels66': {0.0: 'Respondent', 1.0: 'Father', 2.0: 'Other relative', 3.0: 'Someone else', 4.0: 'Lives elsewhere'}, 'labels67': {0.0: 'Month, year and day', 1.0: 'Month and year - information complete', 2.0: 'Month and age - year imputed', 3.0: 'Year and age - month imputed', 4.0: 'Year and age - year ignored', 5.0: 'Year - age/month imputed', 6.0: 'Age - year/month imputed', 7.0: 'Month - age/year imputed', 8.0: 'None - all imputed'}, 'labels68': {0.0: 'No flag', 1.0: '> interview', 2.0: '< breastfeeding', 

In [15]:
print(meta.variable_to_label)

{'V013': 'labels0', 'V014': 'labels1', 'V015': 'labels2', 'V022': 'labels3', 'V023': 'labels4', 'V024': 'labels5', 'V025': 'labels6', 'V026': 'labels7', 'V034': 'labels8', 'V042': 'labels9', 'V045A': 'labels10', 'V045B': 'labels11', 'V045C': 'labels12', 'V046': 'labels13', 'V101': 'labels14', 'V102': 'labels15', 'V106': 'labels16', 'V107': 'labels17', 'V113': 'labels18', 'V115': 'labels19', 'V116': 'labels20', 'V119': 'labels21', 'V120': 'labels22', 'V121': 'labels23', 'V122': 'labels24', 'V123': 'labels25', 'V124': 'labels26', 'V125': 'labels27', 'V127': 'labels28', 'V128': 'labels29', 'V129': 'labels30', 'V130': 'labels31', 'V131': 'labels32', 'V133': 'labels33', 'V134': 'labels34', 'V135': 'labels35', 'V139': 'labels36', 'V140': 'labels37', 'V141': 'labels38', 'V149': 'labels39', 'V150': 'labels40', 'V151': 'labels41', 'V152': 'labels42', 'V153': 'labels43', 'V155': 'labels44', 'V156': 'labels45', 'V157': 'labels46', 'V158': 'labels47', 'V159': 'labels48', 'V160': 'labels49', 'V161': 'labels50', 'V169A': 'labels51', 'V169C': 'labels52', 'V171A': 'labels53', 'V171B': 'labels54', 'V190': 'labels55', 'V190A': 'labels56', 'ML101': 'labels57', 'V459': 'labels58', 'V460': 'labels59', 'V461': 'labels60', 'V468': 'labels61', 'B0': 'labels62', 'B4': 'labels63', 'B5': 'labels64', 'B6': 'labels65', 'B9': 'labels66', 'B10': 'labels67', 'B13': 'labels68', 'B15': 'labels69', 'B16': 'labels70', 'V208': 'labels71', 'V209': 'labels72', 'V213': 'labels73', 'V214A': 'labels74', 'V220': 'labels75', 'V223': 'labels76', 'V237': 'labels77', 'M2A': 'labels78', 'M2B': 'labels79', 'M2C': 'labels80', 'M2D': 'labels81', 'M2E': 'labels82', 'M2F': 'labels83', 'M2G': 'labels84', 'M2H': 'labels85', 'M2I': 'labels86', 'M2J': 'labels87', 'M2K': 'labels88', 'M2L': 'labels89', 'M2M': 'labels90', 'M2N': 'labels91', 'M13': 'labels92', 'M13A': 'labels93', 'M14': 'labels94', 'M49A': 'labels95', 'M49B': 'labels96', 'M49C': 'labels97', 'M49D': 'labels98', 'M49E': 'labels99', 'M49F': 'labels100', 'M49G': 'labels101', 'M49X': 'labels102', 'M49Z': 'labels103', 'M49Y': 'labels104', 'M57A': 'labels105', 'M57B': 'labels106', 'M57C': 'labels107', 'M57D': 'labels108', 'M57E': 'labels109', 'M57F': 'labels110', 'M57G': 'labels111', 'M57H': 'labels112', 'M57I': 'labels113', 'M57J': 'labels114', 'M57K': 'labels115', 'M57L': 'labels116', 'M57M': 'labels117', 'M57N': 'labels118', 'M57O': 'labels119', 'M57P': 'labels120', 'M57Q': 'labels121', 'M57R': 'labels122', 'M57NA': 'labels123', 'M57NB': 'labels124', 'M57NC': 'labels125', 'M57ND': 'labels126', 'M57NE': 'labels127', 'M57S': 'labels128', 'M57T': 'labels129', 'M57U': 'labels130', 'M57V': 'labels131', 'M57X': 'labels132', 'ML1': 'labels133', 'ML2': 'labels134', 'H22': 'labels135', 'H31': 'labels136', 'H32A': 'labels137', 'H32B': 'labels138', 'H32C': 'labels139', 'H32D': 'labels140', 'H32E': 'labels141', 'H32F': 'labels142', 'H32G': 'labels143', 'H32H': 'labels144', 'H32I': 'labels145', 'H32J': 'labels146', 'H32K': 'labels147', 'H32L': 'labels148', 'H32M': 'labels149', 'H32N': 'labels150', 'H32O': 'labels151', 'H32P': 'labels152', 'H32Q': 'labels153', 'H32R': 'labels154', 'H32NA': 'labels155', 'H32NB': 'labels156', 'H32NC': 'labels157', 'H32ND': 'labels158', 'H32NE': 'labels159', 'H32S': 'labels160', 'H32T': 'labels161', 'H32U': 'labels162', 'H32V': 'labels163', 'H32W': 'labels164', 'H32X': 'labels165', 'H32Y': 'labels166', 'H32Z': 'labels167', 'H46A': 'labels168', 'H46B': 'labels169', 'H47': 'labels170', 'H71': 'labels171', 'HW16': 'labels172', 'HW51': 'labels173', 'HW52': 'labels174', 'HW53': 'labels175', 'HW55': 'labels176', 'HW56': 'labels177', 'HW57': 'labels178', 'HW58': 'labels179', 'ML0': 'labels180', 'ML11': 'labels181', 'ML12': 'labels182', 'ML13A': 'labels183', 'ML13B': 'labels184', 'ML13C': 'labels185', 'ML13D': 'labels186', 'ML13DA': 'labels187', 'ML13E': 'labels188', 'ML13AA': 'labels189', 'ML13AB': 'labels190', 'ML13F': 'labels191', 'ML13G': 'labels192', 'ML13H': 'labels193', 'ML13I': 'labels194', 'ML13J': 'labels195', 'ML13K': 'labels196', 'ML13L': 'labels197', 'ML13M': 'labels198', 'ML13N': 'labels199', 'ML13O': 'labels200', 'ML13P': 'labels201', 'ML13X': 'labels202', 'ML13Y': 'labels203', 'ML13Z': 'labels204', 'ML14A': 'labels205', 'ML14B': 'labels206', 'ML14Y': 'labels207', 'ML14Z': 'labels208', 'ML15A': 'labels209', 'ML15B': 'labels210', 'ML15C': 'labels211', 'ML16A': 'labels212', 'ML16B': 'labels213', 'ML16C': 'labels214', 'ML17A': 'labels215', 'ML17B': 'labels216', 'ML17C': 'labels217', 'ML18A': 'labels218', 'ML18B': 'labels219', 'ML18C': 'labels220', 'ML19A': 'labels221', 'ML19B': 'labels222', 'ML19C': 'labels223', 'ML19D': 'labels224', 'ML19E': 'labels225', 'ML19F': 'labels226', 'ML19X': 'labels227', 'ML19Y': 'labels228', 'ML19Z': 'labels229', 'ML20A': 'labels230', 'ML20B': 'labels231', 'ML20C': 'labels232', 'ML21A': 'labels233', 'ML21B': 'labels234', 'ML21C': 'labels235', 'ML22A': 'labels236', 'ML22B': 'labels237', 'ML22C': 'labels238', 'ML23A': 'labels239', 'ML23B': 'labels240', 'ML23C': 'labels241', 'ML24C': 'labels242', 'ML25A': 'labels243', 'ML501': 'labels244', 'ML501A': 'labels245', 'ML501B': 'labels246', 'ML501C': 'labels247', 'ML501D': 'labels248', 'ML501E': 'labels249', 'ML501F': 'labels250', 'ML501G': 'labels251', 'ML501H': 'labels252', 'ML501I': 'labels253', 'ML501J': 'labels254', 'ML501K': 'labels255', 'ML501X': 'labels256', 'ML501Z': 'labels257', 'ML503': 'labels258', 'ML503A': 'labels259', 'ML503B': 'labels260', 'ML503C': 'labels261', 'ML503D': 'labels262', 'ML503E': 'labels263', 'ML503F': 'labels264', 'ML503G': 'labels265', 'ML503H': 'labels266', 'ML503I': 'labels267', 'ML503J': 'labels268', 'ML503K': 'labels269', 'ML503X': 'labels270', 'ML503Z': 'labels271', 'ML505': 'labels272', 'ML506': 'labels273', 'ML507': 'labels274', 'ML508': 'labels275', 'ML509': 'labels276', 'ML510': 'labels277', 'ML511': 'labels278', 'ML512': 'labels279', 'ML513': 'labels280', 'ML514': 'labels281', 'S512A': 'labels282', 'SREGION': 'labels283', 'SBONNY': 'labels284', 'S104A': 'labels285', 'S104B': 'labels286', 'S211': 'labels287', 'S411A': 'labels288', 'S415A': 'labels289'}

In [10]:
print(df.columns[:20])

Index(['CASEID', 'HIDXA', 'V000', 'V001', 'V002', 'V003', 'V004', 'V005',
       'V006', 'V007', 'V008', 'V008A', 'V009', 'V010', 'V011', 'V012', 'V013',
       'V014', 'V015', 'V016'],
      dtype='object')

In [11]:
print(list(meta.column_names_to_labels.items())[:10])

[('CASEID', 'Case Identification'), ('HIDXA', 'Index to birth history'), ('V000', 'Country code and phase'), ('V001', 'Cluster number'), ('V002', 'Household number'), ('V003', "Respondent's line number"), ('V004', 'Ultimate area unit'), ('V005', "Women's individual sample weight (6 decimals)"), ('V006', 'Month of interview'), ('V007', 'Year of interview')]

In [12]:
print(list(meta.variable_to_label.items())[:10])

[('V013', 'labels0'), ('V014', 'labels1'), ('V015', 'labels2'), ('V022', 'labels3'), ('V023', 'labels4'), ('V024', 'labels5'), ('V025', 'labels6'), ('V026', 'labels7'), ('V034', 'labels8'), ('V042', 'labels9')]

In [19]:
print(list(meta.value_labels.keys())[:20])

['labels0', 'labels1', 'labels2', 'labels3', 'labels4', 'labels5', 'labels6', 'labels7', 'labels8', 'labels9', 'labels10', 'labels11', 'labels12', 'labels13', 'labels14', 'labels15', 'labels16', 'labels17', 'labels18', 'labels19']

In [20]:
first_key = list(meta.value_labels.keys())[0]
print(first_key)
print(meta.value_labels[first_key])

labels0
{1.0: '15-19', 2.0: '20-24', 3.0: '25-29', 4.0: '30-34', 5.0: '35-39', 6.0: '40-44', 7.0: '45-49'}

In [13]:
print(meta.column_names_to_labels.get("V024"))

Region

In [22]:
label_set = meta.variable_to_label.get("V024")

print("Label Set:", label_set)

print(meta.value_labels.get(label_set))

Label Set: labels5
{1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}

In [14]:
selected_vars = [
'V024','V025','V190',
'ML0','ML101',
'ML13A','ML13E','ML13H','ML13Y',
'ML501','ML501A','ML501B','ML501H',
'ML503','ML503A','ML503B',
'ML503E','ML503F','ML503G',
'ML505','ML506','ML507','ML514'
]

for var in selected_vars:

    print("\n" + "="*60)

    print("Variable:", var)

    print(
        "Label:",
        meta.column_names_to_labels.get(var)
    )

    label_set = meta.variable_to_label.get(var)

    print(
        "Label Set:",
        label_set
    )

    print(
        "Codes:",
        meta.value_labels.get(label_set)
    )

============================================================
Variable: V024
Label: Region
Label Set: labels5
Codes: {1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}

============================================================
Variable: V025
Label: Type of place of residence
Label Set: labels6
Codes: {1.0: 'Urban', 2.0: 'Rural'}

============================================================
Variable: V190
Label: Wealth index combined
Label Set: labels55
Codes: {1.0: 'Poorest', 2.0: 'Poorer', 3.0: 'Middle', 4.0: 'Richer', 5.0: 'Richest'}

============================================================
Variable: ML0
Label: Type of mosquito bed net(s) child slept under last night
Label Set: labels180
Codes: {0.0: 'No net', 1.0: 'Only treated nets', 2.0: 'Both treated and untreated nets', 3.0: 'Only untreated nets'}

============================================================
Variable: ML101
Label: Type of mosquito bed net(s) slept under last night
Label Set: labels57
Codes: {0.0: 'No net', 1.0: 'Only treated nets', 2.0: 'Both treated and untreated nets', 3.0: 'Only untreated nets'}

============================================================
Variable: ML13A
Label: Fansidar taken for fever
Label Set: labels183
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML13E
Label: Combination with artemisinin taken for fever
Label Set: labels188
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML13H
Label: Other antimalarial taken for fever
Label Set: labels193
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML13Y
Label: Nothing taken and didn't seek treatment for fever/cough
Label Set: labels203
Codes: {0.0: 'No', 1.0: 'Yes, nothing taken'}

============================================================
Variable: ML501
Label: Last six months heard/seen malaria messages
Label Set: labels244
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML501A
Label: Malaria messages were heard/seen: radio
Label Set: labels245
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML501B
Label: Malaria messages were heard/seen: television
Label Set: labels246
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML501H
Label: Malaria messages were heard/seen: social media
Label Set: labels252
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML503
Label: Are there ways to avoid getting malaria
Label Set: labels258
Codes: {0.0: 'No', 1.0: 'Yes', 8.0: "Don't know"}

============================================================
Variable: ML503A
Label: Malaria can be prevented by: sleep inside a mosquito net
Label Set: labels259
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML503B
Label: Malaria can be prevented by: sleep inside an insecticide-treated mosquito net
Label Set: labels260
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML503E
Label: Malaria can be prevented by: spray house with insecticide
Label Set: labels263
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML503F
Label: Malaria can be prevented by: fill in stagnant waters (puddles)
Label Set: labels264
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML503G
Label: Malaria can be prevented by: keep surroundings clean
Label Set: labels265
Codes: {0.0: 'No', 1.0: 'Yes'}

============================================================
Variable: ML505
Label: Agree/disagree with: people in community get malaria in rainy season
Label Set: labels272
Codes: {0.0: 'Disagree', 1.0: 'Agree', 8.0: "Don't know/uncertain"}

============================================================
Variable: ML506
Label: Agree/disagree with: when child has fever worry it is malaria
Label Set: labels273
Codes: {0.0: 'Disagree', 1.0: 'Agree', 8.0: "Don't know/uncertain"}

============================================================
Variable: ML507
Label: Agree/disagree with: getting malaria not a problem as can be treated
Label Set: labels274
Codes: {0.0: 'Disagree', 1.0: 'Agree', 8.0: "Don't know/uncertain"}

============================================================
Variable: ML514
Label: Agree/disagree with: people who have nets usually sleep under every night
Label Set: labels281
Codes: {0.0: 'Disagree/less than half', 1.0: 'Agree/more than half', 8.0: "Don't know/uncertain"}

In [24]:
import pandas as pd

rows = []

for var in selected_vars:

    label_set = meta.variable_to_label.get(var)

    rows.append({
        "Dataset": "MIS 2021 KR",
        "Variable": var,
        "Label": meta.column_names_to_labels.get(var),
        "Codes": str(meta.value_labels.get(label_set)),
        "Notes": ""
    })

dictionary_df = pd.DataFrame(rows)

dictionary_df.to_excel(
    "MIS2021_Variable_Dictionary.xlsx",
    index=False
)

print("Dictionary created successfully")

Dictionary created successfully

In [16]:
import pandas as pd

rows = []

for var in selected_vars:

    label_set = meta.variable_to_label.get(var)

    codes = meta.value_labels.get(label_set)

    rows.append({
        "Dataset": "MIS 2021 KR",
        "Variable": var,
        "Label": meta.column_names_to_labels.get(var),
        "Codes": str(codes),
        "Notes": ""
    })

dictionary_df = pd.DataFrame(rows)

dictionary_df.head()

,Dataset,Variable,Label,Codes,Notes
0,MIS 2021 KR,V024,Region,"{1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina'...",
1,MIS 2021 KR,V025,Type of place of residence,"{1.0: 'Urban', 2.0: 'Rural'}",
2,MIS 2021 KR,V190,Wealth index combined,"{1.0: 'Poorest', 2.0: 'Poorer', 3.0: 'Middle',...",
3,MIS 2021 KR,ML0,Type of mosquito bed net(s) child slept under ...,"{0.0: 'No net', 1.0: 'Only treated nets', 2.0:...",
4,MIS 2021 KR,ML101,Type of mosquito bed net(s) slept under last n...,"{0.0: 'No net', 1.0: 'Only treated nets', 2.0:...",

In [17]:
dictionary_df.to_excel(
    "MIS2021_Variable_Dictionary.xlsx",
    index=False
)

In [18]:
import pyreadstat

kr2010, meta2010 = pyreadstat.read_sav(
    "children recode 2010.sav"
)

kr2015, meta2015 = pyreadstat.read_sav(
    "children recode 2015.sav"
)

kr2021, meta2021 = pyreadstat.read_sav(
    "NGKR81FL.sav"
)

In [19]:
vars2010 = set(kr2010.columns.str.upper())
vars2015 = set(kr2015.columns.str.upper())
vars2021 = set(kr2021.columns.str.upper())

In [30]:
for var in selected_vars:
    print(
        var,
        var in vars2010,
        var in vars2015,
        var in vars2021
    )

V024 True True True
V025 True True True
V190 True True True
ML0 True True True
ML101 True True True
ML13A True True True
ML13E True True True
ML13H True True True
ML13Y True True True
ML501 False False True
ML501A False False True
ML501B False False True
ML501H False False True
ML503 False False True
ML503A False False True
ML503B False False True
ML503E False False True
ML503F False False True
ML503G False False True
ML505 False False True
ML506 False False True
ML507 False False True
ML514 False False True

In [20]:
malaria2015 = [col for col in kr2015.columns if col.upper().startswith('ML')]
print(sorted(malaria2015))

['ML0', 'ML1', 'ML101', 'ML11', 'ML12', 'ML13A', 'ML13B', 'ML13C', 'ML13D', 'ML13E', 'ML13F', 'ML13G', 'ML13H', 'ML13I', 'ML13J', 'ML13K', 'ML13L', 'ML13M', 'ML13N', 'ML13O', 'ML13P', 'ML13X', 'ML13Y', 'ML13Z', 'ML14A', 'ML14B', 'ML14Y', 'ML14Z', 'ML15A', 'ML15B', 'ML15C', 'ML16A', 'ML16B', 'ML16C', 'ML17A', 'ML17B', 'ML17C', 'ML18A', 'ML18B', 'ML18C', 'ML19A', 'ML19B', 'ML19C', 'ML19D', 'ML19E', 'ML19F', 'ML19X', 'ML19Y', 'ML19Z', 'ML2', 'ML20A', 'ML20B', 'ML20C', 'ML21A', 'ML21B', 'ML21C', 'ML22A', 'ML22B', 'ML22C', 'ML23A', 'ML23B', 'ML23C', 'ML24C']

In [21]:
malaria2010 = [col for col in kr2010.columns if col.upper().startswith('ML')]
print(sorted(malaria2010))

['ML0', 'ML1', 'ML101', 'ML11', 'ML12', 'ML13A', 'ML13B', 'ML13C', 'ML13D', 'ML13E', 'ML13F', 'ML13G', 'ML13H', 'ML13I', 'ML13J', 'ML13K', 'ML13L', 'ML13M', 'ML13N', 'ML13O', 'ML13P', 'ML13X', 'ML13Y', 'ML13Z', 'ML14A', 'ML14B', 'ML14Y', 'ML14Z', 'ML15A', 'ML15B', 'ML15C', 'ML16A', 'ML16B', 'ML16C', 'ML17A', 'ML17B', 'ML17C', 'ML18A', 'ML18B', 'ML18C', 'ML19A', 'ML19B', 'ML19C', 'ML19D', 'ML19E', 'ML19F', 'ML19X', 'ML19Y', 'ML19Z', 'ML2', 'ML20A', 'ML20B', 'ML20C', 'ML21A', 'ML21B', 'ML21C', 'ML22A', 'ML22B', 'ML22C', 'ML23A', 'ML23B', 'ML23C', 'ML24C']

In [22]:
pd.DataFrame({
    "ML_Variables_2015": pd.Series(sorted(malaria2015))
}).to_excel(
    "ML_Variables_2015.xlsx",
    index=False
)

pd.DataFrame({
    "ML_Variables_2010": pd.Series(sorted(malaria2010))
}).to_excel(
    "ML_Variables_2010.xlsx",
    index=False
)

In [23]:
# Building the harmonised dataset

kr2010["survey_year"] = 2010
kr2015["survey_year"] = 2015
kr2021["survey_year"] = 2021

harmonized_vars = [
    "survey_year",
    "V024",
    "V025",
    "V190",
    "ML0",
    "ML101",
    "ML13A",
    "ML13E",
    "ML13H",
    "ML13Y"
]

kr2010_small = kr2010[harmonized_vars]
kr2015_small = kr2015[harmonized_vars]
kr2021_small = kr2021[harmonized_vars]

combined_kr = pd.concat(
    [
        kr2010_small,
        kr2015_small,
        kr2021_small
    ],
    ignore_index=True
)

combined_kr.shape

(23490, 10)

In [24]:
# Saving the combined children data

combined_kr.to_excel(
    "MIS_Children_2010_2015_2021_Harmonized.xlsx",
    index=False
)

In [25]:
combined_kr["survey_year"].value_counts()

survey_year
2021    10988
2015     6524
2010     5978
Name: count, dtype: int64

In [26]:
common_2010_2015 = vars2010 & vars2015

ml_common_2010_2015 = sorted([
    var for var in common_2010_2015
    if var.startswith("ML")
])

print(len(ml_common_2010_2015))
print(ml_common_2010_2015)

63
['ML0', 'ML1', 'ML101', 'ML11', 'ML12', 'ML13A', 'ML13B', 'ML13C', 'ML13D', 'ML13E', 'ML13F', 'ML13G', 'ML13H', 'ML13I', 'ML13J', 'ML13K', 'ML13L', 'ML13M', 'ML13N', 'ML13O', 'ML13P', 'ML13X', 'ML13Y', 'ML13Z', 'ML14A', 'ML14B', 'ML14Y', 'ML14Z', 'ML15A', 'ML15B', 'ML15C', 'ML16A', 'ML16B', 'ML16C', 'ML17A', 'ML17B', 'ML17C', 'ML18A', 'ML18B', 'ML18C', 'ML19A', 'ML19B', 'ML19C', 'ML19D', 'ML19E', 'ML19F', 'ML19X', 'ML19Y', 'ML19Z', 'ML2', 'ML20A', 'ML20B', 'ML20C', 'ML21A', 'ML21B', 'ML21C', 'ML22A', 'ML22B', 'ML22C', 'ML23A', 'ML23B', 'ML23C', 'ML24C']

In [27]:
for var in sorted([v for v in meta2015.column_names if v.startswith("ML")]):
    print(var, ":", meta2015.column_names_to_labels.get(var))

ML0 : Type of mosquito bed net(s) child slept under last night
ML1 : Number of times took fansidar during pregnancy
ML101 : Type of mosquito bed net(s) slept under last night
ML11 : NA - Child has fever/cough now
ML12 : NA - Child has had convulsions in last 2 weeks
ML13A : SP/fansidar/amalar/maloxine taken for fever/cough
ML13B : Chloroquine taken for fever/cough
ML13C : Amodiaquine taken for fever/cough
ML13D : Quinine taken for fever/cough
ML13E : Combination with artemisinin (ACT) taken for fever/cough
ML13F : Artesunate (rectal)  taken for fever/cough
ML13G : Artesunate (injection/IV) for fever/cough
ML13H : Other antimalarial taken for fever/cough
ML13I : Antibiotic pill/syrup taken for fever/cough
ML13J : Antibiotic injection taken for fever/cough
ML13K : Aspirin taken for fever/cough
ML13L : Acetaminophen taken for fever/cough
ML13M : Ibuprofen taken for fever/cough
ML13N : Paracetamol taken for fever/cough
ML13O : NA - CS other taken for fever
ML13P : NA - CS other taken for fever
ML13X : Other taken for fever/cough
ML13Y : Nothing taken for fever/cough
ML13Z : Don't know if or what was taken for fever/cough
ML14A : NA - Injection given for fever/convulsion***
ML14B : NA - Suppository given for fever/convulsion***
ML14Y : NA - No suppository or injection given for fever/convulsion***
ML14Z : NA - Don't know if suppository or injection given for fever/convulsion***
ML15A : Timing of start of SP/fansidar
ML15B : NA - Number of days child took fansidar
ML15C : NA - First source for fansidar
ML16A : Timing of start of chloroquine
ML16B : NA - Number of days child took chloroquine
ML16C : NA - First source for chloroquine
ML17A : Timing of start of amodiaquine
ML17B : NA - Number of days child took amodiaquine
ML17C : NA - First source for amodiaquine
ML18A : Timing of start of quinine
ML18B : NA - Number of days child took quinine
ML18C : NA - First source for quinine
ML19A : NA - For fever/convulsion: consulted traditional healer***
ML19B : NA - For fever/convulsion: gave tepid sponging***
ML19C : NA - For fever/convulsion: gave herbs***
ML19D : NA - For fever/convulsion: CS***
ML19E : NA - For fever/convulsion: CS***
ML19F : NA - For fever/convulsion: CS***
ML19X : NA - For fever/convulsion: other***
ML19Y : NA - For fever/convulsion: gave/did nothing***
ML19Z : NA - For fever/convulsion: don't know if something else was done***
ML2 : Source of antimalarial during pregnancy
ML20A : Timing of start of combination with artemisinin
ML20B : NA - Number of days child took combination with artemisinin
ML20C : NA - First source for combination with artemisinin
ML21A : Timing of start of artesunate
ML21B : NA - Number of days child took artesunate
ML21C : NA - First source for artesunate
ML22A : NA - Timing of start of CS antimalarial use
ML22B : NA - Number of days child took CS antimalarial
ML22C : NA - First source for CS antimalarial
ML23A : Timing of start of other anti-malarial use
ML23B : NA - Number of days child took other anti-malarial
ML23C : NA - First source for other anti-malarial
ML24C : NA - First source for antibiotic pill/syrup

In [28]:
for var in ["ML11","ML12","ML13A","ML13E","ML13H","ML13Y"]:
    
    print("\n" + "="*60)
    print(var)
    
    label_set = meta2015.variable_to_label.get(var)
    
    print(meta2015.value_labels.get(label_set))

============================================================
ML11
{0.0: 'No', 1.0: 'Yes, fever only', 2.0: 'Yes, cough only', 3.0: 'Both fever and cough', 8.0: "Don't know"}

============================================================
ML12
{0.0: 'No', 1.0: 'Yes', 8.0: "Don't know"}

============================================================
ML13A
{0.0: 'No', 1.0: 'Yes'}

============================================================
ML13E
{0.0: 'No', 1.0: 'Yes'}

============================================================
ML13H
{0.0: 'No', 1.0: 'Yes'}

============================================================
ML13Y
{0.0: 'No', 1.0: 'Yes, nothing taken'}

Dataset A: Core Trend Dataset (2010, 2015, 2021)

Variables:

survey_year
V024
V025
V190
ML0
ML101
ML13A
ML13E
ML13H
ML13Y

Purpose:

Trend analysis
State comparisons
Wealth comparisons
Urban-rural comparisons
Dataset B: Treatment & Care-Seeking Dataset (2010 + 2015)

Variables:

survey_year
V024
V025
V190

ML11
ML12

ML13A-ML13Z

ML14A-ML14Z

ML15A-ML24C

Purpose:

Treatment-seeking patterns
ACT utilization
Sources of treatment
Delays in treatment
Drug use patterns

This dataset may actually produce the strongest findings.

Dataset C: Awareness & Prevention Dataset (2021)

Variables:

ML501-ML514

Purpose:

Prevention awareness
Media exposure
Malaria knowledge
Community perceptions

In [29]:
# Defining the treatment dataset variables

treatment_vars = [
    "V024",    # State
    "V025",    # Urban/Rural
    "V190",    # Wealth

    "ML11",    # Fever/Cough
    "ML12",    # Convulsions

    "ML13A","ML13B","ML13C","ML13D","ML13E",
    "ML13F","ML13G","ML13H","ML13I","ML13J",
    "ML13K","ML13L","ML13M","ML13N","ML13O",
    "ML13P","ML13X","ML13Y","ML13Z",

    "ML14A","ML14B","ML14Y","ML14Z",

    "ML15A","ML15B","ML15C",

    "ML16A","ML16B","ML16C",

    "ML17A","ML17B","ML17C",

    "ML18A","ML18B","ML18C",

    "ML19A","ML19B","ML19C","ML19D",
    "ML19E","ML19F","ML19X","ML19Y","ML19Z",

    "ML20A","ML20B","ML20C",

    "ML21A","ML21B","ML21C",

    "ML22A","ML22B","ML22C",

    "ML23A","ML23B","ML23C",

    "ML24C"
]

In [33]:
kr2010["survey_year"] = 2010
kr2015["survey_year"] = 2015

keep_vars_B = ["survey_year"] + treatment_vars

kr2010_treatment = kr2010[keep_vars_B]
kr2015_treatment = kr2015[keep_vars_B]

treatment_dataset = pd.concat(
    [kr2010_treatment,
     kr2015_treatment],
    ignore_index=True
)

In [34]:
print(treatment_dataset.shape)

print(
    treatment_dataset["survey_year"]
    .value_counts()
)

(12502, 63)
survey_year
2015    6524
2010    5978
Name: count, dtype: int64

In [35]:
treatment_dataset.to_excel(
    "Dataset_B_Treatment_CareSeeking_2010_2015.xlsx",
    index=False
)

In [36]:
awareness_vars = [
    "V024",
    "V025",
    "V190",

    "ML501",
    "ML501A",
    "ML501B",
    "ML501H",

    "ML503",
    "ML503A",
    "ML503B",
    "ML503E",
    "ML503F",
    "ML503G",

    "ML505",
    "ML506",
    "ML507",
    "ML514"
]

In [37]:
kr2021["survey_year"] = 2021

In [38]:
keep_vars_C = ["survey_year"] + awareness_vars

awareness_dataset = kr2021[keep_vars_C]

In [39]:
print(awareness_dataset.shape)

awareness_dataset.head()

(10988, 18)

,survey_year,V024,V025,V190,ML501,ML501A,ML501B,ML501H,ML503,ML503A,ML503B,ML503E,ML503F,ML503G,ML505,ML506,ML507,ML514
0,2021,18.0,1.0,4.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
1,2021,18.0,1.0,4.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
2,2021,18.0,1.0,4.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,8.0,8.0,8.0
3,2021,18.0,1.0,3.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0
4,2021,18.0,1.0,3.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0

In [40]:
awareness_dataset.to_excel(
    "Dataset_C_Awareness_Prevention_2021.xlsx",
    index=False
)

In [41]:
missing_vars = [
    var for var in keep_vars_B
    if var not in kr2010.columns
    or var not in kr2015.columns
]

print(missing_vars)

[]

In [42]:
meta2010
meta2015
meta2021

metadata_container(column_names=['CASEID', 'HIDXA', 'V000', 'V001', 'V002', 'V003', 'V004', 'V005', 'V006', 'V007', 'V008', 'V008A', 'V009', 'V010', 'V011', 'V012', 'V013', 'V014', 'V015', 'V016', 'V021', 'V022', 'V023', 'V024', 'V025', 'V026', 'V027', 'V028', 'V029', 'V030', 'V031', 'V032', 'V034', 'V040', 'V042', 'V045A', 'V045B', 'V045C', 'V046', 'V047', 'V101', 'V102', 'V106', 'V107', 'V113', 'V115', 'V116', 'V119', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V128', 'V129', 'V130', 'V131', 'V133', 'V134', 'V135', 'V136', 'V137', 'V138', 'V139', 'V140', 'V141', 'V149', 'V150', 'V151', 'V152', 'V153', 'V155', 'V156', 'V157', 'V158', 'V159', 'V160', 'V161', 'V169A', 'V169C', 'V171A', 'V171B', 'V190', 'V191', 'V190A', 'V191A', 'ML101', 'V417', 'V418A', 'V419', 'V459', 'V460', 'V461', 'V468', 'BIDX', 'BORD', 'B0', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B10', 'B11', 'B12', 'B13', 'B15', 'B16', 'B17', 'B18', 'B19', 'V201', 'V202', 'V203', 'V204', 'V205', 'V206', 'V207', 'V208', 'V209', 'V210', 'V213', 'V214', 'V214A', 'V218', 'V219', 'V220', 'V222', 'V223', 'V224', 'V237', 'V238', 'MIDX', 'M2A', 'M2B', 'M2C', 'M2D', 'M2E', 'M2F', 'M2G', 'M2H', 'M2I', 'M2J', 'M2K', 'M2L', 'M2M', 'M2N', 'M13', 'M13A', 'M14', 'M49A', 'M49B', 'M49C', 'M49D', 'M49E', 'M49F', 'M49G', 'M49X', 'M49Z', 'M49Y', 'M57A', 'M57B', 'M57C', 'M57D', 'M57E', 'M57F', 'M57G', 'M57H', 'M57I', 'M57J', 'M57K', 'M57L', 'M57M', 'M57N', 'M57O', 'M57P', 'M57Q', 'M57R', 'M57NA', 'M57NB', 'M57NC', 'M57ND', 'M57NE', 'M57S', 'M57T', 'M57U', 'M57V', 'M57X', 'ML1', 'ML2', 'H22', 'H31', 'H32A', 'H32B', 'H32C', 'H32D', 'H32E', 'H32F', 'H32G', 'H32H', 'H32I', 'H32J', 'H32K', 'H32L', 'H32M', 'H32N', 'H32O', 'H32P', 'H32Q', 'H32R', 'H32NA', 'H32NB', 'H32NC', 'H32ND', 'H32NE', 'H32S', 'H32T', 'H32U', 'H32V', 'H32W', 'H32X', 'H32Y', 'H32Z', 'H46A', 'H46B', 'H47', 'H71', 'HWIDX', 'HW1', 'HW16', 'HW17', 'HW18', 'HW19', 'HW51', 'HW52', 'HW53', 'HW55', 'HW56', 'HW57', 'HW58', 'IDXML', 'ML0', 'ML11', 'ML12', 'ML13A', 'ML13B', 'ML13C', 'ML13D', 'ML13DA', 'ML13E', 'ML13AA', 'ML13AB', 'ML13F', 'ML13G', 'ML13H', 'ML13I', 'ML13J', 'ML13K', 'ML13L', 'ML13M', 'ML13N', 'ML13O', 'ML13P', 'ML13X', 'ML13Y', 'ML13Z', 'ML14A', 'ML14B', 'ML14Y', 'ML14Z', 'ML15A', 'ML15B', 'ML15C', 'ML16A', 'ML16B', 'ML16C', 'ML17A', 'ML17B', 'ML17C', 'ML18A', 'ML18B', 'ML18C', 'ML19A', 'ML19B', 'ML19C', 'ML19D', 'ML19E', 'ML19F', 'ML19X', 'ML19Y', 'ML19Z', 'ML20A', 'ML20B', 'ML20C', 'ML21A', 'ML21B', 'ML21C', 'ML22A', 'ML22B', 'ML22C', 'ML23A', 'ML23B', 'ML23C', 'ML24C', 'ML25A', 'ML501', 'ML501A', 'ML501B', 'ML501C', 'ML501D', 'ML501E', 'ML501F', 'ML501G', 'ML501H', 'ML501I', 'ML501J', 'ML501K', 'ML501X', 'ML501Z', 'ML503', 'ML503A', 'ML503B', 'ML503C', 'ML503D', 'ML503E', 'ML503F', 'ML503G', 'ML503H', 'ML503I', 'ML503J', 'ML503K', 'ML503X', 'ML503Z', 'ML505', 'ML506', 'ML507', 'ML508', 'ML509', 'ML510', 'ML511', 'ML512', 'ML513', 'ML514', 'S512A', 'SLGA', 'SREGION', 'SBONNY', 'S104A', 'S104B', 'S211', 'IDX95', 'S411A', 'S415A'], column_labels=['Case Identification', 'Index to birth history', 'Country code and phase', 'Cluster number', 'Household number', "Respondent's line number", 'Ultimate area unit', "Women's individual sample weight (6 decimals)", 'Month of interview', 'Year of interview', 'Date of interview (CMC)', 'Date of interview Century Day Code (CDC)', "Respondent's month of birth", "Respondent's year of birth", 'Date of birth (CMC)', "Respondent's current age", 'Age in 5-year groups', 'Completeness of age information', 'Result of individual interview', 'Day of interview', 'Primary sampling unit', 'Sample strata for sampling errors', 'Stratification used in sample design', 'Region', 'Type of place of residence', 'NA - De facto place of residence', 'Number of visits', 'Interviewer identification', 'NA - Keyer identification', 'Field supervisor', 'NA - Field editor', 'NA - Office editor', 'NA - Line number of husband', 'Cluster altitude in meters', 'Household selected for hemoglobin', 'Language of questionnaire', 'Language of interview', 'Native language of respondent', 'Translator used', 'Team number', 'Region', 'Type of place of residence', 'Highest educational level', 'Highest year of education', 'Source of drinking water', 'Time to get to water source', 'Type of toilet facility', 'Household has: electricity', 'Household has: radio', 'Household has: television', 'Household has: refrigerator', 'Household has: bicycle', 'Household has: motorcycle/scooter', 'Household has: car/truck', 'Main floor material', 'Main wall material', 'Main roof material', 'Religion', 'Ethnicity', 'Education in single years', 'NA - De facto place of residence', 'Usual resident or visitor', 'Number of household members (listed)', 'Number of children 5 and under in household (de jure)', 'Number of eligible women in household (de facto)', 'De jure region of residence', 'De jure type of place of residence', 'NA - De jure place of residence', 'Educational attainment', 'Relationship to household head', 'Sex of household head', 'Age of household head', 'Household has: telephone (land-line)', 'Literacy', 'NA - Ever participated in a literacy program outside of primary', 'Frequency of reading newspaper or magazine', 'Frequency of listening to radio', 'Frequency of watching television', 'Toilet facilities shared with other households', 'Type of cooking fuel', 'Owns a mobile telephone', "Is respondent's mobile phone a smart phone", 'Use of internet', 'Frequency of using internet last month', 'Wealth index combined', 'Wealth index factor score combined (5 decimals)', 'Wealth index for urban/rural', 'Wealth index factor score for urban/rural (5 decimals)', 'Type of mosquito bed net(s) slept under last night', 'Entries in pregnancy and postnatal care roster', 'Entries in child health roster', 'Entries in height/weight roster', 'Have mosquito bed net for sleeping (from household questionnaire)', 'Children under 5 slept under mosquito bed net last night (household questionnaire)', 'Respondent slept under mosquito bed net', 'Record for Last Birth', 'Birth column number', 'Birth order number', 'Child is twin', 'Month of birth', 'Year of birth', 'Date of birth (CMC)', 'Sex of child', 'Child is alive', 'NA - Age at death', 'NA - Age at death (months, imputed)', 'Current age of child', 'Child lives with whom', 'Completeness of information', 'Preceding birth interval (months)', 'Succeeding birth interval (months)', 'NA - Flag for age at death', 'Live birth between births', "Child's line number in household", 'Day of birth', 'Century Day Code of birth (CDC)', 'Current age of child in months (months since birth for dead children)', 'Total children ever born', 'Sons at home', 'Daughters at home', 'Sons elsewhere', 'Daughters elsewhere', 'Sons who have died', 'Daughters who have died', 'Births in last five years', 'Births in past year', 'Births in month of interview', 'Currently pregnant', 'Duration of current pregnancy in months', 'Duration of current pregnancy original', 'Number of living children', 'Living children + current pregnancy', 'Living children + current pregnancy (grouped)', 'Last birth to interview (months)', 'Completeness of current pregnancy information', 'Entries in birth history', 'Birth between last and interview', 'Births in last three years', 'Index to Birth History', 'Prenatal: doctor', 'Prenatal: nurse/midwife', 'Prenatal: auxiliary midwife', 'Prenatal: government health community extension health worker', 'NA - Prenatal: CS health professional', 'NA - Prenatal: CS health professional', 'Prenatal: traditional birth attendant', 'Prenatal: Community health worker/field worker', 'NA - Prenatal: CS other person', 'NA - Prenatal: CS other person', 'Prenatal: other', 'NA - Prenatal: CS other', 'NA - Prenatal: CS other', 'Prenatal: no one', 'Timing of 1st antenatal check (months)', 'Timing of 1st antenatal check (original)', 'Number of antenatal visits during pregnancy', 'During pregnancy took: SP/fansidar for malaria', 'NA - During pregnancy took: chloroquine for malaria', 'NA - During pregnancy took: CS drug for malaria', 'NA - During pregnancy took: CS drug for malaria', 'NA - During pregnancy took: CS drug for malaria', 'NA - During pregnancy took: CS drug for malaria', 'NA - During pregnancy took: CS drug for malaria', 'NA - During pregnancy took: other drug for malaria', "NA - During pregnancy took: don't know", 'NA - During pregnancy took: no drug for malaria', "Antenatal care: respondent's home", 'Antenatal care: other home', 'NA - Antenatal care: CS home', 'NA - Antenatal care: CS home', 'Antenatal care: government hospital', 'Antenatal care: government health center', 'Antenatal care: government health post', 'Antenatal care: other public sector', 'NA - Antenatal care: CS public health', 'NA - Antenatal care: CS public health', 'NA - Antenatal care: CS public health', 'NA - Antenatal care: CS public health', 'Antenatal care: private hospital', 'Antenatal care: private clinic', 'Antenatal care: other private medical sector', 'NA - Antenatal care: CS private medical', 'NA - Antenatal care: CS private medical', 'NA - Antenatal care: CS private medical', 'Antenatal care: NGO hospital', 'Antenatal care: NGO clinic', 'Antenatal care: other NGO medical sector', 'NA - Antenatal care: NGO medical', 'NA - Antenatal care: NGO medical', 'NA - Antenatal care: CS other', 'NA - Antenatal care: CS other', 'NA - Antenatal care: CS other', 'NA - Antenatal care: CS other', 'Antenatal care: other', 'Number of times took fansidar during pregnancy', 'Source of antimalarial during pregnancy', 'Had fever in last two weeks', 'NA - Had cough in last two weeks', 'Fever/cough: government hospital', 'Fever/cough: government health center', 'Fever/cough: government health post', 'Fever/cough: government mobile clinic', 'Fever/cough: government community health worker/fieldworker', 'Fever/cough: other public sector', 'NA - Fever/cough: CS public sector', 'NA - Fever/cough: CS public sector', 'NA - Fever/cough: CS public sector', 'Fever/cough: private hospital', 'Fever/cough: private pharmacy', 'Fever/cough: private doctor', 'Fever/cough: private clinic', 'Fever/cough: private mobile clinic', 'Fever/cough: private community health worker/fieldworker', 'Fever/cough: other private medical sector', 'NA - Fever/cough: CS private medical', 'NA - Fever/cough: CS private medical', 'Fever/cough: NGO hospital', 'Fever/cough: NGO clinic', 'Fever/cough: other NGO sector', 'NA - Fever/cough: CS NGO', 'NA - Fever/cough: CS NGO', 'Fever/cough: chemist shop/PPMV', 'Fever/cough: traditional practitioner', 'Fever/cough: market', 'Fever/cough: itinerant drug seller', 'Fever/cough: community-oriented resource person', 'Fever/cough: other', 'Fever/cough: no treatment', 'Fever/cough: medical treatment', 'Place first sought treatment for fever', 'Number of days after fever began sought advice or treatment', "Blood taken from child's finger/heel for testing", 'Was respondent told that child had malaria', 'Index to Birth History', "Child's age in months", 'Day of birth of child', 'Date measured (day)', 'Date measured (month)', 'Date measured (year)', 'Line number of parent/caretaker', 'Read consent statement - hemoglobin', 'Hemoglobin level (g/dl - 1 decimal)', 'Result of measurement - hemoglobin', 'Hemoglobin level adjusted for altitude (g/dl - 1 decimal)', 'Anemia level', 'NA - Agrees to referral - anemia', 'Index to Birth History', 'Type of mosquito bed net(s) child slept under last night', 'NA - Child has fever/cough now', 'NA - Child has had convulsions in last 2 weeks', 'Fansidar taken for fever', 'Chloroquine taken for fever', 'Amodiaquine taken for fever', 'Quinine taken for fever', 'Quinine injection/IV taken for fever', 'Combination with artemisinin taken for fever', 'Artesunate rectal taken for fever', 'Artesunate injection/IV taken for fever', 'NA - CS antimalarial taken for fever', 'NA - CS antimalarial taken for fever', 'Other antimalarial taken for fever', 'Antibiotic pill/syrup taken for fever', 'Antibiotic injection taken for fever', 'Aspirin taken for fever', 'Acetaminophen/paracetamol/panadol taken for fever', 'Ibuprofen taken for fever', 'Amoxicillin taken for fever', 'Cotrimoxazole taken for fever', 'NA - CS other taken for fever', 'Other taken for fever', "Nothing taken and didn't seek treatment for fever/cough", "Don't know if or what was taken for fever", 'NA - Injection given for fever/convulsion', 'NA - Suppository given for fever/convulsion', 'NA - No suppository or injection given for fever/convulsion', "NA - Don't know if suppository or injection given for fever/convulsion", 'NA - Timing of start of fansidar', 'NA - Number of days child took fansidar', 'NA - First source for fansidar', 'NA - Timing of start of chloroquine', 'NA - Number of days child took chloroquine', 'NA - First source for chloroquine', 'NA - Timing of start of amodiaquine', 'NA - Number of days child took amodiaquine', 'NA - First source for amodiaquine', 'NA - Timing of start of quinine', 'NA - Number of days child took quinine', 'NA - First source for quinine', 'NA - For fever/convulsion: consulted traditional healer', 'NA - For fever/convulsion: gave tepid sponging', 'NA - For fever/convulsion: gave herbs', 'NA - For fever/convulsion: CS', 'NA - For fever/convulsion: CS', 'NA - For fever/convulsion: CS', 'NA - For fever/convulsion: other', 'NA - For fever/convulsion: gave/did nothing', "NA - For fever/convulsion: don't know if something else was done", 'Timing of start of combination with artemisinin', 'NA - Number of days child took combination with artemisinin', 'NA - First source for combination with artemisinin', 'NA - Timing of start of CS antimalarial use', 'NA - Number of days child took CS antimalarial', 'NA - First source for CS antimalarial', 'NA - Timing of start of CS antimalarial use', 'NA - Number of days child took CS antimalarial', 'NA - First source for CS antimalarial', 'NA - Timing of start of other anti-malarial use', 'NA - Number of days child took other anti-malarial', 'NA - First source for other anti-malarial', 'NA - First source for antibiotic pill/syrup', 'NA - Timing of start of artesunate', 'Last six months heard/seen malaria messages', 'Malaria messages were heard/seen: radio', 'Malaria messages were heard/seen: television', 'Malaria messages were heard/seen: poster/billboard', 'Malaria messages were heard/seen: newspaper/magazine', 'Malaria messages were heard/seen: leaflet/brochure', 'Malaria messages were heard/seen: healthcare provider', 'Malaria messages were heard/seen: community health worker', 'Malaria messages were heard/seen: social media', 'Malaria messages were heard/seen: town announcer', 'Malaria messages were heard/seen: inter-personal communication agent/community volunteer', 'Malaria messages were heard/seen: family/friends', 'Malaria messages were heard/seen: other', "Malaria messages were heard/seen: don't remember", 'Are there ways to avoid getting malaria', 'Malaria can be prevented by: sleep inside a mosquito net', 'Malaria can be prevented by: sleep inside an insecticide-treated mosquito net', 'Malaria can be prevented by: use mosquito repellent or coil', 'Malaria can be prevented by: take preventive medications', 'Malaria can be prevented by: spray house with insecticide', 'Malaria can be prevented by: fill in stagnant waters (puddles)', 'Malaria can be prevented by: keep surroundings clean', 'Malaria can be prevented by: put mosquito screen on windows', 'NA - Malaria can be prevented by: CS', 'NA - Malaria can be prevented by: CS', 'NA - Malaria can be prevented by: CS', 'Malaria can be prevented by: other', "Malaria can be prevented by: don't know", 'Agree/disagree with: people in community get malaria in rainy season', 'Agree/disagree with: when child has fever worry it is malaria', 'Agree/disagree with: getting malaria not a problem as can be treated', 'Agree/disagree with: only weak children can die from malaria', 'Agree/disagree with: sleep inside net when there are lots of mosquitoes', 'Agree/disagree with: sleep inside net when there are few mosquitoes', "Agree/disagree with: don't like sleep inside a net when is too warm", 'Agree/disagree with: if child has fever best to give medicine available at home', 'Agree/disagree with: people take children to health provider same day or next day develop fever', 'Agree/disagree with: people who have nets usually sleep under every night', 'Agree/disagree with: important children take full dose of medicine they are prescribed for malaria', 'Local government area', 'Region', 'Bonny State', 'Had informal education', 'Type of informal education', 'Number of births 2016-2021', 'Index to Birth History', 'Referred to higher level of care', 'Fever went away after took ACT'], column_names_to_labels={'CASEID': 'Case Identification', 'HIDXA': 'Index to birth history', 'V000': 'Country code and phase', 'V001': 'Cluster number', 'V002': 'Household number', 'V003': "Respondent's line number", 'V004': 'Ultimate area unit', 'V005': "Women's individual sample weight (6 decimals)", 'V006': 'Month of interview', 'V007': 'Year of interview', 'V008': 'Date of interview (CMC)', 'V008A': 'Date of interview Century Day Code (CDC)', 'V009': "Respondent's month of birth", 'V010': "Respondent's year of birth", 'V011': 'Date of birth (CMC)', 'V012': "Respondent's current age", 'V013': 'Age in 5-year groups', 'V014': 'Completeness of age information', 'V015': 'Result of individual interview', 'V016': 'Day of interview', 'V021': 'Primary sampling unit', 'V022': 'Sample strata for sampling errors', 'V023': 'Stratification used in sample design', 'V024': 'Region', 'V025': 'Type of place of residence', 'V026': 'NA - De facto place of residence', 'V027': 'Number of visits', 'V028': 'Interviewer identification', 'V029': 'NA - Keyer identification', 'V030': 'Field supervisor', 'V031': 'NA - Field editor', 'V032': 'NA - Office editor', 'V034': 'NA - Line number of husband', 'V040': 'Cluster altitude in meters', 'V042': 'Household selected for hemoglobin', 'V045A': 'Language of questionnaire', 'V045B': 'Language of interview', 'V045C': 'Native language of respondent', 'V046': 'Translator used', 'V047': 'Team number', 'V101': 'Region', 'V102': 'Type of place of residence', 'V106': 'Highest educational level', 'V107': 'Highest year of education', 'V113': 'Source of drinking water', 'V115': 'Time to get to water source', 'V116': 'Type of toilet facility', 'V119': 'Household has: electricity', 'V120': 'Household has: radio', 'V121': 'Household has: television', 'V122': 'Household has: refrigerator', 'V123': 'Household has: bicycle', 'V124': 'Household has: motorcycle/scooter', 'V125': 'Household has: car/truck', 'V127': 'Main floor material', 'V128': 'Main wall material', 'V129': 'Main roof material', 'V130': 'Religion', 'V131': 'Ethnicity', 'V133': 'Education in single years', 'V134': 'NA - De facto place of residence', 'V135': 'Usual resident or visitor', 'V136': 'Number of household members (listed)', 'V137': 'Number of children 5 and under in household (de jure)', 'V138': 'Number of eligible women in household (de facto)', 'V139': 'De jure region of residence', 'V140': 'De jure type of place of residence', 'V141': 'NA - De jure place of residence', 'V149': 'Educational attainment', 'V150': 'Relationship to household head', 'V151': 'Sex of household head', 'V152': 'Age of household head', 'V153': 'Household has: telephone (land-line)', 'V155': 'Literacy', 'V156': 'NA - Ever participated in a literacy program outside of primary', 'V157': 'Frequency of reading newspaper or magazine', 'V158': 'Frequency of listening to radio', 'V159': 'Frequency of watching television', 'V160': 'Toilet facilities shared with other households', 'V161': 'Type of cooking fuel', 'V169A': 'Owns a mobile telephone', 'V169C': "Is respondent's mobile phone a smart phone", 'V171A': 'Use of internet', 'V171B': 'Frequency of using internet last month', 'V190': 'Wealth index combined', 'V191': 'Wealth index factor 

In [43]:
def build_dictionary(meta, variables, dataset_name):

    rows = []

    for var in variables:

        label = meta.column_names_to_labels.get(var)

        label_set = meta.variable_to_label.get(var)

        codes = meta.value_labels.get(label_set)

        rows.append({
            "Dataset": dataset_name,
            "Variable": var,
            "Label": label,
            "Code_Definitions": str(codes),
            "Notes": ""
        })

    return pd.DataFrame(rows)

In [45]:
dict_A = build_dictionary(
    meta2021,
    harmonized_vars[1:],  # remove survey_year
    "Dataset A"
)

dict_B = build_dictionary(
    meta2015,
    treatment_vars,
    "Dataset B"
)

dict_C = build_dictionary(
    meta2021,
    awareness_vars,
    "Dataset C"
)

In [48]:
with pd.ExcelWriter(
    "Dataset_A_Trend_2010_2015_2021.xlsx",
    engine="openpyxl"
) as writer:

    combined_kr.to_excel(
        writer,
        sheet_name="Data",
        index=False
    )

    dict_A.to_excel(
        writer,
        sheet_name="Variable_Dictionary",
        index=False
    )

In [51]:
with pd.ExcelWriter(
    "Dataset_B_Treatment_CareSeeking_2010_2015.xlsx",
    engine="openpyxl"
) as writer:

    treatment_dataset.to_excel(
        writer,
        sheet_name="Data",
        index=False
    )

    dict_B.to_excel(
        writer,
        sheet_name="Variable_Dictionary",
        index=False
    )

In [50]:

with pd.ExcelWriter(
    "Dataset_C_Awareness_Prevention_2021.xlsx",
    engine="openpyxl"
) as writer:

    awareness_dataset.to_excel(
        writer,
        sheet_name="Data",
        index=False
    )

    dict_C.to_excel(
        writer,
        sheet_name="Variable_Dictionary",
        index=False
    )

In [53]:
import pyreadstat

hr2010, hrmeta2010 = pyreadstat.read_sav(
    "household 2010.sav"
)

hr2015, hrmeta2015 = pyreadstat.read_sav(
    "household 2015.sav"
)

hr2021, hrmeta2021 = pyreadstat.read_sav(
    "househol 2021.sav"
)

In [54]:
print(hr2010.shape)
print(hr2015.shape)
print(hr2021.shape)

(5895, 1975)
(7745, 2649)
(13727, 2928)

In [55]:
hr_vars_2021 = hr2021.columns.tolist()

malaria_vars = [
    var for var in hr_vars_2021
    if "ML" in var.upper()
]

print(sorted(malaria_vars))

['HML1', 'HML10$1', 'HML10$2', 'HML10$3', 'HML10$4', 'HML10$5', 'HML10$6', 'HML10$7', 'HML11$1', 'HML11$2', 'HML11$3', 'HML11$4', 'HML11$5', 'HML11$6', 'HML11$7', 'HML12$01', 'HML12$02', 'HML12$03', 'HML12$04', 'HML12$05', 'HML12$06', 'HML12$07', 'HML12$08', 'HML12$09', 'HML12$10', 'HML12$11', 'HML12$12', 'HML12$13', 'HML12$14', 'HML12$15', 'HML12$16', 'HML12$17', 'HML12$18', 'HML12$19', 'HML12$20', 'HML12$21', 'HML12$22', 'HML12$23', 'HML12$24', 'HML12$25', 'HML12$26', 'HML12$27', 'HML12$28', 'HML12$29', 'HML12$30', 'HML12$31', 'HML12$32', 'HML12$33', 'HML12$34', 'HML12$35', 'HML12$36', 'HML12$37', 'HML12$38', 'HML12$39', 'HML12$40', 'HML12$41', 'HML12$42', 'HML12$43', 'HML12$44', 'HML12$45', 'HML12$46', 'HML13$01', 'HML13$02', 'HML13$03', 'HML13$04', 'HML13$05', 'HML13$06', 'HML13$07', 'HML13$08', 'HML13$09', 'HML13$10', 'HML13$11', 'HML13$12', 'HML13$13', 'HML13$14', 'HML13$15', 'HML13$16', 'HML13$17', 'HML13$18', 'HML13$19', 'HML13$20', 'HML13$21', 'HML13$22', 'HML13$23', 'HML13$24', 'HML13$25', 'HML13$26', 'HML13$27', 'HML13$28', 'HML13$29', 'HML13$30', 'HML13$31', 'HML13$32', 'HML13$33', 'HML13$34', 'HML13$35', 'HML13$36', 'HML13$37', 'HML13$38', 'HML13$39', 'HML13$40', 'HML13$41', 'HML13$42', 'HML13$43', 'HML13$44', 'HML13$45', 'HML13$46', 'HML14$01', 'HML14$02', 'HML14$03', 'HML14$04', 'HML14$05', 'HML14$06', 'HML14$07', 'HML14$08', 'HML14$09', 'HML14$10', 'HML14$11', 'HML14$12', 'HML14$13', 'HML14$14', 'HML14$15', 'HML14$16', 'HML14$17', 'HML14$18', 'HML14$19', 'HML14$20', 'HML14$21', 'HML14$22', 'HML14$23', 'HML14$24', 'HML14$25', 'HML14$26', 'HML14$27', 'HML14$28', 'HML14$29', 'HML14$30', 'HML14$31', 'HML14$32', 'HML14$33', 'HML14$34', 'HML14$35', 'HML14$36', 'HML14$37', 'HML14$38', 'HML14$39', 'HML14$40', 'HML14$41', 'HML14$42', 'HML14$43', 'HML14$44', 'HML14$45', 'HML14$46', 'HML15$01', 'HML15$02', 'HML15$03', 'HML15$04', 'HML15$05', 'HML15$06', 'HML15$07', 'HML15$08', 'HML15$09', 'HML15$10', 'HML15$11', 'HML15$12', 'HML15$13', 'HML15$14', 'HML15$15', 'HML15$16', 'HML15$17', 'HML15$18', 'HML15$19', 'HML15$20', 'HML15$21', 'HML15$22', 'HML15$23', 'HML15$24', 'HML15$25', 'HML15$26', 'HML15$27', 'HML15$28', 'HML15$29', 'HML15$30', 'HML15$31', 'HML15$32', 'HML15$33', 'HML15$34', 'HML15$35', 'HML15$36', 'HML15$37', 'HML15$38', 'HML15$39', 'HML15$40', 'HML15$41', 'HML15$42', 'HML15$43', 'HML15$44', 'HML15$45', 'HML15$46', 'HML16$01', 'HML16$02', 'HML16$03', 'HML16$04', 'HML16$05', 'HML16$06', 'HML16$07', 'HML16$08', 'HML16$09', 'HML16$10', 'HML16$11', 'HML16$12', 'HML16$13', 'HML16$14', 'HML16$15', 'HML16$16', 'HML16$17', 'HML16$18', 'HML16$19', 'HML16$20', 'HML16$21', 'HML16$22', 'HML16$23', 'HML16$24', 'HML16$25', 'HML16$26', 'HML16$27', 'HML16$28', 'HML16$29', 'HML16$30', 'HML16$31', 'HML16$32', 'HML16$33', 'HML16$34', 'HML16$35', 'HML16$36', 'HML16$37', 'HML16$38', 'HML16$39', 'HML16$40', 'HML16$41', 'HML16$42', 'HML16$43', 'HML16$44', 'HML16$45', 'HML16$46', 'HML16A$01', 'HML16A$02', 'HML16A$03', 'HML16A$04', 'HML16A$05', 'HML16A$06', 'HML16A$07', 'HML16A$08', 'HML16A$09', 'HML16A$10', 'HML16A$11', 'HML16A$12', 'HML16A$13', 'HML16A$14', 'HML16A$15', 'HML16A$16', 'HML16A$17', 'HML16A$18', 'HML16A$19', 'HML16A$20', 'HML16A$21', 'HML16A$22', 'HML16A$23', 'HML16A$24', 'HML16A$25', 'HML16A$26', 'HML16A$27', 'HML16A$28', 'HML16A$29', 'HML16A$30', 'HML16A$31', 'HML16A$32', 'HML16A$33', 'HML16A$34', 'HML16A$35', 'HML16A$36', 'HML16A$37', 'HML16A$38', 'HML16A$39', 'HML16A$40', 'HML16A$41', 'HML16A$42', 'HML16A$43', 'HML16A$44', 'HML16A$45', 'HML16A$46', 'HML17$01', 'HML17$02', 'HML17$03', 'HML17$04', 'HML17$05', 'HML17$06', 'HML17$07', 'HML17$08', 'HML17$09', 'HML17$10', 'HML17$11', 'HML17$12', 'HML17$13', 'HML17$14', 'HML17$15', 'HML17$16', 'HML17$17', 'HML17$18', 'HML17$19', 'HML17$20', 'HML17$21', 'HML17$22', 'HML17$23', 'HML17$24', 'HML17$25', 'HML17$26', 'HML17$27', 'HML17$28', 'HML17$29', 'HML17$30', 'HML17$31', 'HML17$32', 'HML17$33', 'HML17$34', 'HML17$35', 'HML17$36', 'HML17$37', 'HML17$38', 'HML17$39', 'HML17$40', 'HML17$41', 'HML17$42', 'HML17$43', 'HML17$44', 'HML17$45', 'HML17$46', 'HML18$01', 'HML18$02', 'HML18$03', 'HML18$04', 'HML18$05', 'HML18$06', 'HML18$07', 'HML18$08', 'HML18$09', 'HML18$10', 'HML18$11', 'HML18$12', 'HML18$13', 'HML18$14', 'HML18$15', 'HML18$16', 'HML18$17', 'HML18$18', 'HML18$19', 'HML18$20', 'HML18$21', 'HML18$22', 'HML18$23', 'HML18$24', 'HML18$25', 'HML18$26', 'HML18$27', 'HML18$28', 'HML18$29', 'HML18$30', 'HML18$31', 'HML18$32', 'HML18$33', 'HML18$34', 'HML18$35', 'HML18$36', 'HML18$37', 'HML18$38', 'HML18$39', 'HML18$40', 'HML18$41', 'HML18$42', 'HML18$43', 'HML18$44', 'HML18$45', 'HML18$46', 'HML19$01', 'HML19$02', 'HML19$03', 'HML19$04', 'HML19$05', 'HML19$06', 'HML19$07', 'HML19$08', 'HML19$09', 'HML19$10', 'HML19$11', 'HML19$12', 'HML19$13', 'HML19$14', 'HML19$15', 'HML19$16', 'HML19$17', 'HML19$18', 'HML19$19', 'HML19$20', 'HML19$21', 'HML19$22', 'HML19$23', 'HML19$24', 'HML19$25', 'HML19$26', 'HML19$27', 'HML19$28', 'HML19$29', 'HML19$30', 'HML19$31', 'HML19$32', 'HML19$33', 'HML19$34', 'HML19$35', 'HML19$36', 'HML19$37', 'HML19$38', 'HML19$39', 'HML19$40', 'HML19$41', 'HML19$42', 'HML19$43', 'HML19$44', 'HML19$45', 'HML19$46', 'HML1A', 'HML2', 'HML20$01', 'HML20$02', 'HML20$03', 'HML20$04', 'HML20$05', 'HML20$06', 'HML20$07', 'HML20$08', 'HML20$09', 'HML20$10', 'HML20$11', 'HML20$12', 'HML20$13', 'HML20$14', 'HML20$15', 'HML20$16', 'HML20$17', 'HML20$18', 'HML20$19', 'HML20$20', 'HML20$21', 'HML20$22', 'HML20$23', 'HML20$24', 'HML20$25', 'HML20$26', 'HML20$27', 'HML20$28', 'HML20$29', 'HML20$30', 'HML20$31', 'HML20$32', 'HML20$33', 'HML20$34', 'HML20$35', 'HML20$36', 'HML20$37', 'HML20$38', 'HML20$39', 'HML20$40', 'HML20$41', 'HML20$42', 'HML20$43', 'HML20$44', 'HML20$45', 'HML20$46', 'HML21$1', 'HML21$2', 'HML21$3', 'HML21$4', 'HML21$5', 'HML21$6', 'HML21$7', 'HML22$1', 'HML22$2', 'HML22$3', 'HML22$4', 'HML22$5', 'HML22$6', 'HML22$7', 'HML23$1', 'HML23$2', 'HML23$3', 'HML23$4', 'HML23$5', 'HML23$6', 'HML23$7', 'HML3$1', 'HML3$2', 'HML3$3', 'HML3$4', 'HML3$5', 'HML3$6', 'HML3$7', 'HML30$01', 'HML30$02', 'HML30$03', 'HML30$04', 'HML30$05', 'HML30$06', 'HML30$07', 'HML30$08', 'HML30$09', 'HML30$10', 'HML30$11', 'HML30$12', 'HML30$13', 'HML30$14', 'HML30$15', 'HML30$16', 'HML30$17', 'HML30$18', 'HML30$19', 'HML30$20', 'HML30$21', 'HML30$22', 'HML30$23', 'HML30$24', 'HML30$25', 'HML30$26', 'HML30$27', 'HML30$28', 'HML30$29', 'HML30$30', 'HML30$31', 'HML30$32', 'HML30$33', 'HML30$34', 'HML30$35', 'HML30$36', 'HML30$37', 'HML30$38', 'HML30$39', 'HML30$40', 'HML30$41', 'HML30$42', 'HML30$43', 'HML30$44', 'HML30$45', 'HML30$46', 'HML31$01', 'HML31$02', 'HML31$03', 'HML31$04', 'HML31$05', 'HML31$06', 'HML31$07', 'HML31$08', 'HML31$09', 'HML31$10', 'HML31$11', 'HML31$12', 'HML31$13', 'HML31$14', 'HML31$15', 'HML31$16', 'HML31$17', 'HML31$18', 'HML31$19', 'HML31$20', 'HML31$21', 'HML31$22', 'HML31$23', 'HML31$24', 'HML31$25', 'HML31$26', 'HML31$27', 'HML31$28', 'HML31$29', 'HML31$30', 'HML31$31', 'HML31$32', 'HML31$33', 'HML31$34', 'HML31$35', 'HML31$36', 'HML31$37', 'HML31$38', 'HML31$39', 'HML31$40', 'HML31$41', 'HML31$42', 'HML31$43', 'HML31$44', 'HML31$45', 'HML31$46', 'HML32$01', 'HML32$02', 'HML32$03', 'HML32$04', 'HML32$05', 'HML32$06', 'HML32$07', 'HML32$08', 'HML32$09', 'HML32$10', 'HML32$11', 'HML32$12', 'HML32$13', 'HML32$14', 'HML32$15', 'HML32$16', 'HML32$17', 'HML32$18', 'HML32$19', 'HML32$20', 'HML32$21', 'HML32$22', 'HML32$23', 'HML32$24', 'HML32$25', 'HML32$26', 'HML32$27', 'HML32$28', 'HML32$29', 'HML32$30', 'HML32$31', 'HML32$32', 'HML32$33', 'HML32$34', 'HML32$35', 'HML32$36', 'HML32$37', 'HML32$38', 'HML32$39', 'HML32$40', 'HML32$41', 'HML32$42', 'HML32$43', 'HML32$44', 'HML32$45', 'HML32$46', 'HML32A$01', 'HML32A$02', 'HML32A$03', 'HML32A$04', 'HML32A$05', 'HML32A$06', 'HML32A$07', 'HML32A$08', 'HML32A$09', 'HML32A$10', 'HML32A$11', 'HML32A$12', 'HML32A$13', 'HML32A$14', 'HML32A$15', 'HML32A$16', 'HML32A$17', 'HML32A$18', 'HML32A$19', 'HML32A$20', 'HML32A$21', 'HML32A$22', 'HML32A$23', 'HML32A$24', 'HML32A$25', 'HML32A$26', 'HML32A$27', 'HML32A$28', 'HML32A$29', 'HML32A$30', 'HML32A$31', 'HML32A$32', 'HML32A$33', 'HML32A$34', 'HML32A$35', 'HML32A$36', 'HML32A$37', 'HML32A$38', 'HML32A$39', 'HML32A$40', 'HML32A$41', 'HML32A$42', 'HML32A$43', 'HML32A$44', 'HML32A$45', 'HML32A$46', 'HML32B$01', 'HML32B$02', 'HML32B$03', 'HML32B$04', 'HML32B$05', 'HML32B$06', 'HML32B$07', 'HML32B$08', 'HML32B$09', 'HML32B$10', 'HML32B$11', 'HML32B$12', 'HML32B$13', 'HML32B$14', 'HML32B$15', 'HML32B$16', 'HML32B$17', 'HML32B$18', 'HML32B$19', 'HML32B$20', 'HML32B$21', 'HML32B$22', 'HML32B$23', 'HML32B$24', 'HML32B$25', 'HML32B$26', 'HML32B$27', 'HML32B$28', 'HML32B$29', 'HML32B$30', 'HML32B$31', 'HML32B$32', 'HML32B$33', 'HML32B$34', 'HML32B$35', 'HML32B$36', 'HML32B$37', 'HML32B$38', 'HML32B$39', 'HML32B$40', 'HML32B$41', 'HML32B$42', 'HML32B$43', 'HML32B$44', 'HML32B$45', 'HML32B$46', 'HML32C$01', 'HML32C$02', 'HML32C$03', 'HML32C$04', 'HML32C$05', 'HML32C$06', 'HML32C$07', 'HML32C$08', 'HML32C$09', 'HML32C$10', 'HML32C$11', 'HML32C$12', 'HML32C$13', 'HML32C$14', 'HML32C$15', 'HML32C$16', 'HML32C$17', 'HML32C$18', 'HML32C$19', 'HML32C$20', 'HML32C$21', 'HML32C$22', 'HML32C$23', 'HML32C$24', 'HML32C$25', 'HML32C$26', 'HML32C$27', 'HML32C$28', 'HML32C$29', 'HML32C$30', 'HML32C$31', 'HML32C$32', 'HML32C$33', 'HML32C$34', 'HML32C$35', 'HML32C$36', 'HML32C$37', 'HML32C$38', 'HML32C$39', 'HML32C$40', 'HML32C$41', 'HML32C$42', 'HML32C$43', 'HML32C$44', 'HML32C$45', 'HML32C$46', 'HML32D$01', 'HML32D$02', 'HML32D$03', 'HML32D$04', 'HML32D$05', 'HML32D$06', 'HML32D$07', 'HML32D$08', 'HML32D$09', 'HML32D$10', 'HML32D$11', 'HML32D$12', 'HML32D$13', 'HML32D$14', 'HML32D$15', 'HML32D$16', 'HML32D$17', 'HML32D$18', 'HML32D$19', 'HML32D$20', 'HML32D$21', 'HML32D$22', 'HML32D$23', 'HML32D$24', 'HML32D$25', 'HML32D$26', 'HML32D$27', 'HML32D$28', 'HML32D$29', 'HML32D$30', 'HML32D$31', 'HML32D$32', 'HML32D$33', 'HML32D$34', 'HML32D$35', 'HML32D$36', 'HML32D$37', 'HML32D$38', 'HML32D$39', 'HML32D$40', 'HML32D$41', 'HML32D$42', 'HML32D$43', 'HML32D$44', 'HML32D$45', 'HML32D$46', 'HML32E$01', 'HML32E$02', 'HML32E$03', 'HML32E$04', 'HML32E$05', 'HML32E$06', 'HML32E$07', 'HML32E$08', 'HML32E$09', 'HML32E$10', 'HML32E$11', 'HML32E$12', 'HML32E$13', 'HML32E$14', 'HML32E$15', 'HML32E$16', 'HML32E$17', 'HML32E$18', 'HML32E$19', 'HML32E$20', 'HML32E$21', 'HML32E$22', 'HML32E$23', 'HML32E$24', 'HML32E$25', 'HML32E$26', 'HML32E$27', 'HML32E$28', 'HML32E$29', 'HML32E$30', 'HML32E$31', 'HML32E$32', 'HML32E$33', 'HML32E$34', 'HML32E$35', 'HML32E$36', 'HML32E$37', 'HML32E$38', 'HML32E$39', 'HML32E$40', 'HML32E$41', 'HML32E$42', 'HML32E$43', 'HML32E$44', 'HML32E$45', 'HML32E$46', 'HML32F$01', 'HML32F$02', 'HML32F$03', 'HML32F$04', 'HML32F$05', 'HML32F$06', 'HML32F$07', 'HML32F$08', 'HML32F$09', 'HML32F$10', 'HML32F$11', 'HML32F$12', 'HML32F$13', 'HML32F$14', 'HML32F$15', 'HML32F$16', 'HML32F$17', 'HML32F$18', 'HML32F$19', 'HML32F$20', 'HML32F$21', 'HML32F$22', 'HML32F$23', 'HML32F$24', 'HML32F$25', 'HML32F$26', 'HML32F$27', 'HML32F$28', 'HML32F$29', 'HML32F$30', 'HML32F$31', 'HML32F$32', 'HML32F$33', 'HML32F$34', 'HML32F$35', 'HML32F$36', 'HML32F$37', 'HML32F$38', 'HML32F$39', 'HML32F$40', 'HML32F$41', 'HML32F$42', 'HML32F$43', 'HML32F$44', 'HML32F$45', 'HML32F$46', 'HML32G$01', 'HML32G$02', 'HML32G$03', 'HML32G$04', 'HML32G$05', 'HML32G$06', 'HML32G$07', 'HML32G$08', 'HML32G$09', 'HML32G$10', 'HML32G$11', 'HML32G$12', 'HML32G$13', 'HML32G$14', 'HML32G$15', 'HML32G$16', 'HML32G$17', 'HML32G$18', 'HML32G$19', 'HML32G$20', 'HML32G$21', 'HML32G$22', 'HML32G$23', 'HML32G$24', 'HML32G$25', 'HML32G$26', 'HML32G$27', 'HML32G$28', 'HML32G$29', 'HML32G$30', 'HML32G$31', 'HML32G$32', 'HML32G$33', 'HML32G$34', 'HML32G$35', 'HML32G$36', 'HML32G$37', 'HML32G$38', 'HML32G$39', 'HML32G$40', 'HML32G$41', 'HML32G$42', 'HML32G$43', 'HML32G$44', 'HML32G$45', 'HML32G$46', 'HML33$01', 'HML33$02', 'HML33$03', 'HML33$04', 'HML33$05', 'HML33$06', 'HML33$07', 'HML33$08', 'HML33$09', 'HML33$10', 'HML33$11', 'HML33$12', 'HML33$13', 'HML33$14', 'HML33$15', 'HML33$16', 'HML33$17', 'HML33$18', 'HML33$19', 'HML33$20', 'HML33$21', 'HML33$22', 'HML33$23', 'HML33$24', 'HML33$25', 'HML33$26', 'HML33$27', 'HML33$28', 'HML33$29', 'HML33$30', 'HML33$31', 'HML33$32', 'HML33$33', 'HML33$34', 'HML33$35', 'HML33$36', 'HML33$37', 'HML33$38', 'HML33$39', 'HML33$40', 'HML33$41', 'HML33$42', 'HML33$43', 'HML33$44', 'HML33$45', 'HML33$46', 'HML34$01', 'HML34$02', 'HML34$03', 'HML34$04', 'HML34$05', 'HML34$06', 'HML34$07', 'HML34$08', 'HML34$09', 'HML34$10', 'HML34$11', 'HML34$12', 'HML34$13', 'HML34$14', 'HML34$15', 'HML34$16', 'HML34$17', 'HML34$18', 'HML34$19', 'HML34$20', 'HML34$21', 'HML34$22', 'HML34$23', 'HML34$24', 'HML34$25', 'HML34$26', 'HML34$27', 'HML34$28', 'HML34$29', 'HML34$30', 'HML34$31', 'HML34$32', 'HML34$33', 'HML34$34', 'HML34$35', 'HML34$36', 'HML34$37', 'HML34$38', 'HML34$39', 'HML34$40', 'HML34$41', 'HML34$42', 'HML34$43', 'HML34$44', 'HML34$45', 'HML34$46', 'HML35$01', 'HML35$02', 'HML35$03', 'HML35$04', 'HML35$05', 'HML35$06', 'HML35$07', 'HML35$08', 'HML35$09', 'HML35$10', 'HML35$11', 'HML35$12', 'HML35$13', 'HML35$14', 'HML35$15', 'HML35$16', 'HML35$17', 'HML35$18', 'HML35$19', 'HML35$20', 'HML35$21', 'HML35$22', 'HML35$23', 'HML35$24', 'HML35$25', 'HML35$26', 'HML35$27', 'HML35$28', 'HML35$29', 'HML35$30', 'HML35$31', 'HML35$32', 'HML35$33', 'HML35$34', 'HML35$35', 'HML35$36', 'HML35$37', 'HML35$38', 'HML35$39', 'HML35$40', 'HML35$41', 'HML35$42', 'HML35$43', 'HML35$44', 'HML35$45', 'HML35$46', 'HML36$01', 'HML36$02', 'HML36$03', 'HML36$04', 'HML36$05', 'HML36$06', 'HML36$07', 'HML36$08', 'HML36$09', 'HML36$10', 'HML36$11', 'HML36$12', 'HML36$13', 'HML36$14', 'HML36$15', 'HML36$16', 'HML36$17', 'HML36$18', 'HML36$19', 'HML36$20', 'HML36$21', 'HML36$22', 'HML36$23', 'HML36$24', 'HML36$25', 'HML36$26', 'HML36$27', 'HML36$28', 'HML36$29', 'HML36$30', 'HML36$31', 'HML36$32', 'HML36$33', 'HML36$34', 'HML36$35', 'HML36$36', 'HML36$37', 'HML36$38', 'HML36$39', 'HML36$40', 'HML36$41', 'HML36$42', 'HML36$43', 'HML36$44', 'HML36$45', 'HML36$46', 'HML37A$01', 'HML37A$02', 'HML37A$03', 'HML37A$04', 'HML37A$05', 'HML37A$06', 'HML37A$07', 'HML37A$08', 'HML37A$09', 'HML37A$10', 'HML37A$11', 'HML37A$12', 'HML37A$13', 'HML37A$14', 'HML37A$15', 'HML37A$16', 'HML37A$17', 'HML37A$18', 'HML37A$19', 'HML37A$20', 'HML37A$21', 'HML37A$22', 'HML37A$23', 'HML37A$24', 'HML37A$25', 'HML37A$26', 'HML37A$27', 'HML37A$28', 'HML37A$29', 'HML37A$30', 'HML37A$31', 'HML37A$32', 'HML37A$33', 'HML37A$34', 'HML37A$35', 'HML37A$36', 'HML37A$37', 'HML37A$38', 'HML37A$39', 'HML37A$40', 'HML37A$41', 'HML37A$42', 'HML37A$43', 'HML37A$44', 'HML37A$45', 'HML37A$46', 'HML37B$01', 'HML37B$02', 'HML37B$03', 'HML37B$04', 'HML37B$05', 'HML37B$06', 'HML37B$07', 'HML37B$08', 'HML37B$09', 'HML37B$10', 'HML37B$11', 'HML37B$12', 'HML37B$13', 'HML37B$14', 'HML37B$15', 'HML37B$16', 'HML37B$17', 'HML37B$18', 'HML37B$19', 'HML37B$20', 'HML37B$21', 'HML37B$22', 'HML37B$23', 'HML37B$24', 'HML37B$25', 'HML37B$26', 'HML37B$27', 'HML37B$28', 'HML37B$29', 'HML37B$30', 'HML37B$31', 'HML37B$32', 'HML37B$33', 'HML37B$34', 'HML37B$35', 'HML37B$36', 'HML37B$37', 'HML37B$38', 'HML37B$39', 'HML37B$40', 'HML37B$41', 'HML37B$42', 'HML37B$43', 'HML37B$44', 'HML37B$45', 'HML37B$46', 'HML37C$01', 'HML37C$02', 'HML37C$03', 'HML37C$04', 'HML37C$05', 'HML37C$06', 'HML37C$07', 'HML37C$08', 'HML37C$09', 'HML37C$10', 'HML37C$11', 'HML37C$12', 'HML37C$13', 'HML37C$14', 'HML37C$15', 'HML37C$16', 'HML37C$17', 'HML37C$18', 'HML37C$19', 'HML37C$20', 'HML37C$21', 'HML37C$22', 'HML37C$23', 'HML37C$24', 'HML37C$25', 'HML37C$26', 'HML37C$27', 'HML37C$28', 'HML37C$29', 'HML37C$30', 'HML37C$31', 'HML37C$32', 'HML37C$33', 'HML37C$34', 'HML37C$35', 'HML37C$36', 'HML37C$37', 'HML37C$38', 'HML37C$39', 'HML37C$40', 'HML37C$41', 'HML37C$42', 'HML37C$43', 'HML37C$44', 'HML37C$45', 'HML37C$46', 'HML37D$01', 'HML37D$02', 'HML37D$03', 'HML37D$04', 'HML37D$05', 'HML37D$06', 'HML37D$07', 'HML37D$08', 'HML37D$09', 'HML37D$10', 'HML37D$11', 'HML37D$12', 'HML37D$13', 'HML37D$14', 'HML37D$15', 'HML37D$16', 'HML37D$17', 'HML37D$18', 'HML37D$19', 'HML37D$20', 'HML37D$21', 'HML37D$22', 'HML37D$23', 'HML37D$24', 'HML37D$25', 'HML37D$26', 'HML37D$27', 'HML37D$28', 'HML37D$29', 'HML37D$30', 'HML37D$31', 'HML37D$32', 'HML37D$33', 'HML37D$34', 'HML37D$35', 'HML37D$36', 'HML37D$37', 'HML37D$38', 'HML37D$39', 'HML37D$40', 'HML37D$41', 'HML37D$42', 'HML37D$43', 'HML37D$44', 'HML37D$45', 'HML37D$46', 'HML37E$01', 'HML37E$02', 'HML37E$03', 'HML37E$04', 'HML37E$05', 'HML37E$06', 'HML37E$07', 'HML37E$08', 'HML37E$09', 'HML37E$10', 'HML37E$11', 'HML37E$12', 'HML37E$13', 'HML37E$14', 'HML37E$15', 'HML37E$16', 'HML37E$17', 'HML37E$18', 'HML37E$19', 'HML37E$20', 'HML37E$21', 'HML37E$22', 'HML37E$23', 'HML37E$24', 'HML37E$25', 'HML37E$26', 'HML37E$27', 'HML37E$28', 'HML37E$29', 'HML37E$30', 'HML37E$31', 'HML37E$32', 'HML37E$33', 'HML37E$34', 'HML37E$35', 'HML37E$36', 'HML37E$37', 'HML37E$38', 'HML37E$39', 'HML37E$40', 'HML37E$41', 'HML37E$42', 'HML37E$43', 'HML37E$44', 'HML37E$45', 'HML37E$46', 'HML37F$01', 'HML37F$02', 'HML37F$03', 'HML37F$04', 'HML37F$05', 'HML37F$06', 'HML37F$07', 'HML37F$08', 'HML37F$09', 'HML37F$10', 'HML37F$11', 'HML37F$12', 'HML37F$13', 'HML37F$14', 'HML37F$15', 'HML37F$16', 'HML37F$17', 'HML37F$18', 'HML37F$19', 'HML37F$20', 'HML37F$21', 'HML37F$22', 'HML37F$23', 'HML37F$24', 'HML37F$25', 'HML37F$26', 'HML37F$27', 'HML37F$28', 'HML37F$29', 'HML37F$30', 'HML37F$31', 'HML37F$32', 'HML37F$33', 'HML37F$34', 'HML37F$35', 'HML37F$36', 'HML37F$37', 'HML37F$38', 'HML37F$39', 'HML37F$40', 'HML37F$41', 'HML37F$42', 'HML37F$43', 'HML37F$44', 'HML37F$45', 'HML37F$46', 'HML37G$01', 'HML37G$02', 'HML37G$03', 'HML37G$04', 'HML37G$05', 'HML37G$06', 'HML37G$07', 'HML37G$08', 'HML37G$09', 'HML37G$10', 'HML37G$11', 'HML37G$12', 'HML37G$13', 'HML37G$14', 'HML37G$15', 'HML37G$16', 'HML37G$17', 'HML37G$18', 'HML37G$19', 'HML37G$20', 'HML37G$21', 'HML37G$22', 'HML37G$23', 'HML37G$24', 'HML37G$25', 'HML37G$26', 'HML37G$27', 'HML37G$28', 'HML37G$29', 'HML37G$30', 'HML37G$31', 'HML37G$32', 'HML37G$33', 'HML37G$34', 'HML37G$35', 'HML37G$36', 'HML37G$37', 'HML37G$38', 'HML37G$39', 'HML37G$40', 'HML37G$41', 'HML37G$42', 'HML37G$43', 'HML37G$44', 'HML37G$45', 'HML37G$46', 'HML37H$01', 'HML37H$02', 'HML37H$03', 'HML37H$04', 'HML37H$05', 'HML37H$06', 'HML37H$07', 'HML37H$08', 'HML37H$09', 'HML37H$10', 'HML37H$11', 'HML37H$12', 'HML37H$13', 'HML37H$14', 'HML37H$15', 'HML37H$16', 'HML37H$17', 'HML37H$18', 'HML37H$19', 'HML37H$20', 'HML37H$21', 'HML37H$22', 'HML37H$23', 'HML37H$24', 'HML37H$25', 'HML37H$26', 'HML37H$27', 'HML37H$28', 'HML37H$29', 'HML37H$30', 'HML37H$31', 'HML37H$32', 'HML37H$33', 'HML37H$34', 'HML37H$35', 'HML37H$36', 'HML37H$37', 'HML37H$38', 'HML37H$39', 'HML37H$40', 'HML37H$41', 'HML37H$42', 'HML37H$43', 'HML37H$44', 'HML37H$45', 'HML37H$46', 'HML37I$01', 'HML37I$02', 'HML37I$03', 'HML37I$04', 'HML37I$05', 'HML37I$06', 'HML37I$07', 'HML37I$08', 'HML37I$09', 'HML37I$10', 'HML37I$11', 'HML37I$12', 'HML37I$13', 'HML37I$14', 'HML37I$15', 'HML37I$16', 'HML37I$17', 'HML37I$18', 'HML37I$19', 'HML37I$20', 'HML37I$21', 'HML37I$22', 'HML37I$23', 'HML37I$24', 'HML37I$25', 'HML37I$26', 'HML37I$27', 'HML37I$28', 'HML37I$29', 'HML37I$30', 'HML37I$31', 'HML37I$32', 'HML37I$33', 'HML37I$34', 'HML37I$35', 'HML37I$36', 'HML37I$37', 'HML37I$38', 'HML37I$39', 'HML37I$40', 'HML37I$41', 'HML37I$42', 'HML37I$43', 'HML37I$44', 'HML37I$45', 'HML37I$46', 'HML37J$01', 'HML37J$02', 'HML37J$03', 'HML37J$04', 'HML37J$05', 'HML37J$06', 'HML37J$07', 'HML37J$08', 'HML37J$09', 'HML37J$10', 'HML37J$11', 'HML37J$12', 'HML37J$13', 'HML37J$14', 'HML37J$15', 'HML37J$16', 'HML37J$17', 'HML37J$18', 'HML37J$19', 'HML37J$20', 'HML37J$21', 'HML37J$22', 'HML37J$23', 'HML37J$24', 'HML37J$25', 'HML37J$26', 'HML37J$27', 'HML37J$28', 'HML37J$29', 'HML37J$30', 'HML37J$31', 'HML37J$32', 'HML37J$33', 'HML37J$34', 'HML37J$35', 'HML37J$36', 'HML37J$37', 'HML37J$38', 'HML37J$39', 'HML37J$40', '

In [56]:
for var in sorted(malaria_vars):

    print(
        var,
        ":",
        hrmeta2021.column_names_to_labels.get(var)
    )

HML1 : Number of mosquito bed nets
HML10$1 : Insecticide-Treated Net (ITN)
HML10$2 : Insecticide-Treated Net (ITN)
HML10$3 : Insecticide-Treated Net (ITN)
HML10$4 : Insecticide-Treated Net (ITN)
HML10$5 : Insecticide-Treated Net (ITN)
HML10$6 : Insecticide-Treated Net (ITN)
HML10$7 : Insecticide-Treated Net (ITN)
HML11$1 : Number of persons who slept under this net
HML11$2 : Number of persons who slept under this net
HML11$3 : Number of persons who slept under this net
HML11$4 : Number of persons who slept under this net
HML11$5 : Number of persons who slept under this net
HML11$6 : Number of persons who slept under this net
HML11$7 : Number of persons who slept under this net
HML12$01 : Type of Mosquito Bed Net(s) person slept under last night
HML12$02 : Type of Mosquito Bed Net(s) person slept under last night
HML12$03 : Type of Mosquito Bed Net(s) person slept under last night
HML12$04 : Type of Mosquito Bed Net(s) person slept under last night
HML12$05 : Type of Mosquito Bed Net(s) person slept under last night
HML12$06 : Type of Mosquito Bed Net(s) person slept under last night
HML12$07 : Type of Mosquito Bed Net(s) person slept under last night
HML12$08 : Type of Mosquito Bed Net(s) person slept under last night
HML12$09 : Type of Mosquito Bed Net(s) person slept under last night
HML12$10 : Type of Mosquito Bed Net(s) person slept under last night
HML12$11 : Type of Mosquito Bed Net(s) person slept under last night
HML12$12 : Type of Mosquito Bed Net(s) person slept under last night
HML12$13 : Type of Mosquito Bed Net(s) person slept under last night
HML12$14 : Type of Mosquito Bed Net(s) person slept under last night
HML12$15 : Type of Mosquito Bed Net(s) person slept under last night
HML12$16 : Type of Mosquito Bed Net(s) person slept under last night
HML12$17 : Type of Mosquito Bed Net(s) person slept under last night
HML12$18 : Type of Mosquito Bed Net(s) person slept under last night
HML12$19 : Type of Mosquito Bed Net(s) person slept under last night
HML12$20 : Type of Mosquito Bed Net(s) person slept under last night
HML12$21 : Type of Mosquito Bed Net(s) person slept under last night
HML12$22 : Type of Mosquito Bed Net(s) person slept under last night
HML12$23 : Type of Mosquito Bed Net(s) person slept under last night
HML12$24 : Type of Mosquito Bed Net(s) person slept under last night
HML12$25 : Type of Mosquito Bed Net(s) person slept under last night
HML12$26 : Type of Mosquito Bed Net(s) person slept under last night
HML12$27 : Type of Mosquito Bed Net(s) person slept under last night
HML12$28 : Type of Mosquito Bed Net(s) person slept under last night
HML12$29 : Type of Mosquito Bed Net(s) person slept under last night
HML12$30 : Type of Mosquito Bed Net(s) person slept under last night
HML12$31 : Type of Mosquito Bed Net(s) person slept under last night
HML12$32 : Type of Mosquito Bed Net(s) person slept under last night
HML12$33 : Type of Mosquito Bed Net(s) person slept under last night
HML12$34 : Type of Mosquito Bed Net(s) person slept under last night
HML12$35 : Type of Mosquito Bed Net(s) person slept under last night
HML12$36 : Type of Mosquito Bed Net(s) person slept under last night
HML12$37 : Type of Mosquito Bed Net(s) person slept under last night
HML12$38 : Type of Mosquito Bed Net(s) person slept under last night
HML12$39 : Type of Mosquito Bed Net(s) person slept under last night
HML12$40 : Type of Mosquito Bed Net(s) person slept under last night
HML12$41 : Type of Mosquito Bed Net(s) person slept under last night
HML12$42 : Type of Mosquito Bed Net(s) person slept under last night
HML12$43 : Type of Mosquito Bed Net(s) person slept under last night
HML12$44 : Type of Mosquito Bed Net(s) person slept under last night
HML12$45 : Type of Mosquito Bed Net(s) person slept under last night
HML12$46 : Type of Mosquito Bed Net(s) person slept under last night
HML13$01 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$02 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$03 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$04 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$05 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$06 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$07 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$08 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$09 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$10 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$11 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$12 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$13 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$14 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$15 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$16 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$17 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$18 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$19 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$20 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$21 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$22 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$23 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$24 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$25 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$26 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$27 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$28 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$29 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$30 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$31 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$32 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$33 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$34 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$35 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$36 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$37 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$38 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$39 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$40 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$41 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$42 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$43 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$44 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$45 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML13$46 : Net Designation Number (HMLIDX) for 1st net person slept under last night
HML14$01 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$02 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$03 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$04 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$05 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$06 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$07 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$08 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$09 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$10 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$11 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$12 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$13 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$14 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$15 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$16 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$17 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$18 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$19 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$20 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$21 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$22 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$23 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$24 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$25 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$26 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$27 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$28 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$29 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$30 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$31 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$32 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$33 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$34 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$35 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$36 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$37 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$38 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$39 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$40 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$41 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$42 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$43 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$44 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$45 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML14$46 : Net Designation Number (HMLIDX) for 2nd net person slept under last night
HML15$01 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$02 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$03 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$04 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$05 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$06 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$07 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$08 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$09 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$10 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$11 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$12 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$13 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$14 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$15 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$16 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$17 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$18 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$19 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$20 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$21 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$22 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$23 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$24 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$25 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$26 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$27 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$28 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$29 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$30 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$31 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$32 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$33 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$34 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$35 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$36 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$37 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$38 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$39 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$40 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$41 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$42 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$43 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$44 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$45 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML15$46 : Net Designation Number (HMLIDX) for 3rd net person slept under last night
HML16$01 : Corrected age from Individual file
HML16$02 : Corrected age from Individual file
HML16$03 : Corrected age from Individual file
HML16$04 : Corrected age from Individual file
HML16$05 : Corrected age from Individual file
HML16$06 : Corrected age from Individual file
HML16$07 : Corrected age from Individual file
HML16$08 : Corrected age from Individual file
HML16$09 : Corrected age from Individual file
HML16$10 : Corrected age from Individual file
HML16$11 : Corrected age from Individual file
HML16$12 : Corrected age from Individual file
HML16$13 : Corrected age from Individual file
HML16$14 : Corrected age from Individual file
HML16$15 : Corrected age from Individual file
HML16$16 : Corrected age from Individual file
HML16$17 : Corrected age from Individual file
HML16$18 : Corrected age from Individual file
HML16$19 : Corrected age from Individual file
HML16$20 : Corrected age from Individual file
HML16$21 : Corrected age from Individual file
HML16$22 : Corrected age from Individual file
HML16$23 : Corrected age from Individual file
HML16$24 : Corrected age from Individual file
HML16$25 : Corrected age from Individual file
HML16$26 : Corrected age from Individual file
HML16$27 : Corrected age from Individual file
HML16$28 : Corrected age from Individual file
HML16$29 : Corrected age from Individual file
HML16$30 : Corrected age from Individual file
HML16$31 : Corrected age from Individual file
HML16$32 : Corrected age from Individual file
HML16$33 : Corrected age from Individual file
HML16$34 : Corrected age from Individual file
HML16$35 : Corrected age from Individual file
HML16$36 : Corrected age from Individual file
HML16$37 : Corrected age from Individual file
HML16$38 : Corrected age from Individual file
HML16$39 : Corrected age from Individual file
HML16$40 : Corrected age from Individual file
HML16$41 : Corrected age from Individual file
HML16$42 : Corrected age from Individual file
HML16$43 : Corrected age from Individual file
HML16$44 : Corrected age from Individual file
HML16$45 : Corrected age from Individual file
HML16$46 : Corrected age from Individual file
HML16A$01 : Age in months (for children)
HML16A$02 : Age in months (for children)
HML16A$03 : Age in months (for children)
HML16A$04 : Age in months (for children)
HML16A$05 : Age in months (for children)
HML16A$06 : Age in months (for children)
HML16A$07 : Age in months (for children)
HML16A$08 : Age in months (for children)
HML16A$09 : Age in months (for children)
HML16A$10 : Age in months (for children)
HML16A$11 : Age in months (for children)
HML16A$12 : Age in months (for children)
HML16A$13 : Age in months (for children)
HML16A$14 : Age in months (for children)
HML16A$15 : Age in months (for children)
HML16A$16 : Age in months (for children)
HML16A$17 : Age in months (for children)
HML16A$18 : Age in months (for children)
HML16A$19 : Age in months (for children)
HML16A$20 : Age in months (for children)
HML16A$21 : Age in months (for children)
HML16A$22 : Age in months (for children)
HML16A$23 : Age in months (for children)
HML16A$24 : Age in months (for children)
HML16A$25 : Age in months (for children)
HML16A$26 : Age in months (for children)
HML16A$27 : Age in months (for children)
HML16A$28 : Age in months (for children)
HML16A$29 : Age in months (for children)
HML16A$30 : Age in months (for children)
HML16A$31 : Age in months (for children)
HML16A$32 : Age in months (for children)
HML16A$33 : Age in months (for children)
HML16A$34 : Age in months (for children)
HML16A$35 : Age in months (for children)
HML16A$36 : Age in months (for children)
HML16A$37 : Age in months (for children)
HML16A$38 : Age in months (for children)
HML16A$39 : Age in months (for children)
HML16A$40 : Age in months (for children)
HML16A$41 : Age in months (for children)
HML16A$42 : Age in months (for children)
HML16A$43 : Age in months (for children)
HML16A$44 : Age in months (for children)
HML16A$45 : Age in months (for children)
HML16A$46 : Age in months (for children)
HML17$01 : Flag for age from Individual file
HML17$02 : Flag for age from Individual file
HML17$03 : Flag for age from Individual file
HML17$04 : Flag for age from Individual file
HML17$05 : Flag for age from Individual file
HML17$06 : Flag for age from Individual file
HML17$07 : Flag for age from Individual file
HML17$08 : Flag for age from Individual file
HML17$09 : Flag for age from Individual file

In [57]:
keywords = [
    "malaria",
    "fever",
    "test",
    "rdt",
    "microscopy",
    "blood"
]

for var in hrmeta2021.column_names:

    label = hrmeta2021.column_names_to_labels.get(var)

    if label:

        label_lower = str(label).lower()

        if any(
            word in label_lower
            for word in keywords
        ):

            print(var, ":", label)

SB110E$01 : Read consent statement for additional testing
SB110E$02 : Read consent statement for additional testing
SB110E$03 : Read consent statement for additional testing
SB110E$04 : Read consent statement for additional testing
SB110E$05 : Read consent statement for additional testing
SB110E$06 : Read consent statement for additional testing
SB110E$07 : Read consent statement for additional testing
SB110E$08 : Read consent statement for additional testing
SB110E$09 : Read consent statement for additional testing
SB110E$10 : Read consent statement for additional testing
SB110E$11 : Read consent statement for additional testing
SB110E$12 : Read consent statement for additional testing
SB110E$13 : Read consent statement for additional testing
SB110F$01 : Fieldworker measurer code for additional testing
SB110F$02 : Fieldworker measurer code for additional testing
SB110F$03 : Fieldworker measurer code for additional testing
SB110F$04 : Fieldworker measurer code for additional testing
SB110F$05 : Fieldworker measurer code for additional testing
SB110F$06 : Fieldworker measurer code for additional testing
SB110F$07 : Fieldworker measurer code for additional testing
SB110F$08 : Fieldworker measurer code for additional testing
SB110F$09 : Fieldworker measurer code for additional testing
SB110F$10 : Fieldworker measurer code for additional testing
SB110F$11 : Fieldworker measurer code for additional testing
SB110F$12 : Fieldworker measurer code for additional testing
SB110F$13 : Fieldworker measurer code for additional testing
HML30$01 : Line number of parent/caretaker (for malaria testing)
HML30$02 : Line number of parent/caretaker (for malaria testing)
HML30$03 : Line number of parent/caretaker (for malaria testing)
HML30$04 : Line number of parent/caretaker (for malaria testing)
HML30$05 : Line number of parent/caretaker (for malaria testing)
HML30$06 : Line number of parent/caretaker (for malaria testing)
HML30$07 : Line number of parent/caretaker (for malaria testing)
HML30$08 : Line number of parent/caretaker (for malaria testing)
HML30$09 : Line number of parent/caretaker (for malaria testing)
HML30$10 : Line number of parent/caretaker (for malaria testing)
HML30$11 : Line number of parent/caretaker (for malaria testing)
HML30$12 : Line number of parent/caretaker (for malaria testing)
HML30$13 : Line number of parent/caretaker (for malaria testing)
HML30$14 : Line number of parent/caretaker (for malaria testing)
HML30$15 : Line number of parent/caretaker (for malaria testing)
HML30$16 : Line number of parent/caretaker (for malaria testing)
HML30$17 : Line number of parent/caretaker (for malaria testing)
HML30$18 : Line number of parent/caretaker (for malaria testing)
HML30$19 : Line number of parent/caretaker (for malaria testing)
HML30$20 : Line number of parent/caretaker (for malaria testing)
HML30$21 : Line number of parent/caretaker (for malaria testing)
HML30$22 : Line number of parent/caretaker (for malaria testing)
HML30$23 : Line number of parent/caretaker (for malaria testing)
HML30$24 : Line number of parent/caretaker (for malaria testing)
HML30$25 : Line number of parent/caretaker (for malaria testing)
HML30$26 : Line number of parent/caretaker (for malaria testing)
HML30$27 : Line number of parent/caretaker (for malaria testing)
HML30$28 : Line number of parent/caretaker (for malaria testing)
HML30$29 : Line number of parent/caretaker (for malaria testing)
HML30$30 : Line number of parent/caretaker (for malaria testing)
HML30$31 : Line number of parent/caretaker (for malaria testing)
HML30$32 : Line number of parent/caretaker (for malaria testing)
HML30$33 : Line number of parent/caretaker (for malaria testing)
HML30$34 : Line number of parent/caretaker (for malaria testing)
HML30$35 : Line number of parent/caretaker (for malaria testing)
HML30$36 : Line number of parent/caretaker (for malaria testing)
HML30$37 : Line number of parent/caretaker (for malaria testing)
HML30$38 : Line number of parent/caretaker (for malaria testing)
HML30$39 : Line number of parent/caretaker (for malaria testing)
HML30$40 : Line number of parent/caretaker (for malaria testing)
HML30$41 : Line number of parent/caretaker (for malaria testing)
HML30$42 : Line number of parent/caretaker (for malaria testing)
HML30$43 : Line number of parent/caretaker (for malaria testing)
HML30$44 : Line number of parent/caretaker (for malaria testing)
HML30$45 : Line number of parent/caretaker (for malaria testing)
HML30$46 : Line number of parent/caretaker (for malaria testing)
HML31$01 : Read consent statement for malaria
HML31$02 : Read consent statement for malaria
HML31$03 : Read consent statement for malaria
HML31$04 : Read consent statement for malaria
HML31$05 : Read consent statement for malaria
HML31$06 : Read consent statement for malaria
HML31$07 : Read consent statement for malaria
HML31$08 : Read consent statement for malaria
HML31$09 : Read consent statement for malaria
HML31$10 : Read consent statement for malaria
HML31$11 : Read consent statement for malaria
HML31$12 : Read consent statement for malaria
HML31$13 : Read consent statement for malaria
HML31$14 : Read consent statement for malaria
HML31$15 : Read consent statement for malaria
HML31$16 : Read consent statement for malaria
HML31$17 : Read consent statement for malaria
HML31$18 : Read consent statement for malaria
HML31$19 : Read consent statement for malaria
HML31$20 : Read consent statement for malaria
HML31$21 : Read consent statement for malaria
HML31$22 : Read consent statement for malaria
HML31$23 : Read consent statement for malaria
HML31$24 : Read consent statement for malaria
HML31$25 : Read consent statement for malaria
HML31$26 : Read consent statement for malaria
HML31$27 : Read consent statement for malaria
HML31$28 : Read consent statement for malaria
HML31$29 : Read consent statement for malaria
HML31$30 : Read consent statement for malaria
HML31$31 : Read consent statement for malaria
HML31$32 : Read consent statement for malaria
HML31$33 : Read consent statement for malaria
HML31$34 : Read consent statement for malaria
HML31$35 : Read consent statement for malaria
HML31$36 : Read consent statement for malaria
HML31$37 : Read consent statement for malaria
HML31$38 : Read consent statement for malaria
HML31$39 : Read consent statement for malaria
HML31$40 : Read consent statement for malaria
HML31$41 : Read consent statement for malaria
HML31$42 : Read consent statement for malaria
HML31$43 : Read consent statement for malaria
HML31$44 : Read consent statement for malaria
HML31$45 : Read consent statement for malaria
HML31$46 : Read consent statement for malaria
HML32$01 : Final result of malaria from blood smear test
HML32$02 : Final result of malaria from blood smear test
HML32$03 : Final result of malaria from blood smear test
HML32$04 : Final result of malaria from blood smear test
HML32$05 : Final result of malaria from blood smear test
HML32$06 : Final result of malaria from blood smear test
HML32$07 : Final result of malaria from blood smear test
HML32$08 : Final result of malaria from blood smear test
HML32$09 : Final result of malaria from blood smear test
HML32$10 : Final result of malaria from blood smear test
HML32$11 : Final result of malaria from blood smear test
HML32$12 : Final result of malaria from blood smear test
HML32$13 : Final result of malaria from blood smear test
HML32$14 : Final result of malaria from blood smear test
HML32$15 : Final result of malaria from blood smear test
HML32$16 : Final result of malaria from blood smear test
HML32$17 : Final result of malaria from blood smear test
HML32$18 : Final result of malaria from blood smear test
HML32$19 : Final result of malaria from blood smear test
HML32$20 : Final result of malaria from blood smear test
HML32$21 : Final result of malaria from blood smear test
HML32$22 : Final result of malaria from blood smear test
HML32$23 : Final result of malaria from blood smear test
HML32$24 : Final result of malaria from blood smear test
HML32$25 : Final result of malaria from blood smear test
HML32$26 : Final result of malaria from blood smear test
HML32$27 : Final result of malaria from blood smear test
HML32$28 : Final result of malaria from blood smear test
HML32$29 : Final result of malaria from blood smear test
HML32$30 : Final result of malaria from blood smear test
HML32$31 : Final result of malaria from blood smear test
HML32$32 : Final result of malaria from blood smear test
HML32$33 : Final result of malaria from blood smear test
HML32$34 : Final result of malaria from blood smear test
HML32$35 : Final result of malaria from blood smear test
HML32$36 : Final result of malaria from blood smear test
HML32$37 : Final result of malaria from blood smear test
HML32$38 : Final result of malaria from blood smear test
HML32$39 : Final result of malaria from blood smear test
HML32$40 : Final result of malaria from blood smear test
HML32$41 : Final result of malaria from blood smear test
HML32$42 : Final result of malaria from blood smear test
HML32$43 : Final result of malaria from blood smear test
HML32$44 : Final result of malaria from blood smear test
HML32$45 : Final result of malaria from blood smear test
HML32$46 : Final result of malaria from blood smear test
HML32B$01 : Presence of species: malariae (Pm)
HML32B$02 : Presence of species: malariae (Pm)
HML32B$03 : Presence of species: malariae (Pm)
HML32B$04 : Presence of species: malariae (Pm)
HML32B$05 : Presence of species: malariae (Pm)
HML32B$06 : Presence of species: malariae (Pm)
HML32B$07 : Presence of species: malariae (Pm)
HML32B$08 : Presence of species: malariae (Pm)
HML32B$09 : Presence of species: malariae (Pm)
HML32B$10 : Presence of species: malariae (Pm)
HML32B$11 : Presence of species: malariae (Pm)
HML32B$12 : Presence of species: malariae (Pm)
HML32B$13 : Presence of species: malariae (Pm)
HML32B$14 : Presence of species: malariae (Pm)
HML32B$15 : Presence of species: malariae (Pm)
HML32B$16 : Presence of species: malariae (Pm)
HML32B$17 : Presence of species: malariae (Pm)
HML32B$18 : Presence of species: malariae (Pm)
HML32B$19 : Presence of species: malariae (Pm)
HML32B$20 : Presence of species: malariae (Pm)
HML32B$21 : Presence of species: malariae (Pm)
HML32B$22 : Presence of species: malariae (Pm)
HML32B$23 : Presence of species: malariae (Pm)
HML32B$24 : Presence of species: malariae (Pm)
HML32B$25 : Presence of species: malariae (Pm)
HML32B$26 : Presence of species: malariae (Pm)
HML32B$27 : Presence of species: malariae (Pm)
HML32B$28 : Presence of species: malariae (Pm)
HML32B$29 : Presence of species: malariae (Pm)
HML32B$30 : Presence of species: malariae (Pm)
HML32B$31 : Presence of species: malariae (Pm)
HML32B$32 : Presence of species: malariae (Pm)
HML32B$33 : Presence of species: malariae (Pm)
HML32B$34 : Presence of species: malariae (Pm)
HML32B$35 : Presence of species: malariae (Pm)
HML32B$36 : Presence of species: malariae (Pm)
HML32B$37 : Presence of species: malariae (Pm)
HML32B$38 : Presence of species: malariae (Pm)
HML32B$39 : Presence of species: malariae (Pm)
HML32B$40 : Presence of species: malariae (Pm)
HML32B$41 : Presence of species: malariae (Pm)
HML32B$42 : Presence of species: malariae (Pm)
HML32B$43 : Presence of species: malariae (Pm)
HML32B$44 : Presence of species: malariae (Pm)
HML32B$45 : Presence of species: malariae (Pm)
HML32B$46 : Presence of species: malariae (Pm)
HML33$01 : Result of malaria measurement
HML33$02 : Result of malaria measurement
HML33$03 : Result of malaria measurement
HML33$04 : Result of malaria measurement
HML33$05 : Result of malaria measurement
HML33$06 : Result of malaria measurement
HML33$07 : Result of malaria measurement
HML33$08 : Result of malaria measurement
HML33$09 : Result of malaria measurement
HML33$10 : Result of malaria measurement
HML33$11 : Result of malaria measurement
HML33$12 : Result of malaria measurement
HML33$13 : Result of malaria measurement
HML33$14 : Result of malaria measurement
HML33$15 : Result of malaria measurement
HML33$16 : Result of malaria measurement
HML33$17 : Result of malaria measurement
HML33$18 : Result of malaria measurement
HML33$19 : Result of malaria measurement
HML33$20 : Result of malaria measurement
HML33$21 : Result of malaria measurement
HML33$22 : Result of malaria measurement
HML33$23 : Result of malaria measurement
HML33$24 : Result of malaria measurement
HML33$25 : Result of malaria measurement
HML33$26 : Result of malaria measurement
HML33$27 : Result of malaria measurement
HML33$28 : Result of malaria measurement
HML33$29 : Result of malaria measurement
HML33$30 : Result of malaria measurement
HML33$31 : Result of malaria measurement
HML33$32 : Result of malaria measurement
HML33$33 : Result of malaria measurement
HML33$34 : Result of malaria measurement
HML33$35 : Result of malaria measurement
HML33$36 : Result of malaria measurement
HML33$37 : Result of malaria measurement
HML33$38 : Result of malaria measurement
HML33$39 : Result of malaria measurement
HML33$40 : Result of malaria measurement
HML33$41 : Result of malaria measurement
HML33$42 : Result of malaria measurement
HML33$43 : Result of malaria measurement
HML33$44 : Result of malaria measurement
HML33$45 : Result of malaria measurement
HML33$46 : Result of malaria measurement
HML34$01 : Bar code for blood smear sample
HML34$02 : Bar code for blood smear sample
HML34$03 : Bar code for blood smear sample
HML34$04 : Bar code for blood smear sample
HML34$05 : Bar code for blood smear sample
HML34$06 : Bar code for blood smear sample
HML34$07 : Bar code for blood smear sample
HML34$08 : Bar code for blood smear sample
HML34$09 : Bar code for blood smear sample
HML34$10 : Bar code for blood smear sample
HML34$11 : Bar code for blood smear sample
HML34$12 : Bar code for blood smear sample
HML34$13 : Bar code for blood smear sample
HML34$14 : Bar code for blood smear sample
HML34$15 : Bar code for blood smear sample
HML34$16 : Bar code for blood smear sample
HML34$17 : Bar code for blood smear sample
HML34$18 : Bar code for blood smear sample
HML34$19 : Bar code for blood smear sample
HML34$20 : Bar code for blood smear sample
HML34$21 : Bar code for blood smear sample
HML34$22 : Bar code for blood smear sample
HML34$23 : Bar code for blood smear sample
HML34$24 : Bar code for blood smear sample
HML34$25 : Bar code for blood smear sample
HML34$26 : Bar code for blood smear sample
HML34$27 : Bar code for blood smear sample
HML34$28 : Bar code for blood smear sample
HML34$29 : Bar code for blood smear sample
HML34$30 : Bar code for blood smear sample
HML34$31 : Bar code for blood smear sample
HML34$32 : Bar code for blood smear sample
HML34$33 : Bar code for blood smear sample
HML34$34 : Bar code for blood smear sample
HML34$35 : Bar code for blood smear sample
HML34$36 : Bar code for blood smear sample
HML34$37 : Bar code for blood smear sample
HML34$38 : Bar code for blood smear sample
HML34$39 : Bar code for blood smear sample
HML34$40 : Bar code for blood smear sample
HML34$41 : Bar code for blood smear sample
HML34$42 : Bar code for blood smear sample
HML34$43 : Bar code for blood smear sample
HML34$44 : Bar code for blood smear sample
HML34$45 : Bar code for blood smear sample
HML34$46 : Bar code for blood smear sample
HML35$01 : Result of malaria rapid test
HML35$02 : Result of malaria rapid test
HML35$03 : Result of malaria rapid test
HML35$04 : Result of malaria rapid test
HML35$05 : Result of malaria rapid test
HML35$06 : Result of malaria rapid test
HML35$07 : Result of malaria rapid test
HML35$08 : Result of malaria rapid test
HML35$09 : Result of malaria rapid test
HML35$10 : Result of malaria rapid test
HML35$11 : Result of malaria rapid test
HML35$12 : Result of malaria rapid test
HML35$13 : Result of malaria rapid test
HML35$14 : Result of malaria rapid test
HML35$15 : Result of malaria rapid test
HML35$16 : Result of malaria rapid test
HML35$17 : Result of malaria rapid test
HML35$18 : Result of malaria rapid test
HML35$19 : Result of malaria rapid test
HML35$20 : Result of malaria rapid test
HML35$21 : Result of malaria rapid test
HML35$22 : Result of malaria rapid test
HML35$23 : Result of malaria rapid test
HML35$24 : Result of malaria rapid test
HML35$25 : Result of malaria rapid test
HML35$26 : Result of malaria rapid test
HML35$27 : Result of malaria rapid test
HML35$28 : Result of malaria rapid test
HML35$29 : Result of malaria rapid test
HML35$30 : Result of malaria rapid test
HML35$31 : Result of malaria rapid test
HML35$32 : Result of malaria rapid test
HML35$33 : Result of malaria rapid test
HML35$34 : Result of malaria rapid test
HML35$35 : Result of malaria rapid test
HML35$36 : Result of malaria rapid test
HML35$37 : Result of malaria rapid test
HML35$38 : Result of malaria rapid test
HML35$39 : Result of malaria rapid test
HML35$40 : Result of malaria rapid test
HML35$41 : Result of malaria rapid test
HML35$42 : Result of malaria rapid test
HML35$43 : Result of malaria rapid test
HML35$44 : Result of malaria rapid test
HML35$45 : Result of malaria rapid test
HML35$46 : Result of malaria rapid test
HML36$01 : Fieldworker measurer code for malaria
HML36$02 : Fieldworker measurer code for malaria
HML36$03 : Fieldworker measurer code for malaria
HML36$04 : Fieldworker measurer code for malaria
HML36$05 : Fieldworker measurer code for malaria
HML36$06 : Fieldworker measurer code for malaria
HML36$07 : Fieldworker measurer code for malaria
HML36$08 : Fieldworker measurer code for malaria
HML36$09 : Fieldworker measurer code for malaria
HML36$10 : Fieldworker measurer code for malaria
HML36$11 : Fieldworker measurer code for malaria
HML36$12 : Fieldworker measurer code for malaria
HML36$13 : Fieldworker measurer code for malaria
HML36$14 : Fieldworker measurer code for malaria
HML36$15 : Fieldworker measurer code for malaria
HML36$16 : Fieldworker measurer code for malaria
HML36$17 : Fieldworker measurer code for malaria
HML36$18 : Fieldworker measurer code for malaria
HML36$19 : Fieldworker measurer code for malaria
HML36$20 : Fieldworker measurer code for malaria
HML36$21 : Fieldworker measurer code for malaria
HML36$22 : Fieldworker measurer code for malaria
HML36$23 : Fieldworker measurer code for malaria
HML36$24 : Fieldworker measurer code for malaria
HML36$25 : Fieldworker measurer code for malaria
HML36$26 : Fieldworker measurer code for malaria
HML36$27 : Fieldworker measurer code for malaria
HML36$28 : Fieldworker measurer code for malaria
HML36$29 : Fieldworker measurer code for malaria
HML36$30 : Fieldworker measurer code for malaria
HML36$31 : Fieldworker measurer code for malaria
HML36$32 : Fieldworker measurer code for malaria
HML36$33 : Fieldworker measurer code for malaria
HML36$34 : Fieldworker measurer code for malaria
HML36$35 : Fieldworker measurer code for malaria
HML36$36 : Fieldworker measurer code for malaria
HML36$37 : Fieldworker measurer code for malaria
HML36$38 : Fieldworker measurer code for malaria
HML36$39 : Fieldworker measurer code for malaria
HML36$40 : Fieldworker measurer code for malaria
HML36$41 : Fieldworker measurer code for malaria
HML36$42 : Fieldworker measurer code for malaria
HML36$43 : Fieldworker measurer code for malaria
HML36$44 : Fieldworker measurer code for malaria
HML36$45 : Fieldworker measurer code for malaria
HML36$46 : Fieldworker measurer code for malaria
HML38$01 : Child taken or taking first line medicine given by health provider for malaria
HML38$02 : Child taken or taking first line medicine given by health provider for malaria
HML38$03 : Child taken or taking first line medicine given by health provider for malaria
HML38$04 : Child taken or taking first line medicine given by health provider for malaria
HML38$05 : Child taken or taking first line medicine given by health provider for malaria
HML38$06 : Child taken or taking first line medicine given by health provider for malaria

In [58]:
rows = []

for var in hrmeta2021.column_names:

    rows.append({
        "Variable": var,
        "Label": hrmeta2021.column_names_to_labels.get(var)
    })

household_dict = pd.DataFrame(rows)

household_dict.to_excel(
    "Household2021_Variable_Dictionary.xlsx",
    index=False
)

In [59]:
print(hr2010.shape)
print(hr2015.shape)
print(hr2021.shape)

(5895, 1975)
(7745, 2649)
(13727, 2928)

In [60]:
print(hr2021.columns[:50])

Index(['HHID', 'HV000', 'HV001', 'HV002', 'HV003', 'HV004', 'HV005', 'HV006',
       'HV007', 'HV008', 'HV008A', 'HV009', 'HV010', 'HV011', 'HV012', 'HV013',
       'HV014', 'HV015', 'HV016', 'HV017', 'HV018', 'HV019', 'HV020', 'HV021',
       'HV022', 'HV023', 'HV024', 'HV025', 'HV026', 'HV027', 'HV028', 'HV030',
       'HV031', 'HV032', 'HV035', 'HV040', 'HV041', 'HV042', 'HV045A',
       'HV045B', 'HV045C', 'HV046', 'HV047', 'HV801', 'HV802', 'HV803',
       'HV804', 'HV807D', 'HV807M', 'HV807Y'],
      dtype='object')

In [61]:
keywords = [
    "malaria",
    "fever",
    "test",
    "blood",
    "microscopy",
    "rapid",
    "rdt",
    "parasite"
]

for var in hrmeta2021.column_names:

    label = hrmeta2021.column_names_to_labels.get(var)

    if label:

        label_lower = str(label).lower()

        if any(
            word in label_lower
            for word in keywords
        ):
            print(var, ":", label)

SB110E$01 : Read consent statement for additional testing
SB110E$02 : Read consent statement for additional testing
SB110E$03 : Read consent statement for additional testing
SB110E$04 : Read consent statement for additional testing
SB110E$05 : Read consent statement for additional testing
SB110E$06 : Read consent statement for additional testing
SB110E$07 : Read consent statement for additional testing
SB110E$08 : Read consent statement for additional testing
SB110E$09 : Read consent statement for additional testing
SB110E$10 : Read consent statement for additional testing
SB110E$11 : Read consent statement for additional testing
SB110E$12 : Read consent statement for additional testing
SB110E$13 : Read consent statement for additional testing
SB110F$01 : Fieldworker measurer code for additional testing
SB110F$02 : Fieldworker measurer code for additional testing
SB110F$03 : Fieldworker measurer code for additional testing
SB110F$04 : Fieldworker measurer code for additional testing
SB110F$05 : Fieldworker measurer code for additional testing
SB110F$06 : Fieldworker measurer code for additional testing
SB110F$07 : Fieldworker measurer code for additional testing
SB110F$08 : Fieldworker measurer code for additional testing
SB110F$09 : Fieldworker measurer code for additional testing
SB110F$10 : Fieldworker measurer code for additional testing
SB110F$11 : Fieldworker measurer code for additional testing
SB110F$12 : Fieldworker measurer code for additional testing
SB110F$13 : Fieldworker measurer code for additional testing
HML30$01 : Line number of parent/caretaker (for malaria testing)
HML30$02 : Line number of parent/caretaker (for malaria testing)
HML30$03 : Line number of parent/caretaker (for malaria testing)
HML30$04 : Line number of parent/caretaker (for malaria testing)
HML30$05 : Line number of parent/caretaker (for malaria testing)
HML30$06 : Line number of parent/caretaker (for malaria testing)
HML30$07 : Line number of parent/caretaker (for malaria testing)
HML30$08 : Line number of parent/caretaker (for malaria testing)
HML30$09 : Line number of parent/caretaker (for malaria testing)
HML30$10 : Line number of parent/caretaker (for malaria testing)
HML30$11 : Line number of parent/caretaker (for malaria testing)
HML30$12 : Line number of parent/caretaker (for malaria testing)
HML30$13 : Line number of parent/caretaker (for malaria testing)
HML30$14 : Line number of parent/caretaker (for malaria testing)
HML30$15 : Line number of parent/caretaker (for malaria testing)
HML30$16 : Line number of parent/caretaker (for malaria testing)
HML30$17 : Line number of parent/caretaker (for malaria testing)
HML30$18 : Line number of parent/caretaker (for malaria testing)
HML30$19 : Line number of parent/caretaker (for malaria testing)
HML30$20 : Line number of parent/caretaker (for malaria testing)
HML30$21 : Line number of parent/caretaker (for malaria testing)
HML30$22 : Line number of parent/caretaker (for malaria testing)
HML30$23 : Line number of parent/caretaker (for malaria testing)
HML30$24 : Line number of parent/caretaker (for malaria testing)
HML30$25 : Line number of parent/caretaker (for malaria testing)
HML30$26 : Line number of parent/caretaker (for malaria testing)
HML30$27 : Line number of parent/caretaker (for malaria testing)
HML30$28 : Line number of parent/caretaker (for malaria testing)
HML30$29 : Line number of parent/caretaker (for malaria testing)
HML30$30 : Line number of parent/caretaker (for malaria testing)
HML30$31 : Line number of parent/caretaker (for malaria testing)
HML30$32 : Line number of parent/caretaker (for malaria testing)
HML30$33 : Line number of parent/caretaker (for malaria testing)
HML30$34 : Line number of parent/caretaker (for malaria testing)
HML30$35 : Line number of parent/caretaker (for malaria testing)
HML30$36 : Line number of parent/caretaker (for malaria testing)
HML30$37 : Line number of parent/caretaker (for malaria testing)
HML30$38 : Line number of parent/caretaker (for malaria testing)
HML30$39 : Line number of parent/caretaker (for malaria testing)
HML30$40 : Line number of parent/caretaker (for malaria testing)
HML30$41 : Line number of parent/caretaker (for malaria testing)
HML30$42 : Line number of parent/caretaker (for malaria testing)
HML30$43 : Line number of parent/caretaker (for malaria testing)
HML30$44 : Line number of parent/caretaker (for malaria testing)
HML30$45 : Line number of parent/caretaker (for malaria testing)
HML30$46 : Line number of parent/caretaker (for malaria testing)
HML31$01 : Read consent statement for malaria
HML31$02 : Read consent statement for malaria
HML31$03 : Read consent statement for malaria
HML31$04 : Read consent statement for malaria
HML31$05 : Read consent statement for malaria
HML31$06 : Read consent statement for malaria
HML31$07 : Read consent statement for malaria
HML31$08 : Read consent statement for malaria
HML31$09 : Read consent statement for malaria
HML31$10 : Read consent statement for malaria
HML31$11 : Read consent statement for malaria
HML31$12 : Read consent statement for malaria
HML31$13 : Read consent statement for malaria
HML31$14 : Read consent statement for malaria
HML31$15 : Read consent statement for malaria
HML31$16 : Read consent statement for malaria
HML31$17 : Read consent statement for malaria
HML31$18 : Read consent statement for malaria
HML31$19 : Read consent statement for malaria
HML31$20 : Read consent statement for malaria
HML31$21 : Read consent statement for malaria
HML31$22 : Read consent statement for malaria
HML31$23 : Read consent statement for malaria
HML31$24 : Read consent statement for malaria
HML31$25 : Read consent statement for malaria
HML31$26 : Read consent statement for malaria
HML31$27 : Read consent statement for malaria
HML31$28 : Read consent statement for malaria
HML31$29 : Read consent statement for malaria
HML31$30 : Read consent statement for malaria
HML31$31 : Read consent statement for malaria
HML31$32 : Read consent statement for malaria
HML31$33 : Read consent statement for malaria
HML31$34 : Read consent statement for malaria
HML31$35 : Read consent statement for malaria
HML31$36 : Read consent statement for malaria
HML31$37 : Read consent statement for malaria
HML31$38 : Read consent statement for malaria
HML31$39 : Read consent statement for malaria
HML31$40 : Read consent statement for malaria
HML31$41 : Read consent statement for malaria
HML31$42 : Read consent statement for malaria
HML31$43 : Read consent statement for malaria
HML31$44 : Read consent statement for malaria
HML31$45 : Read consent statement for malaria
HML31$46 : Read consent statement for malaria
HML32$01 : Final result of malaria from blood smear test
HML32$02 : Final result of malaria from blood smear test
HML32$03 : Final result of malaria from blood smear test
HML32$04 : Final result of malaria from blood smear test
HML32$05 : Final result of malaria from blood smear test
HML32$06 : Final result of malaria from blood smear test
HML32$07 : Final result of malaria from blood smear test
HML32$08 : Final result of malaria from blood smear test
HML32$09 : Final result of malaria from blood smear test
HML32$10 : Final result of malaria from blood smear test
HML32$11 : Final result of malaria from blood smear test
HML32$12 : Final result of malaria from blood smear test
HML32$13 : Final result of malaria from blood smear test
HML32$14 : Final result of malaria from blood smear test
HML32$15 : Final result of malaria from blood smear test
HML32$16 : Final result of malaria from blood smear test
HML32$17 : Final result of malaria from blood smear test
HML32$18 : Final result of malaria from blood smear test
HML32$19 : Final result of malaria from blood smear test
HML32$20 : Final result of malaria from blood smear test
HML32$21 : Final result of malaria from blood smear test
HML32$22 : Final result of malaria from blood smear test
HML32$23 : Final result of malaria from blood smear test
HML32$24 : Final result of malaria from blood smear test
HML32$25 : Final result of malaria from blood smear test
HML32$26 : Final result of malaria from blood smear test
HML32$27 : Final result of malaria from blood smear test
HML32$28 : Final result of malaria from blood smear test
HML32$29 : Final result of malaria from blood smear test
HML32$30 : Final result of malaria from blood smear test
HML32$31 : Final result of malaria from blood smear test
HML32$32 : Final result of malaria from blood smear test
HML32$33 : Final result of malaria from blood smear test
HML32$34 : Final result of malaria from blood smear test
HML32$35 : Final result of malaria from blood smear test
HML32$36 : Final result of malaria from blood smear test
HML32$37 : Final result of malaria from blood smear test
HML32$38 : Final result of malaria from blood smear test
HML32$39 : Final result of malaria from blood smear test
HML32$40 : Final result of malaria from blood smear test
HML32$41 : Final result of malaria from blood smear test
HML32$42 : Final result of malaria from blood smear test
HML32$43 : Final result of malaria from blood smear test
HML32$44 : Final result of malaria from blood smear test
HML32$45 : Final result of malaria from blood smear test
HML32$46 : Final result of malaria from blood smear test
HML32B$01 : Presence of species: malariae (Pm)
HML32B$02 : Presence of species: malariae (Pm)
HML32B$03 : Presence of species: malariae (Pm)
HML32B$04 : Presence of species: malariae (Pm)
HML32B$05 : Presence of species: malariae (Pm)
HML32B$06 : Presence of species: malariae (Pm)
HML32B$07 : Presence of species: malariae (Pm)
HML32B$08 : Presence of species: malariae (Pm)
HML32B$09 : Presence of species: malariae (Pm)
HML32B$10 : Presence of species: malariae (Pm)
HML32B$11 : Presence of species: malariae (Pm)
HML32B$12 : Presence of species: malariae (Pm)
HML32B$13 : Presence of species: malariae (Pm)
HML32B$14 : Presence of species: malariae (Pm)
HML32B$15 : Presence of species: malariae (Pm)
HML32B$16 : Presence of species: malariae (Pm)
HML32B$17 : Presence of species: malariae (Pm)
HML32B$18 : Presence of species: malariae (Pm)
HML32B$19 : Presence of species: malariae (Pm)
HML32B$20 : Presence of species: malariae (Pm)
HML32B$21 : Presence of species: malariae (Pm)
HML32B$22 : Presence of species: malariae (Pm)
HML32B$23 : Presence of species: malariae (Pm)
HML32B$24 : Presence of species: malariae (Pm)
HML32B$25 : Presence of species: malariae (Pm)
HML32B$26 : Presence of species: malariae (Pm)
HML32B$27 : Presence of species: malariae (Pm)
HML32B$28 : Presence of species: malariae (Pm)
HML32B$29 : Presence of species: malariae (Pm)
HML32B$30 : Presence of species: malariae (Pm)
HML32B$31 : Presence of species: malariae (Pm)
HML32B$32 : Presence of species: malariae (Pm)
HML32B$33 : Presence of species: malariae (Pm)
HML32B$34 : Presence of species: malariae (Pm)
HML32B$35 : Presence of species: malariae (Pm)
HML32B$36 : Presence of species: malariae (Pm)
HML32B$37 : Presence of species: malariae (Pm)
HML32B$38 : Presence of species: malariae (Pm)
HML32B$39 : Presence of species: malariae (Pm)
HML32B$40 : Presence of species: malariae (Pm)
HML32B$41 : Presence of species: malariae (Pm)
HML32B$42 : Presence of species: malariae (Pm)
HML32B$43 : Presence of species: malariae (Pm)
HML32B$44 : Presence of species: malariae (Pm)
HML32B$45 : Presence of species: malariae (Pm)
HML32B$46 : Presence of species: malariae (Pm)
HML33$01 : Result of malaria measurement
HML33$02 : Result of malaria measurement
HML33$03 : Result of malaria measurement
HML33$04 : Result of malaria measurement
HML33$05 : Result of malaria measurement
HML33$06 : Result of malaria measurement
HML33$07 : Result of malaria measurement
HML33$08 : Result of malaria measurement
HML33$09 : Result of malaria measurement
HML33$10 : Result of malaria measurement
HML33$11 : Result of malaria measurement
HML33$12 : Result of malaria measurement
HML33$13 : Result of malaria measurement
HML33$14 : Result of malaria measurement
HML33$15 : Result of malaria measurement
HML33$16 : Result of malaria measurement
HML33$17 : Result of malaria measurement
HML33$18 : Result of malaria measurement
HML33$19 : Result of malaria measurement
HML33$20 : Result of malaria measurement
HML33$21 : Result of malaria measurement
HML33$22 : Result of malaria measurement
HML33$23 : Result of malaria measurement
HML33$24 : Result of malaria measurement
HML33$25 : Result of malaria measurement
HML33$26 : Result of malaria measurement
HML33$27 : Result of malaria measurement
HML33$28 : Result of malaria measurement
HML33$29 : Result of malaria measurement
HML33$30 : Result of malaria measurement
HML33$31 : Result of malaria measurement
HML33$32 : Result of malaria measurement
HML33$33 : Result of malaria measurement
HML33$34 : Result of malaria measurement
HML33$35 : Result of malaria measurement
HML33$36 : Result of malaria measurement
HML33$37 : Result of malaria measurement
HML33$38 : Result of malaria measurement
HML33$39 : Result of malaria measurement
HML33$40 : Result of malaria measurement
HML33$41 : Result of malaria measurement
HML33$42 : Result of malaria measurement
HML33$43 : Result of malaria measurement
HML33$44 : Result of malaria measurement
HML33$45 : Result of malaria measurement
HML33$46 : Result of malaria measurement
HML34$01 : Bar code for blood smear sample
HML34$02 : Bar code for blood smear sample
HML34$03 : Bar code for blood smear sample
HML34$04 : Bar code for blood smear sample
HML34$05 : Bar code for blood smear sample
HML34$06 : Bar code for blood smear sample
HML34$07 : Bar code for blood smear sample
HML34$08 : Bar code for blood smear sample
HML34$09 : Bar code for blood smear sample
HML34$10 : Bar code for blood smear sample
HML34$11 : Bar code for blood smear sample
HML34$12 : Bar code for blood smear sample
HML34$13 : Bar code for blood smear sample
HML34$14 : Bar code for blood smear sample
HML34$15 : Bar code for blood smear sample
HML34$16 : Bar code for blood smear sample
HML34$17 : Bar code for blood smear sample
HML34$18 : Bar code for blood smear sample
HML34$19 : Bar code for blood smear sample
HML34$20 : Bar code for blood smear sample
HML34$21 : Bar code for blood smear sample
HML34$22 : Bar code for blood smear sample
HML34$23 : Bar code for blood smear sample
HML34$24 : Bar code for blood smear sample
HML34$25 : Bar code for blood smear sample
HML34$26 : Bar code for blood smear sample
HML34$27 : Bar code for blood smear sample
HML34$28 : Bar code for blood smear sample
HML34$29 : Bar code for blood smear sample
HML34$30 : Bar code for blood smear sample
HML34$31 : Bar code for blood smear sample
HML34$32 : Bar code for blood smear sample
HML34$33 : Bar code for blood smear sample
HML34$34 : Bar code for blood smear sample
HML34$35 : Bar code for blood smear sample
HML34$36 : Bar code for blood smear sample
HML34$37 : Bar code for blood smear sample
HML34$38 : Bar code for blood smear sample
HML34$39 : Bar code for blood smear sample
HML34$40 : Bar code for blood smear sample
HML34$41 : Bar code for blood smear sample
HML34$42 : Bar code for blood smear sample
HML34$43 : Bar code for blood smear sample
HML34$44 : Bar code for blood smear sample
HML34$45 : Bar code for blood smear sample
HML34$46 : Bar code for blood smear sample
HML35$01 : Result of malaria rapid test
HML35$02 : Result of malaria rapid test
HML35$03 : Result of malaria rapid test
HML35$04 : Result of malaria rapid test
HML35$05 : Result of malaria rapid test
HML35$06 : Result of malaria rapid test
HML35$07 : Result of malaria rapid test
HML35$08 : Result of malaria rapid test
HML35$09 : Result of malaria rapid test
HML35$10 : Result of malaria rapid test
HML35$11 : Result of malaria rapid test
HML35$12 : Result of malaria rapid test
HML35$13 : Result of malaria rapid test
HML35$14 : Result of malaria rapid test
HML35$15 : Result of malaria rapid test
HML35$16 : Result of malaria rapid test
HML35$17 : Result of malaria rapid test
HML35$18 : Result of malaria rapid test
HML35$19 : Result of malaria rapid test
HML35$20 : Result of malaria rapid test
HML35$21 : Result of malaria rapid test
HML35$22 : Result of malaria rapid test
HML35$23 : Result of malaria rapid test
HML35$24 : Result of malaria rapid test
HML35$25 : Result of malaria rapid test
HML35$26 : Result of malaria rapid test
HML35$27 : Result of malaria rapid test
HML35$28 : Result of malaria rapid test
HML35$29 : Result of malaria rapid test
HML35$30 : Result of malaria rapid test
HML35$31 : Result of malaria rapid test
HML35$32 : Result of malaria rapid test
HML35$33 : Result of malaria rapid test
HML35$34 : Result of malaria rapid test
HML35$35 : Result of malaria rapid test
HML35$36 : Result of malaria rapid test
HML35$37 : Result of malaria rapid test
HML35$38 : Result of malaria rapid test
HML35$39 : Result of malaria rapid test
HML35$40 : Result of malaria rapid test
HML35$41 : Result of malaria rapid test
HML35$42 : Result of malaria rapid test
HML35$43 : Result of malaria rapid test
HML35$44 : Result of malaria rapid test
HML35$45 : Result of malaria rapid test
HML35$46 : Result of malaria rapid test
HML36$01 : Fieldworker measurer code for malaria
HML36$02 : Fieldworker measurer code for malaria
HML36$03 : Fieldworker measurer code for malaria
HML36$04 : Fieldworker measurer code for malaria
HML36$05 : Fieldworker measurer code for malaria
HML36$06 : Fieldworker measurer code for malaria
HML36$07 : Fieldworker measurer code for malaria
HML36$08 : Fieldworker measurer code for malaria
HML36$09 : Fieldworker measurer code for malaria
HML36$10 : Fieldworker measurer code for malaria
HML36$11 : Fieldworker measurer code for malaria
HML36$12 : Fieldworker measurer code for malaria
HML36$13 : Fieldworker measurer code for malaria
HML36$14 : Fieldworker measurer code for malaria
HML36$15 : Fieldworker measurer code for malaria
HML36$16 : Fieldworker measurer code for malaria
HML36$17 : Fieldworker measurer code for malaria
HML36$18 : Fieldworker measurer code for malaria
HML36$19 : Fieldworker measurer code for malaria
HML36$20 : Fieldworker measurer code for malaria
HML36$21 : Fieldworker measurer code for malaria
HML36$22 : Fieldworker measurer code for malaria
HML36$23 : Fieldworker measurer code for malaria
HML36$24 : Fieldworker measurer code for malaria
HML36$25 : Fieldworker measurer code for malaria
HML36$26 : Fieldworker measurer code for malaria
HML36$27 : Fieldworker measurer code for malaria
HML36$28 : Fieldworker measurer code for malaria
HML36$29 : Fieldworker measurer code for malaria
HML36$30 : Fieldworker measurer code for malaria
HML36$31 : Fieldworker measurer code for malaria
HML36$32 : Fieldworker measurer code for malaria
HML36$33 : Fieldworker measurer code for malaria
HML36$34 : Fieldworker measurer code for malaria
HML36$35 : Fieldworker measurer code for malaria
HML36$36 : Fieldworker measurer code for malaria
HML36$37 : Fieldworker measurer code for malaria
HML36$38 : Fieldworker measurer code for malaria
HML36$39 : Fieldworker measurer code for malaria
HML36$40 : Fieldworker measurer code for malaria
HML36$41 : Fieldworker measurer code for malaria
HML36$42 : Fieldworker measurer code for malaria
HML36$43 : Fieldworker measurer code for malaria
HML36$44 : Fieldworker measurer code for malaria
HML36$45 : Fieldworker measurer code for malaria
HML36$46 : Fieldworker measurer code for malaria
HML37D$01 : Suffer from illness/symptom: rapid or difficult breathing
HML37D$02 : Suffer from illness/symptom: rapid or difficult breathing
HML37D$03 : Suffer from illness/symptom: rapid or difficult breathing
HML37D$04 : Suffer from illness/symptom: rapid or difficult breathing
HML37D$05 : Suffer from illness/symptom: rapid or difficult breathing
HML37D$06 : Suffer from illness/symptom: rapid or difficult breathing
HML37D$07 : Suffer from illness/symptom: rapid or difficult breathing
HML37D$08 : Suffer from illness/symptom: rapid or difficult breathing

In [62]:
malaria_vars = [
    var for var in hr2021.columns
    if "ML" in var.upper()
]

print(len(malaria_vars))
print(sorted(malaria_vars))

1969

In [63]:
hml_vars = [
    var for var in hr2021.columns
    if var.upper().startswith("HML")
]

print(hml_vars)

['HML1', 'HML1A', 'HML2', 'HMLIDX$1', 'HMLIDX$2', 'HMLIDX$3', 'HMLIDX$4', 'HMLIDX$5', 'HMLIDX$6', 'HMLIDX$7', 'HML3$1', 'HML3$2', 'HML3$3', 'HML3$4', 'HML3$5', 'HML3$6', 'HML3$7', 'HML4$1', 'HML4$2', 'HML4$3', 'HML4$4', 'HML4$5', 'HML4$6', 'HML4$7', 'HML5$1', 'HML5$2', 'HML5$3', 'HML5$4', 'HML5$5', 'HML5$6', 'HML5$7', 'HML6$1', 'HML6$2', 'HML6$3', 'HML6$4', 'HML6$5', 'HML6$6', 'HML6$7', 'HML7$1', 'HML7$2', 'HML7$3', 'HML7$4', 'HML7$5', 'HML7$6', 'HML7$7', 'HML8$1', 'HML8$2', 'HML8$3', 'HML8$4', 'HML8$5', 'HML8$6', 'HML8$7', 'HML9$1', 'HML9$2', 'HML9$3', 'HML9$4', 'HML9$5', 'HML9$6', 'HML9$7', 'HML10$1', 'HML10$2', 'HML10$3', 'HML10$4', 'HML10$5', 'HML10$6', 'HML10$7', 'HML11$1', 'HML11$2', 'HML11$3', 'HML11$4', 'HML11$5', 'HML11$6', 'HML11$7', 'HML21$1', 'HML21$2', 'HML21$3', 'HML21$4', 'HML21$5', 'HML21$6', 'HML21$7', 'HMLA$1', 'HMLA$2', 'HMLA$3', 'HMLA$4', 'HMLA$5', 'HMLA$6', 'HMLA$7', 'HMLB$1', 'HMLB$2', 'HMLB$3', 'HMLB$4', 'HMLB$5', 'HMLB$6', 'HMLB$7', 'HMLC$1', 'HMLC$2', 'HMLC$3', 'HMLC$4', 'HMLC$5', 'HMLC$6', 'HMLC$7', 'HMLD$1', 'HMLD$2', 'HMLD$3', 'HMLD$4', 'HMLD$5', 'HMLD$6', 'HMLD$7', 'HMLE$1', 'HMLE$2', 'HMLE$3', 'HMLE$4', 'HMLE$5', 'HMLE$6', 'HMLE$7', 'HML22$1', 'HML22$2', 'HML22$3', 'HML22$4', 'HML22$5', 'HML22$6', 'HML22$7', 'HML23$1', 'HML23$2', 'HML23$3', 'HML23$4', 'HML23$5', 'HML23$6', 'HML23$7', 'HML12$01', 'HML12$02', 'HML12$03', 'HML12$04', 'HML12$05', 'HML12$06', 'HML12$07', 'HML12$08', 'HML12$09', 'HML12$10', 'HML12$11', 'HML12$12', 'HML12$13', 'HML12$14', 'HML12$15', 'HML12$16', 'HML12$17', 'HML12$18', 'HML12$19', 'HML12$20', 'HML12$21', 'HML12$22', 'HML12$23', 'HML12$24', 'HML12$25', 'HML12$26', 'HML12$27', 'HML12$28', 'HML12$29', 'HML12$30', 'HML12$31', 'HML12$32', 'HML12$33', 'HML12$34', 'HML12$35', 'HML12$36', 'HML12$37', 'HML12$38', 'HML12$39', 'HML12$40', 'HML12$41', 'HML12$42', 'HML12$43', 'HML12$44', 'HML12$45', 'HML12$46', 'HML13$01', 'HML13$02', 'HML13$03', 'HML13$04', 'HML13$05', 'HML13$06', 'HML13$07', 'HML13$08', 'HML13$09', 'HML13$10', 'HML13$11', 'HML13$12', 'HML13$13', 'HML13$14', 'HML13$15', 'HML13$16', 'HML13$17', 'HML13$18', 'HML13$19', 'HML13$20', 'HML13$21', 'HML13$22', 'HML13$23', 'HML13$24', 'HML13$25', 'HML13$26', 'HML13$27', 'HML13$28', 'HML13$29', 'HML13$30', 'HML13$31', 'HML13$32', 'HML13$33', 'HML13$34', 'HML13$35', 'HML13$36', 'HML13$37', 'HML13$38', 'HML13$39', 'HML13$40', 'HML13$41', 'HML13$42', 'HML13$43', 'HML13$44', 'HML13$45', 'HML13$46', 'HML14$01', 'HML14$02', 'HML14$03', 'HML14$04', 'HML14$05', 'HML14$06', 'HML14$07', 'HML14$08', 'HML14$09', 'HML14$10', 'HML14$11', 'HML14$12', 'HML14$13', 'HML14$14', 'HML14$15', 'HML14$16', 'HML14$17', 'HML14$18', 'HML14$19', 'HML14$20', 'HML14$21', 'HML14$22', 'HML14$23', 'HML14$24', 'HML14$25', 'HML14$26', 'HML14$27', 'HML14$28', 'HML14$29', 'HML14$30', 'HML14$31', 'HML14$32', 'HML14$33', 'HML14$34', 'HML14$35', 'HML14$36', 'HML14$37', 'HML14$38', 'HML14$39', 'HML14$40', 'HML14$41', 'HML14$42', 'HML14$43', 'HML14$44', 'HML14$45', 'HML14$46', 'HML15$01', 'HML15$02', 'HML15$03', 'HML15$04', 'HML15$05', 'HML15$06', 'HML15$07', 'HML15$08', 'HML15$09', 'HML15$10', 'HML15$11', 'HML15$12', 'HML15$13', 'HML15$14', 'HML15$15', 'HML15$16', 'HML15$17', 'HML15$18', 'HML15$19', 'HML15$20', 'HML15$21', 'HML15$22', 'HML15$23', 'HML15$24', 'HML15$25', 'HML15$26', 'HML15$27', 'HML15$28', 'HML15$29', 'HML15$30', 'HML15$31', 'HML15$32', 'HML15$33', 'HML15$34', 'HML15$35', 'HML15$36', 'HML15$37', 'HML15$38', 'HML15$39', 'HML15$40', 'HML15$41', 'HML15$42', 'HML15$43', 'HML15$44', 'HML15$45', 'HML15$46', 'HML16$01', 'HML16$02', 'HML16$03', 'HML16$04', 'HML16$05', 'HML16$06', 'HML16$07', 'HML16$08', 'HML16$09', 'HML16$10', 'HML16$11', 'HML16$12', 'HML16$13', 'HML16$14', 'HML16$15', 'HML16$16', 'HML16$17', 'HML16$18', 'HML16$19', 'HML16$20', 'HML16$21', 'HML16$22', 'HML16$23', 'HML16$24', 'HML16$25', 'HML16$26', 'HML16$27', 'HML16$28', 'HML16$29', 'HML16$30', 'HML16$31', 'HML16$32', 'HML16$33', 'HML16$34', 'HML16$35', 'HML16$36', 'HML16$37', 'HML16$38', 'HML16$39', 'HML16$40', 'HML16$41', 'HML16$42', 'HML16$43', 'HML16$44', 'HML16$45', 'HML16$46', 'HML16A$01', 'HML16A$02', 'HML16A$03', 'HML16A$04', 'HML16A$05', 'HML16A$06', 'HML16A$07', 'HML16A$08', 'HML16A$09', 'HML16A$10', 'HML16A$11', 'HML16A$12', 'HML16A$13', 'HML16A$14', 'HML16A$15', 'HML16A$16', 'HML16A$17', 'HML16A$18', 'HML16A$19', 'HML16A$20', 'HML16A$21', 'HML16A$22', 'HML16A$23', 'HML16A$24', 'HML16A$25', 'HML16A$26', 'HML16A$27', 'HML16A$28', 'HML16A$29', 'HML16A$30', 'HML16A$31', 'HML16A$32', 'HML16A$33', 'HML16A$34', 'HML16A$35', 'HML16A$36', 'HML16A$37', 'HML16A$38', 'HML16A$39', 'HML16A$40', 'HML16A$41', 'HML16A$42', 'HML16A$43', 'HML16A$44', 'HML16A$45', 'HML16A$46', 'HML17$01', 'HML17$02', 'HML17$03', 'HML17$04', 'HML17$05', 'HML17$06', 'HML17$07', 'HML17$08', 'HML17$09', 'HML17$10', 'HML17$11', 'HML17$12', 'HML17$13', 'HML17$14', 'HML17$15', 'HML17$16', 'HML17$17', 'HML17$18', 'HML17$19', 'HML17$20', 'HML17$21', 'HML17$22', 'HML17$23', 'HML17$24', 'HML17$25', 'HML17$26', 'HML17$27', 'HML17$28', 'HML17$29', 'HML17$30', 'HML17$31', 'HML17$32', 'HML17$33', 'HML17$34', 'HML17$35', 'HML17$36', 'HML17$37', 'HML17$38', 'HML17$39', 'HML17$40', 'HML17$41', 'HML17$42', 'HML17$43', 'HML17$44', 'HML17$45', 'HML17$46', 'HML18$01', 'HML18$02', 'HML18$03', 'HML18$04', 'HML18$05', 'HML18$06', 'HML18$07', 'HML18$08', 'HML18$09', 'HML18$10', 'HML18$11', 'HML18$12', 'HML18$13', 'HML18$14', 'HML18$15', 'HML18$16', 'HML18$17', 'HML18$18', 'HML18$19', 'HML18$20', 'HML18$21', 'HML18$22', 'HML18$23', 'HML18$24', 'HML18$25', 'HML18$26', 'HML18$27', 'HML18$28', 'HML18$29', 'HML18$30', 'HML18$31', 'HML18$32', 'HML18$33', 'HML18$34', 'HML18$35', 'HML18$36', 'HML18$37', 'HML18$38', 'HML18$39', 'HML18$40', 'HML18$41', 'HML18$42', 'HML18$43', 'HML18$44', 'HML18$45', 'HML18$46', 'HML19$01', 'HML19$02', 'HML19$03', 'HML19$04', 'HML19$05', 'HML19$06', 'HML19$07', 'HML19$08', 'HML19$09', 'HML19$10', 'HML19$11', 'HML19$12', 'HML19$13', 'HML19$14', 'HML19$15', 'HML19$16', 'HML19$17', 'HML19$18', 'HML19$19', 'HML19$20', 'HML19$21', 'HML19$22', 'HML19$23', 'HML19$24', 'HML19$25', 'HML19$26', 'HML19$27', 'HML19$28', 'HML19$29', 'HML19$30', 'HML19$31', 'HML19$32', 'HML19$33', 'HML19$34', 'HML19$35', 'HML19$36', 'HML19$37', 'HML19$38', 'HML19$39', 'HML19$40', 'HML19$41', 'HML19$42', 'HML19$43', 'HML19$44', 'HML19$45', 'HML19$46', 'HML20$01', 'HML20$02', 'HML20$03', 'HML20$04', 'HML20$05', 'HML20$06', 'HML20$07', 'HML20$08', 'HML20$09', 'HML20$10', 'HML20$11', 'HML20$12', 'HML20$13', 'HML20$14', 'HML20$15', 'HML20$16', 'HML20$17', 'HML20$18', 'HML20$19', 'HML20$20', 'HML20$21', 'HML20$22', 'HML20$23', 'HML20$24', 'HML20$25', 'HML20$26', 'HML20$27', 'HML20$28', 'HML20$29', 'HML20$30', 'HML20$31', 'HML20$32', 'HML20$33', 'HML20$34', 'HML20$35', 'HML20$36', 'HML20$37', 'HML20$38', 'HML20$39', 'HML20$40', 'HML20$41', 'HML20$42', 'HML20$43', 'HML20$44', 'HML20$45', 'HML20$46', 'HML30$01', 'HML30$02', 'HML30$03', 'HML30$04', 'HML30$05', 'HML30$06', 'HML30$07', 'HML30$08', 'HML30$09', 'HML30$10', 'HML30$11', 'HML30$12', 'HML30$13', 'HML30$14', 'HML30$15', 'HML30$16', 'HML30$17', 'HML30$18', 'HML30$19', 'HML30$20', 'HML30$21', 'HML30$22', 'HML30$23', 'HML30$24', 'HML30$25', 'HML30$26', 'HML30$27', 'HML30$28', 'HML30$29', 'HML30$30', 'HML30$31', 'HML30$32', 'HML30$33', 'HML30$34', 'HML30$35', 'HML30$36', 'HML30$37', 'HML30$38', 'HML30$39', 'HML30$40', 'HML30$41', 'HML30$42', 'HML30$43', 'HML30$44', 'HML30$45', 'HML30$46', 'HML31$01', 'HML31$02', 'HML31$03', 'HML31$04', 'HML31$05', 'HML31$06', 'HML31$07', 'HML31$08', 'HML31$09', 'HML31$10', 'HML31$11', 'HML31$12', 'HML31$13', 'HML31$14', 'HML31$15', 'HML31$16', 'HML31$17', 'HML31$18', 'HML31$19', 'HML31$20', 'HML31$21', 'HML31$22', 'HML31$23', 'HML31$24', 'HML31$25', 'HML31$26', 'HML31$27', 'HML31$28', 'HML31$29', 'HML31$30', 'HML31$31', 'HML31$32', 'HML31$33', 'HML31$34', 'HML31$35', 'HML31$36', 'HML31$37', 'HML31$38', 'HML31$39', 'HML31$40', 'HML31$41', 'HML31$42', 'HML31$43', 'HML31$44', 'HML31$45', 'HML31$46', 'HML32$01', 'HML32$02', 'HML32$03', 'HML32$04', 'HML32$05', 'HML32$06', 'HML32$07', 'HML32$08', 'HML32$09', 'HML32$10', 'HML32$11', 'HML32$12', 'HML32$13', 'HML32$14', 'HML32$15', 'HML32$16', 'HML32$17', 'HML32$18', 'HML32$19', 'HML32$20', 'HML32$21', 'HML32$22', 'HML32$23', 'HML32$24', 'HML32$25', 'HML32$26', 'HML32$27', 'HML32$28', 'HML32$29', 'HML32$30', 'HML32$31', 'HML32$32', 'HML32$33', 'HML32$34', 'HML32$35', 'HML32$36', 'HML32$37', 'HML32$38', 'HML32$39', 'HML32$40', 'HML32$41', 'HML32$42', 'HML32$43', 'HML32$44', 'HML32$45', 'HML32$46', 'HML32A$01', 'HML32A$02', 'HML32A$03', 'HML32A$04', 'HML32A$05', 'HML32A$06', 'HML32A$07', 'HML32A$08', 'HML32A$09', 'HML32A$10', 'HML32A$11', 'HML32A$12', 'HML32A$13', 'HML32A$14', 'HML32A$15', 'HML32A$16', 'HML32A$17', 'HML32A$18', 'HML32A$19', 'HML32A$20', 'HML32A$21', 'HML32A$22', 'HML32A$23', 'HML32A$24', 'HML32A$25', 'HML32A$26', 'HML32A$27', 'HML32A$28', 'HML32A$29', 'HML32A$30', 'HML32A$31', 'HML32A$32', 'HML32A$33', 'HML32A$34', 'HML32A$35', 'HML32A$36', 'HML32A$37', 'HML32A$38', 'HML32A$39', 'HML32A$40', 'HML32A$41', 'HML32A$42', 'HML32A$43', 'HML32A$44', 'HML32A$45', 'HML32A$46', 'HML32B$01', 'HML32B$02', 'HML32B$03', 'HML32B$04', 'HML32B$05', 'HML32B$06', 'HML32B$07', 'HML32B$08', 'HML32B$09', 'HML32B$10', 'HML32B$11', 'HML32B$12', 'HML32B$13', 'HML32B$14', 'HML32B$15', 'HML32B$16', 'HML32B$17', 'HML32B$18', 'HML32B$19', 'HML32B$20', 'HML32B$21', 'HML32B$22', 'HML32B$23', 'HML32B$24', 'HML32B$25', 'HML32B$26', 'HML32B$27', 'HML32B$28', 'HML32B$29', 'HML32B$30', 'HML32B$31', 'HML32B$32', 'HML32B$33', 'HML32B$34', 'HML32B$35', 'HML32B$36', 'HML32B$37', 'HML32B$38', 'HML32B$39', 'HML32B$40', 'HML32B$41', 'HML32B$42', 'HML32B$43', 'HML32B$44', 'HML32B$45', 'HML32B$46', 'HML32C$01', 'HML32C$02', 'HML32C$03', 'HML32C$04', 'HML32C$05', 'HML32C$06', 'HML32C$07', 'HML32C$08', 'HML32C$09', 'HML32C$10', 'HML32C$11', 'HML32C$12', 'HML32C$13', 'HML32C$14', 'HML32C$15', 'HML32C$16', 'HML32C$17', 'HML32C$18', 'HML32C$19', 'HML32C$20', 'HML32C$21', 'HML32C$22', 'HML32C$23', 'HML32C$24', 'HML32C$25', 'HML32C$26', 'HML32C$27', 'HML32C$28', 'HML32C$29', 'HML32C$30', 'HML32C$31', 'HML32C$32', 'HML32C$33', 'HML32C$34', 'HML32C$35', 'HML32C$36', 'HML32C$37', 'HML32C$38', 'HML32C$39', 'HML32C$40', 'HML32C$41', 'HML32C$42', 'HML32C$43', 'HML32C$44', 'HML32C$45', 'HML32C$46', 'HML32D$01', 'HML32D$02', 'HML32D$03', 'HML32D$04', 'HML32D$05', 'HML32D$06', 'HML32D$07', 'HML32D$08', 'HML32D$09', 'HML32D$10', 'HML32D$11', 'HML32D$12', 'HML32D$13', 'HML32D$14', 'HML32D$15', 'HML32D$16', 'HML32D$17', 'HML32D$18', 'HML32D$19', 'HML32D$20', 'HML32D$21', 'HML32D$22', 'HML32D$23', 'HML32D$24', 'HML32D$25', 'HML32D$26', 'HML32D$27', 'HML32D$28', 'HML32D$29', 'HML32D$30', 'HML32D$31', 'HML32D$32', 'HML32D$33', 'HML32D$34', 'HML32D$35', 'HML32D$36', 'HML32D$37', 'HML32D$38', 'HML32D$39', 'HML32D$40', 'HML32D$41', 'HML32D$42', 'HML32D$43', 'HML32D$44', 'HML32D$45', 'HML32D$46', 'HML32E$01', 'HML32E$02', 'HML32E$03', 'HML32E$04', 'HML32E$05', 'HML32E$06', 'HML32E$07', 'HML32E$08', 'HML32E$09', 'HML32E$10', 'HML32E$11', 'HML32E$12', 'HML32E$13', 'HML32E$14', 'HML32E$15', 'HML32E$16', 'HML32E$17', 'HML32E$18', 'HML32E$19', 'HML32E$20', 'HML32E$21', 'HML32E$22', 'HML32E$23', 'HML32E$24', 'HML32E$25', 'HML32E$26', 'HML32E$27', 'HML32E$28', 'HML32E$29', 'HML32E$30', 'HML32E$31', 'HML32E$32', 'HML32E$33', 'HML32E$34', 'HML32E$35', 'HML32E$36', 'HML32E$37', 'HML32E$38', 'HML32E$39', 'HML32E$40', 'HML32E$41', 'HML32E$42', 'HML32E$43', 'HML32E$44', 'HML32E$45', 'HML32E$46', 'HML32F$01', 'HML32F$02', 'HML32F$03', 'HML32F$04', 'HML32F$05', 'HML32F$06', 'HML32F$07', 'HML32F$08', 'HML32F$09', 'HML32F$10', 'HML32F$11', 'HML32F$12', 'HML32F$13', 'HML32F$14', 'HML32F$15', 'HML32F$16', 'HML32F$17', 'HML32F$18', 'HML32F$19', 'HML32F$20', 'HML32F$21', 'HML32F$22', 'HML32F$23', 'HML32F$24', 'HML32F$25', 'HML32F$26', 'HML32F$27', 'HML32F$28', 'HML32F$29', 'HML32F$30', 'HML32F$31', 'HML32F$32', 'HML32F$33', 'HML32F$34', 'HML32F$35', 'HML32F$36', 'HML32F$37', 'HML32F$38', 'HML32F$39', 'HML32F$40', 'HML32F$41', 'HML32F$42', 'HML32F$43', 'HML32F$44', 'HML32F$45', 'HML32F$46', 'HML32G$01', 'HML32G$02', 'HML32G$03', 'HML32G$04', 'HML32G$05', 'HML32G$06', 'HML32G$07', 'HML32G$08', 'HML32G$09', 'HML32G$10', 'HML32G$11', 'HML32G$12', 'HML32G$13', 'HML32G$14', 'HML32G$15', 'HML32G$16', 'HML32G$17', 'HML32G$18', 'HML32G$19', 'HML32G$20', 'HML32G$21', 'HML32G$22', 'HML32G$23', 'HML32G$24', 'HML32G$25', 'HML32G$26', 'HML32G$27', 'HML32G$28', 'HML32G$29', 'HML32G$30', 'HML32G$31', 'HML32G$32', 'HML32G$33', 'HML32G$34', 'HML32G$35', 'HML32G$36', 'HML32G$37', 'HML32G$38', 'HML32G$39', 'HML32G$40', 'HML32G$41', 'HML32G$42', 'HML32G$43', 'HML32G$44', 'HML32G$45', 'HML32G$46', 'HML33$01', 'HML33$02', 'HML33$03', 'HML33$04', 'HML33$05', 'HML33$06', 'HML33$07', 'HML33$08', 'HML33$09', 'HML33$10', 'HML33$11', 'HML33$12', 'HML33$13', 'HML33$14', 'HML33$15', 'HML33$16', 'HML33$17', 'HML33$18', 'HML33$19', 'HML33$20', 'HML33$21', 'HML33$22', 'HML33$23', 'HML33$24', 'HML33$25', 'HML33$26', 'HML33$27', 'HML33$28', 'HML33$29', 'HML33$30', 'HML33$31', 'HML33$32', 'HML33$33', 'HML33$34', 'HML33$35', 'HML33$36', 'HML33$37', 'HML33$38', 'HML33$39', 'HML33$40', 'HML33$41', 'HML33$42', 'HML33$43', 'HML33$44', 'HML33$45', 'HML33$46', 'HML34$01', 'HML34$02', 'HML34$03', 'HML34$04', 'HML34$05', 'HML34$06', 'HML34$07', 'HML34$08', 'HML34$09', 'HML34$10', 'HML34$11', 'HML34$12', 'HML34$13', 'HML34$14', 'HML34$15', 'HML34$16', 'HML34$17', 'HML34$18', 'HML34$19', 'HML34$20', 'HML34$21', 'HML34$22', 'HML34$23', 'HML34$24', 'HML34$25', 'HML34$26', 'HML34$27', 'HML34$28', 'HML34$29', 'HML34$30', 'HML34$31', 'HML34$32', 'HML34$33', 'HML34$34', 'HML34$35', 'HML34$36', 'HML34$37', 'HML34$38', 'HML34$39', 'HML34$40', 'HML34$41', 'HML34$42', 'HML34$43', 'HML34$44', 'HML34$45', 'HML34$46', 'HML35$01', 'HML35$02', 'HML35$03', 'HML35$04', 'HML35$05', 'HML35$06', 'HML35$07', 'HML35$08', 'HML35$09', 'HML35$10', 'HML35$11', 'HML35$12', 'HML35$13', 'HML35$14', 'HML35$15', 'HML35$16', 'HML35$17', 'HML35$18', 'HML35$19', 'HML35$20', 'HML35$21', 'HML35$22', 'HML35$23', 'HML35$24', 'HML35$25', 'HML35$26', 'HML35$27', 'HML35$28', 'HML35$29', 'HML35$30', 'HML35$31', 'HML35$32', 'HML35$33', 'HML35$34', 'HML35$35', 'HML35$36', 'HML35$37', 'HML35$38', 'HML35$39', 'HML35$40', 'HML35$41', 'HML35$42', 'HML35$43', 'HML35$44', 'HML35$45', 'HML35$46', 'HML36$01', 'HML36$02', 'HML36$03', 'HML36$04', 'HML36$05', 'HML36$06', 'HML36$07', 'HML36$08', 'HML36$09', 'HML36$10', 'HML36$11', 'HML36$12', 'HML36$13', 'HML36$14', 'HML36$15', 'HML36$16', 'HML36$17', 'HML36$18', 'HML36$19', 'HML36$20', 'HML36$21', 'HML36$22', 'HML36$23', 'HML36$24', 'HML36$25', 'HML36$26', 'HML36$27', 'HML36$28', 'HML36$29', 'HML36$30', 'HML36$31', 'HML36$32', 'HML36$33', 'HML36$34', 'HML36$35', 'HML36$36', 'HML36$37', 'HML36$38', 'HML36$39', 'HML36$40', 'HML36$41', 'HML36$42', 'HML36$43', 'HML36$44', 'HML36$45', 'HML36$46', 'HML37A$01', 'HML37A$02', 'HML37A$03', 'HML37A$04', 'HML37A$05', 'HML37A$06', 'HML37A$07', 'HML37A$08', 'HML37A$09', 'HML37A$10', 'HML37A$11', 'HML37A$12', 'HML37A$13', 'HML37A$14', 'HML37A$15', 'HML37A$16', 'HML37A$17', 'HML37A$18', 'HML37A$19', 'HML37A$20', 'HML37A$21', 'HML37A$22', 'HML37A$23', 'HML37A$24', 'HML37A$25', 'HML37A$26', 'HML37A$27', 'HML37A$28', 'HML37A$29', 'HML37A$30', 'HML37A$31', 'HML37A$32', 'HML37A$33', 'HML37A$34', 'HML37A$35', 'HML37A$36', 'HML37A$37', 'HML37A$38', 'HML37A$39', 'HML37A$40', 'HML37A$41', 'HML37A$42', 'HML37A$43', 'HML37A$44', 'HML37A$45', 'HML37A$46', 'HML37B$01', 'HML37B$02', 'HML37B$03', 'HML37B$04', 'HML37B$05', 'HML37B$06', 'HML37B$07', 'HML37B$08', 'HML37B$09', 'HML37B$10', 'HML37B$11', 'HML37B$12', 'HML37B$13', 'HML37B$14', 'HML37B$15', 'HML37B$16', 'HML37B$17', 'HML37B$18', 'HML37B$19', 'HML37B$20', 'HML37B$21', 'HML37B$22', 'HML37B$23', 'HML37B$24', 'HML37B$25', 'HML37B$26', 'HML37B$27', 'HML37B$28', 'HML37B$29', 'HML37B$30', 'HML37B$31', 'HML37B$32', 'HML37B$33', 'HML37B$34', 'HML37B$35', 'HML37B$36', 'HML37B$37', 'HML37B$38', 'HML37B$39', 'HML37B$40', 'HML37B$41', 'HML37B$42', 'HML37B$43', 'HML37B$44', 'HML37B$45', 'HML37B$46', 'HML37C$01', 'HML37C$02', 'HML37C$03', 'HML37C$04', 'HML37C$05', 'HML37C$06', 'HML37C$07', 'HML37C$08', 'HML37C$09', 'HML37C$10', 'HML37C$11', 'HML37C$12', 'HML37C$13', 'HML37C$14', 'HML37C$15', 'HML37C$16', 'HML37C$17', 'HML37C$18', 'HML37C$19', 'HML37C$20', 'HML37C$21', 'HML37C$22', 'HML37C$23', 'HML37C$24', 'HML37C$25', 'HML37C$26', 'HML37C$27', 'HML37C$28', 'HML37C$29', 'HML37C$30', 'HML37C$31', 'HML37C$32', 'HML37C$33', 'HML37C$34', 'HML37C$35', 'HML37C$36', 'HML37C$37', 'HML37C$38', 'HML37C$39', 'HML37C$40', 'HML37C$41', 'HML37C$42', 'HML37C$43', 'HML37C$44', 'HML37C$45', 'HML37C$46', 'HML37D$01', 'HML37D$02', 'HML37D$03', 'HML37D$04', 'HML37D$05', 'HML37D$06', 'HML37D$07', 'HML37D$08', 'HML37D$09', 'HML37D$10', 'HML37D$11', 'HML37D$12', 'HML37D$13', 'HML37D$14', 'HML37D$15', 'HML37D$16', 'HML37D$17', 'HML37D$18', 'HML37D$19', 'HML37D$20', 'HML37D$21', 'HML37D$22', 'HML37D$23', 'HML37D$24', 'HML37D$25', 'HML37D$26', 'HML37D$27', 'HML37D$28', 'HML37D$29', 'HML37D$30', 'HML37D$31', 'HML37D$32', 'HML37D$33', 'HML37D$34', 'HML37D$35', 'HML37D$36', 'HML37D$37', 'HML37D$38', 'HML37D$39', 'HML37D$40', 'HML37D$41', 'HML37D$42', 'HML37D$43', 'HML37D$44', 'HML37D$45', 'HML37D$46', 'HML37E$01', 'HML37E$02', 'HML37E$03', 'HML37E$04', 'HML37E$05', 'HML37E$06', 'HML37E$07', 'HML37E$08', 'HML37E$09', 'HML37E$10', 'HML37E$11', 'HML37E$12', 'HML37E$13', 'HML37E$14', 'HML37E$15', 'HML37E$16', 'HML37E$17', 'HML37E$18', 'HML37E$19', 'HML37E$20', 'HML37E$21', 'HML37E$22', 'HML37E$23', 'HML37E$24', 'HML37E$25', 'HML37E$26', 'HML37E$27', 'HML37E$28', 'HML37E$29', 'HML37E$30', 'HML37E$31', 'HML37E$32', 'HML37E$33', 'HML37E$34', 'HML37E$35', 'HML37E$36', 'HML37E$37', 'HML37E$38', 'HML37E$39', 'HML37E$40', 'HML37E$41', 'HML37E$42', 'HML37E$43', 'HML37E$44', 'HML37E$45', 'HML37E$46', 'HML37F$01', 'HML37F$02', 'HML37F$03', 'HML37F$04', 'HML37F$05', 'HML37F$06', 'HML37F$07', 'HML37F$08', 'HML37F$09', 'HML37F$10', 'HML37F$11', 'HML37F$12', 'HML37F$13', 'HML37F$14', 'HML37F$15', 'HML37F$16', 'HML37F$17', 'HML37F$18', 'HML37F$19', 'HML37F$20', 'HML37F$21', 'HML37F$22', 'HML37F$23', 'HML37F$24', 'HML37F$25', 'HML37F$26', 'HML37F$27', 'HML37F$28', 'HML37F$29', 'HML37F$30', 'HML37F$31', 'HML37F$32', 'HML37F$33', 'HML37F$34', 'HML37F$35', 'HML37F$36', 'HML37F$37', 'HML37F$38', 'HML37F$39', 'HML37F$40', 'HML37F$41', 'HML37F$42', 'HML37F$43', 'HML37F$44', 'HML37F$45', 'HML37F$46', 'HML37G$01', 'HML37G$02', 'HML37G$03', 'HML37G$04', 'HML37G$05', 'HML37G$06', 'HML37G$07', 'HML37G$08', 'HML37G$09', 'HML37G$10', 'HML37G$11', 'HML37G$12', 'HML37G$13', 'HML37G$14', 'HML37G$15', 'HML37G$16', 'HML37G$17', 'HML37G$18', 'HML37G$19', 'HML37G$20', 'HML37G$21', 'HML37G$22', 'HML37G$23', 'HML37G$24', 'HML37G$25', 'HML37G$26', 'HML37G$27', 'HML37G$28', 'HML37G$29', 'HML37G$30', 'HML37G$31', 'HML37G$32', 'HML37G$33', 'HML37G$34', 'HML37G$35', 'HML37G$36', 'HML37G$37', 'HML37G$38', 'HML37G$39', 'HML37G$40', 'HML37G$41', 'HML37G$42', 'HML37G$43', 'HML37G$44', 'HML37G$45', 'HML37G$46', 'HML37H$01', 'HML37H$02', 'HML37H$03', 'HML37H$04', 'HML37H$05', 'HML37H$06', 'HML37H$07', 'HML37H$08', 'HML37H$09', 'HML37H$10', 'HML37H$11', 'HML37H$12', 'HML37H$13', 'HML37H$14', 'HML37H$15', 'HML37H$16', 'HML37H$17', 'HML37H$18', 'HML37H$19', 'HML37H$20', 'HML37H$21', 'HML37H$22', 'HML37H$23', 'HML37H$24', 'HML37H$25', 'HML37H$26', 'HML37H$27', 'HML37H$28', 'HML37H$29', 'HML37H$30', 'HML37H$31', 'HML37H$32', 'HML37H$33', 'HML37H$34', 'HML37H$35', 'HML37H$36', 'HML37H$37', 'HML37H$38', 'HML37H$39', 'HML37H$40', 'HML37H$41', 'HML37H$42', 'HML37H$43', 'HML37H$44', 'HML37H$45', 'HML37H$46', 'HML37I$01', 'HML37I$02', 'HML37I$03', 'HML37I$04', 'HML37I$05', 'HML37I$06', 'HML37I$07', 'HML37I$08', 'HML37I$09', 'HML37I$10', 'HML37I$11', 'HML37I$12', 'HML37I$13', 'HML37I$14', 'HML37I$15', 'HML37I$16', 'HML37I$17', 'HML37I$18', 'HML37I$19', 'HML37I$20', 'HML3

In [64]:
hk_vars = [
    var for var in hr2021.columns
    if var.upper().startswith("HK")
]

print(hk_vars[:100])

[]

In [66]:
hml_vars

['HML1',
 'HML1A',
 'HML2',
 'HMLIDX$1',
 'HMLIDX$2',
 'HMLIDX$3',
 'HMLIDX$4',
 'HMLIDX$5',
 'HMLIDX$6',
 'HMLIDX$7',
 'HML3$1',
 'HML3$2',
 'HML3$3',
 'HML3$4',
 'HML3$5',
 'HML3$6',
 'HML3$7',
 'HML4$1',
 'HML4$2',
 'HML4$3',
 'HML4$4',
 'HML4$5',
 'HML4$6',
 'HML4$7',
 'HML5$1',
 'HML5$2',
 'HML5$3',
 'HML5$4',
 'HML5$5',
 'HML5$6',
 'HML5$7',
 'HML6$1',
 'HML6$2',
 'HML6$3',
 'HML6$4',
 'HML6$5',
 'HML6$6',
 'HML6$7',
 'HML7$1',
 'HML7$2',
 'HML7$3',
 'HML7$4',
 'HML7$5',
 'HML7$6',
 'HML7$7',
 'HML8$1',
 'HML8$2',
 'HML8$3',
 'HML8$4',
 'HML8$5',
 'HML8$6',
 'HML8$7',
 'HML9$1',
 'HML9$2',
 'HML9$3',
 'HML9$4',
 'HML9$5',
 'HML9$6',
 'HML9$7',
 'HML10$1',
 'HML10$2',
 'HML10$3',
 'HML10$4',
 'HML10$5',
 'HML10$6',
 'HML10$7',
 'HML11$1',
 'HML11$2',
 'HML11$3',
 'HML11$4',
 'HML11$5',
 'HML11$6',
 'HML11$7',
 'HML21$1',
 'HML21$2',
 'HML21$3',
 'HML21$4',
 'HML21$5',
 'HML21$6',
 'HML21$7',
 'HMLA$1',
 'HMLA$2',
 'HMLA$3',
 'HMLA$4',
 'HMLA$5',
 'HMLA$6',
 'HMLA$7',
 'HMLB$1',
 'HMLB$2',
 'HMLB$3',
 'HMLB$4',
 'HMLB$5',
 'HMLB$6',
 'HMLB$7',
 'HMLC$1',
 'HMLC$2',
 'HMLC$3',
 'HMLC$4',
 'HMLC$5',
 'HMLC$6',
 'HMLC$7',
 'HMLD$1',
 'HMLD$2',
 'HMLD$3',
 'HMLD$4',
 'HMLD$5',
 'HMLD$6',
 'HMLD$7',
 'HMLE$1',
 'HMLE$2',
 'HMLE$3',
 'HMLE$4',
 'HMLE$5',
 'HMLE$6',
 'HMLE$7',
 'HML22$1',
 'HML22$2',
 'HML22$3',
 'HML22$4',
 'HML22$5',
 'HML22$6',
 'HML22$7',
 'HML23$1',
 'HML23$2',
 'HML23$3',
 'HML23$4',
 'HML23$5',
 'HML23$6',
 'HML23$7',
 'HML12$01',
 'HML12$02',
 'HML12$03',
 'HML12$04',
 'HML12$05',
 'HML12$06',
 'HML12$07',
 'HML12$08',
 'HML12$09',
 'HML12$10',
 'HML12$11',
 'HML12$12',
 'HML12$13',
 'HML12$14',
 'HML12$15',
 'HML12$16',
 'HML12$17',
 'HML12$18',
 'HML12$19',
 'HML12$20',
 'HML12$21',
 'HML12$22',
 'HML12$23',
 'HML12$24',
 'HML12$25',
 'HML12$26',
 'HML12$27',
 'HML12$28',
 'HML12$29',
 'HML12$30',
 'HML12$31',
 'HML12$32',
 'HML12$33',
 'HML12$34',
 'HML12$35',
 'HML12$36',
 'HML12$37',
 'HML12$38',
 'HML12$39',
 'HML12$40',
 'HML12$41',
 'HML12$42',
 'HML12$43',
 'HML12$44',
 'HML12$45',
 'HML12$46',
 'HML13$01',
 'HML13$02',
 'HML13$03',
 'HML13$04',
 'HML13$05',
 'HML13$06',
 'HML13$07',
 'HML13$08',
 'HML13$09',
 'HML13$10',
 'HML13$11',
 'HML13$12',
 'HML13$13',
 'HML13$14',
 'HML13$15',
 'HML13$16',
 'HML13$17',
 'HML13$18',
 'HML13$19',
 'HML13$20',
 'HML13$21',
 'HML13$22',
 'HML13$23',
 'HML13$24',
 'HML13$25',
 'HML13$26',
 'HML13$27',
 'HML13$28',
 'HML13$29',
 'HML13$30',
 'HML13$31',
 'HML13$32',
 'HML13$33',
 'HML13$34',
 'HML13$35',
 'HML13$36',
 'HML13$37',
 'HML13$38',
 'HML13$39',
 'HML13$40',
 'HML13$41',
 'HML13$42',
 'HML13$43',
 'HML13$44',
 'HML13$45',
 'HML13$46',
 'HML14$01',
 'HML14$02',
 'HML14$03',
 'HML14$04',
 'HML14$05',
 'HML14$06',
 'HML14$07',
 'HML14$08',
 'HML14$09',
 'HML14$10',
 'HML14$11',
 'HML14$12',
 'HML14$13',
 'HML14$14',
 'HML14$15',
 'HML14$16',
 'HML14$17',
 'HML14$18',
 'HML14$19',
 'HML14$20',
 'HML14$21',
 'HML14$22',
 'HML14$23',
 'HML14$24',
 'HML14$25',
 'HML14$26',
 'HML14$27',
 'HML14$28',
 'HML14$29',
 'HML14$30',
 'HML14$31',
 'HML14$32',
 'HML14$33',
 'HML14$34',
 'HML14$35',
 'HML14$36',
 'HML14$37',
 'HML14$38',
 'HML14$39',
 'HML14$40',
 'HML14$41',
 'HML14$42',
 'HML14$43',
 'HML14$44',
 'HML14$45',
 'HML14$46',
 'HML15$01',
 'HML15$02',
 'HML15$03',
 'HML15$04',
 'HML15$05',
 'HML15$06',
 'HML15$07',
 'HML15$08',
 'HML15$09',
 'HML15$10',
 'HML15$11',
 'HML15$12',
 'HML15$13',
 'HML15$14',
 'HML15$15',
 'HML15$16',
 'HML15$17',
 'HML15$18',
 'HML15$19',
 'HML15$20',
 'HML15$21',
 'HML15$22',
 'HML15$23',
 'HML15$24',
 'HML15$25',
 'HML15$26',
 'HML15$27',
 'HML15$28',
 'HML15$29',
 'HML15$30',
 'HML15$31',
 'HML15$32',
 'HML15$33',
 'HML15$34',
 'HML15$35',
 'HML15$36',
 'HML15$37',
 'HML15$38',
 'HML15$39',
 'HML15$40',
 'HML15$41',
 'HML15$42',
 'HML15$43',
 'HML15$44',
 'HML15$45',
 'HML15$46',
 'HML16$01',
 'HML16$02',
 'HML16$03',
 'HML16$04',
 'HML16$05',
 'HML16$06',
 'HML16$07',
 'HML16$08',
 'HML16$09',
 'HML16$10',
 'HML16$11',
 'HML16$12',
 'HML16$13',
 'HML16$14',
 'HML16$15',
 'HML16$16',
 'HML16$17',
 'HML16$18',
 'HML16$19',
 'HML16$20',
 'HML16$21',
 'HML16$22',
 'HML16$23',
 'HML16$24',
 'HML16$25',
 'HML16$26',
 'HML16$27',
 'HML16$28',
 'HML16$29',
 'HML16$30',
 'HML16$31',
 'HML16$32',
 'HML16$33',
 'HML16$34',
 'HML16$35',
 'HML16$36',
 'HML16$37',
 'HML16$38',
 'HML16$39',
 'HML16$40',
 'HML16$41',
 'HML16$42',
 'HML16$43',
 'HML16$44',
 'HML16$45',
 'HML16$46',
 'HML16A$01',
 'HML16A$02',
 'HML16A$03',
 'HML16A$04',
 'HML16A$05',
 'HML16A$06',
 'HML16A$07',
 'HML16A$08',
 'HML16A$09',
 'HML16A$10',
 'HML16A$11',
 'HML16A$12',
 'HML16A$13',
 'HML16A$14',
 'HML16A$15',
 'HML16A$16',
 'HML16A$17',
 'HML16A$18',
 'HML16A$19',
 'HML16A$20',
 'HML16A$21',
 'HML16A$22',
 'HML16A$23',
 'HML16A$24',
 'HML16A$25',
 'HML16A$26',
 'HML16A$27',
 'HML16A$28',
 'HML16A$29',
 'HML16A$30',
 'HML16A$31',
 'HML16A$32',
 'HML16A$33',
 'HML16A$34',
 'HML16A$35',
 'HML16A$36',
 'HML16A$37',
 'HML16A$38',
 'HML16A$39',
 'HML16A$40',
 'HML16A$41',
 'HML16A$42',
 'HML16A$43',
 'HML16A$44',
 'HML16A$45',
 'HML16A$46',
 'HML17$01',
 'HML17$02',
 'HML17$03',
 'HML17$04',
 'HML17$05',
 'HML17$06',
 'HML17$07',
 'HML17$08',
 'HML17$09',
 'HML17$10',
 'HML17$11',
 'HML17$12',
 'HML17$13',
 'HML17$14',
 'HML17$15',
 'HML17$16',
 'HML17$17',
 'HML17$18',
 'HML17$19',
 'HML17$20',
 'HML17$21',
 'HML17$22',
 'HML17$23',
 'HML17$24',
 'HML17$25',
 'HML17$26',
 'HML17$27',
 'HML17$28',
 'HML17$29',
 'HML17$30',
 'HML17$31',
 'HML17$32',
 'HML17$33',
 'HML17$34',
 'HML17$35',
 'HML17$36',
 'HML17$37',
 'HML17$38',
 'HML17$39',
 'HML17$40',
 'HML17$41',
 'HML17$42',
 'HML17$43',
 'HML17$44',
 'HML17$45',
 'HML17$46',
 'HML18$01',
 'HML18$02',
 'HML18$03',
 'HML18$04',
 'HML18$05',
 'HML18$06',
 'HML18$07',
 'HML18$08',
 'HML18$09',
 'HML18$10',
 'HML18$11',
 'HML18$12',
 'HML18$13',
 'HML18$14',
 'HML18$15',
 'HML18$16',
 'HML18$17',
 'HML18$18',
 'HML18$19',
 'HML18$20',
 'HML18$21',
 'HML18$22',
 'HML18$23',
 'HML18$24',
 'HML18$25',
 'HML18$26',
 'HML18$27',
 'HML18$28',
 'HML18$29',
 'HML18$30',
 'HML18$31',
 'HML18$32',
 'HML18$33',
 'HML18$34',
 'HML18$35',
 'HML18$36',
 'HML18$37',
 'HML18$38',
 'HML18$39',
 'HML18$40',
 'HML18$41',
 'HML18$42',
 'HML18$43',
 'HML18$44',
 'HML18$45',
 'HML18$46',
 'HML19$01',
 'HML19$02',
 'HML19$03',
 'HML19$04',
 'HML19$05',
 'HML19$06',
 'HML19$07',
 'HML19$08',
 'HML19$09',
 'HML19$10',
 'HML19$11',
 'HML19$12',
 'HML19$13',
 'HML19$14',
 'HML19$15',
 'HML19$16',
 'HML19$17',
 'HML19$18',
 'HML19$19',
 'HML19$20',
 'HML19$21',
 'HML19$22',
 'HML19$23',
 'HML19$24',
 'HML19$25',
 'HML19$26',
 'HML19$27',
 'HML19$28',
 'HML19$29',
 'HML19$30',
 'HML19$31',
 'HML19$32',
 'HML19$33',
 'HML19$34',
 'HML19$35',
 'HML19$36',
 'HML19$37',
 'HML19$38',
 'HML19$39',
 'HML19$40',
 'HML19$41',
 'HML19$42',
 'HML19$43',
 'HML19$44',
 'HML19$45',
 'HML19$46',
 'HML20$01',
 'HML20$02',
 'HML20$03',
 'HML20$04',
 'HML20$05',
 'HML20$06',
 'HML20$07',
 'HML20$08',
 'HML20$09',
 'HML20$10',
 'HML20$11',
 'HML20$12',
 'HML20$13',
 'HML20$14',
 'HML20$15',
 'HML20$16',
 'HML20$17',
 'HML20$18',
 'HML20$19',
 'HML20$20',
 'HML20$21',
 'HML20$22',
 'HML20$23',
 'HML20$24',
 'HML20$25',
 'HML20$26',
 'HML20$27',
 'HML20$28',
 'HML20$29',
 'HML20$30',
 'HML20$31',
 'HML20$32',
 'HML20$33',
 'HML20$34',
 'HML20$35',
 'HML20$36',
 'HML20$37',
 'HML20$38',
 'HML20$39',
 'HML20$40',
 'HML20$41',
 'HML20$42',
 'HML20$43',
 'HML20$44',
 'HML20$45',
 'HML20$46',
 'HML30$01',
 'HML30$02',
 'HML30$03',
 'HML30$04',
 'HML30$05',
 'HML30$06',
 'HML30$07',
 'HML30$08',
 'HML30$09',
 'HML30$10',
 'HML30$11',
 'HML30$12',
 'HML30$13',
 'HML30$14',
 'HML30$15',
 'HML30$16',
 'HML30$17',
 'HML30$18',
 'HML30$19',
 'HML30$20',
 'HML30$21',
 'HML30$22',
 'HML30$23',
 'HML30$24',
 'HML30$25',
 'HML30$26',
 'HML30$27',
 'HML30$28',
 'HML30$29',
 'HML30$30',
 'HML30$31',
 'HML30$32',
 'HML30$33',
 'HML30$34',
 'HML30$35',
 'HML30$36',
 'HML30$37',
 'HML30$38',
 'HML30$39',
 'HML30$40',
 'HML30$41',
 'HML30$42',
 'HML30$43',
 'HML30$44',
 'HML30$45',
 'HML30$46',
 'HML31$01',
 'HML31$02',
 'HML31$03',
 'HML31$04',
 'HML31$05',
 'HML31$06',
 'HML31$07',
 'HML31$08',
 'HML31$09',
 'HML31$10',
 'HML31$11',
 'HML31$12',
 'HML31$13',
 'HML31$14',
 'HML31$15',
 'HML31$16',
 'HML31$17',
 'HML31$18',
 'HML31$19',
 'HML31$20',
 'HML31$21',
 'HML31$22',
 'HML31$23',
 'HML31$24',
 'HML31$25',
 'HML31$26',
 'HML31$27',
 'HML31$28',
 'HML31$29',
 'HML31$30',
 'HML31$31',
 'HML31$32',
 'HML31$33',
 'HML31$34',
 'HML31$35',
 'HML31$36',
 'HML31$37',
 'HML31$38',
 'HML31$39',
 'HML31$40',
 'HML31$41',
 'HML31$42',
 'HML31$43',
 'HML31$44',
 'HML31$45',
 'HML31$46',
 'HML32$01',
 'HML32$02',
 'HML32$03',
 'HML32$04',
 'HML32$05',
 'HML32$06',
 'HML32$07',
 'HML32$08',
 'HML32$09',
 'HML32$10',
 'HML32$11',
 'HML32$12',
 'HML32$13',
 'HML32$14',
 'HML32$15',
 'HML32$16',
 'HML32$17',
 'HML32$18',
 'HML32$19',
 'HML32$20',
 'HML32$21',
 'HML32$22',
 'HML32$23',
 'HML32$24',
 'HML32$25',
 'HML32$26',
 'HML32$27',
 'HML32$28',
 'HML32$29',
 'HML32$30',
 'HML32$31',
 'HML32$32',
 'HML32$33',
 'HML32$34',
 'HML32$35',
 'HML32$36',
 'HML32$37',
 'HML32$38',
 'HML32$39',
 'HML32$40',
 'HML32$41',
 'HML32$42',
 'HML32$43',
 'HML32$44',
 'HML32$45',
 'HML32$46',
 'HML32A$01',
 'HML32A$02',
 'HML32A$03',
 'HML32A$04',
 'HML32A$05',
 'HML32A$06',
 'HML32A$07',
 'HML32A$08',
 'HML32A$09',
 'HML32A$10',
 'HML32A$11',
 'HML32A$12',
 'HML32A$13',
 'HML32A$14',
 'HML32A$15',
 'HML32A$16',
 'HML32A$17',
 'HML32A$18',
 'HML32A$19',
 'HML32A$20',
 'HML32A$21',
 'HML32A$22',
 'HML32A$23',
 'HML32A$24',
 'HML32A$25',
 'HML32A$26',
 'HML32A$27',
 'HML32A$28',
 'HML32A$29',
 'HML32A$30',
 'HML32A$31',
 'HML32A$32',
 'HML32A$33',
 'HML32A$34',
 'HML32A$35',
 'HML32A$36',
 'HML32A$37',
 'HML32A$38',
 'HML32A$39',
 'HML32A$40',
 'HML32A$41',
 'HML32A$42',
 'HML32A$43',
 'HML32A$44',
 'HML32A$45',
 'HML32A$46',
 'HML32B$01',
 'HML32B$02',
 'HML32B$03',
 'HML32B$04',
 'HML32B$05',
 'HML32B$06',
 'HML32B$07',
 'HML32B$08',
 'HML32B$09',
 'HML32B$10',
 'HML32B$11',
 'HML32B$12',
 'HML32B$13',
 'HML32B$14',
 'HML32B$15',
 'HML32B$16',
 'HML32B$17',
 'HML32B$18',
 'HML32B$19',
 'HML32B$20',
 'HML32B$21',
 'HML32B$22',
 'HML32B$23',
 'HML32B$24',
 'HML32B$25',
 'HML32B$26',
 'HML32B$27',
 'HML32B$28',
 'HML32B$29',
 'HML32B$30',
 'HML32B$31',
 'HML32B$32',
 'HML32B$33',
 'HML32B$34',
 'HML32B$35',
 'HML32B$36',
 'HML32B$37',
 'HML32B$38',
 'HML32B$39',
 'HML32B$40',
 'HML32B$41',
 'HML32B$42',
 'HML32B$43',
 'HML32B$44',
 'HML32B$45',
 'HML32B$46',
 'HML32C$01',
 'HML32C$02',
 'HML32C$03',
 'HML32C$04',
 'HML32C$05',
 'HML32C$06',
 'HML32C$07',
 'HML32C$08',
 'HML32C$09',
 'HML32C$10',
 'HML32C$11',
 'HML32C$12',
 'HML32C$13',
 'HML32C$14',
 'HML32C$15',
 'HML32C$16',
 'HML32C$17',
 'HML32C$18',
 'HML32C$19',
 'HML32C$20',
 'HML32C$21',
 'HML32C$22',
 'HML32C$23',
 'HML32C$24',
 'HML32C$25',
 'HML32C$26',
 'HML32C$27',
 'HML32C$28',
 'HML32C$29',
 'HML32C$30',
 'HML32C$31',
 'HML32C$32',
 'HML32C$33',
 'HML32C$34',
 'HML32C$35',
 'HML32C$36',
 'HML32C$37',
 'HML32C$38',
 'HML32C$39',
 'HML32C$40',
 'HML32C$41',
 'HML32C$42',
 'HML32C$43',
 'HML32C$44',
 'HML32C$45',
 'HML32C$46',
 'HML32D$01',
 'HML32D$02',
 'HML32D$03',
 'HML32D$04',
 'HML32D$05',
 'HML32D$06',
 'HML32D$07',
 'HML32D$08',
 'HML32D$09',
 'HML32D$10',
 'HML32D$11',
 'HML32D$12',
 'HML32D$13',
 'HML32D$14',
 'HML32D$15',
 'HML32D$16',
 'HML32D$17',
 'HML32D$18',
 'HML32D$19',
 'HML32D$20',
 'HML32D$21',
 'HML32D$22',
 'HML32D$23',
 'HML32D$24',
 'HML32D$25',
 'HML32D$26',
 'HML32D$27',
 'HML32D$28',
 'HML32D$29',
 'HML32D$30',
 'HML32D$31',
 'HML32D$32',
 'HML32D$33',
 'HML32D$34',
 'HML32D$35',
 'HML32D$36',
 'HML32D$37',
 'HML32D$38',
 'HML32D$39',
 'HML32D$40',
 'HML32D$41',
 'HML32D$42',
 'HML32D$43',
 'HML32D$44',
 'HML32D$45',
 'HML32D$46',
 'HML32E$01',
 'HML32E$02',
 'HML32E$03',
 'HML32E$04',
 'HML32E$05',
 'HML32E$06',
 'HML32E$07',
 'HML32E$08',
 'HML32E$09',
 'HML32E$10',
 'HML32E$11',
 'HML32E$12',
 'HML32E$13',
 'HML32E$14',
 'HML32E$15',
 'HML32E$16',
 'HML32E$17',
 'HML32E$18',
 'HML32E$19',
 'HML32E$20',
 'HML32E$21',
 'HML32E$22',
 'HML32E$23',
 'HML32E$24',
 'HML32E$25',
 'HML32E$26',
 'HML32E$27',
 'HML32E$28',
 'HML32E$29',
 'HML32E$30',
 'HML32E$31',
 'HML32E$32',
 'HML32E$33',
 'HML32E$34',
 'HML32E$35',
 'HML32E$36',
 'HML32E$37',
 'HML32E$38',
 'HML32E$39',
 'HML32E$40',
 'HML32E$41',
 'HML32E$42',
 'HML32E$43',
 'HML32E$44',
 'HML32E$45',
 'HML32E$46',
 'HML32F$01',
 'HML32F$02',
 'HML32F$03',
 'HML32F$04',
 'HML32F$05',
 'HML32F$06',
 'HML32F$07',
 'HML32F$08',
 'HML32F$09',
 'HML32F$10',
 'HML32F$11',
 'HML32F$12',
 'HML32F$13',
 'HML32F$14',
 'HML32F$15',
 'HML32F$16',
 'HML32F$17',
 'HML32F$18',
 'HML32F$19',
 'HML32F$20',
 'HML32F$21',
 'HML32F$22',
 'HML32F$23',
 'HML32F$24',
 'HML32F$25',
 'HML32F$26',
 'HML32F$27',
 'HML32F$28',
 'HML32F$29',
 'HML32F$30',
 'HML32F$31',
 'HML32F$32',
 'HML32F$33',
 'HML32F$34',
 'HML32F$35',
 'HML32F$36',
 'HML32F$37',
 'HML32F$38',
 'HML32F$39',
 'HML32F$40',
 'HML32F$41',
 'HML32F$42',
 'HML32F$43',
 ...]

In [65]:
malaria_vars

['HML1',
 'HML1A',
 'HML2',
 'HMLIDX$1',
 'HMLIDX$2',
 'HMLIDX$3',
 'HMLIDX$4',
 'HMLIDX$5',
 'HMLIDX$6',
 'HMLIDX$7',
 'HML3$1',
 'HML3$2',
 'HML3$3',
 'HML3$4',
 'HML3$5',
 'HML3$6',
 'HML3$7',
 'HML4$1',
 'HML4$2',
 'HML4$3',
 'HML4$4',
 'HML4$5',
 'HML4$6',
 'HML4$7',
 'HML5$1',
 'HML5$2',
 'HML5$3',
 'HML5$4',
 'HML5$5',
 'HML5$6',
 'HML5$7',
 'HML6$1',
 'HML6$2',
 'HML6$3',
 'HML6$4',
 'HML6$5',
 'HML6$6',
 'HML6$7',
 'HML7$1',
 'HML7$2',
 'HML7$3',
 'HML7$4',
 'HML7$5',
 'HML7$6',
 'HML7$7',
 'HML8$1',
 'HML8$2',
 'HML8$3',
 'HML8$4',
 'HML8$5',
 'HML8$6',
 'HML8$7',
 'HML9$1',
 'HML9$2',
 'HML9$3',
 'HML9$4',
 'HML9$5',
 'HML9$6',
 'HML9$7',
 'HML10$1',
 'HML10$2',
 'HML10$3',
 'HML10$4',
 'HML10$5',
 'HML10$6',
 'HML10$7',
 'HML11$1',
 'HML11$2',
 'HML11$3',
 'HML11$4',
 'HML11$5',
 'HML11$6',
 'HML11$7',
 'HML21$1',
 'HML21$2',
 'HML21$3',
 'HML21$4',
 'HML21$5',
 'HML21$6',
 'HML21$7',
 'HMLA$1',
 'HMLA$2',
 'HMLA$3',
 'HMLA$4',
 'HMLA$5',
 'HMLA$6',
 'HMLA$7',
 'HMLB$1',
 'HMLB$2',
 'HMLB$3',
 'HMLB$4',
 'HMLB$5',
 'HMLB$6',
 'HMLB$7',
 'HMLC$1',
 'HMLC$2',
 'HMLC$3',
 'HMLC$4',
 'HMLC$5',
 'HMLC$6',
 'HMLC$7',
 'HMLD$1',
 'HMLD$2',
 'HMLD$3',
 'HMLD$4',
 'HMLD$5',
 'HMLD$6',
 'HMLD$7',
 'HMLE$1',
 'HMLE$2',
 'HMLE$3',
 'HMLE$4',
 'HMLE$5',
 'HMLE$6',
 'HMLE$7',
 'HML22$1',
 'HML22$2',
 'HML22$3',
 'HML22$4',
 'HML22$5',
 'HML22$6',
 'HML22$7',
 'HML23$1',
 'HML23$2',
 'HML23$3',
 'HML23$4',
 'HML23$5',
 'HML23$6',
 'HML23$7',
 'HML12$01',
 'HML12$02',
 'HML12$03',
 'HML12$04',
 'HML12$05',
 'HML12$06',
 'HML12$07',
 'HML12$08',
 'HML12$09',
 'HML12$10',
 'HML12$11',
 'HML12$12',
 'HML12$13',
 'HML12$14',
 'HML12$15',
 'HML12$16',
 'HML12$17',
 'HML12$18',
 'HML12$19',
 'HML12$20',
 'HML12$21',
 'HML12$22',
 'HML12$23',
 'HML12$24',
 'HML12$25',
 'HML12$26',
 'HML12$27',
 'HML12$28',
 'HML12$29',
 'HML12$30',
 'HML12$31',
 'HML12$32',
 'HML12$33',
 'HML12$34',
 'HML12$35',
 'HML12$36',
 'HML12$37',
 'HML12$38',
 'HML12$39',
 'HML12$40',
 'HML12$41',
 'HML12$42',
 'HML12$43',
 'HML12$44',
 'HML12$45',
 'HML12$46',
 'HML13$01',
 'HML13$02',
 'HML13$03',
 'HML13$04',
 'HML13$05',
 'HML13$06',
 'HML13$07',
 'HML13$08',
 'HML13$09',
 'HML13$10',
 'HML13$11',
 'HML13$12',
 'HML13$13',
 'HML13$14',
 'HML13$15',
 'HML13$16',
 'HML13$17',
 'HML13$18',
 'HML13$19',
 'HML13$20',
 'HML13$21',
 'HML13$22',
 'HML13$23',
 'HML13$24',
 'HML13$25',
 'HML13$26',
 'HML13$27',
 'HML13$28',
 'HML13$29',
 'HML13$30',
 'HML13$31',
 'HML13$32',
 'HML13$33',
 'HML13$34',
 'HML13$35',
 'HML13$36',
 'HML13$37',
 'HML13$38',
 'HML13$39',
 'HML13$40',
 'HML13$41',
 'HML13$42',
 'HML13$43',
 'HML13$44',
 'HML13$45',
 'HML13$46',
 'HML14$01',
 'HML14$02',
 'HML14$03',
 'HML14$04',
 'HML14$05',
 'HML14$06',
 'HML14$07',
 'HML14$08',
 'HML14$09',
 'HML14$10',
 'HML14$11',
 'HML14$12',
 'HML14$13',
 'HML14$14',
 'HML14$15',
 'HML14$16',
 'HML14$17',
 'HML14$18',
 'HML14$19',
 'HML14$20',
 'HML14$21',
 'HML14$22',
 'HML14$23',
 'HML14$24',
 'HML14$25',
 'HML14$26',
 'HML14$27',
 'HML14$28',
 'HML14$29',
 'HML14$30',
 'HML14$31',
 'HML14$32',
 'HML14$33',
 'HML14$34',
 'HML14$35',
 'HML14$36',
 'HML14$37',
 'HML14$38',
 'HML14$39',
 'HML14$40',
 'HML14$41',
 'HML14$42',
 'HML14$43',
 'HML14$44',
 'HML14$45',
 'HML14$46',
 'HML15$01',
 'HML15$02',
 'HML15$03',
 'HML15$04',
 'HML15$05',
 'HML15$06',
 'HML15$07',
 'HML15$08',
 'HML15$09',
 'HML15$10',
 'HML15$11',
 'HML15$12',
 'HML15$13',
 'HML15$14',
 'HML15$15',
 'HML15$16',
 'HML15$17',
 'HML15$18',
 'HML15$19',
 'HML15$20',
 'HML15$21',
 'HML15$22',
 'HML15$23',
 'HML15$24',
 'HML15$25',
 'HML15$26',
 'HML15$27',
 'HML15$28',
 'HML15$29',
 'HML15$30',
 'HML15$31',
 'HML15$32',
 'HML15$33',
 'HML15$34',
 'HML15$35',
 'HML15$36',
 'HML15$37',
 'HML15$38',
 'HML15$39',
 'HML15$40',
 'HML15$41',
 'HML15$42',
 'HML15$43',
 'HML15$44',
 'HML15$45',
 'HML15$46',
 'HML16$01',
 'HML16$02',
 'HML16$03',
 'HML16$04',
 'HML16$05',
 'HML16$06',
 'HML16$07',
 'HML16$08',
 'HML16$09',
 'HML16$10',
 'HML16$11',
 'HML16$12',
 'HML16$13',
 'HML16$14',
 'HML16$15',
 'HML16$16',
 'HML16$17',
 'HML16$18',
 'HML16$19',
 'HML16$20',
 'HML16$21',
 'HML16$22',
 'HML16$23',
 'HML16$24',
 'HML16$25',
 'HML16$26',
 'HML16$27',
 'HML16$28',
 'HML16$29',
 'HML16$30',
 'HML16$31',
 'HML16$32',
 'HML16$33',
 'HML16$34',
 'HML16$35',
 'HML16$36',
 'HML16$37',
 'HML16$38',
 'HML16$39',
 'HML16$40',
 'HML16$41',
 'HML16$42',
 'HML16$43',
 'HML16$44',
 'HML16$45',
 'HML16$46',
 'HML16A$01',
 'HML16A$02',
 'HML16A$03',
 'HML16A$04',
 'HML16A$05',
 'HML16A$06',
 'HML16A$07',
 'HML16A$08',
 'HML16A$09',
 'HML16A$10',
 'HML16A$11',
 'HML16A$12',
 'HML16A$13',
 'HML16A$14',
 'HML16A$15',
 'HML16A$16',
 'HML16A$17',
 'HML16A$18',
 'HML16A$19',
 'HML16A$20',
 'HML16A$21',
 'HML16A$22',
 'HML16A$23',
 'HML16A$24',
 'HML16A$25',
 'HML16A$26',
 'HML16A$27',
 'HML16A$28',
 'HML16A$29',
 'HML16A$30',
 'HML16A$31',
 'HML16A$32',
 'HML16A$33',
 'HML16A$34',
 'HML16A$35',
 'HML16A$36',
 'HML16A$37',
 'HML16A$38',
 'HML16A$39',
 'HML16A$40',
 'HML16A$41',
 'HML16A$42',
 'HML16A$43',
 'HML16A$44',
 'HML16A$45',
 'HML16A$46',
 'HML17$01',
 'HML17$02',
 'HML17$03',
 'HML17$04',
 'HML17$05',
 'HML17$06',
 'HML17$07',
 'HML17$08',
 'HML17$09',
 'HML17$10',
 'HML17$11',
 'HML17$12',
 'HML17$13',
 'HML17$14',
 'HML17$15',
 'HML17$16',
 'HML17$17',
 'HML17$18',
 'HML17$19',
 'HML17$20',
 'HML17$21',
 'HML17$22',
 'HML17$23',
 'HML17$24',
 'HML17$25',
 'HML17$26',
 'HML17$27',
 'HML17$28',
 'HML17$29',
 'HML17$30',
 'HML17$31',
 'HML17$32',
 'HML17$33',
 'HML17$34',
 'HML17$35',
 'HML17$36',
 'HML17$37',
 'HML17$38',
 'HML17$39',
 'HML17$40',
 'HML17$41',
 'HML17$42',
 'HML17$43',
 'HML17$44',
 'HML17$45',
 'HML17$46',
 'HML18$01',
 'HML18$02',
 'HML18$03',
 'HML18$04',
 'HML18$05',
 'HML18$06',
 'HML18$07',
 'HML18$08',
 'HML18$09',
 'HML18$10',
 'HML18$11',
 'HML18$12',
 'HML18$13',
 'HML18$14',
 'HML18$15',
 'HML18$16',
 'HML18$17',
 'HML18$18',
 'HML18$19',
 'HML18$20',
 'HML18$21',
 'HML18$22',
 'HML18$23',
 'HML18$24',
 'HML18$25',
 'HML18$26',
 'HML18$27',
 'HML18$28',
 'HML18$29',
 'HML18$30',
 'HML18$31',
 'HML18$32',
 'HML18$33',
 'HML18$34',
 'HML18$35',
 'HML18$36',
 'HML18$37',
 'HML18$38',
 'HML18$39',
 'HML18$40',
 'HML18$41',
 'HML18$42',
 'HML18$43',
 'HML18$44',
 'HML18$45',
 'HML18$46',
 'HML19$01',
 'HML19$02',
 'HML19$03',
 'HML19$04',
 'HML19$05',
 'HML19$06',
 'HML19$07',
 'HML19$08',
 'HML19$09',
 'HML19$10',
 'HML19$11',
 'HML19$12',
 'HML19$13',
 'HML19$14',
 'HML19$15',
 'HML19$16',
 'HML19$17',
 'HML19$18',
 'HML19$19',
 'HML19$20',
 'HML19$21',
 'HML19$22',
 'HML19$23',
 'HML19$24',
 'HML19$25',
 'HML19$26',
 'HML19$27',
 'HML19$28',
 'HML19$29',
 'HML19$30',
 'HML19$31',
 'HML19$32',
 'HML19$33',
 'HML19$34',
 'HML19$35',
 'HML19$36',
 'HML19$37',
 'HML19$38',
 'HML19$39',
 'HML19$40',
 'HML19$41',
 'HML19$42',
 'HML19$43',
 'HML19$44',
 'HML19$45',
 'HML19$46',
 'HML20$01',
 'HML20$02',
 'HML20$03',
 'HML20$04',
 'HML20$05',
 'HML20$06',
 'HML20$07',
 'HML20$08',
 'HML20$09',
 'HML20$10',
 'HML20$11',
 'HML20$12',
 'HML20$13',
 'HML20$14',
 'HML20$15',
 'HML20$16',
 'HML20$17',
 'HML20$18',
 'HML20$19',
 'HML20$20',
 'HML20$21',
 'HML20$22',
 'HML20$23',
 'HML20$24',
 'HML20$25',
 'HML20$26',
 'HML20$27',
 'HML20$28',
 'HML20$29',
 'HML20$30',
 'HML20$31',
 'HML20$32',
 'HML20$33',
 'HML20$34',
 'HML20$35',
 'HML20$36',
 'HML20$37',
 'HML20$38',
 'HML20$39',
 'HML20$40',
 'HML20$41',
 'HML20$42',
 'HML20$43',
 'HML20$44',
 'HML20$45',
 'HML20$46',
 'HML30$01',
 'HML30$02',
 'HML30$03',
 'HML30$04',
 'HML30$05',
 'HML30$06',
 'HML30$07',
 'HML30$08',
 'HML30$09',
 'HML30$10',
 'HML30$11',
 'HML30$12',
 'HML30$13',
 'HML30$14',
 'HML30$15',
 'HML30$16',
 'HML30$17',
 'HML30$18',
 'HML30$19',
 'HML30$20',
 'HML30$21',
 'HML30$22',
 'HML30$23',
 'HML30$24',
 'HML30$25',
 'HML30$26',
 'HML30$27',
 'HML30$28',
 'HML30$29',
 'HML30$30',
 'HML30$31',
 'HML30$32',
 'HML30$33',
 'HML30$34',
 'HML30$35',
 'HML30$36',
 'HML30$37',
 'HML30$38',
 'HML30$39',
 'HML30$40',
 'HML30$41',
 'HML30$42',
 'HML30$43',
 'HML30$44',
 'HML30$45',
 'HML30$46',
 'HML31$01',
 'HML31$02',
 'HML31$03',
 'HML31$04',
 'HML31$05',
 'HML31$06',
 'HML31$07',
 'HML31$08',
 'HML31$09',
 'HML31$10',
 'HML31$11',
 'HML31$12',
 'HML31$13',
 'HML31$14',
 'HML31$15',
 'HML31$16',
 'HML31$17',
 'HML31$18',
 'HML31$19',
 'HML31$20',
 'HML31$21',
 'HML31$22',
 'HML31$23',
 'HML31$24',
 'HML31$25',
 'HML31$26',
 'HML31$27',
 'HML31$28',
 'HML31$29',
 'HML31$30',
 'HML31$31',
 'HML31$32',
 'HML31$33',
 'HML31$34',
 'HML31$35',
 'HML31$36',
 'HML31$37',
 'HML31$38',
 'HML31$39',
 'HML31$40',
 'HML31$41',
 'HML31$42',
 'HML31$43',
 'HML31$44',
 'HML31$45',
 'HML31$46',
 'HML32$01',
 'HML32$02',
 'HML32$03',
 'HML32$04',
 'HML32$05',
 'HML32$06',
 'HML32$07',
 'HML32$08',
 'HML32$09',
 'HML32$10',
 'HML32$11',
 'HML32$12',
 'HML32$13',
 'HML32$14',
 'HML32$15',
 'HML32$16',
 'HML32$17',
 'HML32$18',
 'HML32$19',
 'HML32$20',
 'HML32$21',
 'HML32$22',
 'HML32$23',
 'HML32$24',
 'HML32$25',
 'HML32$26',
 'HML32$27',
 'HML32$28',
 'HML32$29',
 'HML32$30',
 'HML32$31',
 'HML32$32',
 'HML32$33',
 'HML32$34',
 'HML32$35',
 'HML32$36',
 'HML32$37',
 'HML32$38',
 'HML32$39',
 'HML32$40',
 'HML32$41',
 'HML32$42',
 'HML32$43',
 'HML32$44',
 'HML32$45',
 'HML32$46',
 'HML32A$01',
 'HML32A$02',
 'HML32A$03',
 'HML32A$04',
 'HML32A$05',
 'HML32A$06',
 'HML32A$07',
 'HML32A$08',
 'HML32A$09',
 'HML32A$10',
 'HML32A$11',
 'HML32A$12',
 'HML32A$13',
 'HML32A$14',
 'HML32A$15',
 'HML32A$16',
 'HML32A$17',
 'HML32A$18',
 'HML32A$19',
 'HML32A$20',
 'HML32A$21',
 'HML32A$22',
 'HML32A$23',
 'HML32A$24',
 'HML32A$25',
 'HML32A$26',
 'HML32A$27',
 'HML32A$28',
 'HML32A$29',
 'HML32A$30',
 'HML32A$31',
 'HML32A$32',
 'HML32A$33',
 'HML32A$34',
 'HML32A$35',
 'HML32A$36',
 'HML32A$37',
 'HML32A$38',
 'HML32A$39',
 'HML32A$40',
 'HML32A$41',
 'HML32A$42',
 'HML32A$43',
 'HML32A$44',
 'HML32A$45',
 'HML32A$46',
 'HML32B$01',
 'HML32B$02',
 'HML32B$03',
 'HML32B$04',
 'HML32B$05',
 'HML32B$06',
 'HML32B$07',
 'HML32B$08',
 'HML32B$09',
 'HML32B$10',
 'HML32B$11',
 'HML32B$12',
 'HML32B$13',
 'HML32B$14',
 'HML32B$15',
 'HML32B$16',
 'HML32B$17',
 'HML32B$18',
 'HML32B$19',
 'HML32B$20',
 'HML32B$21',
 'HML32B$22',
 'HML32B$23',
 'HML32B$24',
 'HML32B$25',
 'HML32B$26',
 'HML32B$27',
 'HML32B$28',
 'HML32B$29',
 'HML32B$30',
 'HML32B$31',
 'HML32B$32',
 'HML32B$33',
 'HML32B$34',
 'HML32B$35',
 'HML32B$36',
 'HML32B$37',
 'HML32B$38',
 'HML32B$39',
 'HML32B$40',
 'HML32B$41',
 'HML32B$42',
 'HML32B$43',
 'HML32B$44',
 'HML32B$45',
 'HML32B$46',
 'HML32C$01',
 'HML32C$02',
 'HML32C$03',
 'HML32C$04',
 'HML32C$05',
 'HML32C$06',
 'HML32C$07',
 'HML32C$08',
 'HML32C$09',
 'HML32C$10',
 'HML32C$11',
 'HML32C$12',
 'HML32C$13',
 'HML32C$14',
 'HML32C$15',
 'HML32C$16',
 'HML32C$17',
 'HML32C$18',
 'HML32C$19',
 'HML32C$20',
 'HML32C$21',
 'HML32C$22',
 'HML32C$23',
 'HML32C$24',
 'HML32C$25',
 'HML32C$26',
 'HML32C$27',
 'HML32C$28',
 'HML32C$29',
 'HML32C$30',
 'HML32C$31',
 'HML32C$32',
 'HML32C$33',
 'HML32C$34',
 'HML32C$35',
 'HML32C$36',
 'HML32C$37',
 'HML32C$38',
 'HML32C$39',
 'HML32C$40',
 'HML32C$41',
 'HML32C$42',
 'HML32C$43',
 'HML32C$44',
 'HML32C$45',
 'HML32C$46',
 'HML32D$01',
 'HML32D$02',
 'HML32D$03',
 'HML32D$04',
 'HML32D$05',
 'HML32D$06',
 'HML32D$07',
 'HML32D$08',
 'HML32D$09',
 'HML32D$10',
 'HML32D$11',
 'HML32D$12',
 'HML32D$13',
 'HML32D$14',
 'HML32D$15',
 'HML32D$16',
 'HML32D$17',
 'HML32D$18',
 'HML32D$19',
 'HML32D$20',
 'HML32D$21',
 'HML32D$22',
 'HML32D$23',
 'HML32D$24',
 'HML32D$25',
 'HML32D$26',
 'HML32D$27',
 'HML32D$28',
 'HML32D$29',
 'HML32D$30',
 'HML32D$31',
 'HML32D$32',
 'HML32D$33',
 'HML32D$34',
 'HML32D$35',
 'HML32D$36',
 'HML32D$37',
 'HML32D$38',
 'HML32D$39',
 'HML32D$40',
 'HML32D$41',
 'HML32D$42',
 'HML32D$43',
 'HML32D$44',
 'HML32D$45',
 'HML32D$46',
 'HML32E$01',
 'HML32E$02',
 'HML32E$03',
 'HML32E$04',
 'HML32E$05',
 'HML32E$06',
 'HML32E$07',
 'HML32E$08',
 'HML32E$09',
 'HML32E$10',
 'HML32E$11',
 'HML32E$12',
 'HML32E$13',
 'HML32E$14',
 'HML32E$15',
 'HML32E$16',
 'HML32E$17',
 'HML32E$18',
 'HML32E$19',
 'HML32E$20',
 'HML32E$21',
 'HML32E$22',
 'HML32E$23',
 'HML32E$24',
 'HML32E$25',
 'HML32E$26',
 'HML32E$27',
 'HML32E$28',
 'HML32E$29',
 'HML32E$30',
 'HML32E$31',
 'HML32E$32',
 'HML32E$33',
 'HML32E$34',
 'HML32E$35',
 'HML32E$36',
 'HML32E$37',
 'HML32E$38',
 'HML32E$39',
 'HML32E$40',
 'HML32E$41',
 'HML32E$42',
 'HML32E$43',
 'HML32E$44',
 'HML32E$45',
 'HML32E$46',
 'HML32F$01',
 'HML32F$02',
 'HML32F$03',
 'HML32F$04',
 'HML32F$05',
 'HML32F$06',
 'HML32F$07',
 'HML32F$08',
 'HML32F$09',
 'HML32F$10',
 'HML32F$11',
 'HML32F$12',
 'HML32F$13',
 'HML32F$14',
 'HML32F$15',
 'HML32F$16',
 'HML32F$17',
 'HML32F$18',
 'HML32F$19',
 'HML32F$20',
 'HML32F$21',
 'HML32F$22',
 'HML32F$23',
 'HML32F$24',
 'HML32F$25',
 'HML32F$26',
 'HML32F$27',
 'HML32F$28',
 'HML32F$29',
 'HML32F$30',
 'HML32F$31',
 'HML32F$32',
 'HML32F$33',
 'HML32F$34',
 'HML32F$35',
 'HML32F$36',
 'HML32F$37',
 'HML32F$38',
 'HML32F$39',
 'HML32F$40',
 'HML32F$41',
 'HML32F$42',
 'HML32F$43',
 ...]

In [68]:
for var in [
    "HML1",
    "HML1A",
    "HML2",
    "HML21$1",
    "HML22$1",
    "HML23$1",
    "HML30$01",
    "HML31$01",
    "HML32$01",
    "HML32A$01",
    "HML32B$01"
]:
    
    print("\n")
    print(var)
    print(hrmeta2021.column_names_to_labels.get(var))

HML1
Number of mosquito bed nets


HML1A
Number of mosquito bed nets with specific information


HML2
Number of children under mosquito bed net previous night


HML21$1
Someone slept under this net last night


HML22$1
Obtained net from campaign, antenatal or immunization visit


HML23$1
Place where net was obtained


HML30$01
Line number of parent/caretaker (for malaria testing)


HML31$01
Read consent statement for malaria


HML32$01
Final result of malaria from blood smear test


HML32A$01
Presence of species: falciparum (Pf)


HML32B$01
Presence of species: malariae (Pm)

In [69]:
rows = []

for var in hrmeta2021.column_names:

    if var.startswith("HML"):

        rows.append({
            "Variable": var,
            "Label": hrmeta2021.column_names_to_labels.get(var)
        })

pd.DataFrame(rows).to_excel(
    "HML_Variable_Labels_2021.xlsx",
    index=False
)

In [70]:
rows = []

for var in hrmeta2021.column_names:

    if var.startswith("HML"):

        label = hrmeta2021.column_names_to_labels.get(var)

        label_set = hrmeta2021.variable_to_label.get(var)

        codes = hrmeta2021.value_labels.get(label_set)

        rows.append({
            "Variable": var,
            "Label": label,
            "Codes": str(codes)
        })

hml_dict = pd.DataFrame(rows)

hml_dict.to_excel(
    "Household_HML_Dictionary_2021.xlsx",
    index=False
)

print(hml_dict.head())

   Variable                                              Label  \
0      HML1                        Number of mosquito bed nets
1     HML1A  Number of mosquito bed nets with specific info...
2      HML2  Number of children under mosquito bed net prev...
3  HMLIDX$1                Mosquito Bed Net Designation Number
4  HMLIDX$2                Mosquito Bed Net Designation Number

                  Codes
0  {98.0: "Don't know"}
1                  None
2                  None
3                  None
4                  None

In [72]:
rows = []

for var in hrmeta2015.column_names:

    if var.startswith("HML"):

        label = hrmeta2015.column_names_to_labels.get(var)

        label_set = hrmeta2015.variable_to_label.get(var)

        codes = hrmeta2015.value_labels.get(label_set)

        rows.append({
            "Variable": var,
            "Label": label,
            "Codes": str(codes)
        })

hml_dict_2015 = pd.DataFrame(rows)

hml_dict_2015.to_excel(
    "Household_HML_Dictionary_2015.xlsx",
    index=False
)

In [73]:
rows = []

for var in hrmeta2010.column_names:

    if var.startswith("HML"):

        label = hrmeta2010.column_names_to_labels.get(var)

        label_set = hrmeta2010.variable_to_label.get(var)

        codes = hrmeta2010.value_labels.get(label_set)

        rows.append({
            "Variable": var,
            "Label": label,
            "Codes": str(codes)
        })

hml_dict_2010 = pd.DataFrame(rows)

hml_dict_2010.to_excel(
    "Household_HML_Dictionary_2010.xlsx",
    index=False
)

In [74]:
hml2010 = set(
    hml_dict_2010["Variable"]
)

hml2015 = set(
    hml_dict_2015["Variable"]
)

hml2021 = set(
    hml_dict["Variable"]
)

common_hml = (
    hml2010 &
    hml2015 &
    hml2021
)

print(len(common_hml))

print(sorted(common_hml))

805
['HML1', 'HML10$1', 'HML10$2', 'HML10$3', 'HML10$4', 'HML10$5', 'HML10$6', 'HML10$7', 'HML11$1', 'HML11$2', 'HML11$3', 'HML11$4', 'HML11$5', 'HML11$6', 'HML11$7', 'HML12$01', 'HML12$02', 'HML12$03', 'HML12$04', 'HML12$05', 'HML12$06', 'HML12$07', 'HML12$08', 'HML12$09', 'HML12$10', 'HML12$11', 'HML12$12', 'HML12$13', 'HML12$14', 'HML12$15', 'HML12$16', 'HML12$17', 'HML12$18', 'HML12$19', 'HML12$20', 'HML12$21', 'HML12$22', 'HML12$23', 'HML12$24', 'HML12$25', 'HML12$26', 'HML12$27', 'HML12$28', 'HML12$29', 'HML12$30', 'HML13$01', 'HML13$02', 'HML13$03', 'HML13$04', 'HML13$05', 'HML13$06', 'HML13$07', 'HML13$08', 'HML13$09', 'HML13$10', 'HML13$11', 'HML13$12', 'HML13$13', 'HML13$14', 'HML13$15', 'HML13$16', 'HML13$17', 'HML13$18', 'HML13$19', 'HML13$20', 'HML13$21', 'HML13$22', 'HML13$23', 'HML13$24', 'HML13$25', 'HML13$26', 'HML13$27', 'HML13$28', 'HML13$29', 'HML13$30', 'HML14$01', 'HML14$02', 'HML14$03', 'HML14$04', 'HML14$05', 'HML14$06', 'HML14$07', 'HML14$08', 'HML14$09', 'HML14$10', 'HML14$11', 'HML14$12', 'HML14$13', 'HML14$14', 'HML14$15', 'HML14$16', 'HML14$17', 'HML14$18', 'HML14$19', 'HML14$20', 'HML14$21', 'HML14$22', 'HML14$23', 'HML14$24', 'HML14$25', 'HML14$26', 'HML14$27', 'HML14$28', 'HML14$29', 'HML14$30', 'HML15$01', 'HML15$02', 'HML15$03', 'HML15$04', 'HML15$05', 'HML15$06', 'HML15$07', 'HML15$08', 'HML15$09', 'HML15$10', 'HML15$11', 'HML15$12', 'HML15$13', 'HML15$14', 'HML15$15', 'HML15$16', 'HML15$17', 'HML15$18', 'HML15$19', 'HML15$20', 'HML15$21', 'HML15$22', 'HML15$23', 'HML15$24', 'HML15$25', 'HML15$26', 'HML15$27', 'HML15$28', 'HML15$29', 'HML15$30', 'HML16$01', 'HML16$02', 'HML16$03', 'HML16$04', 'HML16$05', 'HML16$06', 'HML16$07', 'HML16$08', 'HML16$09', 'HML16$10', 'HML16$11', 'HML16$12', 'HML16$13', 'HML16$14', 'HML16$15', 'HML16$16', 'HML16$17', 'HML16$18', 'HML16$19', 'HML16$20', 'HML16$21', 'HML16$22', 'HML16$23', 'HML16$24', 'HML16$25', 'HML16$26', 'HML16$27', 'HML16$28', 'HML16$29', 'HML16$30', 'HML16A$01', 'HML16A$02', 'HML16A$03', 'HML16A$04', 'HML16A$05', 'HML16A$06', 'HML16A$07', 'HML16A$08', 'HML16A$09', 'HML16A$10', 'HML16A$11', 'HML16A$12', 'HML16A$13', 'HML16A$14', 'HML16A$15', 'HML16A$16', 'HML16A$17', 'HML16A$18', 'HML16A$19', 'HML16A$20', 'HML16A$21', 'HML16A$22', 'HML16A$23', 'HML16A$24', 'HML16A$25', 'HML16A$26', 'HML16A$27', 'HML16A$28', 'HML16A$29', 'HML16A$30', 'HML17$01', 'HML17$02', 'HML17$03', 'HML17$04', 'HML17$05', 'HML17$06', 'HML17$07', 'HML17$08', 'HML17$09', 'HML17$10', 'HML17$11', 'HML17$12', 'HML17$13', 'HML17$14', 'HML17$15', 'HML17$16', 'HML17$17', 'HML17$18', 'HML17$19', 'HML17$20', 'HML17$21', 'HML17$22', 'HML17$23', 'HML17$24', 'HML17$25', 'HML17$26', 'HML17$27', 'HML17$28', 'HML17$29', 'HML17$30', 'HML18$01', 'HML18$02', 'HML18$03', 'HML18$04', 'HML18$05', 'HML18$06', 'HML18$07', 'HML18$08', 'HML18$09', 'HML18$10', 'HML18$11', 'HML18$12', 'HML18$13', 'HML18$14', 'HML18$15', 'HML18$16', 'HML18$17', 'HML18$18', 'HML18$19', 'HML18$20', 'HML18$21', 'HML18$22', 'HML18$23', 'HML18$24', 'HML18$25', 'HML18$26', 'HML18$27', 'HML18$28', 'HML18$29', 'HML18$30', 'HML19$01', 'HML19$02', 'HML19$03', 'HML19$04', 'HML19$05', 'HML19$06', 'HML19$07', 'HML19$08', 'HML19$09', 'HML19$10', 'HML19$11', 'HML19$12', 'HML19$13', 'HML19$14', 'HML19$15', 'HML19$16', 'HML19$17', 'HML19$18', 'HML19$19', 'HML19$20', 'HML19$21', 'HML19$22', 'HML19$23', 'HML19$24', 'HML19$25', 'HML19$26', 'HML19$27', 'HML19$28', 'HML19$29', 'HML19$30', 'HML1A', 'HML2', 'HML20$01', 'HML20$02', 'HML20$03', 'HML20$04', 'HML20$05', 'HML20$06', 'HML20$07', 'HML20$08', 'HML20$09', 'HML20$10', 'HML20$11', 'HML20$12', 'HML20$13', 'HML20$14', 'HML20$15', 'HML20$16', 'HML20$17', 'HML20$18', 'HML20$19', 'HML20$20', 'HML20$21', 'HML20$22', 'HML20$23', 'HML20$24', 'HML20$25', 'HML20$26', 'HML20$27', 'HML20$28', 'HML20$29', 'HML20$30', 'HML21$1', 'HML21$2', 'HML21$3', 'HML21$4', 'HML21$5', 'HML21$6', 'HML21$7', 'HML3$1', 'HML3$2', 'HML3$3', 'HML3$4', 'HML3$5', 'HML3$6', 'HML3$7', 'HML30$01', 'HML30$02', 'HML30$03', 'HML30$04', 'HML30$05', 'HML30$06', 'HML30$07', 'HML30$08', 'HML30$09', 'HML30$10', 'HML30$11', 'HML30$12', 'HML30$13', 'HML30$14', 'HML30$15', 'HML30$16', 'HML30$17', 'HML30$18', 'HML30$19', 'HML30$20', 'HML30$21', 'HML30$22', 'HML30$23', 'HML30$24', 'HML30$25', 'HML30$26', 'HML30$27', 'HML30$28', 'HML30$29', 'HML30$30', 'HML31$01', 'HML31$02', 'HML31$03', 'HML31$04', 'HML31$05', 'HML31$06', 'HML31$07', 'HML31$08', 'HML31$09', 'HML31$10', 'HML31$11', 'HML31$12', 'HML31$13', 'HML31$14', 'HML31$15', 'HML31$16', 'HML31$17', 'HML31$18', 'HML31$19', 'HML31$20', 'HML31$21', 'HML31$22', 'HML31$23', 'HML31$24', 'HML31$25', 'HML31$26', 'HML31$27', 'HML31$28', 'HML31$29', 'HML31$30', 'HML32$01', 'HML32$02', 'HML32$03', 'HML32$04', 'HML32$05', 'HML32$06', 'HML32$07', 'HML32$08', 'HML32$09', 'HML32$10', 'HML32$11', 'HML32$12', 'HML32$13', 'HML32$14', 'HML32$15', 'HML32$16', 'HML32$17', 'HML32$18', 'HML32$19', 'HML32$20', 'HML32$21', 'HML32$22', 'HML32$23', 'HML32$24', 'HML32$25', 'HML32$26', 'HML32$27', 'HML32$28', 'HML32$29', 'HML32$30', 'HML32A$01', 'HML32A$02', 'HML32A$03', 'HML32A$04', 'HML32A$05', 'HML32A$06', 'HML32A$07', 'HML32A$08', 'HML32A$09', 'HML32A$10', 'HML32A$11', 'HML32A$12', 'HML32A$13', 'HML32A$14', 'HML32A$15', 'HML32A$16', 'HML32A$17', 'HML32A$18', 'HML32A$19', 'HML32A$20', 'HML32A$21', 'HML32A$22', 'HML32A$23', 'HML32A$24', 'HML32A$25', 'HML32A$26', 'HML32A$27', 'HML32A$28', 'HML32A$29', 'HML32A$30', 'HML32B$01', 'HML32B$02', 'HML32B$03', 'HML32B$04', 'HML32B$05', 'HML32B$06', 'HML32B$07', 'HML32B$08', 'HML32B$09', 'HML32B$10', 'HML32B$11', 'HML32B$12', 'HML32B$13', 'HML32B$14', 'HML32B$15', 'HML32B$16', 'HML32B$17', 'HML32B$18', 'HML32B$19', 'HML32B$20', 'HML32B$21', 'HML32B$22', 'HML32B$23', 'HML32B$24', 'HML32B$25', 'HML32B$26', 'HML32B$27', 'HML32B$28', 'HML32B$29', 'HML32B$30', 'HML32C$01', 'HML32C$02', 'HML32C$03', 'HML32C$04', 'HML32C$05', 'HML32C$06', 'HML32C$07', 'HML32C$08', 'HML32C$09', 'HML32C$10', 'HML32C$11', 'HML32C$12', 'HML32C$13', 'HML32C$14', 'HML32C$15', 'HML32C$16', 'HML32C$17', 'HML32C$18', 'HML32C$19', 'HML32C$20', 'HML32C$21', 'HML32C$22', 'HML32C$23', 'HML32C$24', 'HML32C$25', 'HML32C$26', 'HML32C$27', 'HML32C$28', 'HML32C$29', 'HML32C$30', 'HML32D$01', 'HML32D$02', 'HML32D$03', 'HML32D$04', 'HML32D$05', 'HML32D$06', 'HML32D$07', 'HML32D$08', 'HML32D$09', 'HML32D$10', 'HML32D$11', 'HML32D$12', 'HML32D$13', 'HML32D$14', 'HML32D$15', 'HML32D$16', 'HML32D$17', 'HML32D$18', 'HML32D$19', 'HML32D$20', 'HML32D$21', 'HML32D$22', 'HML32D$23', 'HML32D$24', 'HML32D$25', 'HML32D$26', 'HML32D$27', 'HML32D$28', 'HML32D$29', 'HML32D$30', 'HML32E$01', 'HML32E$02', 'HML32E$03', 'HML32E$04', 'HML32E$05', 'HML32E$06', 'HML32E$07', 'HML32E$08', 'HML32E$09', 'HML32E$10', 'HML32E$11', 'HML32E$12', 'HML32E$13', 'HML32E$14', 'HML32E$15', 'HML32E$16', 'HML32E$17', 'HML32E$18', 'HML32E$19', 'HML32E$20', 'HML32E$21', 'HML32E$22', 'HML32E$23', 'HML32E$24', 'HML32E$25', 'HML32E$26', 'HML32E$27', 'HML32E$28', 'HML32E$29', 'HML32E$30', 'HML32F$01', 'HML32F$02', 'HML32F$03', 'HML32F$04', 'HML32F$05', 'HML32F$06', 'HML32F$07', 'HML32F$08', 'HML32F$09', 'HML32F$10', 'HML32F$11', 'HML32F$12', 'HML32F$13', 'HML32F$14', 'HML32F$15', 'HML32F$16', 'HML32F$17', 'HML32F$18', 'HML32F$19', 'HML32F$20', 'HML32F$21', 'HML32F$22', 'HML32F$23', 'HML32F$24', 'HML32F$25', 'HML32F$26', 'HML32F$27', 'HML32F$28', 'HML32F$29', 'HML32F$30', 'HML32G$01', 'HML32G$02', 'HML32G$03', 'HML32G$04', 'HML32G$05', 'HML32G$06', 'HML32G$07', 'HML32G$08', 'HML32G$09', 'HML32G$10', 'HML32G$11', 'HML32G$12', 'HML32G$13', 'HML32G$14', 'HML32G$15', 'HML32G$16', 'HML32G$17', 'HML32G$18', 'HML32G$19', 'HML32G$20', 'HML32G$21', 'HML32G$22', 'HML32G$23', 'HML32G$24', 'HML32G$25', 'HML32G$26', 'HML32G$27', 'HML32G$28', 'HML32G$29', 'HML32G$30', 'HML33$01', 'HML33$02', 'HML33$03', 'HML33$04', 'HML33$05', 'HML33$06', 'HML33$07', 'HML33$08', 'HML33$09', 'HML33$10', 'HML33$11', 'HML33$12', 'HML33$13', 'HML33$14', 'HML33$15', 'HML33$16', 'HML33$17', 'HML33$18', 'HML33$19', 'HML33$20', 'HML33$21', 'HML33$22', 'HML33$23', 'HML33$24', 'HML33$25', 'HML33$26', 'HML33$27', 'HML33$28', 'HML33$29', 'HML33$30', 'HML34$01', 'HML34$02', 'HML34$03', 'HML34$04', 'HML34$05', 'HML34$06', 'HML34$07', 'HML34$08', 'HML34$09', 'HML34$10', 'HML34$11', 'HML34$12', 'HML34$13', 'HML34$14', 'HML34$15', 'HML34$16', 'HML34$17', 'HML34$18', 'HML34$19', 'HML34$20', 'HML34$21', 'HML34$22', 'HML34$23', 'HML34$24', 'HML34$25', 'HML34$26', 'HML34$27', 'HML34$28', 'HML34$29', 'HML34$30', 'HML35$01', 'HML35$02', 'HML35$03', 'HML35$04', 'HML35$05', 'HML35$06', 'HML35$07', 'HML35$08', 'HML35$09', 'HML35$10', 'HML35$11', 'HML35$12', 'HML35$13', 'HML35$14', 'HML35$15', 'HML35$16', 'HML35$17', 'HML35$18', 'HML35$19', 'HML35$20', 'HML35$21', 'HML35$22', 'HML35$23', 'HML35$24', 'HML35$25', 'HML35$26', 'HML35$27', 'HML35$28', 'HML35$29', 'HML35$30', 'HML4$1', 'HML4$2', 'HML4$3', 'HML4$4', 'HML4$5', 'HML4$6', 'HML4$7', 'HML5$1', 'HML5$2', 'HML5$3', 'HML5$4', 'HML5$5', 'HML5$6', 'HML5$7', 'HML6$1', 'HML6$2', 'HML6$3', 'HML6$4', 'HML6$5', 'HML6$6', 'HML6$7', 'HML7$1', 'HML7$2', 'HML7$3', 'HML7$4', 'HML7$5', 'HML7$6', 'HML7$7', 'HML8$1', 'HML8$2', 'HML8$3', 'HML8$4', 'HML8$5', 'HML8$6', 'HML8$7', 'HML9$1', 'HML9$2', 'HML9$3', 'HML9$4', 'HML9$5', 'HML9$6', 'HML9$7', 'HMLA$1', 'HMLA$2', 'HMLA$3', 'HMLA$4', 'HMLA$5', 'HMLA$6', 'HMLA$7', 'HMLB$1', 'HMLB$2', 'HMLB$3', 'HMLB$4', 'HMLB$5', 'HMLB$6', 'HMLB$7', 'HMLC$1', 'HMLC$2', 'HMLC$3', 'HMLC$4', 'HMLC$5', 'HMLC$6', 'HMLC$7', 'HMLD$1', 'HMLD$2', 'HMLD$3', 'HMLD$4', 'HMLD$5', 'HMLD$6', 'HMLD$7', 'HMLE$1', 'HMLE$2', 'HMLE$3', 'HMLE$4', 'HMLE$5', 'HMLE$6', 'HMLE$7', 'HMLIDX$1', 'HMLIDX$2', 'HMLIDX$3', 'HMLIDX$4', 'HMLIDX$5', 'HMLIDX$6', 'HMLIDX$7']

In [75]:
roots = []

for var in hrmeta2021.column_names:

    if var.startswith("HML"):

        root = var.split("$")[0]

        roots.append(root)

roots = sorted(list(set(roots)))

print(len(roots))

print(roots)

61
['HML1', 'HML10', 'HML11', 'HML12', 'HML13', 'HML14', 'HML15', 'HML16', 'HML16A', 'HML17', 'HML18', 'HML19', 'HML1A', 'HML2', 'HML20', 'HML21', 'HML22', 'HML23', 'HML3', 'HML30', 'HML31', 'HML32', 'HML32A', 'HML32B', 'HML32C', 'HML32D', 'HML32E', 'HML32F', 'HML32G', 'HML33', 'HML34', 'HML35', 'HML36', 'HML37A', 'HML37B', 'HML37C', 'HML37D', 'HML37E', 'HML37F', 'HML37G', 'HML37H', 'HML37I', 'HML37J', 'HML37K', 'HML37L', 'HML37M', 'HML38', 'HML39', 'HML4', 'HML40', 'HML5', 'HML6', 'HML7', 'HML8', 'HML9', 'HMLA', 'HMLB', 'HMLC', 'HMLD', 'HMLE', 'HMLIDX']

In [77]:
rows = []

for var in roots:

    rows.append({
        "Variable": var,
        "Label": hrmeta2021.column_names_to_labels.get(var)
    })

pd.DataFrame(rows).to_excel(
    "HML_Root_Variables_2021.xlsx",
    index=False
)

In [76]:
for var in roots:

    print("\n")
    print(var)
    print(hrmeta2021.column_names_to_labels.get(var))

HML1
Number of mosquito bed nets


HML10
None


HML11
None


HML12
None


HML13
None


HML14
None


HML15
None


HML16
None


HML16A
None


HML17
None


HML18
None


HML19
None


HML1A
Number of mosquito bed nets with specific information


HML2
Number of children under mosquito bed net previous night


HML20
None


HML21
None


HML22
None


HML23
None


HML3
None


HML30
None


HML31
None


HML32
None


HML32A
None


HML32B
None


HML32C
None


HML32D
None


HML32E
None


HML32F
None


HML32G
None


HML33
None


HML34
None


HML35
None


HML36
None


HML37A
None


HML37B
None


HML37C
None


HML37D
None


HML37E
None


HML37F
None


HML37G
None


HML37H
None


HML37I
None


HML37J
None


HML37K
None


HML37L
None


HML37M
None


HML38
None


HML39
None


HML4
None


HML40
None


HML5
None


HML6
None


HML7
None


HML8
None


HML9
None


HMLA
None


HMLB
None


HMLC
None


HMLD
None


HMLE
None


HMLIDX
None

In [78]:
print(len(roots))
print(roots)

61
['HML1', 'HML10', 'HML11', 'HML12', 'HML13', 'HML14', 'HML15', 'HML16', 'HML16A', 'HML17', 'HML18', 'HML19', 'HML1A', 'HML2', 'HML20', 'HML21', 'HML22', 'HML23', 'HML3', 'HML30', 'HML31', 'HML32', 'HML32A', 'HML32B', 'HML32C', 'HML32D', 'HML32E', 'HML32F', 'HML32G', 'HML33', 'HML34', 'HML35', 'HML36', 'HML37A', 'HML37B', 'HML37C', 'HML37D', 'HML37E', 'HML37F', 'HML37G', 'HML37H', 'HML37I', 'HML37J', 'HML37K', 'HML37L', 'HML37M', 'HML38', 'HML39', 'HML4', 'HML40', 'HML5', 'HML6', 'HML7', 'HML8', 'HML9', 'HMLA', 'HMLB', 'HMLC', 'HMLD', 'HMLE', 'HMLIDX']

In [80]:
for var in [
    "HML10$1",
    "HML11$1",
    "HML12$01",
    "HML13$01",
    "HML14$01",
    "HML15$01",
    "HML16$01",
    "HML17$01",
    "HML18$01",
    "HML19$01",
    "HML20$01",
    "HML21$1",
    "HML30$01",
    "HML31$01",
    "HML32$01",
    "HML32A$01",
    "HML32B$01",
    "HML33$01",
    "HML34$01",
    "HML35$01"
]:
    
    print("\n====================")
    print(var)
    print("Label:", hrmeta2021.column_names_to_labels.get(var))

    label_set = hrmeta2021.variable_to_label.get(var)

    print("Label Set:", label_set)

    if label_set:
        print(
            "Codes:",
            hrmeta2021.value_labels.get(label_set)
        )

====================
HML10$1
Label: Insecticide-Treated Net (ITN)
Label Set: labels685
Codes: {0.0: "No, don't know", 1.0: 'Yes'}

====================
HML11$1
Label: Number of persons who slept under this net
Label Set: labels692
Codes: {5.0: '5+'}

====================
HML12$01
Label: Type of Mosquito Bed Net(s) person slept under last night
Label Set: labels734
Codes: {0.0: 'Did not sleep under a net', 1.0: 'Only treated (ITN) nets', 2.0: 'Both treated (ITN) and untreated nets', 3.0: 'Only untreated nets'}

====================
HML13$01
Label: Net Designation Number (HMLIDX) for 1st net person slept under last night
Label Set: labels780
Codes: {0.0: 'Did not sleep under net'}

====================
HML14$01
Label: Net Designation Number (HMLIDX) for 2nd net person slept under last night
Label Set: None

====================
HML15$01
Label: Net Designation Number (HMLIDX) for 3rd net person slept under last night
Label Set: None

====================
HML16$01
Label: Corrected age from Individual file
Label Set: labels826
Codes: {97.0: '97+', 98.0: "Don't know"}

====================
HML17$01
Label: Flag for age from Individual file
Label Set: labels872
Codes: {0.0: 'No data from Individual file', 1.0: 'Month and year - information complete', 2.0: 'Month and age - year imputed', 3.0: 'Year and age - month imputed', 4.0: 'Year and age - year ignored', 5.0: 'Year - age/month imputed', 6.0: 'Age - year/month imputed', 7.0: 'Month - age/year imputed', 8.0: 'None - all imputed'}

====================
HML18$01
Label: Pregnancy status from Individual file
Label Set: labels918
Codes: {0.0: "Not pregnant, don't know", 1.0: 'Pregnant'}

====================
HML19$01
Label: Person slept under an ever-treated net
Label Set: labels964
Codes: {0.0: 'No', 1.0: 'Yes'}

====================
HML20$01
Label: Person slept under an LLIN net
Label Set: labels1010
Codes: {0.0: 'No', 1.0: 'Yes'}

====================
HML21$1
Label: Someone slept under this net last night
Label Set: labels699
Codes: {0.0: 'No', 1.0: 'Yes', 8.0: "Not sure (Don't know)"}

====================
HML30$01
Label: Line number of parent/caretaker (for malaria testing)
Label Set: labels1056
Codes: {0.0: 'Not in household'}

====================
HML31$01
Label: Read consent statement for malaria
Label Set: labels1102
Codes: {1.0: 'Granted', 2.0: 'Parent/other responsible refused', 3.0: 'Respondent refused', 4.0: 'Adult/parent not present', 5.0: 'Minor not present'}

====================
HML32$01
Label: Final result of malaria from blood smear test
Label Set: labels1148
Codes: {0.0: 'Negative', 1.0: 'Positive', 6.0: 'Test undetermined', 7.0: 'Sample not found in lab database'}

====================
HML32A$01
Label: Presence of species: falciparum (Pf)
Label Set: labels1194
Codes: {0.0: 'No', 1.0: 'Yes'}

====================
HML32B$01
Label: Presence of species: malariae (Pm)
Label Set: labels1240
Codes: {0.0: 'No', 1.0: 'Yes'}

====================
HML33$01
Label: Result of malaria measurement
Label Set: labels1516
Codes: {0.0: 'Measured', 3.0: 'Not present', 4.0: 'Refused', 6.0: 'Other'}

====================
HML34$01
Label: Bar code for blood smear sample
Label Set: labels1562
Codes: {'?': 'Missing', '99993': 'Sample damaged/insufficient/not found in lab', '99994': 'Not present', '99995': 'Refused', '99996': 'Other'}

====================
HML35$01
Label: Result of malaria rapid test
Label Set: labels1608
Codes: {0.0: 'Negative', 1.0: 'Positive', 3.0: 'Not present', 4.0: 'Refused', 6.0: 'Other'}

In [81]:
target_vars = [
    'HV024',
    'HV025',
    'HV270',
    'HML12$01',
    'HML16$01',
    'HML18$01',
    'HML19$01',
    'HML20$01',
    'HML32$01',
    'HML35$01'
]

for var in target_vars:

    print(
        var,
        var in hr2010.columns,
        var in hr2015.columns,
        var in hr2021.columns
    )

HV024 True True True
HV025 True True True
HV270 True True True
HML12$01 True True True
HML16$01 True True True
HML18$01 True True True
HML19$01 True True True
HML20$01 True True True
HML32$01 True True True
HML35$01 True True True

In [82]:
vars_D = [
    'HV024',
    'HV025',
    'HV270',
    'HML12$01',
    'HML16$01',
    'HML18$01',
    'HML19$01',
    'HML20$01',
    'HML32$01',
    'HML35$01',
    'HML32A$01',
    'HML32B$01'
]

D2010 = hr2010[vars_D].copy()

D2010["survey_year"] = 2010

D2015 = hr2015[vars_D].copy()

D2015["survey_year"] = 2015

D2021 = hr2021[vars_D].copy()

D2021["survey_year"] = 2021

Dataset_D = pd.concat(
    [D2010, D2015, D2021],
    ignore_index=True
)

Dataset_D.shape

(27367, 13)

In [83]:
Dataset_D = Dataset_D.rename(columns={

    'HV024':'state',

    'HV025':'residence',

    'HV270':'wealth_index',

    'HML12$01':'net_type',

    'HML16$01':'age',

    'HML18$01':'pregnancy_status',

    'HML19$01':'slept_under_treated_net',

    'HML20$01':'slept_under_llin',

    'HML32$01':'blood_smear_result',

    'HML35$01':'rapid_test_result',

    'HML32A$01':'pfalciparum',

    'HML32B$01':'pmalariae'

})

dictionary_D = pd.DataFrame({

    "Variable":[
        "state",
        "residence",
        "wealth_index",
        "net_type",
        "age",
        "pregnancy_status",
        "slept_under_treated_net",
        "slept_under_llin",
        "blood_smear_result",
        "rapid_test_result",
        "pfalciparum",
        "pmalariae",
        "survey_year"
    ],

    "Description":[
        "State of residence",
        "Urban or rural",
        "Household wealth category",
        "Type of mosquito net used",
        "Age",
        "Pregnancy status",
        "Slept under treated net",
        "Slept under LLIN",
        "Blood smear malaria result",
        "Rapid diagnostic malaria result",
        "Presence of Plasmodium falciparum",
        "Presence of Plasmodium malariae",
        "Survey year"
    ]

})

In [84]:
project_notes = pd.DataFrame({

    "Notes":[

        "Dataset D combines Nigeria MIS 2010, 2015 and 2021 household malaria datasets.",

        "Blood smear result is the primary machine learning target variable.",

        "Rapid diagnostic test result is a secondary target variable.",

        "Dataset intended for malaria risk prediction modelling."

    ]

})

In [85]:
with pd.ExcelWriter(
    "Dataset_D_Malaria_Testing_and_Risk_Prediction.xlsx"
) as writer:

    Dataset_D.to_excel(
        writer,
        sheet_name="Data",
        index=False
    )

    dictionary_D.to_excel(
        writer,
        sheet_name="Variable_Dictionary",
        index=False
    )

    project_notes.to_excel(
        writer,
        sheet_name="Project_Notes",
        index=False
    )

In [86]:
Dataset_D[
    [
        'blood_smear_result',
        'rapid_test_result',
        'pfalciparum',
        'pmalariae'
    ]
].head(20)

    blood_smear_result  rapid_test_result  pfalciparum  pmalariae
0                  NaN                NaN          NaN        NaN
1                  NaN                NaN          NaN        NaN
2                  NaN                NaN          NaN        NaN
3                  NaN                NaN          NaN        NaN
4                  NaN                NaN          NaN        NaN
5                  NaN                NaN          NaN        NaN
6                  NaN                NaN          NaN        NaN
7                  NaN                NaN          NaN        NaN
8                  NaN                NaN          NaN        NaN
9                  NaN                NaN          NaN        NaN
10                 NaN                NaN          NaN        NaN
11                 NaN                NaN          NaN        NaN
12                 NaN                NaN          NaN        NaN
13                 NaN                NaN          NaN        NaN
14                 NaN                NaN          NaN        NaN
15                 NaN                NaN          NaN        NaN
16                 NaN                NaN          NaN        NaN
17                 NaN                NaN          NaN        NaN
18                 NaN                NaN          NaN        NaN
19                 NaN                NaN          NaN        NaN

In [87]:
Dataset_D[
    [
        'blood_smear_result',
        'rapid_test_result',
        'pfalciparum',
        'pmalariae'
    ]
].isnull().sum()

blood_smear_result    27367
rapid_test_result     27367
pfalciparum           27367
pmalariae             27367
dtype: int64

In [88]:
hr2021[
    [
        'HML32$01',
        'HML35$01',
        'HML32A$01',
        'HML32B$01'
    ]
].head(20)

    HML32$01  HML35$01  HML32A$01  HML32B$01
0        NaN       NaN        NaN        NaN
1        NaN       NaN        NaN        NaN
2        NaN       NaN        NaN        NaN
3        NaN       NaN        NaN        NaN
4        NaN       NaN        NaN        NaN
5        NaN       NaN        NaN        NaN
6        NaN       NaN        NaN        NaN
7        NaN       NaN        NaN        NaN
8        NaN       NaN        NaN        NaN
9        NaN       NaN        NaN        NaN
10       NaN       NaN        NaN        NaN
11       NaN       NaN        NaN        NaN
12       NaN       NaN        NaN        NaN
13       NaN       NaN        NaN        NaN
14       NaN       NaN        NaN        NaN
15       NaN       NaN        NaN        NaN
16       NaN       NaN        NaN        NaN
17       NaN       NaN        NaN        NaN
18       NaN       NaN        NaN        NaN
19       NaN       NaN        NaN        NaN

In [89]:
hr2021[
    [
        'HML32$01',
        'HML35$01',
        'HML32A$01',
        'HML32B$01'
    ]
].describe(include='all')

       HML32$01  HML35$01  HML32A$01  HML32B$01
count       0.0       0.0        0.0        0.0
mean        NaN       NaN        NaN        NaN
std         NaN       NaN        NaN        NaN
min         NaN       NaN        NaN        NaN
25%         NaN       NaN        NaN        NaN
50%         NaN       NaN        NaN        NaN
75%         NaN       NaN        NaN        NaN
max         NaN       NaN        NaN        NaN

In [90]:
hr2021['HML32$01'].value_counts(dropna=False)

HML32$01
NaN    13727
Name: count, dtype: int64

In [91]:
hr2021['HML35$01'].value_counts(dropna=False)

HML35$01
NaN    13727
Name: count, dtype: int64

In [92]:
hr2021['HML32$01'].notna().sum()

0

In [93]:
hr2021['HML32$02'].notna().sum()

163

In [94]:
hr2021['HML32$03'].notna().sum()

1695

In [95]:
hr2021['HML32$04'].notna().sum()

1841

In [101]:
for i in range(1,31):

    col = f'HML32${i:02d}'

    if col in hr2021.columns:

        print(
            col,
            hr2021[col].notna().sum()
        )

HML32$01 0
HML32$02 163
HML32$03 1695
HML32$04 1841
HML32$05 1645
HML32$06 1360
HML32$07 1054
HML32$08 781
HML32$09 534
HML32$10 368
HML32$11 343
HML32$12 231
HML32$13 169
HML32$14 121
HML32$15 90
HML32$16 66
HML32$17 38
HML32$18 37
HML32$19 26
HML32$20 23
HML32$21 21
HML32$22 16
HML32$23 4
HML32$24 3
HML32$25 3
HML32$26 3
HML32$27 1
HML32$28 2
HML32$29 2
HML32$30 2

In [97]:
for i in range(1,31):

    col = f'HML35${i:02d}'

    if col in hr2021.columns:

        print(
            col,
            hr2021[col].notna().sum()
        )

HML35$01 0
HML35$02 167
HML35$03 1794
HML35$04 1915
HML35$05 1709
HML35$06 1415
HML35$07 1105
HML35$08 807
HML35$09 564
HML35$10 389
HML35$11 351
HML35$12 237
HML35$13 176
HML35$14 124
HML35$15 93
HML35$16 67
HML35$17 39
HML35$18 37
HML35$19 28
HML35$20 24
HML35$21 21
HML35$22 16
HML35$23 4
HML35$24 3
HML35$25 3
HML35$26 4
HML35$27 1
HML35$28 3
HML35$29 2
HML35$30 2

In [100]:
for var in ['HML32$01','HML35$01']:

    print("\n", var)

    print(
        hrmeta2010.column_names_to_labels.get(var)
    )

    print(
        hrmeta2015.column_names_to_labels.get(var)
    )

 HML32$01
Final result of malaria from blood smear test
Final result of malaria from blood smear test

 HML35$01
Result of malaria rapid test
Result of malaria rapid test

In [102]:
for var in [
    'HML32$02',
    'HML35$02',
    'HML32A$02',
    'HML32B$02'
]:
    print(var)

    print(
        hrmeta2021.column_names_to_labels.get(var)
    )

    print(
        hrmeta2021.variable_to_label.get(var)
    )

    print(
        hrmeta2021.value_labels.get(
            hrmeta2021.variable_to_label.get(var)
        )
    )

    print("="*50)

HML32$02
Final result of malaria from blood smear test
labels1149
{0.0: 'Negative', 1.0: 'Positive', 6.0: 'Test undetermined', 7.0: 'Sample not found in lab database'}
==================================================
HML35$02
Result of malaria rapid test
labels1609
{0.0: 'Negative', 1.0: 'Positive', 3.0: 'Not present', 4.0: 'Refused', 6.0: 'Other'}
==================================================
HML32A$02
Presence of species: falciparum (Pf)
labels1195
{0.0: 'No', 1.0: 'Yes'}
==================================================
HML32B$02
Presence of species: malariae (Pm)
labels1241
{0.0: 'No', 1.0: 'Yes'}
==================================================

In [103]:
for col in hr2010.columns:
    if "HML32" in col:
        print(col)

print("="*50)

for col in hr2015.columns:
    if "HML32" in col:
        print(col)

print("="*50)

for col in hr2021.columns:
    if "HML32" in col:
        print(col)

HML32$01
HML32$02
HML32$03
HML32$04
HML32$05
HML32$06
HML32$07
HML32$08
HML32$09
HML32$10
HML32$11
HML32$12
HML32$13
HML32$14
HML32$15
HML32$16
HML32$17
HML32$18
HML32$19
HML32$20
HML32$21
HML32$22
HML32$23
HML32$24
HML32$25
HML32$26
HML32$27
HML32$28
HML32$29
HML32$30
HML32A$01
HML32A$02
HML32A$03
HML32A$04
HML32A$05
HML32A$06
HML32A$07
HML32A$08
HML32A$09
HML32A$10
HML32A$11
HML32A$12
HML32A$13
HML32A$14
HML32A$15
HML32A$16
HML32A$17
HML32A$18
HML32A$19
HML32A$20
HML32A$21
HML32A$22
HML32A$23
HML32A$24
HML32A$25
HML32A$26
HML32A$27
HML32A$28
HML32A$29
HML32A$30
HML32B$01
HML32B$02
HML32B$03
HML32B$04
HML32B$05
HML32B$06
HML32B$07
HML32B$08
HML32B$09
HML32B$10
HML32B$11
HML32B$12
HML32B$13
HML32B$14
HML32B$15
HML32B$16
HML32B$17
HML32B$18
HML32B$19
HML32B$20
HML32B$21
HML32B$22
HML32B$23
HML32B$24
HML32B$25
HML32B$26
HML32B$27
HML32B$28
HML32B$29
HML32B$30
HML32C$01
HML32C$02
HML32C$03
HML32C$04
HML32C$05
HML32C$06
HML32C$07
HML32C$08
HML32C$09
HML32C$10
HML32C$11
HML32C$12
HML32C$13
HML32C$14
HML32C$15
HML32C$16
HML32C$17
HML32C$18
HML32C$19
HML32C$20
HML32C$21
HML32C$22
HML32C$23
HML32C$24
HML32C$25
HML32C$26
HML32C$27
HML32C$28
HML32C$29
HML32C$30
HML32D$01
HML32D$02
HML32D$03
HML32D$04
HML32D$05
HML32D$06
HML32D$07
HML32D$08
HML32D$09
HML32D$10
HML32D$11
HML32D$12
HML32D$13
HML32D$14
HML32D$15
HML32D$16
HML32D$17
HML32D$18
HML32D$19
HML32D$20
HML32D$21
HML32D$22
HML32D$23
HML32D$24
HML32D$25
HML32D$26
HML32D$27
HML32D$28
HML32D$29
HML32D$30
HML32E$01
HML32E$02
HML32E$03
HML32E$04
HML32E$05
HML32E$06
HML32E$07
HML32E$08
HML32E$09
HML32E$10
HML32E$11
HML32E$12
HML32E$13
HML32E$14
HML32E$15
HML32E$16
HML32E$17
HML32E$18
HML32E$19
HML32E$20
HML32E$21
HML32E$22
HML32E$23
HML32E$24
HML32E$25
HML32E$26
HML32E$27
HML32E$28
HML32E$29
HML32E$30
HML32F$01
HML32F$02
HML32F$03
HML32F$04
HML32F$05
HML32F$06
HML32F$07
HML32F$08
HML32F$09
HML32F$10
HML32F$11
HML32F$12
HML32F$13
HML32F$14
HML32F$15
HML32F$16
HML32F$17
HML32F$18
HML32F$19
HML32F$20
HML32F$21
HML32F$22
HML32F$23
HML32F$24
HML32F$25
HML32F$26
HML32F$27
HML32F$28
HML32F$29
HML32F$30
HML32G$01
HML32G$02
HML32G$03
HML32G$04
HML32G$05
HML32G$06
HML32G$07
HML32G$08
HML32G$09
HML32G$10
HML32G$11
HML32G$12
HML32G$13
HML32G$14
HML32G$15
HML32G$16
HML32G$17
HML32G$18
HML32G$19
HML32G$20
HML32G$21
HML32G$22
HML32G$23
HML32G$24
HML32G$25
HML32G$26
HML32G$27
HML32G$28
HML32G$29
HML32G$30
==================================================
HML32$01
HML32$02
HML32$03
HML32$04
HML32$05
HML32$06
HML32$07
HML32$08
HML32$09
HML32$10
HML32$11
HML32$12
HML32$13
HML32$14
HML32$15
HML32$16
HML32$17
HML32$18
HML32$19
HML32$20
HML32$21
HML32$22
HML32$23
HML32$24
HML32$25
HML32$26
HML32$27
HML32$28
HML32$29
HML32$30
HML32$31
HML32A$01
HML32A$02
HML32A$03
HML32A$04
HML32A$05
HML32A$06
HML32A$07
HML32A$08
HML32A$09
HML32A$10
HML32A$11
HML32A$12
HML32A$13
HML32A$14
HML32A$15
HML32A$16
HML32A$17
HML32A$18
HML32A$19
HML32A$20
HML32A$21
HML32A$22
HML32A$23
HML32A$24
HML32A$25
HML32A$26
HML32A$27
HML32A$28
HML32A$29
HML32A$30
HML32A$31
HML32B$01
HML32B$02
HML32B$03
HML32B$04
HML32B$05
HML32B$06
HML32B$07
HML32B$08
HML32B$09
HML32B$10
HML32B$11
HML32B$12
HML32B$13
HML32B$14
HML32B$15
HML32B$16
HML32B$17
HML32B$18
HML32B$19
HML32B$20
HML32B$21
HML32B$22
HML32B$23
HML32B$24
HML32B$25
HML32B$26
HML32B$27
HML32B$28
HML32B$29
HML32B$30
HML32B$31
HML32C$01
HML32C$02
HML32C$03
HML32C$04
HML32C$05
HML32C$06
HML32C$07
HML32C$08
HML32C$09
HML32C$10
HML32C$11
HML32C$12
HML32C$13
HML32C$14
HML32C$15
HML32C$16
HML32C$17
HML32C$18
HML32C$19
HML32C$20
HML32C$21
HML32C$22
HML32C$23
HML32C$24
HML32C$25
HML32C$26
HML32C$27
HML32C$28
HML32C$29
HML32C$30
HML32C$31
HML32D$01
HML32D$02
HML32D$03
HML32D$04
HML32D$05
HML32D$06
HML32D$07
HML32D$08
HML32D$09
HML32D$10
HML32D$11
HML32D$12
HML32D$13
HML32D$14
HML32D$15
HML32D$16
HML32D$17
HML32D$18
HML32D$19
HML32D$20
HML32D$21
HML32D$22
HML32D$23
HML32D$24
HML32D$25
HML32D$26
HML32D$27
HML32D$28
HML32D$29
HML32D$30
HML32D$31
HML32E$01
HML32E$02
HML32E$03
HML32E$04
HML32E$05
HML32E$06
HML32E$07
HML32E$08
HML32E$09
HML32E$10
HML32E$11
HML32E$12
HML32E$13
HML32E$14
HML32E$15
HML32E$16
HML32E$17
HML32E$18
HML32E$19
HML32E$20
HML32E$21
HML32E$22
HML32E$23
HML32E$24
HML32E$25
HML32E$26
HML32E$27
HML32E$28
HML32E$29
HML32E$30
HML32E$31
HML32F$01
HML32F$02
HML32F$03
HML32F$04
HML32F$05
HML32F$06
HML32F$07
HML32F$08
HML32F$09
HML32F$10
HML32F$11
HML32F$12
HML32F$13
HML32F$14
HML32F$15
HML32F$16
HML32F$17
HML32F$18
HML32F$19
HML32F$20
HML32F$21
HML32F$22
HML32F$23
HML32F$24
HML32F$25
HML32F$26
HML32F$27
HML32F$28
HML32F$29
HML32F$30
HML32F$31
HML32G$01
HML32G$02
HML32G$03
HML32G$04
HML32G$05
HML32G$06
HML32G$07
HML32G$08
HML32G$09
HML32G$10
HML32G$11
HML32G$12
HML32G$13
HML32G$14
HML32G$15
HML32G$16
HML32G$17
HML32G$18
HML32G$19
HML32G$20
HML32G$21
HML32G$22
HML32G$23
HML32G$24
HML32G$25
HML32G$26
HML32G$27
HML32G$28
HML32G$29
HML32G$30
HML32G$31
==================================================
HML32$01
HML32$02
HML32$03
HML32$04
HML32$05
HML32$06
HML32$07
HML32$08
HML32$09
HML32$10
HML32$11
HML32$12
HML32$13
HML32$14
HML32$15
HML32$16
HML32$17
HML32$18
HML32$19
HML32$20
HML32$21
HML32$22
HML32$23
HML32$24
HML32$25
HML32$26
HML32$27
HML32$28
HML32$29
HML32$30
HML32$31
HML32$32
HML32$33
HML32$34
HML32$35
HML32$36
HML32$37
HML32$38
HML32$39
HML32$40
HML32$41
HML32$42
HML32$43
HML32$44
HML32$45
HML32$46
HML32A$01
HML32A$02
HML32A$03
HML32A$04
HML32A$05
HML32A$06
HML32A$07
HML32A$08
HML32A$09
HML32A$10
HML32A$11
HML32A$12
HML32A$13
HML32A$14
HML32A$15
HML32A$16
HML32A$17
HML32A$18
HML32A$19
HML32A$20
HML32A$21
HML32A$22
HML32A$23
HML32A$24
HML32A$25
HML32A$26
HML32A$27
HML32A$28
HML32A$29
HML32A$30
HML32A$31
HML32A$32
HML32A$33
HML32A$34
HML32A$35
HML32A$36
HML32A$37
HML32A$38
HML32A$39
HML32A$40
HML32A$41
HML32A$42
HML32A$43
HML32A$44
HML32A$45
HML32A$46
HML32B$01
HML32B$02
HML32B$03
HML32B$04
HML32B$05
HML32B$06
HML32B$07
HML32B$08
HML32B$09
HML32B$10
HML32B$11
HML32B$12
HML32B$13
HML32B$14
HML32B$15
HML32B$16
HML32B$17
HML32B$18
HML32B$19
HML32B$20
HML32B$21
HML32B$22
HML32B$23
HML32B$24
HML32B$25
HML32B$26
HML32B$27
HML32B$28
HML32B$29
HML32B$30
HML32B$31
HML32B$32
HML32B$33
HML32B$34
HML32B$35
HML32B$36
HML32B$37
HML32B$38
HML32B$39
HML32B$40
HML32B$41
HML32B$42
HML32B$43
HML32B$44
HML32B$45
HML32B$46
HML32C$01
HML32C$02
HML32C$03
HML32C$04
HML32C$05
HML32C$06
HML32C$07
HML32C$08
HML32C$09
HML32C$10
HML32C$11
HML32C$12
HML32C$13
HML32C$14
HML32C$15
HML32C$16
HML32C$17
HML32C$18
HML32C$19
HML32C$20
HML32C$21
HML32C$22
HML32C$23
HML32C$24
HML32C$25
HML32C$26
HML32C$27
HML32C$28
HML32C$29
HML32C$30
HML32C$31
HML32C$32
HML32C$33
HML32C$34
HML32C$35
HML32C$36
HML32C$37
HML32C$38
HML32C$39
HML32C$40
HML32C$41
HML32C$42
HML32C$43
HML32C$44
HML32C$45
HML32C$46
HML32D$01
HML32D$02
HML32D$03
HML32D$04
HML32D$05
HML32D$06
HML32D$07
HML32D$08
HML32D$09
HML32D$10
HML32D$11
HML32D$12
HML32D$13
HML32D$14
HML32D$15
HML32D$16
HML32D$17
HML32D$18
HML32D$19
HML32D$20
HML32D$21
HML32D$22
HML32D$23
HML32D$24
HML32D$25
HML32D$26
HML32D$27
HML32D$28
HML32D$29
HML32D$30
HML32D$31
HML32D$32
HML32D$33
HML32D$34
HML32D$35
HML32D$36
HML32D$37
HML32D$38
HML32D$39
HML32D$40
HML32D$41
HML32D$42
HML32D$43
HML32D$44
HML32D$45
HML32D$46
HML32E$01
HML32E$02
HML32E$03
HML32E$04
HML32E$05
HML32E$06
HML32E$07
HML32E$08
HML32E$09
HML32E$10
HML32E$11
HML32E$12
HML32E$13
HML32E$14
HML32E$15
HML32E$16
HML32E$17
HML32E$18
HML32E$19
HML32E$20
HML32E$21
HML32E$22
HML32E$23
HML32E$24
HML32E$25
HML32E$26
HML32E$27
HML32E$28
HML32E$29
HML32E$30
HML32E$31
HML32E$32
HML32E$33
HML32E$34
HML32E$35
HML32E$36
HML32E$37
HML32E$38
HML32E$39
HML32E$40
HML32E$41
HML32E$42
HML32E$43
HML32E$44
HML32E$45
HML32E$46
HML32F$01
HML32F$02
HML32F$03
HML32F$04
HML32F$05
HML32F$06
HML32F$07
HML32F$08
HML32F$09
HML32F$10
HML32F$11
HML32F$12
HML32F$13
HML32F$14
HML32F$15
HML32F$16
HML32F$17
HML32F$18
HML32F$19
HML32F$20
HML32F$21
HML32F$22
HML32F$23
HML32F$24
HML32F$25
HML32F$26
HML32F$27
HML32F$28
HML32F$29
HML32F$30
HML32F$31
HML32F$32
HML32F$33
HML32F$34
HML32F$35
HML32F$36
HML32F$37
HML32F$38
HML32F$39
HML32F$40
HML32F$41
HML32F$42
HML32F$43
HML32F$44
HML32F$45
HML32F$46
HML32G$01
HML32G$02
HML32G$03
HML32G$04
HML32G$05
HML32G$06
HML32G$07
HML32G$08
HML32G$09
HML32G$10
HML32G$11
HML32G$12
HML32G$13
HML32G$14
HML32G$15
HML32G$16
HML32G$17
HML32G$18
HML32G$19
HML32G$20
HML32G$21
HML32G$22
HML32G$23
HML32G$24
HML32G$25
HML32G$26
HML32G$27
HML32G$28
HML32G$29
HML32G$30
HML32G$31
HML32G$32
HML32G$33
HML32G$34
HML32G$35
HML32G$36
HML32G$37
HML32G$38
HML32G$39
HML32G$40
HML32G$41
HML32G$42
HML32G$43
HML32G$44
HML32G$45
HML32G$46

In [104]:
for col in hr2010.columns:
    if "HML35" in col:
        print(col)

print("="*50)

for col in hr2015.columns:
    if "HML35" in col:
        print(col)

print("="*50)

for col in hr2021.columns:
    if "HML35" in col:
        print(col)

HML35$01
HML35$02
HML35$03
HML35$04
HML35$05
HML35$06
HML35$07
HML35$08
HML35$09
HML35$10
HML35$11
HML35$12
HML35$13
HML35$14
HML35$15
HML35$16
HML35$17
HML35$18
HML35$19
HML35$20
HML35$21
HML35$22
HML35$23
HML35$24
HML35$25
HML35$26
HML35$27
HML35$28
HML35$29
HML35$30
==================================================
HML35$01
HML35$02
HML35$03
HML35$04
HML35$05
HML35$06
HML35$07
HML35$08
HML35$09
HML35$10
HML35$11
HML35$12
HML35$13
HML35$14
HML35$15
HML35$16
HML35$17
HML35$18
HML35$19
HML35$20
HML35$21
HML35$22
HML35$23
HML35$24
HML35$25
HML35$26
HML35$27
HML35$28
HML35$29
HML35$30
HML35$31
==================================================
HML35$01
HML35$02
HML35$03
HML35$04
HML35$05
HML35$06
HML35$07
HML35$08
HML35$09
HML35$10
HML35$11
HML35$12
HML35$13
HML35$14
HML35$15
HML35$16
HML35$17
HML35$18
HML35$19
HML35$20
HML35$21
HML35$22
HML35$23
HML35$24
HML35$25
HML35$26
HML35$27
HML35$28
HML35$29
HML35$30
HML35$31
HML35$32
HML35$33
HML35$34
HML35$35
HML35$36
HML35$37
HML35$38
HML35$39
HML35$40
HML35$41
HML35$42
HML35$43
HML35$44
HML35$45
HML35$46

In [105]:
[x for x in hr2010.columns if 'HML30$' in x]

['HML30$01',
 'HML30$02',
 'HML30$03',
 'HML30$04',
 'HML30$05',
 'HML30$06',
 'HML30$07',
 'HML30$08',
 'HML30$09',
 'HML30$10',
 'HML30$11',
 'HML30$12',
 'HML30$13',
 'HML30$14',
 'HML30$15',
 'HML30$16',
 'HML30$17',
 'HML30$18',
 'HML30$19',
 'HML30$20',
 'HML30$21',
 'HML30$22',
 'HML30$23',
 'HML30$24',
 'HML30$25',
 'HML30$26',
 'HML30$27',
 'HML30$28',
 'HML30$29',
 'HML30$30']

In [106]:
for i in range(1,31):
    col = f'HML30${i:02d}'
    if col in hr2010.columns:
        print(col, hr2010[col].notna().sum())

HML30$01 0
HML30$02 99
HML30$03 879
HML30$04 1003
HML30$05 929
HML30$06 782
HML30$07 579
HML30$08 405
HML30$09 292
HML30$10 213
HML30$11 130
HML30$12 90
HML30$13 79
HML30$14 56
HML30$15 35
HML30$16 21
HML30$17 13
HML30$18 10
HML30$19 6
HML30$20 8
HML30$21 1
HML30$22 0
HML30$23 1
HML30$24 0
HML30$25 1
HML30$26 2
HML30$27 1
HML30$28 1
HML30$29 0
HML30$30 0