In [3]:
# Cleaning Dataset D final: Call it out

import pandas as pd

Dataset_D_Final = pd.read_excel("Dataset_D_Final.xlsx")

print(Dataset_D_Final.shape)
Dataset_D_Final.head()

(21545, 29)

,HHID,HV001,HV002,person_no,age,slept_under_treated_net,slept_under_llin,blood_smear_result,rapid_test_result,pfalciparum,...,HV219,HV220,HV271,HV201,HV205,HV226,HML1,HV270,HV024,HV025
0,2 23,2,23,2,3,0,0,1,1.0,1.0,...,2,23.0,-51978,32.0,22.0,8.0,0.0,3,1,2
1,2 24,2,24,2,4,1,1,1,1.0,1.0,...,2,27.0,-94706,32.0,31.0,8.0,1.0,2,1,2
2,4 3,4,3,2,4,0,0,1,1.0,1.0,...,1,35.0,-108517,31.0,31.0,8.0,0.0,2,1,2
3,4 20,4,20,2,2,0,0,1,1.0,1.0,...,1,18.0,-107283,43.0,31.0,8.0,0.0,2,1,2
4,6 7,6,7,2,1,0,0,0,0.0,0.0,...,2,35.0,-98578,43.0,43.0,8.0,0.0,2,1,2

In [4]:
Dataset_D_Final.duplicated(
    subset=['HHID', 'person_no', 'survey_year']
).sum()

0

In [8]:
# Checking column names
Dataset_D_Final.columns.tolist()

['HHID',
 'HV001',
 'HV002',
 'person_no',
 'age',
 'slept_under_treated_net',
 'slept_under_llin',
 'blood_smear_result',
 'rapid_test_result',
 'pfalciparum',
 'pmalariae',
 'survey_year',
 'malaria_positive',
 'HV005',
 'HV206',
 'HV207',
 'HV208',
 'HV209',
 'HV216',
 'HV219',
 'HV220',
 'HV271',
 'HV201',
 'HV205',
 'HV226',
 'HML1',
 'HV270',
 'HV024',
 'HV025']

In [9]:
# Checking data types and missing values
Dataset_D_Final.info()

Dataset_D_Final.isnull().sum().sort_values(
    ascending=False
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21545 entries, 0 to 21544
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   HHID                     21545 non-null  object
 1   HV001                    21545 non-null  int64
 2   HV002                    21545 non-null  int64
 3   person_no                21545 non-null  int64
 4   age                      21545 non-null  int64
 5   slept_under_treated_net  21545 non-null  int64
 6   slept_under_llin         21545 non-null  int64
 7   blood_smear_result       21545 non-null  int64
 8   rapid_test_result        21527 non-null  float64
 9   pfalciparum              17357 non-null  float64
 10  pmalariae                17357 non-null  float64
 11  survey_year              21545 non-null  int64
 12  malaria_positive         21545 non-null  int64
 13  HV005                    21545 non-null  int64
 14  HV206                    21525 non-null  float64
 15  HV207                    21527 non-null  float64
 16  HV208                    21523 non-null  float64
 17  HV209                    21524 non-null  float64
 18  HV216                    21529 non-null  float64
 19  HV219                    21545 non-null  int64
 20  HV220                    21531 non-null  float64
 21  HV271                    21545 non-null  int64
 22  HV201                    21537 non-null  float64
 23  HV205                    21532 non-null  float64
 24  HV226                    21540 non-null  float64
 25  HML1                     21542 non-null  float64
 26  HV270                    21545 non-null  int64
 27  HV024                    21545 non-null  int64
 28  HV025                    21545 non-null  int64
dtypes: float64(13), int64(15), object(1)
memory usage: 4.8+ MB

pmalariae                  4188
pfalciparum                4188
HV208                        22
HV209                        21
HV206                        20
HV207                        18
rapid_test_result            18
HV216                        16
HV220                        14
HV205                        13
HV201                         8
HV226                         5
HML1                          3
HV270                         0
HV024                         0
HV271                         0
HV219                         0
HHID                          0
HV001                         0
HV005                         0
malaria_positive              0
survey_year                   0
blood_smear_result            0
slept_under_llin              0
slept_under_treated_net       0
age                           0
person_no                     0
HV002                         0
HV025                         0
dtype: int64

In [10]:
# Viewing first few malaria positive cases

Dataset_D_Final[
    Dataset_D_Final['malaria_positive'] == 1
].head()

,HHID,HV001,HV002,person_no,age,slept_under_treated_net,slept_under_llin,blood_smear_result,rapid_test_result,pfalciparum,...,HV219,HV220,HV271,HV201,HV205,HV226,HML1,HV270,HV024,HV025
0,2 23,2,23,2,3,0,0,1,1.0,1.0,...,2,23.0,-51978,32.0,22.0,8.0,0.0,3,1,2
1,2 24,2,24,2,4,1,1,1,1.0,1.0,...,2,27.0,-94706,32.0,31.0,8.0,1.0,2,1,2
2,4 3,4,3,2,4,0,0,1,1.0,1.0,...,1,35.0,-108517,31.0,31.0,8.0,0.0,2,1,2
3,4 20,4,20,2,2,0,0,1,1.0,1.0,...,1,18.0,-107283,43.0,31.0,8.0,0.0,2,1,2
6,9 10,9,10,2,3,0,0,1,1.0,1.0,...,1,36.0,15904,21.0,31.0,8.0,0.0,4,1,2

In [11]:
# Viewing malaria prevalence

Dataset_D_Final['malaria_positive'].value_counts()

Dataset_D_Final['malaria_positive'].value_counts(
    normalize=True
) * 100

malaria_positive
0    73.135298
1    26.864702
Name: proportion, dtype: float64

In [12]:
# Checking age distribution
Dataset_D_Final['age'].describe()

count    21545.000000
mean         2.341611
std          1.316681
min          0.000000
25%          1.000000
50%          2.000000
75%          4.000000
max          5.000000
Name: age, dtype: float64

In [13]:
Dataset_D_Final['HV024'].nunique()

37

In [14]:
sorted(Dataset_D_Final['HV024'].unique())

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37]

In [18]:
hrmeta2021.value_labels[
    hrmeta2021.variable_to_label['HV024']
]

{1.0: 'Sokoto',
 2.0: 'Zamfara',
 3.0: 'Katsina',
 4.0: 'Jigawa',
 5.0: 'Yobe',
 6.0: 'Borno',
 7.0: 'Adamawa',
 8.0: 'Gombe',
 9.0: 'Bauchi',
 10.0: 'Kano',
 11.0: 'Kaduna',
 12.0: 'Kebbi',
 13.0: 'Niger',
 14.0: 'FCT',
 15.0: 'Nasarawa',
 16.0: 'Plateau',
 17.0: 'Taraba',
 18.0: 'Benue',
 19.0: 'Kogi',
 20.0: 'Kwara',
 21.0: 'Oyo',
 22.0: 'Osun',
 23.0: 'Ekiti',
 24.0: 'Ondo',
 25.0: 'Edo',
 26.0: 'Anambra',
 27.0: 'Enugu',
 28.0: 'Ebonyi',
 29.0: 'Cross River',
 30.0: 'Akwa Ibom',
 31.0: 'Abia',
 32.0: 'Imo',
 33.0: 'Rivers',
 34.0: 'Bayelsa',
 35.0: 'Delta',
 36.0: 'Lagos',
 37.0: 'Ogun'}

In [19]:
'hrmeta2021' in globals()

True

In [17]:
import pyreadstat

hr2021, hrmeta2021 = pyreadstat.read_sav(
    "househol 2021.SAV"
)

In [20]:
type(hrmeta2021)

pyreadstat.pyclasses.metadata_container

In [21]:
hrmeta2021.variable_value_labels['HV024']

{1.0: 'Sokoto',
 2.0: 'Zamfara',
 3.0: 'Katsina',
 4.0: 'Jigawa',
 5.0: 'Yobe',
 6.0: 'Borno',
 7.0: 'Adamawa',
 8.0: 'Gombe',
 9.0: 'Bauchi',
 10.0: 'Kano',
 11.0: 'Kaduna',
 12.0: 'Kebbi',
 13.0: 'Niger',
 14.0: 'FCT',
 15.0: 'Nasarawa',
 16.0: 'Plateau',
 17.0: 'Taraba',
 18.0: 'Benue',
 19.0: 'Kogi',
 20.0: 'Kwara',
 21.0: 'Oyo',
 22.0: 'Osun',
 23.0: 'Ekiti',
 24.0: 'Ondo',
 25.0: 'Edo',
 26.0: 'Anambra',
 27.0: 'Enugu',
 28.0: 'Ebonyi',
 29.0: 'Cross River',
 30.0: 'Akwa Ibom',
 31.0: 'Abia',
 32.0: 'Imo',
 33.0: 'Rivers',
 34.0: 'Bayelsa',
 35.0: 'Delta',
 36.0: 'Lagos',
 37.0: 'Ogun'}

In [22]:
hrmeta2021.value_labels[
    hrmeta2021.variable_to_label['HV024']
]

{1.0: 'Sokoto',
 2.0: 'Zamfara',
 3.0: 'Katsina',
 4.0: 'Jigawa',
 5.0: 'Yobe',
 6.0: 'Borno',
 7.0: 'Adamawa',
 8.0: 'Gombe',
 9.0: 'Bauchi',
 10.0: 'Kano',
 11.0: 'Kaduna',
 12.0: 'Kebbi',
 13.0: 'Niger',
 14.0: 'FCT',
 15.0: 'Nasarawa',
 16.0: 'Plateau',
 17.0: 'Taraba',
 18.0: 'Benue',
 19.0: 'Kogi',
 20.0: 'Kwara',
 21.0: 'Oyo',
 22.0: 'Osun',
 23.0: 'Ekiti',
 24.0: 'Ondo',
 25.0: 'Edo',
 26.0: 'Anambra',
 27.0: 'Enugu',
 28.0: 'Ebonyi',
 29.0: 'Cross River',
 30.0: 'Akwa Ibom',
 31.0: 'Abia',
 32.0: 'Imo',
 33.0: 'Rivers',
 34.0: 'Bayelsa',
 35.0: 'Delta',
 36.0: 'Lagos',
 37.0: 'Ogun'}

In [23]:
state_labels = hrmeta2021.value_labels[
    hrmeta2021.variable_to_label['HV024']
]

print(state_labels)

{1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}

In [24]:
Dataset_D_Final['state'] = Dataset_D_Final['HV024'].map(state_labels)

In [25]:
Dataset_D_Final[['HV024', 'state']].drop_duplicates().sort_values('HV024')

       HV024        state
0          1       Sokoto
18         2      Zamfara
22         3      Katsina
26         4       Jigawa
40         5         Yobe
77         6        Borno
10926      7      Adamawa
10933      8        Gombe
10931      9       Bauchi
11802     10         Kano
10941     11       Kaduna
10946     12        Kebbi
10919     13        Niger
10902     14          FCT
10915     15     Nasarawa
10920     16      Plateau
10934     17       Taraba
10890     18        Benue
10905     19         Kogi
10909     20        Kwara
12720     21          Oyo
11051     22         Osun
11029     23        Ekiti
11039     24         Ondo
11016     25          Edo
10952     26      Anambra
10966     27        Enugu
10953     28       Ebonyi
10985     29  Cross River
10976     30    Akwa Ibom
10950     31         Abia
10975     32          Imo
11018     33       Rivers
10981     34      Bayelsa
10998     35        Delta
11031     36        Lagos
11035     37         Ogun

In [33]:
Dataset_D_Final['HV024'] = Dataset_D_Final['HV024'].map(state_labels)

KeyError: 'HV024'

In [27]:
Dataset_D_Final = Dataset_D_Final.rename(columns={'HV024': 'state'})
Dataset_D_Final['state'] = Dataset_D_Final['state'].map(state_labels)

TypeError: the first argument must be callable

In [28]:
type(state_labels)

dict

In [30]:
print(hrmeta2021.variable_to_label.get('HV024'))

labels5

In [31]:
label_name = hrmeta2021.variable_to_label['HV024']
print(label_name)

state_labels = hrmeta2021.value_labels[label_name]

print(type(state_labels))
print(state_labels)

labels5
<class 'dict'>
{1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}

In [30]:
Dataset_D_Final = Dataset_D_Final.rename(columns={'HV024': 'state'})
Dataset_D_Final['state'] = Dataset_D_Final['state'].map(state_labels)

TypeError: the first argument must be callable

In [32]:
Dataset_D_Final['HV024'].head()

KeyError: 'HV024'

In [31]:
Dataset_D_Final['HV024'].unique()[:10]

KeyError: 'HV024'

In [34]:
type(state_labels)
print(state_labels)

Dataset_D_Final['HV024'].head()

Dataset_D_Final['HV024'].unique()[:10]

{1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}

KeyError: 'HV024'

In [35]:
print(Dataset_D_Final.columns.tolist())

['HHID', 'HV001', 'HV002', 'person_no', 'age', 'slept_under_treated_net', 'slept_under_llin', 'blood_smear_result', 'rapid_test_result', 'pfalciparum', 'pmalariae', 'survey_year', 'malaria_positive', 'HV005', 'HV206', 'HV207', 'HV208', 'HV209', 'HV216', 'HV219', 'HV220', 'HV271', 'HV201', 'HV205', 'HV226', 'HML1', 'HV270', 'state', 'HV025', 'state']

In [36]:
Dataset_D_Final['state'].head()

    state   state
0  Sokoto  Sokoto
1  Sokoto  Sokoto
2  Sokoto  Sokoto
3  Sokoto  Sokoto
4  Sokoto  Sokoto

In [38]:
Dataset_D_Final.columns[Dataset_D_Final.columns == 'state']

Index(['state', 'state'], dtype='object')

In [39]:
Dataset_D_Final.loc[:, Dataset_D_Final.columns == 'state'].head()

    state   state
0  Sokoto  Sokoto
1  Sokoto  Sokoto
2  Sokoto  Sokoto
3  Sokoto  Sokoto
4  Sokoto  Sokoto

In [40]:
Dataset_D_Final = Dataset_D_Final.loc[
    :, ~Dataset_D_Final.columns.duplicated()
]

In [41]:
Dataset_D_Final['state'].head()
Dataset_D_Final['state'].unique()[:10]

array(['Sokoto', 'Zamfara', 'Katsina', 'Jigawa', 'Yobe', 'Borno', 'Benue',
       'FCT', 'Kogi', 'Kwara'], dtype=object)

In [42]:
type(Dataset_D_Final['state'])

(Dataset_D_Final.columns == 'state').sum()

Dataset_D_Final.loc[
    :, Dataset_D_Final.columns == 'state'
].head()

    state
0  Sokoto
1  Sokoto
2  Sokoto
3  Sokoto
4  Sokoto

In [43]:
print((Dataset_D_Final.columns == 'HV024').sum())

0

In [44]:
Dataset_D_Final['state'].value_counts().head(10)

state
Katsina     3134
Sokoto      2421
Zamfara     2390
Yobe        2071
Jigawa      1605
Borno       1563
Kano         521
Nasarawa     452
Kaduna       424
Bauchi       416
Name: count, dtype: int64

In [45]:
Dataset_D_Final['state'].value_counts()

state
Katsina        3134
Sokoto         2421
Zamfara        2390
Yobe           2071
Jigawa         1605
Borno          1563
Kano            521
Nasarawa        452
Kaduna          424
Bauchi          416
Kebbi           395
Taraba          388
Niger           363
Rivers          349
Delta           347
Plateau         325
Benue           317
Ebonyi          301
Adamawa         261
Gombe           259
Bayelsa         245
FCT             243
Cross River     237
Abia            231
Enugu           223
Ondo            211
Kogi            204
Imo             196
Anambra         194
Lagos           180
Oyo             179
Ogun            172
Kwara           170
Akwa Ibom       155
Ekiti           150
Osun            148
Edo             105
Name: count, dtype: int64

In [46]:
print(Dataset_D_Final['state'].nunique())
print(sorted(Dataset_D_Final['state'].unique()))

37
['Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara']

In [47]:
with pd.ExcelWriter(
    "Dataset_D_Final.xlsx",
    engine="openpyxl",
    mode="a",
    if_sheet_exists="replace"
) as writer:
    Dataset_D_Final.to_excel(
        writer,
        sheet_name="Data",
        index=False
    )

In [48]:
saved_df = pd.read_excel(
    "Dataset_D_Final.xlsx",
    sheet_name="Data"
)

print(saved_df.shape)
print(saved_df['state'].nunique())
print(saved_df[['state', 'survey_year']].head())

(21545, 29)
37
    state  survey_year
0  Sokoto         2010
1  Sokoto         2010
2  Sokoto         2010
3  Sokoto         2010
4  Sokoto         2010

In [49]:
variables = [
    'HHID','HV001','HV002','HV024','HV025',
    'HV270','HV271','HV206','HV207','HV208',
    'HV209','HV216','HV219','HV220','HV201',
    'HV205','HV226','HML1'
]

for var in variables:
    print("="*50)
    print(var)
    print(hrmeta2021.column_names_to_labels.get(var))

==================================================
HHID
Case Identification
==================================================
HV001
Cluster number
==================================================
HV002
Household number
==================================================
HV024
Region
==================================================
HV025
Type of place of residence
==================================================
HV270
Wealth index combined
==================================================
HV271
Wealth index factor score combined (5 decimals)
==================================================
HV206
Has electricity
==================================================
HV207
Has radio
==================================================
HV208
Has television
==================================================
HV209
Has refrigerator
==================================================
HV216
Number of rooms used for sleeping
==================================================
HV219
Sex of head of household
==================================================
HV220
Age of head of household
==================================================
HV201
Source of drinking water
==================================================
HV205
Type of toilet facility
==================================================
HV226
Type of cooking fuel
==================================================
HML1
Number of mosquito bed nets

In [50]:
for var in [
    'HV024','HV025','HV270',
    'HV206','HV207','HV208',
    'HV209','HV219','HV201',
    'HV205','HV226'
]:
    print("="*60)
    print(var)

    label_set = hrmeta2021.variable_to_label.get(var)

    if label_set:
        print(hrmeta2021.value_labels[label_set])

============================================================
HV024
{1.0: 'Sokoto', 2.0: 'Zamfara', 3.0: 'Katsina', 4.0: 'Jigawa', 5.0: 'Yobe', 6.0: 'Borno', 7.0: 'Adamawa', 8.0: 'Gombe', 9.0: 'Bauchi', 10.0: 'Kano', 11.0: 'Kaduna', 12.0: 'Kebbi', 13.0: 'Niger', 14.0: 'FCT', 15.0: 'Nasarawa', 16.0: 'Plateau', 17.0: 'Taraba', 18.0: 'Benue', 19.0: 'Kogi', 20.0: 'Kwara', 21.0: 'Oyo', 22.0: 'Osun', 23.0: 'Ekiti', 24.0: 'Ondo', 25.0: 'Edo', 26.0: 'Anambra', 27.0: 'Enugu', 28.0: 'Ebonyi', 29.0: 'Cross River', 30.0: 'Akwa Ibom', 31.0: 'Abia', 32.0: 'Imo', 33.0: 'Rivers', 34.0: 'Bayelsa', 35.0: 'Delta', 36.0: 'Lagos', 37.0: 'Ogun'}
============================================================
HV025
{1.0: 'Urban', 2.0: 'Rural'}
============================================================
HV270
{1.0: 'Poorest', 2.0: 'Poorer', 3.0: 'Middle', 4.0: 'Richer', 5.0: 'Richest'}
============================================================
HV206
{0.0: 'No', 1.0: 'Yes'}
============================================================
HV207
{0.0: 'No', 1.0: 'Yes'}
============================================================
HV208
{0.0: 'No', 1.0: 'Yes'}
============================================================
HV209
{0.0: 'No', 1.0: 'Yes'}
============================================================
HV219
{1.0: 'Male', 2.0: 'Female'}
============================================================
HV201
{10.0: 'PIPED WATER', 11.0: 'Piped into dwelling', 12.0: 'Piped to yard/plot', 13.0: 'Piped to neighbor', 14.0: 'Public tap/standpipe', 20.0: 'TUBE WELL WATER', 21.0: 'Tube well or borehole', 30.0: 'DUG WELL (OPEN/PROTECTED)', 31.0: 'Protected well', 32.0: 'Unprotected well', 40.0: 'SURFACE FROM SPRING', 41.0: 'Protected spring', 42.0: 'Unprotected spring', 43.0: 'River/dam/lake/ponds/stream/canal/irrigation channel', 51.0: 'Rainwater', 61.0: 'Tanker truck', 62.0: 'Cart with small tank', 71.0: 'Bottled water', 72.0: 'Sachet water', 96.0: 'Other'}
============================================================
HV205
{10.0: 'FLUSH TOILET', 11.0: 'Flush to piped sewer system', 12.0: 'Flush to septic tank', 13.0: 'Flush to pit latrine', 14.0: 'Flush to somewhere else', 15.0: "Flush, don't know where", 20.0: 'PIT TOILET LATRINE', 21.0: 'Ventilated Improved Pit latrine (VIP)', 22.0: 'Pit latrine with slab', 23.0: 'Pit latrine without slab/open pit', 30.0: 'NO FACILITY', 31.0: 'No facility/bush/field', 41.0: 'Composting toilet', 42.0: 'Bucket toilet', 43.0: 'Hanging toilet/latrine', 96.0: 'Other'}
============================================================
HV226
{1.0: 'Electricity', 2.0: 'Solar cooker', 3.0: 'LPG', 4.0: 'Natural gas', 5.0: 'Biogas', 6.0: 'Alcohol/ethanol', 7.0: 'Gasoline/diesel', 8.0: 'Kerosene/paraffin', 9.0: 'Coal/lignite', 10.0: 'Charcoal', 11.0: 'Wood', 12.0: 'Straw/shrubs/grass', 13.0: 'Agricultural crop', 14.0: 'Animal dung/waste', 15.0: 'Processed biomass (pellets) or woodchips', 16.0: 'Garbage/plastic', 17.0: 'Sawdust', 95.0: 'No food cooked in house', 96.0: 'Other'}

# To start cleaning Dataset D

In [51]:
# Load dataset D
import pandas as pd
import numpy as np

Dataset_D = pd.read_excel("Dataset_D_Final2.xlsx")

print(Dataset_D.shape)
Dataset_D.head()

(21545, 29)

,HHID,HV001,HV002,person_no,age,slept_under_treated_net,slept_under_llin,blood_smear_result,rapid_test_result,pfalciparum,...,HV219,HV220,HV271,HV201,HV205,HV226,HML1,HV270,HV024,HV025
0,2 23,2,23,2,3,0,0,1,1.0,1.0,...,2,23.0,-51978,32.0,22.0,8.0,0.0,3,1,2
1,2 24,2,24,2,4,1,1,1,1.0,1.0,...,2,27.0,-94706,32.0,31.0,8.0,1.0,2,1,2
2,4 3,4,3,2,4,0,0,1,1.0,1.0,...,1,35.0,-108517,31.0,31.0,8.0,0.0,2,1,2
3,4 20,4,20,2,2,0,0,1,1.0,1.0,...,1,18.0,-107283,43.0,31.0,8.0,0.0,2,1,2
4,6 7,6,7,2,1,0,0,0,0.0,0.0,...,2,35.0,-98578,43.0,43.0,8.0,0.0,2,1,2

In [73]:
# Fixing their data types
# Categories
cat_cols = [
    'HV024',
    'HV025',
    'HV270',
    'HV219',
    'survey_year'
]

Dataset_D[cat_cols] = (
    Dataset_D[cat_cols]
    .astype('category')
)

# Binary
binary_cols = [
    'slept_under_treated_net',
    'slept_under_llin',
    'malaria_positive',
    'HV206',
    'HV207',
    'HV208',
    'HV209',
    'pfalciparum',
    'pmalariae'
]

Dataset_D[binary_cols] = (
    Dataset_D[binary_cols]
    .astype('int8')
)

# Checking data types
Dataset_D.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21545 entries, 0 to 21544
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   HHID                     21545 non-null  object
 1   HV001                    21545 non-null  int64
 2   HV002                    21545 non-null  int64
 3   person_no                21545 non-null  int64
 4   age                      21545 non-null  int64
 5   slept_under_treated_net  21545 non-null  int8
 6   slept_under_llin         21545 non-null  int8
 7   blood_smear_result       21545 non-null  int64
 8   rapid_test_result        21545 non-null  float64
 9   pfalciparum              21545 non-null  int8
 10  pmalariae                21545 non-null  int8
 11  survey_year              21545 non-null  category
 12  malaria_positive         21545 non-null  int8
 13  HV005                    21545 non-null  int64
 14  HV206                    21545 non-null  int8
 15  HV207                    21545 non-null  int8
 16  HV208                    21545 non-null  int8
 17  HV209                    21545 non-null  int8
 18  HV216                    21545 non-null  float64
 19  HV219                    21545 non-null  category
 20  HV220                    21545 non-null  float64
 21  HV271                    21545 non-null  int64
 22  HV201                    21545 non-null  float64
 23  HV205                    21545 non-null  float64
 24  HV226                    21545 non-null  float64
 25  HML1                     21545 non-null  float64
 26  HV270                    21545 non-null  category
 27  HV024                    21545 non-null  category
 28  HV025                    21545 non-null  category
dtypes: category(5), float64(7), int64(7), int8(9), object(1)
memory usage: 2.8+ MB

In [74]:
# Checking for missing
missing_percent = (
    Dataset_D
    .isnull()
    .mean()
    .mul(100)
    .round(2)
)

missing_percent.sort_values(
    ascending=False
)

HHID                       0.0
HV207                      0.0
HV024                      0.0
HV270                      0.0
HML1                       0.0
HV226                      0.0
HV205                      0.0
HV201                      0.0
HV271                      0.0
HV220                      0.0
HV219                      0.0
HV216                      0.0
HV209                      0.0
HV208                      0.0
HV206                      0.0
HV001                      0.0
HV005                      0.0
malaria_positive           0.0
survey_year                0.0
pmalariae                  0.0
pfalciparum                0.0
rapid_test_result          0.0
blood_smear_result         0.0
slept_under_llin           0.0
slept_under_treated_net    0.0
age                        0.0
person_no                  0.0
HV002                      0.0
HV025                      0.0
dtype: float64

# Handling the missing

In [70]:
# To handle the missing values in binary variables, fill them with 0
binary_cols = [
    'HV206',
    'HV207',
    'HV208',
    'HV209',
    'slept_under_treated_net',
    'slept_under_llin',
    'pfalciparum',
    'pmalariae'
]

for col in binary_cols:
    Dataset_D[col] = (
        Dataset_D[col]
        .fillna(0)
    )


# To handle the missing values in continous variables, fill them with the median

continuous = [
    'age',
    'HV220',
    'HV216',
    'HV271',
    'HML1'
]

for col in continuous:
    Dataset_D[col] = (
        Dataset_D[col]
        .fillna(
            Dataset_D[col].median()
        )
    )

# To handle Rapid Test and Blood Smear Variables Because these tests were not conducted for everybody, I would not impute them with medians.
# but instead fill it with -1 and this mean "NOT TESTED"

Dataset_D['blood_smear_result'] = (
    Dataset_D['blood_smear_result']
    .fillna(-1)
)

Dataset_D['rapid_test_result'] = (
    Dataset_D['rapid_test_result']
    .fillna(-1)
)

# To fill 1 and 2 coding bianry
for col in ['HV201','HV205','HV226']:
    Dataset_D[col] = Dataset_D[col].fillna(
        Dataset_D[col].mode()[0]
    )


# To finally check if all missing has been handled so everything becomes ZERO
Dataset_D.isnull().sum().sort_values(
    ascending=False
)

HHID                       0
HV207                      0
HV024                      0
HV270                      0
HML1                       0
HV226                      0
HV205                      0
HV201                      0
HV271                      0
HV220                      0
HV219                      0
HV216                      0
HV209                      0
HV208                      0
HV206                      0
HV001                      0
HV005                      0
malaria_positive           0
survey_year                0
pmalariae                  0
pfalciparum                0
rapid_test_result          0
blood_smear_result         0
slept_under_llin           0
slept_under_treated_net    0
age                        0
person_no                  0
HV002                      0
HV025                      0
dtype: int64

In [75]:
# Checking duplicates
Dataset_D.duplicated().sum()

# If there were duplicates, i would have fixed with (Dataset_D = Dataset_D.drop_duplicates())

0

In [76]:
# To check for malaria outcomes
Dataset_D['malaria_positive'].value_counts(
    dropna=False
)

malaria_positive
0    15757
1     5788
Name: count, dtype: int64

In [77]:
# To check the percentage of positive to negative
Dataset_D['malaria_positive'].value_counts(
    normalize=True
) * 100

malaria_positive
0    73.135298
1    26.864702
Name: proportion, dtype: float64

In [78]:
# To confirm survey years
Dataset_D['survey_year'].value_counts()

survey_year
2021    10655
2015     5753
2010     5137
Name: count, dtype: int64

In [79]:
# To check if the states are complete
Dataset_D['HV024'].nunique()

37

In [80]:
# To count the states
Dataset_D['HV024'].value_counts()

HV024
3     3134
1     2421
2     2390
5     2071
4     1605
6     1563
10     521
15     452
11     424
9      416
12     395
17     388
13     363
33     349
35     347
16     325
18     317
28     301
7      261
8      259
34     245
14     243
29     237
31     231
27     223
24     211
19     204
32     196
26     194
36     180
21     179
37     172
20     170
30     155
23     150
22     148
25     105
Name: count, dtype: int64

In [81]:
# To check the wealth categories
Dataset_D['HV270'].value_counts(
    dropna=False
)

HV270
3    4609
4    4507
2    4305
1    4168
5    3956
Name: count, dtype: int64

In [82]:
# To check the residence type
Dataset_D['HV025'].value_counts(
    dropna=False
)

HV025
2    15054
1     6491
Name: count, dtype: int64

In [83]:
continuous = [
    'age',
    'HV220',
    'HV216',
    'HV271',
    'HML1'
]

Dataset_D[
    continuous
].describe()

                age         HV220         HV216          HV271          HML1
count  21545.000000  21545.000000  21545.000000   21545.000000  21545.000000
mean       2.341611     43.885728      2.770712  -20423.294500      1.683082
std        1.316681     14.224868      1.852795   94763.450259      1.764364
min        0.000000     15.000000      1.000000 -218760.000000      0.000000
25%        1.000000     35.000000      2.000000  -99680.000000      0.000000
50%        2.000000     40.000000      2.000000  -39469.000000      1.000000
75%        4.000000     50.000000      3.000000   54451.000000      3.000000
max        5.000000     98.000000     24.000000  284041.000000      7.000000

In [84]:
Dataset_D.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21545 entries, 0 to 21544
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   HHID                     21545 non-null  object
 1   HV001                    21545 non-null  int64
 2   HV002                    21545 non-null  int64
 3   person_no                21545 non-null  int64
 4   age                      21545 non-null  int64
 5   slept_under_treated_net  21545 non-null  int8
 6   slept_under_llin         21545 non-null  int8
 7   blood_smear_result       21545 non-null  int64
 8   rapid_test_result        21545 non-null  float64
 9   pfalciparum              21545 non-null  int8
 10  pmalariae                21545 non-null  int8
 11  survey_year              21545 non-null  category
 12  malaria_positive         21545 non-null  int8
 13  HV005                    21545 non-null  int64
 14  HV206                    21545 non-null  int8
 15  HV207                    21545 non-null  int8
 16  HV208                    21545 non-null  int8
 17  HV209                    21545 non-null  int8
 18  HV216                    21545 non-null  float64
 19  HV219                    21545 non-null  category
 20  HV220                    21545 non-null  float64
 21  HV271                    21545 non-null  int64
 22  HV201                    21545 non-null  float64
 23  HV205                    21545 non-null  float64
 24  HV226                    21545 non-null  float64
 25  HML1                     21545 non-null  float64
 26  HV270                    21545 non-null  category
 27  HV024                    21545 non-null  category
 28  HV025                    21545 non-null  category
dtypes: category(5), float64(7), int64(7), int8(9), object(1)
memory usage: 2.8+ MB

In [86]:
# To save a clean dataset D
Dataset_D.to_excel(
    "Dataset_D_Clean.xlsx",
    index=False
)

# To clean Dataset A

In [87]:
import pandas as pd

Dataset_A = pd.read_excel(
    "Dataset_A_Trend_2010_2015_2021.xlsx",
    sheet_name="Data"
)

Dataset_A.shape
Dataset_A.head()

   survey_year  V024  V025  V190  ML0  ML101  ML13A  ML13E  ML13H  ML13Y
0         2010     1     2     1  0.0      0    NaN    NaN    NaN    NaN
1         2010     1     2     1  1.0      0    NaN    NaN    NaN    NaN
2         2010     1     2     1  0.0      0    NaN    NaN    NaN    NaN
3         2010     1     2     1  0.0      0    NaN    NaN    NaN    NaN
4         2010     1     2     2  0.0      0    0.0    0.0    0.0    0.0

In [91]:
# Checking the data structure

Dataset_A.info()
Dataset_A.dtypes  # data type check
Dataset_A.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23490 entries, 0 to 23489
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survey_year  23490 non-null  int64
 1   V024         23490 non-null  int64
 2   V025         23490 non-null  int64
 3   V190         23490 non-null  int64
 4   ML0          21842 non-null  float64
 5   ML101        23490 non-null  int64
 6   ML13A        8126 non-null   float64
 7   ML13E        8126 non-null   float64
 8   ML13H        8126 non-null   float64
 9   ML13Y        8126 non-null   float64
dtypes: float64(5), int64(5)
memory usage: 1.8 MB

,survey_year,V024,V025,V190,ML0,ML101,ML13A,ML13E,ML13H,ML13Y
count,23490.000000,23490.000000,23490.000000,23490.000000,21842.000000,23490.000000,8126.000000,8126.000000,8126.000000,8126.000000
mean,2016.534185,9.342444,1.697020,2.985100,0.432744,0.460792,0.049348,0.137583,0.029166,0.175117
std,4.566103,9.886381,0.459556,1.394551,0.569500,0.577819,0.216606,0.344483,0.168281,0.380090
min,2010.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2010.000000,3.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2015.000000,5.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2021.000000,13.000000,2.000000,4.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,2021.000000,37.000000,2.000000,5.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [93]:
# Checking the missing values
Dataset_A.isnull().sum()

# Checking what percentage of each variables is missing
missing = pd.DataFrame({
    'Missing_Count': Dataset_A.isnull().sum(),
    'Missing_Percent':
    (
        Dataset_A.isnull().sum()
        / len(Dataset_A)
    ) * 100
})

missing.sort_values(
    'Missing_Percent',
    ascending=False
)

             Missing_Count  Missing_Percent
ML13A                15364        65.406556
ML13E                15364        65.406556
ML13H                15364        65.406556
ML13Y                15364        65.406556
ML0                   1648         7.015751
survey_year              0         0.000000
V024                     0         0.000000
V025                     0         0.000000
V190                     0         0.000000
ML101                    0         0.000000

In [95]:
# Analysing the missing values
for col in [
    'ML0',
    'ML13A',
    'ML13E',
    'ML13H',
    'ML13Y'
]:
    print("\n", col)
    print(
        Dataset_A[col]
        .value_counts(dropna=False)
    )

 ML0
ML0
0.0    12964
1.0     8591
NaN     1648
3.0      287
Name: count, dtype: int64

 ML13A
ML13A
NaN    15364
0.0     7725
1.0      401
Name: count, dtype: int64

 ML13E
ML13E
NaN    15364
0.0     7008
1.0     1118
Name: count, dtype: int64

 ML13H
ML13H
NaN    15364
0.0     7889
1.0      237
Name: count, dtype: int64

 ML13Y
ML13Y
NaN    15364
0.0     6703
1.0     1423
Name: count, dtype: int64

In [96]:
# To replace the true missing
malaria_vars = [
    'ML13A',
    'ML13E',
    'ML13H',
    'ML13Y'
]

Dataset_A[malaria_vars] = (
    Dataset_A[malaria_vars]
    .fillna(0)
)

In [97]:
Dataset_A['ML0'].value_counts(
    dropna=False
)

ML0
0.0    12964
1.0     8591
NaN     1648
3.0      287
Name: count, dtype: int64

In [98]:
Dataset_A['ML0'] = (
    Dataset_A['ML0']
    .fillna(
        Dataset_A['ML0'].mode()[0]
    )
)

In [99]:
cat_cols = [
    'survey_year',
    'V024',
    'V025',
    'V190',
    'ML0',
    'ML101'
]

Dataset_A[cat_cols] = (
    Dataset_A[cat_cols]
    .astype('category')
)

In [100]:
binary_cols = [
    'ML13A',
    'ML13E',
    'ML13H',
    'ML13Y'
]

Dataset_A[binary_cols] = (
    Dataset_A[binary_cols]
    .astype('int8')
)

In [101]:
Dataset_A.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23490 entries, 0 to 23489
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survey_year  23490 non-null  category
 1   V024         23490 non-null  category
 2   V025         23490 non-null  category
 3   V190         23490 non-null  category
 4   ML0          23490 non-null  category
 5   ML101        23490 non-null  category
 6   ML13A        23490 non-null  int8
 7   ML13E        23490 non-null  int8
 8   ML13H        23490 non-null  int8
 9   ML13Y        23490 non-null  int8
dtypes: category(6), int8(4)
memory usage: 231.6 KB

In [102]:
Dataset_A.isnull().sum()

survey_year    0
V024           0
V025           0
V190           0
ML0            0
ML101          0
ML13A          0
ML13E          0
ML13H          0
ML13Y          0
dtype: int64

In [103]:
with pd.ExcelWriter(
    "Dataset_A_Cleaned.xlsx",
    engine="openpyxl"
) as writer:

    Dataset_A.to_excel(
        writer,
        sheet_name="Data",
        index=False
    )

In [104]:
Dataset_A = Dataset_A[
    [
        'survey_year',
        'V024',
        'V025',
        'V190'
    ]
].copy()

In [105]:
Dataset_A.info()

Dataset_A.isnull().sum()

Dataset_A.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23490 entries, 0 to 23489
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survey_year  23490 non-null  category
 1   V024         23490 non-null  category
 2   V025         23490 non-null  category
 3   V190         23490 non-null  category
dtypes: category(4)
memory usage: 93.7 KB

        survey_year   V024   V025   V190
count         23490  23490  23490  23490
unique            3     37      2      5
top            2021      3      2      3
freq          10988   3659  16373   4849

In [106]:
Dataset_A.duplicated().sum()

23063

In [107]:
with pd.ExcelWriter(
    "Dataset_A_Cleaned.xlsx",
    engine="openpyxl"
) as writer:

    Dataset_A.to_excel(
        writer,
        sheet_name="Data",
        index=False
    )

In [108]:
# To clean dataset B
import pandas as pd
Dataset_B = pd.read_excel(
    "Dataset_B_Treatment_CareSeeking_2010_2015.xlsx",
    sheet_name="Data"
)

In [109]:
Dataset_B.shape
Dataset_B.info()
Dataset_B.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12502 entries, 0 to 12501
Data columns (total 63 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survey_year  12502 non-null  int64
 1   V024         12502 non-null  int64
 2   V025         12502 non-null  int64
 3   V190         12502 non-null  int64
 4   ML11         0 non-null      float64
 5   ML12         0 non-null      float64
 6   ML13A        4394 non-null   float64
 7   ML13B        4394 non-null   float64
 8   ML13C        4394 non-null   float64
 9   ML13D        4394 non-null   float64
 10  ML13E        4394 non-null   float64
 11  ML13F        2622 non-null   float64
 12  ML13G        2622 non-null   float64
 13  ML13H        4394 non-null   float64
 14  ML13I        4394 non-null   float64
 15  ML13J        4394 non-null   float64
 16  ML13K        4394 non-null   float64
 17  ML13L        4394 non-null   float64
 18  ML13M        4394 non-null   float64
 19  ML13N        4394 non-null   float64
 20  ML13O        0 non-null      float64
 21  ML13P        0 non-null      float64
 22  ML13X        4394 non-null   float64
 23  ML13Y        4394 non-null   float64
 24  ML13Z        4394 non-null   float64
 25  ML14A        0 non-null      float64
 26  ML14B        0 non-null      float64
 27  ML14Y        0 non-null      float64
 28  ML14Z        0 non-null      float64
 29  ML15A        340 non-null    float64
 30  ML15B        173 non-null    float64
 31  ML15C        0 non-null      float64
 32  ML16A        768 non-null    float64
 33  ML16B        463 non-null    float64
 34  ML16C        0 non-null      float64
 35  ML17A        86 non-null     float64
 36  ML17B        19 non-null     float64
 37  ML17C        0 non-null      float64
 38  ML18A        101 non-null    float64
 39  ML18B        26 non-null     float64
 40  ML18C        0 non-null      float64
 41  ML19A        0 non-null      float64
 42  ML19B        0 non-null      float64
 43  ML19C        0 non-null      float64
 44  ML19D        0 non-null      float64
 45  ML19E        0 non-null      float64
 46  ML19F        0 non-null      float64
 47  ML19X        0 non-null      float64
 48  ML19Y        0 non-null      float64
 49  ML19Z        0 non-null      float64
 50  ML20A        496 non-null    float64
 51  ML20B        107 non-null    float64
 52  ML20C        0 non-null      float64
 53  ML21A        118 non-null    float64
 54  ML21B        0 non-null      float64
 55  ML21C        0 non-null      float64
 56  ML22A        0 non-null      float64
 57  ML22B        0 non-null      float64
 58  ML22C        0 non-null      float64
 59  ML23A        149 non-null    float64
 60  ML23B        78 non-null     float64
 61  ML23C        0 non-null      float64
 62  ML24C        0 non-null      float64
dtypes: float64(59), int64(4)
memory usage: 6.0 MB

,survey_year,V024,V025,V190,ML11,ML12,ML13A,ML13B,ML13C,ML13D,...,ML21A,ML21B,ML21C,ML22A,ML22B,ML22C,ML23A,ML23B,ML23C,ML24C
0,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,1,2,2,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
missing = pd.DataFrame({
    'Missing_Count':
        Dataset_B.isnull().sum(),

    'Missing_Percent':
        (
            Dataset_B.isnull().sum()
            / len(Dataset_B)
        ) * 100
})

missing.sort_values(
    'Missing_Percent',
    ascending=False
)

             Missing_Count  Missing_Percent
ML15C                12502       100.000000
ML14A                12502       100.000000
ML14Y                12502       100.000000
ML14Z                12502       100.000000
ML16C                12502       100.000000
...                    ...              ...
ML13X                 8108        64.853623
V190                     0         0.000000
V024                     0         0.000000
V025                     0         0.000000
survey_year              0         0.000000

[63 rows x 2 columns]

In [111]:
Dataset_B = Dataset_B.dropna(
    axis=1,
    how='all'
)

In [112]:
Dataset_B.columns

Index(['survey_year', 'V024', 'V025', 'V190', 'ML13A', 'ML13B', 'ML13C',
       'ML13D', 'ML13E', 'ML13F', 'ML13G', 'ML13H', 'ML13I', 'ML13J', 'ML13K',
       'ML13L', 'ML13M', 'ML13N', 'ML13X', 'ML13Y', 'ML13Z', 'ML15A', 'ML15B',
       'ML16A', 'ML16B', 'ML17A', 'ML17B', 'ML18A', 'ML18B', 'ML20A', 'ML20B',
       'ML21A', 'ML23A', 'ML23B'],
      dtype='object')

In [114]:
Dataset_B = Dataset_B.dropna(
    axis=1,
    how='all'
)

In [115]:
Dataset_B.shape

(12502, 34)

In [116]:
Dataset_B.columns

Index(['survey_year', 'V024', 'V025', 'V190', 'ML13A', 'ML13B', 'ML13C',
       'ML13D', 'ML13E', 'ML13F', 'ML13G', 'ML13H', 'ML13I', 'ML13J', 'ML13K',
       'ML13L', 'ML13M', 'ML13N', 'ML13X', 'ML13Y', 'ML13Z', 'ML15A', 'ML15B',
       'ML16A', 'ML16B', 'ML17A', 'ML17B', 'ML18A', 'ML18B', 'ML20A', 'ML20B',
       'ML21A', 'ML23A', 'ML23B'],
      dtype='object')

In [117]:
Dataset_B.duplicated().sum()

10422

In [118]:
for col in Dataset_B.columns:
    print("\n", col)
    print(
        Dataset_B[col]
        .value_counts(
            dropna=False
        )
    )

 survey_year
survey_year
2015    6524
2010    5978
Name: count, dtype: int64

 V024
V024
3    3160
2    2467
1    2263
5    1796
6    1411
4    1405
Name: count, dtype: int64

 V025
V025
2    8651
1    3851
Name: count, dtype: int64

 V190
V190
2    2615
4    2612
3    2584
1    2351
5    2340
Name: count, dtype: int64

 ML13A
ML13A
NaN    8108
0.0    4043
1.0     351
Name: count, dtype: int64

 ML13B
ML13B
NaN    8108
0.0    3584
1.0     810
Name: count, dtype: int64

 ML13C
ML13C
NaN    8108
0.0    4307
1.0      87
Name: count, dtype: int64

 ML13D
ML13D
NaN    8108
0.0    4291
1.0     103
Name: count, dtype: int64

 ML13E
ML13E
NaN    8108
0.0    3888
1.0     506
Name: count, dtype: int64

 ML13F
ML13F
NaN    9880
0.0    2567
1.0      55
Name: count, dtype: int64

 ML13G
ML13G
NaN    9880
0.0    2556
1.0      66
Name: count, dtype: int64

 ML13H
ML13H
NaN    8108
0.0    4185
1.0     209
Name: count, dtype: int64

 ML13I
ML13I
NaN    8108
0.0    3908
1.0     486
Name: count, dtype: int64

 ML13J
ML13J
NaN    8108
0.0    4153
1.0     241
Name: count, dtype: int64

 ML13K
ML13K
NaN    8108
0.0    4358
1.0      36
Name: count, dtype: int64

 ML13L
ML13L
NaN    8108
0.0    4386
1.0       8
Name: count, dtype: int64

 ML13M
ML13M
NaN    8108
0.0    4380
1.0      14
Name: count, dtype: int64

 ML13N
ML13N
NaN    8108
0.0    2763
1.0    1631
Name: count, dtype: int64

 ML13X
ML13X
NaN    8108
0.0    4075
1.0     319
Name: count, dtype: int64

 ML13Y
ML13Y
NaN    8108
0.0    3886
1.0     508
Name: count, dtype: int64

 ML13Z
ML13Z
NaN    8108
0.0    3875
1.0     519
Name: count, dtype: int64

 ML15A
ML15A
NaN    12162
0.0      115
1.0      104
2.0       65
3.0       34
4.0       17
8.0        5
Name: count, dtype: int64

 ML15B
ML15B
NaN    12329
3.0       67
4.0       45
1.0       18
2.0       15
7.0       12
5.0        8
8.0        7
6.0        1
Name: count, dtype: int64

 ML16A
ML16A
NaN    11734
1.0      248
0.0      228
2.0      177
3.0       73
4.0       34
8.0        8
Name: count, dtype: int64

 ML16B
ML16B
NaN    12039
3.0      166
5.0      105
4.0       68
2.0       48
7.0       46
8.0       15
6.0        9
1.0        6
Name: count, dtype: int64

 ML17A
ML17A
NaN    12416
0.0       33
1.0       25
2.0       18
3.0        9
4.0        1
Name: count, dtype: int64

 ML17B
ML17B
NaN    12483
3.0        9
5.0        3
4.0        3
6.0        3
2.0        1
Name: count, dtype: int64

 ML18A
ML18A
NaN    12401
2.0       31
1.0       25
0.0       25
3.0       17
8.0        2
4.0        1
Name: count, dtype: int64

 ML18B
ML18B
NaN    12476
3.0       15
4.0        4
5.0        3
2.0        3
7.0        1
Name: count, dtype: int64

 ML20A
ML20A
NaN    12006
0.0      202
1.0      137
2.0       81
3.0       61
8.0        9
4.0        6
Name: count, dtype: int64

 ML20B
ML20B
NaN    12395
3.0       53
4.0       14
5.0       11
1.0       10
7.0        6
2.0        6
6.0        4
8.0        3
Name: count, dtype: int64

 ML21A
ML21A
NaN    12384
0.0       44
1.0       33
3.0       20
2.0       19
8.0        2
Name: count, dtype: int64

 ML23A
ML23A
NaN    12353
0.0       49
1.0       37
2.0       30
3.0       24
4.0        9
Name: count, dtype: int64

 ML23B
ML23B
NaN    12424
3.0       28
2.0       15
5.0       13
4.0        9
7.0        7
1.0        6
Name: count, dtype: int64

In [119]:
cat_cols = [
    'survey_year',
    'V024',
    'V025',
    'V190'
]

for c in cat_cols:
    if c in Dataset_B.columns:
        Dataset_B[c] = (
            Dataset_B[c]
            .astype('category')
        )

In [120]:
binary_cols = []

for col in Dataset_B.columns:

    vals = (
        Dataset_B[col]
        .dropna()
        .unique()
    )

    if set(vals).issubset(
        {0, 1}
    ):
        binary_cols.append(col)

binary_cols

['ML13A',
 'ML13B',
 'ML13C',
 'ML13D',
 'ML13E',
 'ML13F',
 'ML13G',
 'ML13H',
 'ML13I',
 'ML13J',
 'ML13K',
 'ML13L',
 'ML13M',
 'ML13N',
 'ML13X',
 'ML13Y',
 'ML13Z']

In [122]:
with pd.ExcelWriter(
    "Dataset_B_Cleaned.xlsx",
    engine="openpyxl"
) as writer:

    Dataset_B.to_excel(
        writer,
        sheet_name='Data',
        index=False
    )

In [123]:
Dataset_B.duplicated(
    subset=[
        'survey_year',
        'V024',
        'V025',
        'V190'
    ]
).sum()

12390

In [124]:
dup_rows = Dataset_B[
    Dataset_B.duplicated(
        keep=False
    )
]

dup_rows.head(20)

,survey_year,V024,V025,V190,ML13A,ML13B,ML13C,ML13D,ML13E,ML13F,...,ML16B,ML17A,ML17B,ML18A,ML18B,ML20A,ML20B,ML21A,ML23A,ML23B
0,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,1,2,2,0.0,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2010,1,2,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2010,1,2,3,0.0,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2010,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2010,1,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# TO MERGE DATASET D and CLIMATE DATA TOGETHER

In [125]:
NASA = pd.read_csv(
    "Nigeria_NASA_Climate_2010_2015_2021.csv"
)

NASA.head()

     STATE  YEAR    T2M   RH2M  WS10M  PRECTOTCORR  T2M_MAX  T2M_MIN
0     Abia  2010  25.79  86.45   2.31         5.13    33.69    15.61
1     Abia  2015  25.43  85.15   2.56         4.04    32.78    13.13
2     Abia  2021  25.78  86.39   2.27         5.14    32.72    17.88
3  Adamawa  2010  27.32  59.00   2.49         2.78    42.12    12.82
4  Adamawa  2015  27.71  51.59   2.53         2.20    42.19    10.31

In [126]:
# Renaming variables
NASA = NASA.rename(
    columns={
        'STATE': 'state',
        'YEAR': 'survey_year',
        'T2M': 'avg_temperature',
        'RH2M': 'relative_humidity',
        'WS10M': 'wind_speed',
        'PRECTOTCORR': 'precipitation',
        'T2M_MAX': 'max_temperature',
        'T2M_MIN': 'min_temperature'
    }
)

In [127]:
# Check duplicates
NASA.duplicated().sum()

0

In [128]:
# Check missing
NASA.isnull().sum()

state                0
survey_year          0
avg_temperature      0
relative_humidity    0
wind_speed           0
precipitation        0
max_temperature      0
min_temperature      0
dtype: int64

In [129]:
# To verify state-year combination
NASA[
    ['state', 'survey_year']
].drop_duplicates().shape

(111, 2)

In [130]:
# Converting state names to title case
NASA['state'] = (
    NASA['state']
    .str.strip()
    .str.title()
)

In [141]:
Dataset_D_Clean = pd.read_excel("Dataset_D_Clean.xlsx")

Dataset_D_Clean.head(10)

,HHID,HV001,HV002,person_no,age,slept_under_treated_net,slept_under_llin,blood_smear_result,rapid_test_result,pfalciparum,...,HV219,HV220,HV271,HV201,HV205,HV226,HML1,HV270,HV024,HV025
0,2 23,2,23,2,3,0,0,1,1,1,...,2,23,-51978,32,22,8,0,3,1,2
1,2 24,2,24,2,4,1,1,1,1,1,...,2,27,-94706,32,31,8,1,2,1,2
2,4 3,4,3,2,4,0,0,1,1,1,...,1,35,-108517,31,31,8,0,2,1,2
3,4 20,4,20,2,2,0,0,1,1,1,...,1,18,-107283,43,31,8,0,2,1,2
4,6 7,6,7,2,1,0,0,0,0,0,...,2,35,-98578,43,43,8,0,2,1,2
5,7 22,7,22,2,2,0,0,0,0,0,...,1,26,-60027,32,23,8,0,3,1,2
6,9 10,9,10,2,3,0,0,1,1,1,...,1,36,15904,21,31,8,0,4,1,2
7,10 5,10,5,2,4,0,0,0,0,0,...,2,26,102984,51,12,5,0,5,1,1
8,15 20,15,20,2,3,0,0,0,0,0,...,2,55,62306,21,31,8,0,4,1,1
9,15 24,15,24,2,2,0,0,0,1,0,...,2,60,3081,43,31,8,0,4,1,1

In [142]:
state_labels = {
    1:'Sokoto',
    2:'Zamfara',
    3:'Katsina',
    4:'Jigawa',
    5:'Yobe',
    6:'Borno',
    7:'Adamawa',
    8:'Gombe',
    9:'Bauchi',
    10:'Kano',
    11:'Kaduna',
    12:'Kebbi',
    13:'Niger',
    14:'FCT',
    15:'Nasarawa',
    16:'Plateau',
    17:'Taraba',
    18:'Benue',
    19:'Kogi',
    20:'Kwara',
    21:'Oyo',
    22:'Osun',
    23:'Ekiti',
    24:'Ondo',
    25:'Edo',
    26:'Anambra',
    27:'Enugu',
    28:'Ebonyi',
    29:'Cross River',
    30:'Akwa Ibom',
    31:'Abia',
    32:'Imo',
    33:'Rivers',
    34:'Bayelsa',
    35:'Delta',
    36:'Lagos',
    37:'Ogun'
}

Dataset_D_Clean['state'] = (
    Dataset_D_Clean['HV024']
    .map(state_labels)
)

In [145]:
set(Dataset_D_Clean['state']) - set(NASA['state'])

{'FCT'}

In [146]:
set(NASA['state']) - set(Dataset_D_Clean['state'])

{'Fct'}

In [147]:
# Merging the two files together
Final_Model_Data = pd.merge(
    Dataset_D_Clean,
    NASA,
    on=[
        'state',
        'survey_year'
    ],
    how='left'
)

In [148]:
Final_Model_Data.shape

(21545, 36)

In [149]:
Final_Model_Data[
    [
        'avg_temperature',
        'relative_humidity',
        'wind_speed',
        'precipitation',
        'max_temperature',
        'min_temperature'
    ]
].isnull().sum()

avg_temperature      243
relative_humidity    243
wind_speed           243
precipitation        243
max_temperature      243
min_temperature      243
dtype: int64